StudyKit.content('typeIt', {
  'What do we call the set of letters we use to write and read words?': ['alphabet'],
  'What letter comes right after D in the alphabet?': [],
  'What letter comes right before H?': [],
  'What do we call the beginning consonant sound of a word?': [],
  'If you put the onset /b/ with the rime /at/, what word do you get?': [],
  'If you put the onset /s/ with the rime /it/, what word do you get?': [],
  'What math word describes the answer 5?\n8 &minus; 3 = 5': [],
  'What math word describes the answer 8?\n5 + 3 = 8': [],
  'What is the feminine word for "king"?': [],
  'What is the masculine word for "aunt"?': [],
  'What is the feminine word for "actor"?': [],
  'What is the feminine word for "prince"?': [],
  'What do we call words that tell about the action of people or animals?': ['action verb', 'verbs', 'verb'],
  'What do we call words that describe people, places, animals, and things?': ['adjective', 'describing words'],
  'What do we call words that replace the names of people, things, or animals?': ['personal pronoun', 'pronouns', 'pronoun'],
  'Which pronoun would you use to talk about yourself?': [],
  'Which pronoun would you use to refer to a boy who was already mentioned?': [],
  'Which pronoun fits?\n"Ben and I are friends. ___ play together."': [],
  'Which word do we use for ONE thing that is near you?': [],
  'Which word do we use for MORE THAN ONE thing that is near you?': [],
  'The dog is far away. Which word fits?\n"___ dog is barking loudly."': [],
  'What do we call a group of words that expresses a complete thought?': [],
  'Who is Ou Ou?': ['porcupine', 'a porcupine', 'little porcupine'],
  'What did the little mouse make for Ou Ou first?': ['shirt', 'special shirt', 'a shirt']
});
