StudyKit.lesson({
  id: 'songs',
  icon: '🎤',
  title: 'Songs in Precolonial Life',
  subtitle: 'Occasions for songs, singing & the pentatonic scale',
  cards: [
    { front: 'Music / Songs in Everyday Life', back: 'Precolonial songs marked six kinds of occasions:<br>1. <b>Birth</b><br>2. <b>Marriage</b><br>3. <b>Death</b><br>4. <b>Occupational events</b> (work, like planting rice and fishing)<br>5. <b>Rituals</b><br>6. <b>Festive occasions</b>' },
    { front: 'Singing in Precolonial Music', back: 'Singing was a <b>very important</b> part of precolonial music. Little to none of their vocal music was <b>written down</b> because most of it was <b>improvised</b> and <b>performed on the spot</b>.' },
    { front: 'Half-Sung, Half-Spoken', back: 'Vocal music was <b>chanted</b> in a <b>half-sung, half-spoken</b> manner.' },
    { front: 'Acapella or Accompanied', back: 'Songs were performed either <b>unaccompanied (acapella)</b> &mdash; voices only &mdash; or <b>accompanied</b> with one of several local instruments.' },
    { front: 'Passed On Orally', back: 'Singing was often <b>improvised and impromptu</b>. The knowledge of performing songs was <b>passed on orally</b> (by word of mouth), not by writing.' },
    { front: 'Singing vs. Instruments', back: 'Singing was considered <b>more important</b> than instrumental music, because singing could <b>express thoughts and ideas more clearly</b> than instruments could.' },
    { front: 'Example: Hiligaynon Songs', back: 'The deck names the Hiligaynon <b>panawagon</b> (love songs) and plays &ldquo;Ili-Ili Tulog Anay,&rdquo; a Hiligaynon (Ilonggo) folk song.' },
    { front: 'Pentatonic Scale', back: 'A scale that uses <b>five notes</b> instead of the usual eight. (<i>Penta</i> means five.) A pentatonic scale was often used in the early vocal music of precolonial indigenous groups.' },
    { front: 'Diatonic Scale', back: 'The usual <b>eight-note</b> scale is called the <b>diatonic scale</b> (do-re-mi-fa-sol-la-ti-do).' },
    { front: 'Pentatonic in C', back: 'The deck&rsquo;s staff in the key of C shows <b>C &ndash; D &ndash; E &ndash; G &ndash; A</b> (then C again). Notice that <b>F (fa) and B (ti) are left out</b>.' },
    { front: '🔑 How to Answer', tip: true, back: 'Work or job (planting, fishing) = <b>occupational events</b>. Not written down = <b>improvised</b>. Five notes = <b>pentatonic</b>; eight notes = <b>diatonic</b>. Voices only = <b>acapella</b>.' }
  ],
  quiz: [
    { q: 'A community sings while planting rice and fishing. Which occasion for songs does this match?', options: ['Birth', 'Occupational events', 'Marriage', 'Death'], correct: 1, explain: 'Precolonial songs marked birth, marriage, death, occupational events (work), rituals and festive occasions. Songs that go with planting or fishing belong to occupational events.', why: ['Birth songs are for a new baby. Planting rice and fishing are kinds of work.', '', 'Marriage songs are for weddings, not for planting or fishing.', 'Death songs are for mourning someone who died. Planting and fishing are work.'], tip: 'Occupation means job or work. Any song sung while working goes under occupational events.' },
    { q: 'Why was little of the precolonial vocal music ever written down?', options: ['Nobody liked to sing', 'Most of it was improvised and performed on the spot', 'Singers were not allowed to practice anywhere', 'Paper had not been invented'], correct: 1, explain: 'Most precolonial vocal music was improvised and performed on the spot. It was chanted in a half-sung, half-spoken way and passed on orally.', why: ['The opposite is true: singing was a very important part of precolonial life.', '', 'The lesson never says singers were stopped from practicing. Their songs were made up on the spot.', 'The lesson does not give this reason. It says the songs were improvised and performed on the spot.'], tip: 'Improvised = made up on the spot. Something made up on the spot is hard to write down.' },
    { q: 'How many notes does a pentatonic scale use?', options: ['Three', 'Five', 'Eight', 'Twelve'], correct: 1, explain: '&ldquo;Penta&rdquo; means five. The pentatonic scale uses five notes instead of the usual eight of the diatonic scale, and early vocal music of indigenous groups often used it.', why: ['Three is too few. Penta means five.', '', 'Eight notes is the usual diatonic scale, not the pentatonic.', 'Twelve is not in the lesson. Penta means five.'], tip: 'Penta = 5, like a pentagon with 5 sides.' },
    { q: 'The usual scale with eight notes is called the ___ scale.', options: ['Pentatonic', 'Diatonic', 'Acapella', 'Chanted'], correct: 1, explain: 'Eight notes are also known as the diatonic scale. The pentatonic scale uses only five.', why: ['Pentatonic is the FIVE-note scale.', '', 'Acapella means singing without instruments, not a scale.', 'Chanting is a way of singing (half-sung, half-spoken), not a scale.'], tip: 'Diatonic = the usual 8 (do-re-mi-fa-sol-la-ti-do). Pentatonic = only 5.' },
    { q: 'Precolonial vocal music was often chanted. What does chanted mean here?', options: ['Sung in a half-sung, half-spoken manner', 'Played only on bamboo flutes by the elders', 'Written down in a song book', 'Sung only by the children of the village'], correct: 0, explain: 'The deck says vocal music was chanted in a half-sung, half-spoken manner.', why: ['', 'Chanting is done with the voice, not with a flute.', 'Little to none of the vocal music was written down.', 'The lesson never says only children chanted.'], tip: 'Chant = half singing, half speaking.' },
    { q: 'A singer performs a song with no instruments at all, voices only. What is this called?', options: ['Accompanied', 'Diatonic', 'Acapella', 'Percussive'], correct: 2, explain: 'Songs were performed either unaccompanied (acapella) or accompanied with local instruments. Voices only = acapella.', why: ['Accompanied means WITH instruments. This song has none.', 'Diatonic is the eight-note scale, not a way of performing.', '', 'Percussive describes instruments that are struck. This song has no instruments.'], tip: 'Acapella = unaccompanied = voices only.' },
    { q: 'Why was singing considered more important than instrumental music?', options: ['Instruments had not been invented yet', 'Singing could express thoughts and ideas more clearly', 'Only the datu was allowed to sing', 'Singing was always much louder than any gong, drum or flute'], correct: 1, explain: 'Singing was considered more important because it could express thoughts and ideas more clearly than instruments could.', why: ['Precolonial Filipinos had many instruments, like the kulintang and the tongali.', '', 'The lesson never says only the datu could sing.', 'The lesson does not talk about loudness. The reason is that words express ideas clearly.'], tip: 'A song has WORDS. Words can tell ideas more clearly than sounds alone.' },
    { q: 'How was the knowledge of performing songs passed on in precolonial times?', options: ['Through printed music books', 'Orally, by word of mouth', 'Through recordings on the radio', 'Through letters to other villages'], correct: 1, explain: 'Singing was often improvised and impromptu, and the knowledge of performing songs was passed on orally.', why: ['The songs were not written down, so there were no music books.', '', 'There was no radio in precolonial times.', 'The lesson says the songs were passed on orally, not in writing.'], tip: 'Orally = by mouth. Older people sang, younger people listened and learned.' },
    { q: 'Which group of notes is the pentatonic scale in the key of C shown in the lesson?', options: ['C &ndash; D &ndash; E &ndash; F &ndash; G', 'C &ndash; D &ndash; E &ndash; G &ndash; A', 'C &ndash; E &ndash; G &ndash; B &ndash; D', 'D &ndash; E &ndash; F &ndash; G &ndash; A'], correct: 1, explain: 'The deck&rsquo;s pentatonic scale in C is C &ndash; D &ndash; E &ndash; G &ndash; A. F and B are skipped.', why: ['This set has F in it. The pentatonic scale in C skips F and B.', '', 'This set has B in it. The pentatonic scale in C skips F and B.', 'This set does not start on C, and it includes F.'], tip: 'Pentatonic in C = do, re, mi, sol, la. No fa, no ti.' },
    { q: 'Which is NOT one of the six occasions for songs in the lesson?', options: ['Rituals', 'Festive occasions', 'Death', 'Going shopping'], correct: 3, explain: 'The six occasions are birth, marriage, death, occupational events, rituals and festive occasions. Shopping is not one of them.', why: ['Rituals is one of the six occasions.', 'Festive occasions is one of the six occasions.', 'Death is one of the six occasions.', ''], tip: 'Memorize the six: Birth, Marriage, Death, Occupational events, Rituals, Festive occasions.' },
    { q: 'True or False: Most precolonial songs were carefully written down so they would not be forgotten.', options: ['True', 'False'], correct: 1, explain: 'False. Little to none of their vocal music was written down, because most of it was improvised and performed on the spot.', why: ['True is not right. The lesson says little to none of the vocal music was written down.', ''], tip: 'Remember: improvised and passed on orally, not written.' },
    { q: 'True or False: A pentatonic scale was often used in the early vocal music of precolonial indigenous groups.', options: ['True', 'False'], correct: 0, explain: 'True. The deck says the pentatonic scale was often used in early precolonial vocal music, and the melody of most music followed it.', why: ['', 'False is not right. This sentence is exactly what the pentatonic scale card says.'], tip: 'Precolonial melodies = pentatonic (five notes).' }
  ]
});
