StudyKit.lesson({
  id: 'antas',
  icon: '🧑‍🤝‍🧑',
  title: 'Antas ng Sinaunang Lipunan',
  subtitle: 'Maginoo, Timawa, at Oripun',
  cards: [
    { front: 'Maginoo', back: 'Ang <b>pinakamataas</b> na antas ng sinaunang lipunan. Kabilang dito ang mga datu at iba pang may mataas na katayuan.', en: '<b>Maginoo</b>: the <b>highest</b> level of the early society. It includes the <b>datu</b> (chiefs) and others with high status.' },
    { front: 'Timawa', back: 'Ang <b>malayang pangkat</b> ng sinaunang lipunan.', en: '<b>Timawa</b>: the <b>free group</b> of the early society.' },
    { front: 'Oripun', back: 'Ang <b>pinakamababang</b> antas ng sinaunang lipunan. Hindi pare-pareho ang kalagayan ng lahat ng oripun.', en: '<b>Oripun</b>: the <b>lowest</b> level of the early society. The situation of the oripun was not the same for all of them.' },
    { front: 'Hindi Lamang Pinuno', back: 'Hindi lamang ang pinuno ang bumubuo sa isang lipunan. May iba\'t ibang pangkat ng tao, may iba\'t ibang katayuan at tungkulin, at may ugnayan at pagtutulungan sa pamayanan.', en: '<b>Not only the leader</b>: The leader is not the only one who makes up a society. There are different groups of people, with different status and duties, and there are connections and teamwork in the community.' },
    { front: 'Ayos ng mga Antas', back: 'MAGINOO (pinakamataas) → TIMAWA (malaya) → ORIPUN (pinakamababa).', en: '<b>Order of the levels</b>: MAGINOO (highest) &rarr; TIMAWA (free) &rarr; ORIPUN (lowest).' },
    { front: 'Tandaan', back: 'Ang bawat tao sa sinaunang lipunan ay may kanya-kanyang gampanin — kahit magkakaiba ang kanilang antas.', en: '<b>Remember</b>: Each person in the early society had his or her own role &mdash; even if their levels were different.' },
    { front: '🔑 Paano Sagutin?', back: 'Pormula ng antas (mataas &rarr; mababa): <b>maginoo &rarr; timawa &rarr; oripun</b>.<br><b>Maginoo</b> = pinakamataas (kasama ang datu). <b>Timawa</b> = malaya. <b>Oripun</b> = pinakamababa.<br>Bantayan ang &ldquo;lamang&rdquo; at &ldquo;pare-pareho&rdquo;: hindi lamang pinuno ang bumubuo sa lipunan, at hindi pare-pareho ang kalagayan ng lahat ng oripun.<br>Sa tanong na may <b>HINDI</b>: ang <b>balangay</b> ay sasakyang pandagat, hindi antas.', en: 'Social class formula (high &rarr; low): <b>maginoo &rarr; timawa &rarr; oripun</b>.<br><b>Maginoo</b> = highest (includes the datu (chief)). <b>Timawa</b> = free. <b>Oripun</b> = lowest.<br>Watch out for &ldquo;lamang&rdquo; (only) and &ldquo;pare-pareho&rdquo; (all the same): society is not made up of leaders only, and the situation of all oripun was not the same.<br>In a question with <b>HINDI</b> (NOT): the <b>balangay</b> is a sea vessel, not a level.', tip: true }
  ],
  quiz: [
    { q: 'Alin ang <b>pinakamataas</b> na antas ng sinaunang lipunan?', options: ['Maginoo', 'Timawa', 'Oripun', 'Barangay'], correct: 0, explain: 'Maginoo ang pinakamataas na antas — kabilang dito ang mga datu at iba pang may mataas na katayuan.', qen: 'Which is the <b>highest</b> level of the early society?', en: '<b>Maginoo</b> is the highest level &mdash; it includes the <b>datu</b> (chiefs) and others with high status.', why: ['', 'Ang timawa ay ang malayang pangkat — nasa gitna ito, hindi pinakamataas.', 'Ang oripun ang pinakamababang antas, kabaligtaran ng hinahanap.', 'Ang barangay ay ang pamayanan mismo, hindi isang antas ng tao.'], tip: 'Pormula (mataas → mababa): maginoo → timawa → oripun. Ang una sa pormula ang pinakamataas.', whyEn: ['', 'The timawa is the free group — it is in the middle, not the highest.', 'The oripun is the lowest level, the opposite of what we need.', 'The barangay is the community itself, not a level of people.'], tipEn: 'Formula (high → low): maginoo → timawa → oripun. The first in the formula is the highest.' },
    { q: 'Tama o Mali: Ang <b>timawa</b> ang malayang pangkat ng sinaunang lipunan.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama. Ang timawa ang tinutukoy bilang malayang pangkat ng lipunan.', qen: 'True or False: The <b>timawa</b> is the free group of the early society.', en: '<b>Tama</b> (True). The timawa is the one called the free group of society.', why: ['', 'Tama — ang timawa talaga ang malayang pangkat. Hindi ito pinagpalit sa maginoo o oripun.'], tip: 'Iugnay ang bawat antas sa isang salita: maginoo = mataas, timawa = malaya, oripun = mababa. Suriin kung tama ang salitang ikinabit.', whyEn: ['', 'Correct — the timawa really is the free group. It was not swapped with maginoo or oripun.'], tipEn: 'Link each level to one word: maginoo = high, timawa = free, oripun = low. Check if the right word is attached.' },
    { q: '"Kabilang ako sa pinakamababang antas ng sinaunang lipunan." Sino ako?', options: ['Oripun', 'Maginoo', 'Timawa', 'Datu'], correct: 0, explain: 'Oripun ang pinakamababang antas ng sinaunang lipunan.', qen: '&ldquo;I belong to the lowest level of the early society.&rdquo; Who am I?', en: '<b>Oripun</b> is the lowest level of the early society.', why: ['', 'Ang maginoo ang pinakamataas na antas, kabaligtaran ng hinahanap.', 'Ang timawa ay ang malayang pangkat, hindi pinakamababa.', 'Ang datu ay pinuno at kabilang sa maginoo, ang pinakamataas na antas.'], tip: 'Kapag “pinakamababa” ang nasa tanong, kunin ang huli sa pormula: maginoo → timawa → <b>oripun</b>.', whyEn: ['', 'The maginoo is the highest level, the opposite of what we need.', 'The timawa is the free group, not the lowest.', 'The datu is a leader and belongs to the maginoo, the highest level.'], tipEn: 'When the question says “pinakamababa” (lowest), take the last one in the formula: maginoo → timawa → <b>oripun</b>.' },
    { q: 'Tama o Mali: Pare-pareho ang eksaktong kalagayan ng lahat ng oripun.', options: ['Tama', 'Mali'], correct: 1, explain: 'Mali. Sinasabi mismo ng aralin na <b>hindi</b> pare-pareho ang kalagayan ng lahat ng oripun.', qen: 'True or False: All oripun were in exactly the same situation.', en: '<b>Mali</b> (False). The lesson itself says that the situation of all oripun was <b>not</b> the same.', why: ['Ang salitang “pare-pareho” ang mali. Sinasabi mismo ng flashcard na <b>hindi</b> pare-pareho ang kalagayan ng lahat ng oripun.', ''], tip: 'Bantayan ang “pare-pareho” at “lahat.” Kapag sinabing magkakapareho ang kalagayan ng lahat ng oripun, Mali ito.', whyEn: ['The word “pare-pareho” (all the same) is the wrong part. The flashcard itself says the situation of all oripun was <b>not</b> the same.', ''], tipEn: 'Watch for “pare-pareho” (all the same) and “lahat” (all). When it says all oripun were in the same situation, it is <b>Mali</b> (False).' },
    { q: 'Saang antas kabilang ang mga datu at iba pang may mataas na katayuan?', options: ['Maginoo', 'Timawa', 'Oripun', 'Barangay'], correct: 0, explain: 'Kabilang sila sa maginoo, ang pinakamataas na antas ng lipunan.', qen: 'Which level did the <b>datu</b> (chiefs) and others with high status belong to?', en: 'They belonged to the <b>maginoo</b>, the highest level of society.', why: ['', 'Ang timawa ay malayang pangkat, hindi ang antas ng mga may mataas na katayuan.', 'Ang oripun ay pinakamababang antas — kabaligtaran ng mataas na katayuan.', 'Ang barangay ay pamayanan, hindi antas ng tao.'], tip: 'Tandaan: ang datu ay kasama sa <b>maginoo</b>. Kapag may “mataas na katayuan” sa tanong, maginoo ang sagot.', whyEn: ['', 'The timawa is the free group, not the level of people with high status.', 'The oripun is the lowest level — the opposite of high status.', 'The barangay is a community, not a level of people.'], tipEn: 'Remember: the datu is part of the <b>maginoo</b>. When the question says “mataas na katayuan” (high status), the answer is maginoo.' },
    { q: 'Tama o Mali: Ang mga pinuno lamang ang bumubuo sa sinaunang lipunan.', options: ['Tama', 'Mali'], correct: 1, explain: 'Mali. Hindi lamang pinuno — may iba\'t ibang pangkat ng tao na may iba\'t ibang katayuan at tungkulin.', qen: 'True or False: Only the leaders made up the early society.', en: '<b>Mali</b> (False). Not only the leaders &mdash; there were different groups of people with different status and duties.', why: ['Ang “lamang” ang mali. Hindi lamang pinuno ang bumubuo sa lipunan — may iba\'t ibang pangkat pa, tulad ng timawa at oripun.', ''], tip: 'Kapag may “lamang” sa pangungusap, itanong: may iba pa bang kasama? Kung mayroon (timawa, oripun), Mali ito.', whyEn: ['“Lamang” (only) is the wrong part. Society was not made up of leaders only — there were other groups too, like the timawa and oripun.', ''], tipEn: 'When a sentence has “lamang” (only), ask: is anyone else included? If yes (timawa, oripun), it is <b>Mali</b> (False).' },
    { q: 'Ayusin ang mga antas mula <b>pinakamataas</b> hanggang <b>pinakamababa</b>.', options: ['Maginoo, Timawa, Oripun', 'Oripun, Timawa, Maginoo', 'Timawa, Maginoo, Oripun', 'Maginoo, Oripun, Timawa'], correct: 0, explain: 'Maginoo (pinakamataas) → Timawa (malaya) → Oripun (pinakamababa).', qen: 'Arrange the levels from <b>highest</b> to <b>lowest</b>.', en: 'Maginoo (highest) &rarr; Timawa (free) &rarr; Oripun (lowest).', why: ['', 'Baligtad ito — mula pinakamababa papuntang pinakamataas. Ang hinihingi ay mula pinakamataas.', 'Ang maginoo ang dapat nasa una; ang timawa ay nasa gitna.', 'Tama ang simula (maginoo), pero ang oripun ay dapat nasa huli dahil ito ang pinakamababa.'], tip: 'Tingnan muna ang hinihinging simula (pinakamataas) at dulo (pinakamababa). Dapat maginoo sa una at oripun sa huli — timawa sa gitna.', whyEn: ['', 'This is reversed — from lowest to highest. The question asks to start from the highest.', 'The maginoo should come first; the timawa is in the middle.', 'The start is right (maginoo), but the oripun should be last because it is the lowest.'], tipEn: 'First check the start the question wants (highest) and the end (lowest). Maginoo must be first and oripun last — timawa in the middle.' },
    { q: 'Tama o Mali: May iba\'t ibang katayuan at tungkulin ang mga tao sa sinaunang lipunan.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama. Iba-iba ang kanilang katayuan at gampanin, ngunit may ugnayan at pagtutulungan pa rin sila.', qen: 'True or False: People in the early society had different status and duties.', en: '<b>Tama</b> (True). Their status and roles were different, but they still had connections and helped each other.', why: ['', 'Tama — iba-iba ang katayuan (maginoo, timawa, oripun) at gampanin ng mga tao sa sinaunang lipunan.'], tip: 'Kapag sinabing “iba\'t iba” ang katayuan at tungkulin, tugma ito sa aralin. Ang may “pare-pareho” o “lamang” ang kadalasang Mali.', whyEn: ['', 'Correct — people\'s status (maginoo, timawa, oripun) and roles were different in the early society.'], tipEn: 'When it says status and duties were “iba\'t iba” (different), it matches the lesson. Sentences with “pare-pareho” (all the same) or “lamang” (only) are usually <b>Mali</b> (False).' },
    { q: 'Alin ang <b>HINDI</b> isang antas o pangkat ng sinaunang lipunan?', options: ['Balangay', 'Maginoo', 'Timawa', 'Oripun'], correct: 0, explain: 'Ang balangay ay isang sasakyang pandagat, hindi isang antas ng lipunan.', qen: 'Which is <b>NOT</b> a level or group of the early society?', en: 'The <b>balangay</b> is a sea vessel, not a level of society.', why: ['', 'Ang maginoo <b>ay</b> isang antas (pinakamataas), kaya hindi ito ang sagot — ang hinahanap natin ay ang HINDI antas.', 'Ang timawa <b>ay</b> isang antas (malaya), kaya hindi ito ang sagot — ang hinahanap natin ay ang HINDI antas.', 'Ang oripun <b>ay</b> isang antas (pinakamababa), kaya hindi ito ang sagot — ang hinahanap natin ay ang HINDI antas.'], tip: 'Ingat sa magkahawig na salita: <b>balangay</b> (sasakyang pandagat) at <b>barangay</b> (pamayanan). Tatlo lang ang antas: maginoo, timawa, oripun.', whyEn: ['', 'The maginoo <b>is</b> a level (highest), so it is not the answer — we need the one that is NOT a level.', 'The timawa <b>is</b> a level (free), so it is not the answer — we need the one that is NOT a level.', 'The oripun <b>is</b> a level (lowest), so it is not the answer — we need the one that is NOT a level.'], tipEn: 'Be careful with look-alike words: <b>balangay</b> (sea vessel) and <b>barangay</b> (community). There are only three levels: maginoo, timawa, oripun.' },
    { q: 'Tama o Mali: Ang mga kasapi ng sinaunang lipunan ay may ugnayan at pagtutulungan sa isa\'t isa.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama. May ugnayan at pagtutulungan sa pamayanan kahit magkakaiba ang kanilang antas.', qen: 'True or False: The members of the early society had connections and helped each other.', en: '<b>Tama</b> (True). There were connections and teamwork in the community even if their levels were different.', why: ['', 'Tama — kahit magkakaiba ang antas, may ugnayan at pagtutulungan ang mga kasapi ayon sa aralin.'], tip: 'Tandaan ang flashcard na “Hindi Lamang Pinuno”: may ugnayan at pagtutulungan sa pamayanan. Magkaibang antas ay hindi nangangahulugang walang ugnayan.', whyEn: ['', 'Correct — even with different levels, the members had connections and helped each other, according to the lesson.'], tipEn: 'Remember the flashcard “Hindi Lamang Pinuno” (Not only the leader): there are connections and teamwork in the community. Different levels do not mean no connection.' }
  ]
});
