StudyKit.content('typeIt', {
  'How many ones make 1 ten?': [],
  'How many tens make 1 hundred?': [],
  'How many ones make 1 hundred?': [],
  'What number is made of 2 thousands, 3 hundreds, 0 tens, 4 ones?': ['2,304'],
  'Which numeral is this?\nfive thousand two hundred thirty-one': ['5,231'],
  'Which numeral is this?\nnine thousand six hundred eighty-four': ['9,684'],
  'How do you write 830 in words?': ['eight hundred and thirty'],
  'Skip count by 2s. Which number is missing?\n2, 4, 6, __, 10': [],
  'Skip count by 5s. Which number is missing?\n15, 20, __, 30': [],
  'Skip count by 10s. Which number is missing?\n40, 50, __, 70': [],
  'Skip count by 100s. Which number is missing?\n500, 600, __, 800': [],
  'Order the numbers from smallest to greatest.\n238, 170, 209': [],
  'What is the ordinal number for 3?': [],
  'What is the ordinal word for 5th?': [],
  'What is 14 in ordinal form?': ['fourteenth'],
  'Write the number: 3 hundreds, 5 tens, 8 ones': [],
  'What number does 6 hundreds, 0 tens, 9 ones make?': [],
  'Write the number: 7 hundreds, 0 tens, 4 ones': [],
  'In 2369, which digit is in the ones place?': [],
  'In 8104, which digit is in the tens place?': [],
  'Write 700 + 50 + 4 in standard form.': [],
  'Write 6000 + 50 + 9 in standard form.': ['6,059'],
  '426 + 142 = ?': [],
  '234 + 145 = ?': [],
  '1023 + 2431 = ?': ['3,454'],
  'What do we call the answer in an addition problem?': ['sum'],
  '426 + 146 = ?': [],
  '186 + 447 = ?': [],
  '489 + 156 = ?': [],
  'Which bill is this?': ['100', '100 peso'],
  'How many centavos make 1 peso?': []
});
