StudyKit.lesson({
  id: 'compare',
  emoji: '⚖️',
  title: 'Comparing Numbers',
  subtitle: 'Using <, >, and =',
  flashcards: [
    { icon: '>', term: 'Greater Than (>)', def: 'The open side faces the bigger number.' },
    { icon: '<', term: 'Less Than (<)', def: 'The open side faces the bigger number, so the point faces the smaller one.' },
    { icon: '=', term: 'Equal To (=)', def: 'Both numbers have the exact same value.' },
    { icon: '📊', term: 'How to Compare', def: 'Compare the hundreds digit first. If they are equal, compare tens, then ones.' },
    { icon: '🔍', term: 'Example', def: '443 vs 210: hundreds 4 > 2, so 443 > 210.' }
  ],
  quiz: [
    { q: 'Which symbol means "greater than"?', options: ['<', '>', '=', '+'], correct: 1, explain: 'The > symbol opens toward the bigger number.', why: ['&lt; means less than. It is the opposite of greater than.', '', '= means equal to. It says both numbers are the same.', '+ is the plus sign for adding. It does not compare numbers.'], tip: 'For greater than, the open side faces the first number, because the first number is bigger: 5 &gt; 2.' },
    { q: 'Which symbol goes in the blank?\n443 ___ 210', options: ['>', '<', '='], correct: 0, explain: '443 has more hundreds (4) than 210 (2), so 443 is greater.', why: ['', '&lt; would say 443 is less than 210. But 443 has 4 hundreds and 210 has only 2.', '= means the same number. 443 and 210 are different.'], tip: 'Compare the hundreds first: 4 and 2. Then make the open side of the symbol face the bigger number.' },
    { q: 'Which symbol goes in the blank?\n443 ___ 470', options: ['>', '<', '='], correct: 1, explain: 'The hundreds are equal (4=4), but tens: 4 is less than 7, so 443 < 470.', why: ['&gt; would say 443 is greater. The hundreds are the same (4), but 443 has 4 tens and 470 has 7 tens, so 443 is smaller.', '', '= means the same number. 443 and 470 are different in the tens and the ones.'], tip: 'If the hundreds are the same, move one place to the right and compare the tens.' },
    { q: 'Which symbol goes in the blank?\n470 ___ 470', options: ['>', '<', '='], correct: 2, explain: 'Every digit matches, so the numbers are equal.', why: ['&gt; means the first number is bigger. But both numbers are 470.', '&lt; means the first number is smaller. But both numbers are 470.', ''], tip: 'Before you pick &gt; or &lt;, check if the two numbers are exactly the same, digit by digit.' },
    { q: 'True or False: 136 is smaller than 225.', options: ['True', 'False'], correct: 0, explain: '136 has 1 hundred, 225 has 2 hundreds, so 136 is smaller.', why: ['', 'You said False, but this is true: 136 has 1 hundred and 225 has 2 hundreds, so 136 is smaller.'], tip: 'Compare the first digit (the hundreds) first. The number with fewer hundreds is smaller.' },
    { q: 'Which symbol goes in the blank?\n99 ___ 99', options: ['>', '<', '='], correct: 2, explain: 'Same number on both sides means they are equal.', why: ['&gt; says the first number is bigger, but both sides are 99.', '&lt; says the first number is smaller, but both sides are 99.', ''], tip: 'Look at both numbers slowly. When every digit matches, use =.' },
    { q: 'Which symbol goes in the blank?\n56 ___ 75', options: ['>', '<', '='], correct: 1, explain: '56 has fewer tens (5) than 75 (7), so 56 is less than 75.', why: ['&gt; would say 56 is bigger. But 56 has 5 tens and 75 has 7 tens, so 56 is smaller.', '', '= means the same. 56 and 75 are different numbers.'], tip: 'These numbers have no hundreds, so start with the tens: 5 tens and 7 tens.' },
    { q: 'True or False: When comparing numbers, we look at the ones digit first.', options: ['True', 'False'], correct: 1, explain: 'We always compare the biggest place value first — hundreds, then tens, then ones.', why: ['You said True, but we start with the biggest place: hundreds first, then tens, then ones.', ''], tip: 'Compare from the LEFT, where the biggest place is. Only look at the ones if everything before them is the same.' },
    { q: 'Which symbol goes in the blank?\n308 ___ 380', options: ['>', '<', '='], correct: 1, explain: 'Comparing tens: 0 is less than 8, so 308 < 380.', why: ['&gt; would say 308 is bigger. The hundreds are the same, but 308 has 0 tens and 380 has 8 tens.', '', 'They look alike, but they are not the same. The 0 and the 8 are in different places.'], tip: 'When two numbers use the same digits, compare place by place. Here the tens decide: 0 tens and 8 tens.' },
    { q: 'True or False: 712 is greater than 721.', options: ['True', 'False'], correct: 1, explain: 'Comparing tens: 1 is less than 2, so 712 is actually less than 721.', why: ['You said True, but 712 is smaller. The hundreds are both 7, and then 1 ten is less than 2 tens.', ''], tip: 'Watch out for numbers with the same digits in a different order. When the hundreds match, compare the tens.' },
    { q: 'Which symbol goes in the blank?\n605 ___ 650', options: ['>', '<', '='], correct: 1, explain: 'Comparing tens: 0 is less than 5, so 605 < 650.', why: ['&gt; would say 605 is bigger. Both have 6 hundreds, but 605 has 0 tens and 650 has 5 tens.', '', '605 and 650 look alike but are not the same. The 0 and the 5 swap places.'], tip: 'Line up the places: 6-0-5 and 6-5-0. The hundreds match, so compare the tens: 0 and 5.' },
    { q: 'Which symbol means "equal to"?', options: ['>', '<', '='], correct: 2, explain: 'The = symbol means both numbers have the same value.', why: ['&gt; means greater than. It shows the first number is bigger.', '&lt; means less than. It shows the first number is smaller.', ''], tip: 'The = sign has no open side and no point. It does not lean toward either number, because they are the same.' }
  ]
});
