StudyKit.lesson({
  id: 'order',
  emoji: '📶',
  title: 'Ordering Numbers',
  subtitle: 'Smallest to Greatest',
  flashcards: [
    { icon: '⬆️', term: 'Ascending Order', def: 'Arranging numbers from smallest to greatest.' },
    { icon: '⬇️', term: 'Descending Order', def: 'Arranging numbers from greatest to smallest.' },
    { icon: '🧮', term: 'How to Order', def: 'First compare the numbers using their place values, then arrange them in the order you need.' },
    { icon: '🔎', term: 'Example', def: 'Compare 238, 170, 209 by hundreds and tens: order is 170, 209, 238.' }
  ],
  quiz: [
    { q: 'What does "ascending order" mean?', options: ['Smallest to greatest', 'Greatest to smallest', 'Random order', 'Odd numbers only'], correct: 0, explain: 'Ascending means the numbers climb up from smallest to greatest.', why: ['', 'Greatest to smallest is descending order, the opposite.', 'Ascending order is never random. The numbers must go up in order.', 'Ascending order is about the order of numbers, not about odd numbers.'], tip: 'Remember: ascending means going UP (small to big), and descending means going DOWN (big to small).' },
    { q: 'What does "descending order" mean?', options: ['Smallest to greatest', 'Greatest to smallest', 'Random order', 'Even numbers only'], correct: 1, explain: 'Descending means the numbers go down from greatest to smallest.', why: ['Smallest to greatest is ascending order, the opposite.', '', 'Descending order is not random. The numbers must go down in order.', 'Descending order is about the order of numbers, not about even numbers.'], tip: 'Descending means going DOWN, like walking down the stairs: start with the biggest number.' },
    { q: 'Order the numbers from smallest to greatest.\n238, 170, 209', options: ['170, 209, 238', '238, 209, 170', '209, 170, 238', '170, 238, 209'], correct: 0, explain: 'Comparing hundreds and tens: 170 is smallest, then 209, then 238.', why: ['', 'This is greatest to smallest. The question asks for smallest first.', '209 is not the smallest. 170 has only 1 hundred, so it comes first.', '170 first is right! But 238 has 3 tens and 209 has 0 tens, so 209 is smaller and comes next.'], tip: 'Find the smallest number first and write it down. Then find the smallest of the numbers left.' },
    { q: 'True or False: 935 is less than 943.', options: ['True', 'False'], correct: 0, explain: 'Comparing tens: 3 is less than 4, so 935 < 943.', why: ['', 'You said False, but this is true: both have 9 hundreds, and 3 tens is less than 4 tens.'], tip: 'Hundreds the same? Move to the tens and compare them.' },
    { q: 'True or False: 625 is less than 421.', options: ['True', 'False'], correct: 1, explain: '625 has more hundreds (6) than 421 (4), so 625 is greater, not less.', why: ['You said True, but 625 has 6 hundreds and 421 has only 4 hundreds, so 625 is bigger.', ''], tip: 'Read the words less than carefully, then compare the hundreds digits.' },
    { q: 'To order numbers, what should you do first?', options: ['Compare their place values', 'Guess', 'Add all the numbers together first', 'Multiply them'], correct: 0, explain: 'You must compare place values (hundreds, then tens, then ones) before you can put numbers in order.', why: ['', 'Guessing can give the wrong order. We need to check the numbers.', 'Adding the numbers gives one new number. It does not tell us which one is bigger.', 'To put numbers in order we must compare them. Multiplying does not compare anything.'], tip: 'To order numbers, always compare them first: hundreds, then tens, then ones.' },
    { q: 'Which is the greatest?\n529, 592, 421', options: ['529', '592', '421'], correct: 1, explain: 'Comparing tens: 592 has 9 tens, more than 529 (2 tens) and 421 (2 tens).', why: ['529 and 592 both have 5 hundreds, but 529 has only 2 tens and 592 has 9 tens.', '', '421 has only 4 hundreds. 529 and 592 have 5 hundreds, so they are bigger.'], tip: 'First find the biggest hundreds. If two numbers tie, compare their tens.' },
    { q: 'Arrange the numbers from greatest to smallest.\n873, 730, 625', options: ['873, 730, 625', '625, 730, 873', '730, 873, 625', '625, 873, 730'], correct: 0, explain: 'Comparing hundreds: 873 (8) is greatest, then 730 (7), then 625 (6).', why: ['', 'This is smallest to greatest. The question asks for greatest first.', '730 is not the greatest. 873 has 8 hundreds, so it goes first.', '625 is the smallest, so it cannot go first when we start with the greatest.'], tip: 'Find the words greatest or smallest at the start of the question, so you know which number goes first.' },
    { q: 'Order the numbers from smallest to greatest.\n512, 125, 251', options: ['125, 251, 512', '512, 251, 125', '251, 125, 512', '125, 512, 251'], correct: 0, explain: 'Comparing hundreds: 125 (1) is smallest, then 251 (2), then 512 (5).', why: ['', 'This is greatest to smallest. We need smallest first.', '251 is not the smallest. 125 has only 1 hundred, so it comes first.', '125 first is right! But 512 has 5 hundreds and 251 has 2 hundreds, so 251 comes next.'], tip: 'These numbers all have different hundreds, so just look at the first digit: 1, 2, 5.' },
    { q: 'Which is the smallest?\n348, 384, 438', options: ['348', '384', '438'], correct: 0, explain: 'Comparing hundreds and tens: 348 has the fewest tens among these hundreds.', why: ['', '384 has 3 hundreds like 348, but 8 tens. 348 has only 4 tens, so 348 is smaller.', '438 has 4 hundreds. The other two have only 3 hundreds, so 438 is the biggest.'], tip: 'Same digits in a different order! Compare the hundreds first, then the tens, to find the smallest.' },
    { q: 'True or False: Arranging numbers from greatest to smallest is called ascending order.', options: ['True', 'False'], correct: 1, explain: 'That is actually descending order — ascending means smallest to greatest.', why: ['You said True, but greatest to smallest is called descending order. Ascending goes up, from smallest to greatest.', ''], tip: 'Ascending = up, descending = down. Check which way the numbers go.' },
    { q: 'Arrange the numbers from smallest to greatest.\n96, 69, 609', options: ['69, 96, 609', '96, 69, 609', '609, 96, 69', '69, 609, 96'], correct: 0, explain: '609 has a hundreds digit, so it is largest; between 69 and 96, 69 is smaller.', why: ['', '96 is not the smallest. 69 has 6 tens and 96 has 9 tens, so 69 comes first.', 'This is greatest to smallest. We need the smallest first.', '609 has a hundreds digit, so it is the biggest. It must go last, after 96.'], tip: 'A number with a hundreds digit is bigger than a number with only tens and ones. Put it last.' }
  ]
});
