StudyKit.lesson({
  id: 'ordinal',
  emoji: '🥇',
  title: 'Ordinal Numbers',
  subtitle: '1st up to 20th',
  flashcards: [
    { icon: '🏁', term: 'What are Ordinal Numbers?', def: 'Numbers that tell the position or order of something, like 1st, 2nd, 3rd.' },
    { icon: '⭐', term: 'The Special Three', def: '1st, 2nd, and 3rd do not just add "th" — they are special.' },
    { icon: '🔤', term: 'The "th" Rule', def: 'For numbers ending in 0 or 4-9, add "th": 10th, 14th, 17th.' },
    { icon: '🔟', term: '11th-20th', def: 'All of these end in "th," even 11th and 12th: eleventh, twelfth, up to twentieth.' }
  ],
  quiz: [
    { q: 'What is the ordinal number for 1?', options: ['1th', '1st', '1nd', 'first only'], correct: 1, explain: '1 becomes "1st" — one of the three special ordinal endings.', why: ['1 is one of the special three. It does not take th. We write 1st.', '', 'nd belongs to 2, as in 2nd. For 1 we write 1st.', 'first is the word, but the question asks for the ordinal number. That is 1st.'], tip: 'Remember the special three: 1st, 2nd, 3rd. Say the word out loud: firST, so we write st.' },
    { q: 'What is the ordinal number for 3?', options: ['3th', '3rd', '3nd', '3st'], correct: 1, explain: '3 becomes "3rd" — another one of the special endings.', why: ['3 is one of the special three, so it does not take th. It is 3rd.', '', 'nd goes with 2, like 2nd. 3 uses rd: 3rd.', 'st goes with 1, like 1st. 3 uses rd: 3rd.'], tip: 'Listen to the end of the word: thiRD, so we write 3rd.' },
    { q: 'What is the ordinal word for 5th?', options: ['fiveth', 'fifth', 'fivth', 'fifeth'], correct: 1, explain: '5th is written as "fifth" in words.', why: ['We do not just add th to five. The word changes to fifth.', '', 'Close! But the v changes to f. The word is fifth.', 'There is no e in the middle. The word is fifth: f-i-f-t-h.'], tip: 'Some ordinal words change their spelling. Spell fifth slowly: f-i-f-t-h.' },
    { q: 'True or False: For numbers ending in 4-9, we add "th."', options: ['True', 'False'], correct: 0, explain: 'Yes — like 14th, 17th, 19th, following the "th" rule.', why: ['', 'You said False, but this is true: 14th, 17th and 19th all end in th.'], tip: 'Look at the last digit. If it is 0 or 4 to 9, add th.' },
    { q: 'What is 10 in ordinal form?', options: ['10st', '10nd', '10th', 'tenst'], correct: 2, explain: '10 becomes "10th," following the "th" rule.', why: ['st is only for 1st. 10 ends in 0, so we add th: 10th.', 'nd is only for 2nd. 10 ends in 0, so we add th: 10th.', '', 'There is no word tenst. 10 ends in 0, so it is 10th.'], tip: 'Check the last digit: 10 ends in 0, and numbers ending in 0 take th.' },
    { q: 'What is 14 in ordinal form?', options: ['14st', '14th', '14rd', '14nd'], correct: 1, explain: '14 becomes "14th," following the "th" rule.', why: ['st is for 1st. 14 ends in 4, so we add th.', '', 'rd is for 3rd. 14 ends in 4, so we add th.', 'nd is for 2nd. 14 ends in 4, so we add th.'], tip: 'Say it out loud: fourteenTH. The sound at the end tells you the letters.' },
    { q: 'True or False: Ordinal numbers tell how many things there are.', options: ['True', 'False'], correct: 1, explain: 'Ordinal numbers tell POSITION or order (1st, 2nd...), not how many — that is what cardinal numbers do.', why: ['You said True, but ordinal numbers tell position, like 1st or 2nd in a line. They do not count how many.', ''], tip: 'Ask yourself: is it about WHERE something is in the order? Then it is an ordinal number.' },
    { q: 'What is the ordinal word for 20th?', options: ['twentyth', 'twentieth', 'twenth', 'twentith'], correct: 1, explain: '20th is written as "twentieth" in words.', why: ['Close! But the y changes to ie. The word is twentieth.', '', 'This leaves out part of the word. Say it slowly: twen-ti-eth.', 'An e is missing. The word is twentieth, with ie before the th.'], tip: 'Say the word slowly in parts: twen-ti-eth. Write one part at a time.' },
    { q: 'What is the ordinal number for 2?', options: ['2th', '2nd', '2st', '2rd'], correct: 1, explain: '2 becomes "2nd" — one of the three special ordinal endings.', why: ['2 is one of the special three, so it does not take th. It is 2nd.', '', 'st goes with 1, like 1st. 2 uses nd: 2nd.', 'rd goes with 3, like 3rd. 2 uses nd: 2nd.'], tip: 'Listen to the end of the word: secoND, so we write 2nd.' },
    { q: 'What is the ordinal word for 12th?', options: ['twelveth', 'twelfth', 'twelth', 'twelfeth'], correct: 1, explain: '12th is written as "twelfth" in words.', why: ['We do not just add th to twelve. The ve changes to f: twelfth.', '', 'The f is missing. Twelfth has an f before the th.', 'There is no e after the f. The word is t-w-e-l-f-t-h.'], tip: 'Spell twelfth slowly and look for the f: twel-f-th.' },
    { q: 'True or False: 11th is written as "eleventh."', options: ['True', 'False'], correct: 0, explain: 'Correct — 11th = eleventh, even though it ends in "th" like the regular rule.', why: ['', 'You said False, but this is true: 11th is written eleventh, with th at the end.'], tip: '11th and 12th are not special like 1st, 2nd and 3rd. They take th too.' },
    { q: 'What is 18 in ordinal form?', options: ['18st', '18th', '18nd', 'eighteenst'], correct: 1, explain: '18 becomes "18th," following the "th" rule.', why: ['st is for 1st. 18 ends in 8, so we add th.', '', 'nd is for 2nd. 18 ends in 8, so we add th.', 'There is no word eighteenst. 18 is eighteenth, so we write 18th.'], tip: 'All the numbers from 11th to 20th end in th. Only 1st, 2nd and 3rd are special.' },
    { q: 'Who finished first?\nIn a race, Jay finished 1st and Lim finished 2nd.', options: ['Jay', 'Lim', 'Both of them', 'None of them'], correct: 0, explain: '1st place means Jay finished first.', why: ['', 'Lim finished 2nd, which means second, after Jay.', 'Only one person can be 1st. Jay was 1st and Lim was 2nd.', 'Someone did finish first: Jay was 1st.'], tip: 'Find 1st in the sentence. The name next to 1st is the one who finished first.' },
    { q: 'Who is after Ben?\nFour children lined up: 1st - Ana, 2nd - Ben, 3rd - Cara, 4th - Dan.', options: ['Ana', 'Ben', 'Cara', 'Dan'], correct: 2, explain: 'Ben is 2nd, so the position right after him is 3rd, which is Cara.', why: ['Ana is 1st, so she is before Ben, not after him.', 'The question asks who is after Ben, so it cannot be Ben himself.', '', 'Dan is 4th. He comes later, but not right after Ben. Cara is 3rd, right after Ben.'], tip: 'Find Ben&rsquo;s place (2nd), then go one more: 3rd. Who is 3rd?' }
  ]
});
