StudyKit.lesson({
  id: 'panguri',
  emoji: '🎨',
  title: 'Pang-uri at Pangungusap na Paturol',
  subtitle: 'Mga Salitang Naglalarawan',
  flashcards: [
    { icon: '🎨', term: 'Pang-uri', def: 'Salitang NAGLALARAWAN sa tao, hayop, bagay, o lugar.\nHal: "MATAMIS ang saging."', en: 'Pang-uri = adjective. A describing word.' },
    { icon: '🌈', term: 'Mga Uri ng Pang-uri (1)', def: 'KULAY — pula, asul, dilaw, berde\nHUGIS — bilog, parisukat, tatsulok, pahaba\nLAKI — malaki, maliit, matangkad, pandak\nBILANG — isa, dalawa, tatlo, sampu', en: 'Kulay = color. Hugis = shape. Laki = size. Bilang = number.' },
    { icon: '🍬', term: 'Mga Uri ng Pang-uri (2)', def: 'KATANGIAN — mabait, masipag, matalino, malinis\nLASA — matamis, maasim, maalat, mapait\nAMOY — mabango, mabaho', en: 'Katangian = trait (how a person or thing is). Lasa = taste. Amoy = smell.' },
    { icon: '📝', term: 'Pangungusap na Paturol', def: 'NAGSASABI ng impormasyon o katotohanan.\nLaging nagtatapos sa TULDOK (.)\nHal: "Masarap ang mangga."', en: 'A telling sentence. It gives information and ends with a period (.).' },
    { icon: '🚫', term: 'HINDI Paturol', def: '"Saan ka pupunta?" — nagtatanong (?)\n"Isara mo ang bintana." — nag-uutos\n"Ang ganda!" — may (!)', en: 'These are NOT paturol: asking a question, giving a command, or a sentence with (!).' },
    { icon: '🔑', tip: true, term: 'Paano Sagutin?', def: 'Uri ng pang-uri — itanong:\nAnong KULAY? HUGIS? LAKI? ILAN?\nAnong UGALI? LASA? AMOY?\n\nPaturol ba? Nagsasabi lang at may TULDOK (.)? → Paturol!', en: 'Ask: What color? shape? size? how many? what trait? what taste? what smell?\nPaturol: it just tells something and ends with a period.' }
  ],
  quiz: [
    { q: 'Anong uri ng pang-uri ang "Bilog"?\n"Bilog ang bola."', qen: 'What kind of describing word is "Bilog" (round)?', options: ['Kulay', 'Hugis', 'Laki', 'Bilang'], correct: 1, explain: '"Bilog" — hugis iyan. Pang-uring Hugis.', en: 'Round is a shape.', why: ['Ang Kulay ay gaya ng pula, asul, at dilaw. Hindi kulay ang "bilog."', '', 'Ang Laki ay gaya ng malaki, maliit, at matangkad. Hindi sukat ang "bilog," kundi hugis.', 'Ang Bilang ay gaya ng isa, dalawa, at tatlo. Hindi bilang ang "bilog."'], whyEn: ['Kulay (color) is like red, blue, and yellow. "bilog" (round) is not a color.', '', 'Laki (size) is like big, small, and tall. "bilog" is not a size. It is a shape.', 'Bilang (number) is like one, two, and three. "bilog" is not a number.'], tip: 'Itanong ang bawat uri: Anong KULAY? Anong HUGIS? Kung ang sagot ay "bilog," hugis iyan.', tipEn: 'Ask each kind: What COLOR? What SHAPE? If the answer is "round," it is a shape.' },
    { q: 'Anong uri ng pang-uri ang "Matangkad"?\n"Matangkad ang puno sa likod-bahay."', qen: 'What kind of describing word is "Matangkad" (tall)?', options: ['Laki', 'Kulay', 'Lasa', 'Amoy'], correct: 0, explain: '"Matangkad" — laki iyan. Pang-uring Laki.', en: 'Tall is about size.', why: ['', 'Ang Kulay ay gaya ng pula at dilaw. Hindi kulay ang "matangkad."', 'Ang Lasa ay natitikman, gaya ng matamis at maalat. Hindi natitikman ang pagiging matangkad.', 'Ang Amoy ay naaamoy, gaya ng mabango at mabaho. Hindi naaamoy ang pagiging matangkad.'], whyEn: ['', 'Kulay (color) is like red and yellow. "matangkad" (tall) is not a color.', 'Lasa (taste) is something you taste, like sweet and salty. You cannot taste "tall."', 'Amoy (smell) is something you smell, like fragrant and smelly. You cannot smell "tall."'], tip: 'Itanong: gaano kalaki o kataas? Kung tungkol sa taas o sukat, Laki iyan.', tipEn: 'Ask: how big or how tall? If it is about height or size, it is Laki.' },
    { q: 'Anong uri ng pang-uri ang "Maalat"?\n"Maalat ang sabaw ng sinigang."', qen: 'What kind of describing word is "Maalat" (salty)?', options: ['Amoy', 'Lasa', 'Katangian', 'Hugis'], correct: 1, explain: '"Maalat" — lasa iyan. Pang-uring Lasa.', en: 'Salty is a taste.', why: ['Ang Amoy ay naaamoy ng ilong, gaya ng mabango. Ang "maalat" ay natitikman ng dila.', '', 'Ang Katangian ay ugali, gaya ng mabait at masipag. Hindi ugali ang "maalat."', 'Ang Hugis ay gaya ng bilog at tatsulok. Hindi hugis ang "maalat."'], whyEn: ['Amoy (smell) is what your nose smells, like fragrant. "maalat" (salty) is what your tongue tastes.', '', 'Katangian (trait) is how a person is, like kind and hardworking. "maalat" is not a trait.', 'Hugis (shape) is like round and triangle. "maalat" is not a shape.'], tip: 'Itanong: natitikman ba ito ng dila? Kung oo, Lasa iyan.', tipEn: 'Ask: can your tongue taste it? If yes, it is Lasa.' },
    { q: 'Anong uri ng pang-uri ang "Tatlong"?\n"Tatlong pusa ang natutulog sa sopa."', qen: 'What kind of describing word is "Tatlong" (three)?', options: ['Bilang', 'Laki', 'Kulay', 'Hugis'], correct: 0, explain: '"Tatlong" — ilan? Tatlo. Pang-uring Bilang.', en: 'Three is a number.', why: ['', 'Ang Laki ay malaki o maliit. Ang "tatlo" ay nagsasabi kung ILAN, hindi kung gaano kalaki.', 'Ang Kulay ay gaya ng pula at asul. Hindi kulay ang "tatlo."', 'Ang Hugis ay gaya ng bilog at parisukat. Hindi hugis ang "tatlo."'], whyEn: ['', 'Laki (size) is big or small. "tatlo" (three) tells HOW MANY, not how big.', 'Kulay (color) is like red and blue. "tatlo" is not a color.', 'Hugis (shape) is like round and square. "tatlo" is not a shape.'], tip: 'Itanong: ILAN? Kung ang sagot ay isa, dalawa, o tatlo — Bilang iyan.', tipEn: 'Ask: HOW MANY? If the answer is one, two, or three, it is Bilang.' },
    { q: 'Anong uri ng pang-uri ang "Masipag"?\n"Masipag mag-aral ang mga estudyante."', qen: 'What kind of describing word is "Masipag" (hardworking)?', options: ['Katangian', 'Bilang', 'Lasa', 'Hugis'], correct: 0, explain: '"Masipag" — ugali iyan. Pang-uring Katangian.', en: 'Hardworking is a trait (how a person is).', why: ['', 'Ang Bilang ay isa, dalawa, tatlo. Hindi bilang ang "masipag."', 'Ang Lasa ay natitikman, gaya ng matamis. Hindi natitikman ang pagiging masipag.', 'Ang Hugis ay gaya ng bilog at tatsulok. Hindi hugis ang "masipag."'], whyEn: ['', 'Bilang (number) is one, two, three. "masipag" (hardworking) is not a number.', 'Lasa (taste) is something you taste, like sweet. You cannot taste "hardworking."', 'Hugis (shape) is like round and triangle. "masipag" is not a shape.'], tip: 'Itanong: ugali ba ito ng tao, gaya ng mabait o matalino? Kung oo, Katangian iyan.', tipEn: 'Ask: is it how a person is, like kind or smart? If yes, it is Katangian.' },
    { q: 'Anong uri ng pang-uri ang "Mabaho"?\n"Mabaho ang basura sa labas."', qen: 'What kind of describing word is "Mabaho" (smelly)?', options: ['Amoy', 'Lasa', 'Kulay', 'Bilang'], correct: 0, explain: '"Mabaho" — amoy iyan. Pang-uring Amoy.', en: 'Smelly is about smell.', why: ['', 'Ang Lasa ay natitikman ng dila. Ang "mabaho" ay naaamoy ng ilong.', 'Ang Kulay ay gaya ng pula at berde. Hindi kulay ang "mabaho."', 'Ang Bilang ay isa, dalawa, tatlo. Hindi bilang ang "mabaho."'], whyEn: ['', 'Lasa (taste) is what your tongue tastes. "mabaho" (smelly) is what your nose smells.', 'Kulay (color) is like red and green. "mabaho" is not a color.', 'Bilang (number) is one, two, three. "mabaho" is not a number.'], tip: 'Itanong: naaamoy ba ito ng ilong? Mabango o mabaho → Amoy.', tipEn: 'Ask: can your nose smell it? Fragrant or smelly → Amoy.' },
    { q: 'Alin ang pangungusap na PATUROL?', qen: 'Which one is a TELLING sentence (paturol)?', options: ['"Ilan ang bola mo?"', '"Pakisara mo ang pinto ng silid."', '"Malinis ang paaralan namin."', '"Sino ang guro mo?"'], correct: 2, explain: '"Malinis ang paaralan namin." — nagsasabi at may tuldok (.). Paturol!', en: 'It tells information and ends with a period.', why: ['Nagtatanong ito at may tandang pananong (?). Hindi ito paturol.', 'Nag-uutos ito — may ipinagagawa sa iyo. Hindi ito paturol.', '', 'Nagtatanong ito at may tandang pananong (?). Hindi ito paturol.'], whyEn: ['It asks a question and has a question mark (?). It is not paturol.', 'It gives a command. It asks you to do something. It is not paturol.', '', 'It asks a question and has a question mark (?). It is not paturol.'], tip: 'Tingnan ang dulo: may tuldok (.) ba? Pagkatapos, itanong: nagsasabi lang ba, o nag-uutos? Ang nagsasabi lang ang Paturol.', tipEn: 'Look at the end: is there a period (.)? Then ask: does it just tell something, or give a command? Only the one that just tells is Paturol.' },
    { q: 'Alin ang HINDI pangungusap na paturol?', qen: 'Which one is NOT a telling sentence?', options: ['"Maganda ang bulaklak."', '"Nagluto si Nanay ng ulam."', '"Saan ka nakatira?"', '"Malamig ang tubig sa gripo."'], correct: 2, explain: 'Ang "Saan ka nakatira?" ay nagtatanong (may ?), kaya hindi paturol.', en: 'It asks a question, so it is not paturol.', why: ['Nagsasabi ito at may tuldok (.) — paturol ito, kaya hindi ito ang sagot. Hanapin ang HINDI paturol.', 'Nagsasabi ito at may tuldok (.) — paturol ito, kaya hindi ito ang sagot. Hanapin ang HINDI paturol.', '', 'Nagsasabi ito at may tuldok (.) — paturol ito, kaya hindi ito ang sagot. Hanapin ang HINDI paturol.'], whyEn: ['It tells something and ends with a period (.). It IS paturol, so it is not the answer. We need the one that is NOT.', 'It tells something and ends with a period (.). It IS paturol, so it is not the answer. We need the one that is NOT.', '', 'It tells something and ends with a period (.). It IS paturol, so it is not the answer. We need the one that is NOT.'], tip: 'Tingnan ang dulo ng bawat pangungusap. Ang may tandang pananong (?) ay HINDI paturol.', tipEn: 'Look at the end of each sentence. The one with a question mark (?) is NOT paturol.' },
    { q: 'Anong uri ng pang-uri ang "Dilaw"?\n"Dilaw ang saging na hinog."', qen: 'What kind of describing word is "Dilaw" (yellow)?', options: ['Kulay', 'Hugis', 'Laki', 'Amoy'], correct: 0, explain: '"Dilaw" — kulay iyan. Pang-uring Kulay.', en: 'Yellow is a color.', why: ['', 'Ang Hugis ay gaya ng bilog at tatsulok. Hindi hugis ang "dilaw."', 'Ang Laki ay gaya ng malaki at maliit. Hindi sukat ang "dilaw."', 'Ang Amoy ay gaya ng mabango at mabaho. Hindi naaamoy ang "dilaw."'], whyEn: ['', 'Hugis (shape) is like round and triangle. "dilaw" (yellow) is not a shape.', 'Laki (size) is like big and small. "dilaw" is not a size.', 'Amoy (smell) is like fragrant and smelly. You cannot smell "yellow."'], tip: 'Itanong: Anong KULAY? Kung ang sagot ay pula, asul, dilaw, o berde — Kulay iyan.', tipEn: 'Ask: What COLOR? If the answer is red, blue, yellow, or green, it is Kulay.' },
    { q: 'Tama o Mali: Ang pang-uri ay naglalarawan ng kulay, hugis, laki, bilang, katangian, lasa, at amoy.', qen: 'True or False: A pang-uri can describe color, shape, size, number, trait, taste, and smell.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama — pitong uri ang natutuhan natin.', en: 'True. We learned 7 kinds.', why: ['', 'Pinili mo ang Mali, pero totoo ang pangungusap. Lahat ng pitong uri ay nasa pangungusap: kulay, hugis, laki, bilang, katangian, lasa, at amoy.'], whyEn: ['', 'You said False, but it is true. All 7 kinds are in the sentence: color, shape, size, number, trait, taste, and smell.'], tip: 'Bilangin sa daliri ang pitong uri: kulay, hugis, laki, bilang, katangian, lasa, amoy. Tingnan kung may kulang o sobra sa pangungusap.', tipEn: 'Count the 7 kinds on your fingers: color, shape, size, number, trait, taste, smell. Check if the sentence has anything missing or extra.' },
    { q: 'Alin ang pang-uri para sa HUGIS?\n"___ ang tela na binili ni Nanay."', qen: 'Which describing word tells the SHAPE?', options: ['Pahaba', 'Matamis', 'Pula', 'Isa'], correct: 0, explain: '"Pahaba" — hugis iyan. Ang matamis ay lasa, pula ay kulay, isa ay bilang.', en: 'Pahaba (long shape) is a shape.', why: ['', 'Ang "matamis" ay lasa, hindi hugis.', 'Ang "pula" ay kulay, hindi hugis.', 'Ang "isa" ay bilang, hindi hugis.'], whyEn: ['', '"matamis" (sweet) is a taste, not a shape.', '"pula" (red) is a color, not a shape.', '"isa" (one) is a number, not a shape.'], tip: 'Basahin ang salitang HUGIS sa tanong. Tandaan ang mga hugis: bilog, parisukat, tatsulok, pahaba.', tipEn: 'Read the word SHAPE in the question. Remember the shapes: round, square, triangle, long.' },
    { q: 'Tama o Mali: Ang pangungusap na paturol ay nagtatapos sa tandang padamdam (!).', qen: 'True or False: A telling sentence ends with an exclamation point (!).', options: ['Tama', 'Mali'], correct: 1, explain: 'Mali — TULDOK (.) ang dulo ng paturol.', en: 'False. It ends with a period (.).', why: ['Pinili mo ang Tama, pero hindi totoo ang pangungusap. Ang "tandang padamdam (!)" ang mali. Tuldok (.) ang dulo ng paturol.', ''], whyEn: ['You said True, but it is false. The "exclamation point (!)" part is wrong. A paturol sentence ends with a period (.).', ''], tip: 'Tandaan: Paturol = nagsasabi + tuldok (.). Ang may (!) ay hindi paturol.', tipEn: 'Remember: Paturol = it tells + a period (.). A sentence with (!) is not paturol.' }
  ]
});
