StudyKit.lesson({
  id: 'pandiwa',
  emoji: '🏃',
  title: 'Pandiwa',
  subtitle: 'Mga Salitang Kumikilos',
  flashcards: [
    { icon: '🏃', term: 'Pandiwa', def: 'Salitang nagsasabi ng KILOS o GALAW — ang GINAGAWA.\nSa Ingles: verb.', en: 'Pandiwa = verb. An action word. It tells what someone is DOING.' },
    { icon: '🍽️', term: 'Mga Halimbawa', def: 'kumakain, tumatakbo, tumatalon, naglalakad, naglilinis', en: 'eating, running, jumping, walking, cleaning' },
    { icon: '🏞️', term: 'Sa Pangungusap', def: '"TUMATAKBO si Ben sa palaruan."\n"KUMAKAIN ng almusal ang mga bata."\n"NAGBABASA si Liza ng aklat."', en: 'The word in BIG letters is the action word (pandiwa).' },
    { icon: '❓', term: 'Tanong na Sinasagot', def: 'Sinasagot ng pandiwa ang tanong:\n"ANO ANG GINAGAWA?"', en: 'A verb answers the question: "What is someone doing?"' },
    { icon: '🔤', term: 'Mga Panlapi', def: 'Madalas may nag-, um-, ma-, o -in ang pandiwa.\nHal: NAG-lalaro, t-UM-atakbo', en: 'Many verbs have these word parts: nag-, um-, ma-, -in.' },
    { icon: '🌧️', term: 'Kilos, Galaw, o Estado', def: 'Ang pandiwa ay nagsasabi ng kilos, galaw, o ESTADO — hindi lang kilos.', en: 'A verb can tell an action, a movement, or a state (something happening).' },
    { icon: '🔑', tip: true, term: 'Paano Sagutin?', def: 'Laro ni Teacher: "Stand up, Sit down!"\nKaya mo bang GAWIN ang salita?\n\nOO → PANDIWA (kumakain, tumatakbo, umaawit)\nHINDI → hindi pandiwa (lapis, bola, ulam, kahon)', en: 'Can you DO or act out the word?\nYes = verb. No = not a verb (pencil, ball, food, box).' }
  ],
  quiz: [
    { q: 'Alin ang pandiwa?\n"Naglilinis si Ate ng bahay."', qen: 'Which word is the verb (action word)?', options: ['Ate', 'bahay', 'Naglilinis'], correct: 2, explain: '"Naglilinis" — iyan ang ginagawa ni Ate. Pandiwa!', en: 'Naglilinis (cleaning) is the action.', why: ['Si Ate ay tao — siya ang gumagawa, pero hindi siya ang kilos.', 'Ang "bahay" ay bagay o lugar. Hindi mo ito magagawa, kaya hindi kilos.', ''], whyEn: ['Ate is a person. She is the one doing it, but she is not the action.', '"bahay" (house) is a thing or place. You cannot do it, so it is not an action.', ''], tip: 'Itanong: ANO ANG GINAGAWA ni Ate? Ang sagot ang pandiwa.', tipEn: 'Ask: WHAT IS Ate DOING? The answer is the verb.' },
    { q: 'Alin ang pandiwa?\n"Sumasayaw ang mga bata sa entablado."', qen: 'Which word is the verb (action word)?', options: ['bata', 'Sumasayaw', 'entablado'], correct: 1, explain: '"Sumasayaw" — iyan ang ginagawa ng mga bata.', en: 'Sumasayaw (dancing) is the action.', why: ['Ang "bata" ay tao, hindi kilos. Sila ang gumagawa ng kilos.', '', 'Ang "entablado" ay lugar kung saan sila sumasayaw. Hindi ito kilos.'], whyEn: ['"bata" (children) are people, not an action. They are the ones doing the action.', '', '"entablado" (stage) is the place where they dance. It is not an action.'], tip: 'Laro ni Teacher: kaya mo bang GAWIN ang salita? Subukan ang bawat pagpipilian.', tipEn: 'Teacher&rsquo;s game: can you DO the word? Try each choice.' },
    { q: 'Anong tanong ang sinasagot ng pandiwa?', qen: 'What question does a verb answer?', options: ['Sino?', 'Ano ang ginagawa?', 'Ilan?', 'Ano ang kulay nito?'], correct: 1, explain: 'Sinasagot ng pandiwa ang "Ano ang ginagawa?"', en: '"What is someone doing?"', why: ['Ang "Sino?" ay para sa tao, hindi para sa kilos.', '', 'Ang "Ilan?" ay para sa bilang, hindi para sa kilos.', 'Ang "Ano ang kulay nito?" ay para sa pang-uring kulay, hindi para sa kilos.'], whyEn: ['"Sino?" (Who?) is for a person, not for an action.', '', '"Ilan?" (How many?) is for a number, not for an action.', '"What color is it?" is for a color describing word, not for an action.'], tip: 'Tandaan: pandiwa = kilos. Ang kilos ay sagot sa "Ano ang ginagawa?"', tipEn: 'Remember: verb = action. An action answers "What is someone doing?"' },
    { q: 'Alin ang pandiwa?', qen: 'Which one is a verb?', options: ['masaya', 'umiiyak', 'payong', 'maganda'], correct: 1, explain: '"umiiyak" — kaya mong gawin iyan. Kilos, kaya pandiwa.', en: 'umiiyak (crying) is an action.', why: ['Ang "masaya" ay naglalarawan ng damdamin. Hindi ito kilos na ginagawa.', '', 'Ang "payong" ay bagay. Hindi mo ito magagawa.', 'Ang "maganda" ay naglalarawan. Hindi ito kilos.'], whyEn: ['"masaya" (happy) describes a feeling. It is not an action you do.', '', '"payong" (umbrella) is a thing. You cannot do it.', '"maganda" (beautiful) is a describing word. It is not an action.'], tip: 'Subukang gawin o iarte ang bawat salita. Ang kaya mong gawin ay pandiwa.', tipEn: 'Try to act out each word. The one you can do is the verb.' },
    { q: 'Alin ang HINDI pandiwa?', qen: 'Which one is NOT a verb?', options: ['lumalangoy', 'tumutugtog', 'aklat', 'sumusulat'], correct: 2, explain: 'Ang "aklat" ay bagay (pangngalan). Hindi mo ito magagawa — hindi kilos.', en: 'aklat (book) is a thing, not an action.', why: ['Ang "lumalangoy" ay kilos — pandiwa ito, kaya hindi ito ang sagot. Hanapin ang HINDI pandiwa.', 'Ang "tumutugtog" ay kilos — pandiwa ito, kaya hindi ito ang sagot. Hanapin ang HINDI pandiwa.', '', 'Ang "sumusulat" ay kilos — pandiwa ito, kaya hindi ito ang sagot. Hanapin ang HINDI pandiwa.'], whyEn: ['"lumalangoy" (swimming) is an action. It IS a verb, so it is not the answer. We need the one that is NOT.', '"tumutugtog" (playing music) is an action. It IS a verb, so it is not the answer. We need the one that is NOT.', '', '"sumusulat" (writing) is an action. It IS a verb, so it is not the answer. We need the one that is NOT.'], tip: 'Hanapin ang salitang HINDI mo magagawa. Kadalasan, bagay iyon, gaya ng lapis o bola.', tipEn: 'Find the word you CANNOT do. Usually it is a thing, like a pencil or a ball.' },
    { q: 'Alin ang angkop na pandiwa sa patlang?\n"___ ng tubig ang halaman tuwing umaga."', qen: 'Which verb fits in the blank?', options: ['Dinidiligan', 'Pinakamalago', 'Halaman', 'Umaga'], correct: 0, explain: '"Dinidiligan" — iyan ang ginagawa sa halaman.', en: 'Dinidiligan (watering) is the action.', why: ['', 'Ang "Pinakamalago" ay naglalarawan, hindi kilos. Hindi ito ginagawa sa halaman.', 'Ang "Halaman" ay bagay na nasa pangungusap na. Hindi ito kilos.', 'Ang "Umaga" ay oras, hindi kilos.'], whyEn: ['', '"Pinakamalago" (most lush) is a describing word, not an action. It is not something done to the plant.', '"Halaman" (plant) is a thing that is already in the sentence. It is not an action.', '"Umaga" (morning) is a time, not an action.'], tip: 'Basahin ang pangungusap kasama ang bawat pagpipilian. Hanapin ang salitang GINAGAWA sa halaman.', tipEn: 'Read the sentence with each choice. Find the word that tells what is DONE to the plant.' },
    { q: 'Tama o Mali: Ang pandiwa ay maaari ring magsabi ng estado, hindi lang kilos.', qen: 'True or False: A verb can also tell a state, not only an action.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama — kilos, galaw, o estado.', en: 'True.', why: ['', 'Pinili mo ang Mali, pero totoo ang pangungusap. Ang pandiwa ay kilos, galaw, o ESTADO — hindi lang kilos.'], whyEn: ['', 'You said False, but it is true. A verb can be an action, a movement, or a STATE. Not only an action.'], tip: 'Tandaan ang tatlo: kilos, galaw, estado. Gaya ng "Umuulan" — nangyayari ito, at pandiwa pa rin.', tipEn: 'Remember the three: action, movement, state. Like "Umuulan" (raining): it is happening, and it is still a verb.' },
    { q: 'Aling panlapi ang MADALAS makita sa pandiwa?', qen: 'Which word part is OFTEN found in verbs?', options: ['taga-', 'nag-', 'pang-', 'ika-'], correct: 1, explain: 'Ang "nag-" ay isa sa mga panlapi ng pandiwa (nag-, um-, ma-, -in). Hal: naglalaro.', en: 'nag- is often in verbs, like naglalaro (playing).', why: ['Hindi kasama ang "taga-" sa mga panlapi ng pandiwa na natutuhan natin: nag-, um-, ma-, -in.', '', 'Hindi kasama ang "pang-" sa mga panlapi ng pandiwa na natutuhan natin: nag-, um-, ma-, -in.', 'Hindi kasama ang "ika-" sa mga panlapi ng pandiwa na natutuhan natin: nag-, um-, ma-, -in.'], whyEn: ['"taga-" is not one of the verb parts we learned: nag-, um-, ma-, -in.', '', '"pang-" is not one of the verb parts we learned: nag-, um-, ma-, -in.', '"ika-" is not one of the verb parts we learned: nag-, um-, ma-, -in.'], tip: 'Tandaan ang apat: nag-, um-, ma-, -in. Isipin: NAG-lalaro, t-UM-atakbo.', tipEn: 'Remember the four: nag-, um-, ma-, -in. Think: NAG-lalaro, t-UM-atakbo.' },
    { q: 'Alin ang pandiwa?\n"Umuulan nang malakas kagabi."', qen: 'Which word is the verb?', options: ['Umuulan', 'malakas', 'kagabi'], correct: 0, explain: '"Umuulan" — iyan ang nangyayari. Pandiwa.', en: 'Umuulan (raining) is what is happening.', why: ['', 'Ang "malakas" ay naglalarawan kung paano umuulan. Hindi ito ang nangyayari.', 'Ang "kagabi" ay oras — kung kailan nangyari. Hindi ito kilos.'], whyEn: ['', '"malakas" (hard) describes how it rains. It is not what is happening.', '"kagabi" (last night) is a time. It tells when. It is not an action.'], tip: 'Itanong: ANO ANG NANGYAYARI? Ang sagot ang pandiwa, kahit estado ito gaya ng pag-ulan.', tipEn: 'Ask: WHAT IS HAPPENING? The answer is the verb, even if it is a state like raining.' },
    { q: 'Ilan ang pandiwa sa pangungusap?\n"Kumakain at umiinom ang mga bata."', qen: 'How many verbs are in the sentence?', options: ['1', '2', '3', '0'], correct: 1, explain: 'Dalawa: "Kumakain" at "umiinom."', en: 'Two: kumakain (eating) and umiinom (drinking).', why: ['Isa lang ang nabilang mo. Baka "Kumakain" lang ang nakita mo. Kilos din ang "umiinom." 1 + 1 = 2.', '', 'Sobra ang 3. Baka binilang mo ang "bata." Tao ang bata, hindi kilos. Kumakain + umiinom = 2.', 'May pandiwa rito: "Kumakain" at "umiinom." Kaya mong gawin ang dalawa.'], whyEn: ['You counted only one. Maybe you saw only "Kumakain." "umiinom" (drinking) is an action too. 1 + 1 = 2.', '', '3 is too many. Maybe you counted "bata." Children are people, not an action. Kumakain + umiinom = 2.', 'There are verbs here: "Kumakain" (eating) and "umiinom" (drinking). You can do both.'], tip: 'Ituro ang bawat salita at itanong: kaya ko bang gawin ito? Bilangin ang mga OO.', tipEn: 'Point at each word and ask: can I do this? Count the YES words.' },
    { q: 'Alin ang pandiwang bubuo sa pangungusap?\n"___ si Tatay ng bagong sasakyan."', qen: 'Which verb completes the sentence?', options: ['Bumili', 'Malaki', 'Masaya', 'Sasakyan'], correct: 0, explain: '"Bumili" — iyan ang ginawa ni Tatay.', en: 'Bumili (bought) is the action.', why: ['', 'Ang "Malaki" ay naglalarawan ng laki, hindi kilos.', 'Ang "Masaya" ay naglalarawan ng damdamin, hindi kilos.', 'Ang "Sasakyan" ay bagay, at nasa pangungusap na ito.'], whyEn: ['', '"Malaki" (big) describes size. It is not an action.', '"Masaya" (happy) describes a feeling. It is not an action.', '"Sasakyan" (car) is a thing, and it is already in the sentence.'], tip: 'Itanong: ANO ANG GINAWA ni Tatay? Basahin nang malakas kasama ang bawat pagpipilian.', tipEn: 'Ask: WHAT DID Tatay DO? Read it out loud with each choice.' },
    { q: 'Tama o Mali: Pandiwa lahat ang "tumatakbo," "kumakain," at "naglalaro."', qen: 'True or False: "tumatakbo," "kumakain," and "naglalaro" are all verbs.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama — lahat sila ay kilos.', en: 'True. They are all actions.', why: ['', 'Pinili mo ang Mali, pero totoo ang pangungusap. Kaya mong tumakbo, kumain, at maglaro — lahat sila ay kilos.'], whyEn: ['', 'You said False, but it is true. You can run, eat, and play. They are all actions.'], tip: 'Subukan ang bawat salita sa laro ni Teacher: kaya ko bang gawin? Kung OO lahat, Tama.', tipEn: 'Try each word in Teacher&rsquo;s game: can I do it? If all are YES, it is True.' }
  ]
});
