StudyKit.lesson({
  id: 'kwento',
  emoji: '📖',
  title: 'Maikling Kwento at Tampok na Akda',
  subtitle: 'Tauhan, Tagpuan, Pangyayari',
  flashcards: [
    { icon: '📖', term: 'Maikling Kwento', def: '• Maikli at mabilis basahin\n• May SIMULA, GITNA, at WAKAS\n• May isang SULIRANIN (problema)\n• May mga TAUHAN', en: 'A short story: it is short, has a beginning, middle, and end, one problem, and characters.' },
    { icon: '🧑', term: 'Tauhan', def: 'Ang mga GUMAGANAP sa kuwento. Sagot sa "SINO?"\n"Si Ana ay isang masipag at mabait na mag-aaral."\nTauhan: Si Ana', en: 'Tauhan = characters. The people or animals in the story. Answers "Who?"' },
    { icon: '🗺️', term: 'Tagpuan', def: 'Kung SAAN at KAILAN nangyari ang kuwento.\n"Tuwing umaga, pumapasok si Ben sa paaralan."\nSaan? Sa paaralan. Kailan? Tuwing umaga.', en: 'Tagpuan = setting. WHERE and WHEN the story happened.' },
    { icon: '🔁', term: 'Simula, Gitna, Wakas', def: 'SIMULA — makikilala ang tauhan at tagpuan.\n"Pumasok si Lito sa paaralan kasama ang ina."\nGITNA — ang suliranin.\n"Naiwan ni Lito ang baunan sa bahay."\nWAKAS — nalulutas ang suliranin.\n"Dinala ng ina ang baunan sa paaralan."', en: 'Beginning = meet the characters and place.\nMiddle = the problem.\nEnd = the problem is solved.' },
    { icon: '🦁', term: 'Ang Leon at ang Daga', def: 'Tauhan: ang leon at ang daga.\nKinagat ng daga ang lubid para mapalaya ang leon.\nAral: Huwag maliitin ang iba — kahit maliit ay makatutulong.', en: 'The mouse bit the rope to free the lion.\nLesson: do not look down on others. Even small ones can help.' },
    { icon: '📜', term: 'Akda', def: 'Isinulat o inisip ng isang tao. May kaisipan, pangyayari, o aral.\nMaaaring: ALAMAT, KUWENTO, o TULA.', en: 'Akda = a written work. It can be a legend (alamat), a story (kuwento), or a poem (tula).' },
    { icon: '🌱', term: 'Alamat', def: 'Nagsasabi kung PAANO NAGSIMULA ang isang bagay, halaman, hayop, lugar, o pangalan.\nHal: Ang Alamat ng Pinya', en: 'Alamat = legend. It tells HOW something began.' },
    { icon: '🍍', term: 'Ang Alamat ng Pinya', def: 'Laging nagpapahanap si Pina sa kaniyang ina. Nainis ang ina at nasabing sana magkaroon si Pina ng maraming mata. Nawala si Pina, at may lumitaw na halamang maraming "mata" — ang pinya.\nAral: Maging masipag at huwag agad umasa sa iba.', en: 'Pina always asked her mother to find things. Her mother wished Pina had many eyes. The pineapple has many "eyes."\nLesson: work hard and do not depend on others right away.' },
    { icon: '🔑', tip: true, term: 'Paano Sagutin?', def: 'Sa bawat kuwento, hanapin:\nSINO? → tauhan\nSAAN / KAILAN? → tagpuan\nANO ang problema? → gitna\nPAANO nalutas? → wakas\nANO ang natutunan? → aral', en: 'For any story, ask: Who? Where and when? What is the problem? How was it solved? What is the lesson?' }
  ],
  quiz: [
    { q: 'Sino-sino ang mga tauhan sa kuwento?', qen: 'Who are the characters in the story?', options: ['Ang langgam at ang tipaklong', 'Ang pagong at ang liyebre', 'Ang leon at ang daga', 'Ang magsasaka at ang kaniyang kalabaw'], correct: 0, explain: 'Ang mga tauhan ay ang langgam at ang tipaklong.', en: 'The ant and the grasshopper.', passage: true, why: ['', 'Wala ang pagong at ang liyebre sa kuwentong binasa. Basahin muli ang kuwento.', 'Ibang kuwento ang "Ang Leon at ang Daga." Hindi sila ang nasa kuwentong ito.', 'Walang magsasaka o kalabaw sa kuwentong binasa.'], whyEn: ['', 'The turtle and the hare are not in this story. Read the story again.', '"The Lion and the Mouse" is a different story. They are not in this story.', 'There is no farmer or carabao in this story.'], tip: 'Itanong: SINO ang nasa kuwento? Hanapin ang mga hayop na paulit-ulit na lumalabas sa kuwento.', tipEn: 'Ask: WHO is in the story? Look for the animals that keep showing up in the story.' },
    { q: 'Saan nangyari ang kuwento?', qen: 'Where did the story happen?', options: ['Sa ilalim ng punong-kahoy', 'Sa ilog', 'Sa loob ng isang malaking paaralan', 'Sa bahay'], correct: 0, explain: 'Nangyari ang kuwento sa ilalim ng punong-kahoy.', en: 'Under a tree.', passage: true, why: ['', 'Walang ilog sa kuwento. Basahin muli kung saan umaawit ang tipaklong.', 'Walang paaralan sa kuwentong ito.', 'Hindi bahay ang tagpuan. Basahin muli kung saan umaawit ang tipaklong.'], whyEn: ['', 'There is no river in the story. Read again where the grasshopper was singing.', 'There is no school in this story.', 'The setting is not a house. Read again where the grasshopper was singing.'], tip: 'Itanong: SAAN? Hanapin sa kuwento ang salitang "sa" na sinusundan ng lugar.', tipEn: 'Ask: WHERE? Look in the story for the word "sa" followed by a place.' },
    { q: 'Ano ang suliranin ng tipaklong nang dumating ang tag-ulan?', qen: 'What problem did the grasshopper have when the rainy season came?', options: ['Wala itong pagkain', 'Nawalan ito ng bahay', 'Nasaktan ito', 'Naligaw ito'], correct: 0, explain: 'Nang dumating ang tag-ulan, wala nang pagkain ang tipaklong.', en: 'It had no food.', passage: true, why: ['', 'Walang sinabing nawalan ng bahay ang tipaklong. Pagkain ang wala sa kaniya.', 'Hindi nasaktan ang tipaklong sa kuwento.', 'Hindi naligaw ang tipaklong. Pagkain ang kaniyang problema.'], whyEn: ['', 'The story never says the grasshopper lost its home. It had no food.', 'The grasshopper did not get hurt in the story.', 'The grasshopper did not get lost. Food was its problem.'], tip: 'Hanapin sa kuwento ang bahaging "Nang dumating ang tag-ulan." Doon makikita ang problema.', tipEn: 'Find the part of the story that says "When the rainy season came." The problem is there.' },
    { q: 'Paano nalutas ang suliranin sa wakas?', qen: 'How was the problem solved at the end?', options: ['Ibinahagi ng langgam ang pagkain sa tipaklong', 'Umalis ang tipaklong at naghanap ng ibang punong-kahoy', 'Umiyak ang langgam', 'Walang nangyari'], correct: 0, explain: 'Ibinahagi ng langgam ang kaniyang pagkain sa tipaklong.', en: 'The ant shared its food.', passage: true, why: ['', 'Hindi umalis ang tipaklong. Ang langgam ang tumulong sa kaniya.', 'Hindi umiyak ang langgam. Ibinahagi nito ang pagkain.', 'May nangyari sa wakas: tumulong ang langgam sa tipaklong.'], whyEn: ['', 'The grasshopper did not leave. The ant helped it.', 'The ant did not cry. It shared its food.', 'Something did happen at the end: the ant helped the grasshopper.'], tip: 'Itanong: PAANO nalutas ang problema? Basahin ang huling bahagi ng kuwento.', tipEn: 'Ask: HOW was the problem solved? Read the last part of the story.' },
    { q: 'Ano ang aral ng kuwento?', qen: 'What is the lesson of the story?', options: ['Mahalaga ang paghahanda at pagiging masipag', 'Huwag kumain nang marami', 'Laging matulog sa umaga', 'Huwag magtiwala sa sinumang kaibigan o kapitbahay'], correct: 0, explain: 'Natuto ang tipaklong na maging masipag. Mahalaga ang paghahanda at pagiging masipag.', en: 'Be ready and work hard.', passage: true, why: ['', 'Hindi tungkol sa pagkain nang marami ang kuwento. Tungkol ito sa paghahanda.', 'Walang natutulog sa kuwento. Hindi ito ang aral.', 'Kabaligtaran ito — tumulong pa ang langgam sa tipaklong.'], whyEn: ['', 'The story is not about eating a lot. It is about getting ready.', 'Nobody sleeps in the story. This is not the lesson.', 'This is the opposite. The ant even helped the grasshopper.'], tip: 'Itanong: ANO ang natutunan ng tauhan sa wakas? Doon makikita ang aral.', tipEn: 'Ask: WHAT did the character learn at the end? That is where the lesson is.' },
    { q: 'Anong bahagi ng kuwento ito?\n"Napansin ni Lito na naiwan niya ang kaniyang baunan sa bahay."', qen: 'Which part of the story is this?', options: ['Simula', 'Gitna', 'Wakas'], correct: 1, explain: 'Ito ang suliranin (problema), kaya GITNA.', en: 'This is the problem, so it is the Middle.', why: ['Sa Simula, makikilala pa lang ang tauhan at tagpuan. Pero dito, may problema na — naiwan ang baunan.', '', 'Sa Wakas, nalulutas ang problema. Hindi pa ito nalulutas dito — naiwan pa ang baunan.'], whyEn: ['At the Beginning, we just meet the characters and the place. But here there is already a problem: the lunchbox was left behind.', '', 'At the End, the problem is solved. It is not solved yet here. The lunchbox is still at home.'], tip: 'Itanong: may PROBLEMA ba? Problema → Gitna. Nalutas na → Wakas.', tipEn: 'Ask: is there a PROBLEM? Problem → Middle. Already solved → End.' },
    { q: 'Anong bahagi ng kuwento ito?\n"Dinala ng kaniyang ina ang baunan niya sa paaralan."', qen: 'Which part of the story is this?', options: ['Simula', 'Gitna', 'Wakas'], correct: 2, explain: 'Nalutas na ang problema, kaya WAKAS.', en: 'The problem is solved, so it is the End.', why: ['Sa Simula, ipinakikilala pa lang si Lito. Dito, nalutas na ang problema.', 'Ang Gitna ay ang problema. Dito, nalutas na ang problema dahil dinala ng ina ang baunan.', ''], whyEn: ['At the Beginning, we just meet Lito. Here, the problem is already solved.', 'The Middle is the problem. Here the problem is already solved, because his mother brought the lunchbox.', ''], tip: 'Itanong: nalutas na ba ang problema? Kung oo, Wakas iyan.', tipEn: 'Ask: is the problem solved now? If yes, it is the End.' },
    { q: 'Tama o Mali: Sa SIMULA ng kuwento, ipinakikilala ang mga tauhan at tagpuan.', qen: 'True or False: At the BEGINNING, we meet the characters and the setting.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama — sa Simula makikilala ang tauhan at tagpuan.', en: 'True.', why: ['', 'Pinili mo ang Mali, pero tama ito. Sa Simula talaga ipinakikilala ang tauhan at tagpuan, gaya ni Lito na pumasok sa paaralan.'], whyEn: ['', 'You said False, but it is true. The Beginning really is where we meet the characters and the setting, like Lito going to school.'], tip: 'Tandaan ang ayos: Simula → tauhan at tagpuan. Gitna → problema. Wakas → nalutas.', tipEn: 'Remember the order: Beginning → characters and setting. Middle → problem. End → solved.' },
    { q: 'Sa "Ang Leon at ang Daga," ano ang ginawa ng daga para matulungan ang leon?', qen: 'In "The Lion and the Mouse," what did the mouse do to help the lion?', options: ['Kinagat ang lubid', 'Tumakbo palayo', 'Umawit', 'Natulog sa tabi ng leon buong araw'], correct: 0, explain: 'Kinagat ng daga ang lubid para mapalaya ang leon.', en: 'The mouse bit the rope to free the lion.', why: ['', 'Hindi tumakbo palayo ang daga. Tumulong siya sa leon.', 'Hindi umawit ang daga. Kinagat niya ang lubid.', 'Hindi natulog ang daga. Kinagat niya ang lubid para mapalaya ang leon.'], whyEn: ['', 'The mouse did not run away. It helped the lion.', 'The mouse did not sing. It bit the rope.', 'The mouse did not sleep. It bit the rope to free the lion.'], tip: 'Isipin ang problema ng leon: kailangan niyang mapalaya. Ano ang ginawa ng daga para mangyari iyon?', tipEn: 'Think about the lion&rsquo;s problem: it needed to be set free. What did the mouse do to make that happen?' },
    { q: 'Ano ang aral ng "Ang Leon at ang Daga"?', qen: 'What is the lesson of "The Lion and the Mouse"?', options: ['Huwag maliitin ang iba — kahit maliit ay makatutulong', 'Laging matulog nang maaga', 'Huwag tumulong sa iba', 'Ang malalaki at malalakas lang ang may kakayahang tumulong'], correct: 0, explain: 'Huwag maliitin ang iba, dahil kahit maliit ay maaaring makatulong.', en: 'Do not look down on others. Even small ones can help.', why: ['', 'Walang tungkol sa pagtulog sa kuwento.', 'Kabaligtaran ito — tumulong ang daga sa leon.', 'Kabaligtaran ito. Maliit ang daga, pero nakatulong siya.'], whyEn: ['', 'The story is not about sleeping.', 'This is the opposite. The mouse helped the lion.', 'This is the opposite. The mouse is small, but it helped.'], tip: 'Isipin kung sino ang maliit at sino ang malaki sa kuwento. Sino ang tumulong? Doon ang aral.', tipEn: 'Think about who is small and who is big in the story. Who helped? That is the lesson.' },
    { q: 'Sa "Alamat ng Pinya," bakit marami raw "mata" ang pinya?', qen: 'In "The Legend of the Pineapple," why does the pineapple have many "eyes"?', options: ['Dahil ito ang naging bunga ng sinabi ng ina ni Pina', 'Dahil mahilig itong tumingin sa lahat ng dumaraan sa hardin', 'Dahil ito ay puno', 'Dahil kulay dilaw ito'], correct: 0, explain: 'Nasabi ng ina na sana magkaroon si Pina ng maraming mata — at ito ang naging pinya.', en: 'Her mother wished Pina had many eyes.', why: ['', 'Hindi ito ang dahilan sa kuwento. Galing ang mga mata sa nasabi ng ina ni Pina.', 'Hindi ito ang dahilan. Ang mga mata ay galing sa nasabi ng ina ni Pina.', 'Walang sinabi ang kuwento tungkol sa kulay. Ang mga mata ay galing sa nasabi ng ina.'], whyEn: ['', 'This is not the reason in the story. The eyes came from what Pina&rsquo;s mother said.', 'This is not the reason. The eyes came from what Pina&rsquo;s mother said.', 'The story says nothing about color. The eyes came from what her mother said.'], tip: 'Alalahanin ang nangyari sa kuwento: ano ang nasabi ng ina kay Pina? Doon nanggaling ang mga mata.', tipEn: 'Remember what happened in the story: what did the mother say about Pina? That is where the eyes came from.' },
    { q: 'Ano ang aral ng "Alamat ng Pinya"?', qen: 'What is the lesson of "The Legend of the Pineapple"?', options: ['Maging masipag at huwag agad umasa sa iba', 'Laging magpahanap ng mga nawawalang gamit sa nanay', 'Huwag kumain ng prutas', 'Matulog nang maaga'], correct: 0, explain: 'Maging masipag at huwag agad umasa sa iba.', en: 'Work hard and do not depend on others right away.', why: ['', 'Iyan ang ginagawa ni Pina na hindi mabuti. Ang aral ay huwag agad umasa sa iba.', 'Walang sinabi ang kuwento tungkol sa hindi pagkain ng prutas.', 'Walang tungkol sa pagtulog sa kuwento.'], whyEn: ['', 'That is what Pina did, and it was not good. The lesson is not to depend on others right away.', 'The story does not say anything about not eating fruit.', 'The story is not about sleeping.'], tip: 'Isipin ang maling ginawa ni Pina. Ang aral ay ang kabaligtaran nito.', tipEn: 'Think about what Pina did wrong. The lesson is the opposite of that.' },
    { q: 'Ano ang katangian ng maikling kwento?', qen: 'What is a feature of a short story?', options: ['Napakahaba', 'May simula, gitna, at wakas', 'Walang tauhan', 'Walang suliranin at walang nangyayari sa kuwento'], correct: 1, explain: 'Ang maikling kwento ay may simula, gitna, at wakas, may suliranin, at may tauhan.', en: 'It has a beginning, middle, and end.', why: ['Maikli ang maikling kwento — mabilis itong basahin, hindi napakahaba.', '', 'May mga tauhan ang maikling kwento.', 'May isang suliranin (problema) ang maikling kwento.'], whyEn: ['A short story is short. It is quick to read, not very long.', '', 'A short story has characters.', 'A short story has one problem.'], tip: 'Basahin ang pangalan: MAIKLING kwento. Tandaan: may simula-gitna-wakas, tauhan, at problema.', tipEn: 'Read the name: SHORT story. Remember: it has a beginning-middle-end, characters, and a problem.' },
    { q: 'Tama o Mali: Ang alamat ay nagsasabi kung paano nagsimula ang isang bagay, hayop, o lugar.', qen: 'True or False: A legend (alamat) tells how something, an animal, or a place began.', options: ['Tama', 'Mali'], correct: 0, explain: 'Tama — iyan ang alamat. Hal: Alamat ng Pinya.', en: 'True.', why: ['', 'Pinili mo ang Mali, pero tama ito. Ang alamat ay nagsasabi kung paano nagsimula ang isang bagay, gaya ng pinya sa Alamat ng Pinya.'], whyEn: ['', 'You said False, but it is true. A legend tells how something began, like the pineapple in the Legend of the Pineapple.'], tip: 'Tandaan: alamat → PAANO NAGSIMULA. Isipin ang Alamat ng Pinya.', tipEn: 'Remember: legend → HOW IT BEGAN. Think of the Legend of the Pineapple.' }
  ]
});
