StudyKit.lesson({
  id: 'netwall',
  icon: '🏓',
  title: 'Net & Wall Games',
  subtitle: 'Pickleball, wall ball & equipment',
  cards: [
    { front: 'What Are Net and Wall Games?', back: 'Activities where players send an object (like a ball) back and forth OVER a net or AGAINST a wall.' },
    { front: 'Pickleball', back: 'Using paddles to hit a ball over a LOW net.' },
    { front: 'Wall Ball', back: 'Bouncing or throwing a ball against a wall so another player can catch or return it.' },
    { front: 'Why Play Them?', back: 'They promote active living and overall health, and they develop important movement skills.' },
    { front: 'Pickleball Equipment', back: 'Lightweight kid-friendly paddles, perforated plastic pickleballs, a low or portable net, court markers (cones, floor tape, chalk), and boundary lines.' },
    { front: 'Wall Ball Equipment', back: 'Rubber or foam balls (safe indoors and outdoors), a smooth wall surface, floor markers for distance lines, and chalk or tape to mark target zones on the wall.' },
    { front: 'Remember', back: 'Net and wall games are not just fun — they build the movement skills you use in every sport.' }
  ],
  quiz: [
    { q: 'True or False: In net and wall games, players send an object back and forth over a net or against a wall.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is exactly the definition of net and wall games.', why: ['', 'False is not right because the statement matches the definition exactly: an object goes back and forth OVER a net or AGAINST a wall.'], tip: 'Check each part of the statement against the flashcard. Net games go OVER a net, wall games go AGAINST a wall. If every part matches, it is True.' },
    { q: 'Which equipment belongs to PICKLEBALL and not to wall ball?', options: ['A smooth wall surface', 'A perforated plastic ball and a paddle', 'Chalk for wall targets', 'A rubber or foam ball'], correct: 1, explain: 'Pickleball uses lightweight paddles and a perforated plastic ball. The wall, chalk targets, and foam balls belong to wall ball.', why: ['A smooth wall surface is wall ball equipment, because you bounce the ball against it. Pickleball needs a net, not a wall.', '', 'Chalk for wall targets is wall ball equipment. It marks target zones on the wall.', 'A rubber or foam ball is the wall ball ball. Pickleball uses a perforated plastic ball.'], tip: 'Ask yourself, “Does this thing need a wall?” If yes, it belongs to wall ball. Pickleball’s must-haves are a paddle, a ball with holes, and a low net.' },
    { q: 'True or False: Pickleball is played by hitting a ball over a very HIGH net.', options: ['True', 'False'], correct: 1, explain: 'False — pickleball uses a LOW net. That is one of the things that makes it easy for beginners to learn.', why: ['True is not right because of the word HIGH. Pickleball uses a LOW net, so the statement has the height swapped.', ''], tip: 'Watch for size words like HIGH or LOW in a True/False. Memory hook: pickleball = paddle + LOW net.' },
    { q: 'Ramon throws a ball against the gym wall so his partner can catch it and return it. Which game is he playing?', options: ['Pickleball', 'Wall ball', 'Basketball', 'Volleyball'], correct: 1, explain: 'Bouncing or throwing a ball against a wall for another player to catch or return is wall ball.', why: ['Pickleball uses paddles to hit a ball over a low net. Ramon has no paddle and no net. He uses a wall.', '', 'Basketball is not one of the net and wall games in this lesson. Throwing a ball against a wall for a partner to catch or return is wall ball.', 'Volleyball is not taught in this lesson. The clue is the WALL: throwing against a wall so a partner can catch or return it is wall ball.'], tip: 'Look for the clue object in the story. A wall means wall ball; a paddle and a low net mean pickleball.' },
    { q: 'True or False: Net and wall games help promote active living and overall health.', options: ['True', 'False'], correct: 0, explain: 'Correct — the lesson lists promoting active living and overall health as a key reason for playing them.', why: ['', 'False is not right because the lesson lists promoting active living and overall health as a reason to play net and wall games.'], tip: 'Remember the “Why Play Them?” card: active living, overall health, and movement skills. If a statement names one of these, it is True.' },
    { q: 'Your class is setting up a pickleball court in the covered court. Which items do you need for the boundaries?', options: ['Cones, floor tape, or chalk', 'A basketball ring', 'Foam mats', 'A whistle only'], correct: 0, explain: 'Court markers such as cones, floor tape, or chalk are used to mark the court and boundary lines.', why: ['', 'A basketball ring is not on the pickleball equipment list, and it cannot mark boundary lines on the floor.', 'Foam mats are not on the pickleball equipment list, and they do not mark lines.', 'A whistle cannot draw any lines. Boundaries need court markers like cones, floor tape, or chalk.'], tip: 'Boundaries are lines on the floor, so ask, “Which items can MARK the floor?” Cones, tape, and chalk can.' },
    { q: 'True or False: Wall ball needs a rough, bumpy wall so the ball bounces in surprising directions.', options: ['True', 'False'], correct: 1, explain: 'False — wall ball needs a SMOOTH wall surface, such as a gym wall or an outdoor wall.', why: ['True is not right because of the words ROUGH and BUMPY. Wall ball needs a SMOOTH wall surface.', ''], tip: 'Spot describing words like rough, smooth, high, or low, and check them against the equipment list. Wall ball says SMOOTH wall.' },
    { q: 'Why are foam or rubber balls used for wall ball in school?', options: ['They are the most expensive', 'They are safe for indoor and outdoor use', 'They are the heaviest', 'They never bounce'], correct: 1, explain: 'The lesson lists rubber or foam balls because they are safe for both indoor and outdoor play.', why: ['The lesson never chooses balls for being expensive. Rubber or foam balls are chosen because they are safe.', '', 'Being heavy is not the reason. The lesson says rubber or foam balls are chosen because they are safe indoors and outdoors.', 'Wall ball needs the ball to bounce off the wall, so a ball that never bounces would not work.'], tip: 'When a question asks WHY equipment is used in school, think about safety first. The card says rubber or foam balls are “safe indoors and outdoors.”' },
    { q: 'True or False: A pickleball paddle for children should be lightweight and kid-friendly.', options: ['True', 'False'], correct: 0, explain: 'Correct — the equipment list specifies lightweight, kid-friendly paddles.', why: ['', 'False is not right because the equipment list says the paddles are lightweight and kid-friendly.'], tip: 'Link “children” with “lightweight”. Pickleball paddles in this lesson are light and kid-friendly.' },
    { q: 'Your teacher says, "Today we will play a net game." Which activity fits BEST?', options: ['Running laps around the field', 'Pickleball over a low net', 'Sit-ups in pairs', 'Rope climbing'], correct: 1, explain: 'Pickleball sends a ball over a net, so it is a net game. The others do not involve sending an object over a net.', why: ['Running laps does not send any object over a net, so it is not a net game.', '', 'Sit-ups in pairs are an exercise. No ball goes over a net, so it is not a net game.', 'Rope climbing has no ball and no net, so it is not a net game.'], tip: 'For a “net game”, ask, “Is something being sent OVER a net?” Only one choice has a net in it.' }
  ]
});
