StudyKit.lesson({
  id: 'gameon',
  icon: '🥅',
  title: 'Game On!',
  subtitle: 'Positioning, attacking & defending',
  cards: [
    { front: 'Positioning', back: 'Being in the right place at the right time.' },
    { front: 'The Ready Position', back: 'Knees bent and paddle or hand up — so you can react to the ball in any direction.' },
    { front: 'Move Back to the Centre', back: 'After you hit, move to the centre so you can cover more space. Stay alert to where the ball might go next.' },
    { front: 'Attacking', back: 'Trying to score or win the rally. Hit the ball into open spaces, use fast and strong shots (but controlled!), and aim low in pickleball to make the ball harder to return.' },
    { front: 'Defending', back: 'Stopping your opponent from scoring. Stay balanced and ready to react, move quickly to block or return shots, and use high, safe returns to give yourself time to recover.' },
    { front: 'Attack vs Defend', back: 'Attacking = hit to open space, low and fast. Defending = high and safe, so you have time to get back into position.' },
    { front: 'Remember', back: 'Good players are not just fast — they are in the right place, ready before the ball arrives.' }
  ],
  quiz: [
    { q: 'True or False: Positioning means being in the right place at the right time.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is exactly how the lesson defines positioning.', why: ['', 'False is not right because “being in the right place at the right time” is exactly how the lesson defines positioning.'], tip: 'Memory hook: POSITIONing is about your position, or PLACE. Right place + right time = positioning.' },
    { q: 'What does the READY POSITION look like?', options: ['Standing straight with arms down', 'Knees bent with paddle or hand up', 'Sitting on the floor', 'Leaning on the net'], correct: 1, explain: 'The ready position is knees bent and paddle or hand up, so you can move in any direction.', why: ['Standing straight with arms down is not ready: your knees are not bent and your paddle or hand is not up.', '', 'Sitting on the floor means you cannot move toward the ball at all.', 'Leaning on the net is not the ready position. You need knees bent and paddle or hand up.'], tip: 'Ask yourself, “Could I move quickly in any direction from here?” Bent knees and a raised paddle or hand let you.' },
    { q: 'True or False: After hitting the ball, you should stay exactly where you are and wait.', options: ['True', 'False'], correct: 1, explain: 'False — the lesson says move to the centre after hitting so you can cover more space.', why: ['True is not right because the lesson says to MOVE back to the centre after you hit, so you can cover more space.', ''], tip: 'Remember “Hit, then back to the centre.” A statement that says stay where you are and wait is False.' },
    { q: 'You want to WIN the rally. Where should you aim the ball?', options: ['Straight at your opponent', 'Into the open space', 'Into the net', 'Out of bounds'], correct: 1, explain: 'Attacking means hitting the ball to open spaces, where your opponent is not standing.', why: ['Hitting straight at your opponent sends the ball to where they already are, so it is easy for them to return.', '', 'A ball hit into the net does not reach your opponent’s side, so it cannot win the rally.', 'Out of bounds is outside the boundary lines. To attack, you aim for the open space where your opponent is not standing.'], tip: 'Attack = aim where your opponent is NOT. Look for the open space.' },
    { q: 'True or False: When attacking in pickleball, you should aim HIGH to make the ball harder to return.', options: ['True', 'False'], correct: 1, explain: 'False — aim LOW in pickleball. A low ball is much harder for your opponent to return.', why: ['True is not right because of the word HIGH. When attacking in pickleball you aim LOW, because a low ball is harder to return.', ''], tip: 'Memory hook: Attack LOW and fast, Defend HIGH and safe. First check which one the statement is about.' },
    { q: 'Your opponent hit a hard shot and you are off balance at the side of the court. What is the BEST defending choice?', options: ['A high, safe return to give yourself time to recover', 'A hard smash straight down', 'Ignore the ball', 'Run to the net and stand still'], correct: 0, explain: 'Defending means using high, safe returns that give you time to recover and get back into position.', why: ['', 'A hard smash is an attacking shot. When you are off balance you need time to recover, so you defend with a high, safe return.', 'If you ignore the ball, you are not defending at all, and your opponent can score.', 'Running to the net and standing still does not return the ball. Defending means staying ready to react and move.'], tip: 'First decide: am I attacking or defending? If you are off balance or in trouble, you are defending, so choose high and safe.' },
    { q: 'True or False: Attacking shots should be fast and strong, but still controlled.', options: ['True', 'False'], correct: 0, explain: 'Correct — the lesson says to use fast and strong shots, but controlled.', why: ['', 'False is not right because the lesson says attacking shots are fast and strong, but controlled.'], tip: 'Look for the word “but”. Attacking shots are strong AND controlled at the same time, just like the Attacking card says.' },
    { q: 'Which of these BEST describes defending?', options: ['Trying to score as fast as possible', 'Stopping the opponent from scoring', 'Standing in the kitchen', 'Serving the ball'], correct: 1, explain: 'Defending is stopping the opponent from scoring — staying balanced, moving quickly, and returning safely.', why: ['Trying to score is ATTACKING, not defending.', '', 'Standing in the kitchen is about the Non-Volley Zone, not what defending means.', 'Serving the ball is not what defending means. Defending is stopping your opponent from scoring.'], tip: 'Attacking and defending are opposites: attacking tries to score, defending stops the other side from scoring.' },
    { q: 'True or False: Defending means using low, fast smashes to win the point quickly.', options: ['True', 'False'], correct: 1, explain: 'False — that describes ATTACKING. Defending means staying balanced and using high, safe returns that give you time to recover.', why: ['True is not right because low, fast smashes to win the point describe ATTACKING. Defending uses high, safe returns.', ''], tip: 'If a statement puts an attacking shot under the word “defending” (or the other way around), it is False. Attack = low and fast; Defend = high and safe.' },
    { q: 'Lara keeps getting beaten by shots to the far corner because she stands on one side after every hit. What should she change?', options: ['Hit harder every time', 'Move back to the centre after hitting', 'Stand closer to the net and stay there', 'Stop moving completely'], correct: 1, explain: 'Moving to the centre after hitting lets her cover more space, so corner shots are easier to reach.', why: ['Hitting harder does not change where she stands. Her problem is that she stays on one side.', '', 'Standing close to the net and staying there still leaves her stuck in one spot, so the far corner stays hard to reach.', 'If she stops moving completely, she cannot reach any shot at all.'], tip: 'Find the cause of the problem in the story: she stands on one side after every hit. Then use the Positioning rule to fix it.' }
  ]
});
