StudyKit.lesson({
  id: 'kitchen',
  icon: '🍳',
  title: 'Pickleball Facts & The Kitchen',
  subtitle: 'History, the ball & the Non-Volley Zone',
  cards: [
    { front: 'Where and When It Began', back: 'Pickleball started in 1965 on Bainbridge Island, Washington, USA.' },
    { front: 'Who Invented It', back: 'Joel Pritchard, Bill Bell, and Barney McCallum — as a backyard game for their families.' },
    { front: 'How It Started', back: 'They improvised with ping-pong paddles, a perforated plastic ball, and a badminton court, and eventually developed the rules of the sport we know today.' },
    { front: 'The Pickleball', back: 'A perforated plastic ball — a lightweight ball with holes in it.' },
    { front: 'What Is "The Kitchen"?', back: 'The informal name for the Non-Volley Zone (NVZ).' },
    { front: 'How Big Is the Kitchen?', back: 'It is the 7-foot area on BOTH sides of the net.' },
    { front: 'The Kitchen Rule', back: 'Players cannot hit a volley (hitting the ball before it bounces) while standing inside the kitchen.' },
    { front: 'You CAN Enter the Kitchen', back: 'Players may enter the kitchen to hit a ball AFTER it bounces. The rule only stops volleys.' },
    { front: 'Why the Kitchen Exists', back: 'It prevents players from standing too close to the net and constantly smashing the ball.' }
  ],
  quiz: [
    { q: 'True or False: Pickleball started in 1965 on Bainbridge Island, Washington, USA.', options: ['True', 'False'], correct: 0, explain: 'Correct — 1965, Bainbridge Island, Washington, USA.', why: ['', 'False is not right because the year (1965) and the place (Bainbridge Island, Washington, USA) both match the lesson.'], tip: 'For history True/False items, check each detail one by one: the year, then the place. If every detail matches the card, it is True.' },
    { q: 'Who invented pickleball?', options: ['Joel Pritchard, Bill Bell, and Barney McCallum', 'James Naismith', 'William G. Morgan', 'Walter Camp'], correct: 0, explain: 'Joel Pritchard, Bill Bell, and Barney McCallum invented it as a backyard game for their families.', why: ['', 'James Naismith is not one of the people this lesson names as pickleball’s inventors.', 'William G. Morgan is not one of the people this lesson names as pickleball’s inventors.', 'Walter Camp is not one of the people this lesson names as pickleball’s inventors.'], tip: 'Pickleball had THREE inventors. Look for the choice with three names: Pritchard, Bell, and McCallum.' },
    { q: 'True or False: A pickleball is a heavy rubber ball with a smooth surface.', options: ['True', 'False'], correct: 1, explain: 'False — a pickleball is a perforated plastic ball: lightweight, with holes in it.', why: ['True is not right because a pickleball is a LIGHTWEIGHT PLASTIC ball WITH HOLES. It is not heavy, not rubber, and not smooth.', ''], tip: 'Remember “perforated plastic” = light plastic with holes. A statement that says heavy, rubber, or smooth is False.' },
    { q: 'What is the real name of "the kitchen" in pickleball?', options: ['The service box', 'The Non-Volley Zone (NVZ)', 'The baseline', 'The centre line'], correct: 1, explain: '"The kitchen" is the informal name for the Non-Volley Zone, or NVZ.', why: ['The service box is not the kitchen. The kitchen’s real name is the Non-Volley Zone.', '', 'The baseline is not the kitchen. The kitchen is the Non-Volley Zone, the 7-foot area on both sides of the net.', 'The centre line is not the kitchen. The kitchen is the Non-Volley Zone.'], tip: 'Link “kitchen” to its rule: no volleys there. That is why its real name is the NON-VOLLEY Zone.' },
    { q: 'True or False: The kitchen is a 7-foot area on both sides of the net.', options: ['True', 'False'], correct: 0, explain: 'Correct — the kitchen is the 7-foot Non-Volley Zone on both sides of the net.', why: ['', 'False is not right because the lesson says the kitchen is the 7-foot area on BOTH sides of the net.'], tip: 'Memory hook: 7 feet, both sides of the net. Check the number and the word “both”.' },
    { q: 'You are standing inside the kitchen and the ball comes toward you in the air, before bouncing. What are you NOT allowed to do?', options: ['Step backward out of the kitchen', 'Hit it as a volley while standing in the kitchen', 'Let it bounce first', 'Call for your partner'], correct: 1, explain: 'You cannot hit a volley — hitting the ball before it bounces — while standing inside the kitchen.', why: ['Stepping backward out of the kitchen is allowed. The rule only stops volleys inside the kitchen.', '', 'Letting the ball bounce first is allowed. After it bounces, you may even hit it inside the kitchen.', 'Calling for your partner is allowed. The kitchen rule is only about volleys.'], tip: 'The question asks what is NOT allowed. The only thing banned in the kitchen is a volley: hitting the ball before it bounces.' },
    { q: 'True or False: Players are never allowed to step into the kitchen for any reason.', options: ['True', 'False'], correct: 1, explain: 'False — players CAN enter the kitchen to hit a ball after it bounces. Only volleys are banned there.', why: ['True is not right because of the word NEVER. Players CAN enter the kitchen to hit a ball after it bounces.', ''], tip: 'Words like “never” and “always” are warning signs. The kitchen rule stops volleys only, not stepping in.' },
    { q: 'The ball bounces inside the kitchen. What may you do?', options: ['Nothing — it is an automatic loss', 'Step in and hit it after the bounce', 'Volley it from inside the kitchen', 'Catch it with your hand'], correct: 1, explain: 'Once the ball has bounced, you may enter the kitchen and hit it. The rule only stops volleys.', why: ['It is not an automatic loss. Once the ball bounces, you are allowed to step in and hit it.', '', 'A volley means hitting the ball before it bounces, and volleying from inside the kitchen is exactly what the rule does not allow.', 'Pickleball uses paddles to hit the ball, so catching it with your hand is not a pickleball shot.'], tip: 'Ask, “Has the ball bounced yet?” Bounced = you may hit it in the kitchen. Not bounced yet = no volley from the kitchen.' },
    { q: 'Why does the kitchen rule exist?', options: ['To make the court look nicer', 'To stop players standing too close to the net and constantly smashing', 'To give the referee somewhere to stand', 'To slow down the serve'], correct: 1, explain: 'The kitchen prevents players from standing right at the net and smashing every ball downward.', why: ['The kitchen is a rule about how you play, not decoration for the court.', '', 'The kitchen is not a place for the referee. It is the Non-Volley Zone for players.', 'The kitchen rule is about volleys near the net, not about the serve.'], tip: 'Think about what the rule stops: no volleys close to the net. So it keeps players from standing at the net and smashing every ball.' },
    { q: 'True or False: The inventors of pickleball first used ping-pong paddles and a badminton court.', options: ['True', 'False'], correct: 0, explain: 'Correct — they improvised with ping-pong paddles, a perforated plastic ball, and a badminton court.', why: ['', 'False is not right because the lesson says they improvised with ping-pong paddles, a perforated plastic ball, and a badminton court.'], tip: 'Memory hook: pickleball borrowed from other games — PING-PONG paddles on a BADMINTON court.' }
  ]
});
