StudyKit.lesson({
  id: 'stress',
  icon: '🧠',
  title: 'Stress & Healthy Coping',
  subtitle: 'Signs of stress, healthy vs unhealthy choices',
  cards: [
    { front: 'What Is Stress?', back: 'The feeling of being worried, overwhelmed or under pressure &mdash; often from <b>responsibilities</b> like many assignments or an upcoming quiz.' },
    { front: 'Signs of Stress', back: 'Feeling <b>worried</b>, <b>overwhelmed</b>, <b>nervous</b>, <b>anxious</b>, <b>tense</b>, <b>frustrated</b> or <b>mentally tired</b>, and having <b>difficulty concentrating</b>.' },
    { front: 'Healthy Coping', back: 'Deals with the problem <b>calmly</b>: make a plan, take a short break, organize your tasks, ask for help, practise ahead, breathe deeply, move your body.' },
    { front: 'Unhealthy Coping', back: 'Runs away from the problem or makes it worse: avoiding people or school, <b>blaming others</b>, pretending to be sick, staying up late on games, scrolling for hours, <b>comparing yourself</b> with classmates, ignoring your work.' },
    { front: 'Positive Thinking', back: 'Reminding yourself that <b>mistakes are part of learning</b> and that you <b>can improve with more practice</b>.' },
    { front: 'Low Score? Make a Plan', back: 'Sofia felt disappointed after a low score. The healthy choice: <b>create a plan to improve her study habits</b> &mdash; not blame others or stay away from school.' },
    { front: 'Overwhelmed? Break, Organize, Ask', back: 'Marco still had unfinished homework. First: <b>take a short break, organize his tasks, and ask for help if needed</b>.' },
    { front: 'Nervous? Prepare and Breathe', back: 'Paolo before presenting: <b>deep breathing and reviewing calmly</b>. Alyssa after forgetting her lines: <b>practise ahead of time and use deep breathing</b>.' }
  ],
  quiz: [
    { q: 'Miguel has several assignments and an upcoming quiz. He starts feeling worried and overwhelmed. What is the feeling Miguel is experiencing?', options: ['stress caused by pressure from responsibilities', 'happiness from having free time', 'confidence from being well-prepared', 'excitement about learning new lessons'], correct: 0, explain: 'Worried and overwhelmed by assignments and a quiz &mdash; that is <b>stress</b> from the pressure of responsibilities.', why: ['', 'Happiness from free time does not fit. Miguel has lots of work and feels worried, not free.', 'Confidence from being well-prepared does not fit. He feels overwhelmed, not ready and sure.', 'Excitement about learning does not fit. Worried and overwhelmed are signs of stress, not excitement.'], tip: 'Look for the feeling words in the story: worried and overwhelmed. Those are signs of stress, so pick the choice that names stress.' },
    { q: 'After getting a low score on a test, Sofia feels disappointed. Which action demonstrates a healthy way of coping with stress?', options: ['creating a plan to improve her study habits', 'avoiding her classmates', 'blaming others for the result instead of reflecting on her mistakes', 'staying away from school until she feels better about the test result'], correct: 0, explain: 'A plan faces the problem and fixes it. Avoiding, blaming and staying away only make it worse.', why: ['', 'Avoiding her classmates runs away from the problem. That is unhealthy coping.', 'Blaming others is unhealthy coping. It stops her from reflecting on her own mistakes, so nothing improves.', 'Staying away from school avoids the problem, and the test result is still there. That is unhealthy coping.'], tip: 'Ask, “Does this choice FACE the problem and fix it, or RUN AWAY from it?” Healthy coping faces it, like making a plan.' },
    { q: 'Paolo feels nervous before presenting in front of the class. Which action is most likely to help him manage his stress in a healthy way?', options: ['practicing deep breathing and reviewing his presentation calmly', 'pretending to be sick so he can skip the presentation', 'playing online games until late at night to forget about it', 'comparing himself with classmates who speak better than he does'], correct: 0, explain: 'Deep breathing calms him, and reviewing prepares him. The other choices avoid the problem or make him feel worse.', why: ['', 'Pretending to be sick avoids the presentation, but it is still waiting for him. That is unhealthy coping.', 'Staying up late on games is on the unhealthy list. It helps him forget instead of prepare.', 'Comparing himself with classmates is unhealthy coping, and it makes him feel worse.'], tip: 'For “nervous before an event” questions, look for the choice that calms you AND prepares you. Deep breathing calms; reviewing prepares.' },
    { q: 'After studying for several hours, Marco feels overwhelmed because he still has unfinished homework. What should Marco do <b>first</b> to cope with his stress in a healthy way?', options: ['Take a short break, organize his tasks, and ask for help if needed.', 'Stay awake until midnight to finish everything at once.', 'Compare his work with his classmates and worry about finishing first.', 'Ignore all his homework and play online games for the rest of the day.'], correct: 0, explain: 'Rest a little, then make the work manageable. Staying up until midnight, comparing and ignoring the work all add stress.', why: ['', 'Staying up until midnight adds more stress, and staying up late is on the unhealthy list.', 'Comparing his work with classmates is unhealthy coping, and it makes him worry more.', 'Ignoring his homework and playing games runs away from the problem. The homework is still there.'], tip: 'Notice the word FIRST. When you feel overwhelmed, first rest a little and make the work manageable: break, organize, ask.' },
    { q: 'Alyssa becomes upset after forgetting her lines during a class presentation. She still has another presentation next week. What is the <b>BEST</b> way for Alyssa to cope with her stress?', options: ['Practice her presentation ahead of time and use deep breathing to stay calm.', 'Avoid volunteering for presentations again.', 'Blame her classmates for making her nervous.', 'Tell everyone she does not care about her grades.'], correct: 0, explain: 'Practising ahead fixes the cause (forgetting lines) and deep breathing handles the nerves.', why: ['', 'Avoiding presentations runs away from the problem, and she still has one next week.', 'Blaming her classmates is unhealthy coping. It does not help her remember her lines.', 'Saying she does not care does not fix anything. It ignores the problem instead of preparing for next week.'], tip: 'Find the CAUSE in the story (she forgot her lines), then pick the choice that fixes that cause. Practising ahead fixes forgetting.' },
    { q: 'True or False: Blaming others for a low score is a healthy way of coping with stress.', options: ['True', 'False'], correct: 1, explain: 'False — blaming others stops you from <b>reflecting on your own mistakes</b>, so nothing improves.', why: ['True is not right because blaming others is on the UNHEALTHY list. It stops you from reflecting on your own mistakes.', ''], tip: 'Sort the action into a box: faces the problem calmly = healthy; blames, avoids, or pretends = unhealthy.' },
    { q: 'True or False: Taking a short break and organizing your tasks can help when you feel overwhelmed.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is exactly what Marco should do first.', why: ['', 'False is not right because taking a short break and organizing your tasks is exactly what Marco should do first when he feels overwhelmed.'], tip: 'Remember Marco’s three steps: Break, Organize, Ask. If a statement names them for feeling overwhelmed, it is True.' },
    { q: 'True or False: Pretending to be sick to skip a presentation is a healthy way to manage stress.', options: ['True', 'False'], correct: 1, explain: 'False — it avoids the problem, and the presentation is still waiting. Practising and deep breathing are the healthy choices.', why: ['True is not right because pretending to be sick is on the UNHEALTHY list. It only avoids the presentation.', ''], tip: 'Ask, “After I do this, is the problem still waiting?” If yes, the choice is avoiding it, and avoiding is unhealthy.' },
    { q: 'True or False: Feeling tense and having difficulty concentrating can be signs of stress.', options: ['True', 'False'], correct: 0, explain: 'Correct — Joshua on your test felt exactly this after a long day of schoolwork.', why: ['', 'False is not right because feeling tense and having difficulty concentrating are both on the Signs of Stress card.'], tip: 'Learn the Signs of Stress card: worried, overwhelmed, nervous, anxious, tense, frustrated, mentally tired, and difficulty concentrating.' },
    { q: 'Which of these is an example of <b>positive thinking</b>?', options: ['&ldquo;Mistakes are part of learning. I can improve with practice.&rdquo;', '&ldquo;I always fail at this, so there is no point in trying.&rdquo;', '&ldquo;It is all my classmates&rsquo; fault that our team lost the game.&rdquo;', '&ldquo;I will never play this game again after losing it today.&rdquo;'], correct: 0, explain: 'Positive thinking reminds you that mistakes help you learn and that you can get better.', why: ['', '“There is no point in trying” gives up. Positive thinking says you can improve with practice.', 'Blaming classmates is unhealthy coping, not positive thinking.', 'Quitting forever after one loss gives up. Positive thinking says mistakes are part of learning.'], tip: 'Positive thinking has two parts: mistakes help you learn, and you can get better. Watch out for giving-up words like “always fail”, “never”, and “no point”.' },
    { q: 'Which of these is an <b>unhealthy</b> way to cope with stress?', options: ['Comparing yourself with classmates who do better', 'Asking your teacher for help with the hard lesson', 'Making a plan to improve all your study habits', 'Taking a few slow, deep breaths before you begin'], correct: 0, explain: 'Comparing yourself with others only makes you feel worse. The other three are healthy ways to cope.', why: ['', 'Asking your teacher for help IS a healthy way to cope, so it is not the answer — we need the unhealthy one.', 'Making a plan to improve IS a healthy way to cope, so it is not the answer — we need the unhealthy one.', 'Taking slow, deep breaths IS a healthy way to cope, so it is not the answer — we need the unhealthy one.'], tip: 'This question wants the UNHEALTHY one. Three choices face the problem calmly; find the one from the unhealthy list, like comparing yourself.' }
  ]
});
