StudyKit.lesson({
  id: 'puberty',
  icon: '🌱',
  title: 'Going Through Puberty',
  subtitle: 'What puberty is, when it starts & body changes',
  cards: [
    { front: 'Puberty', back: 'A period of <b>growth and changes</b> in a person’s body. It is triggered by <b>hormones</b> &mdash; special chemicals in the body that start physical and emotional changes.' },
    { front: 'When Does It Start?', back: '<b>Girls:</b> usually between ages <b>8 and 13</b>. <b>Boys:</b> usually between ages <b>9 and 14</b>. Some start earlier or later, and changes happen at different rates &mdash; that is normal.' },
    { front: 'Adolescents', back: 'The general term for kids going through puberty, in <b>transition from childhood to adulthood</b>.' },
    { front: 'Growth Spurt', back: 'A sudden, big <b>increase in height</b>, because bones and muscles grow rapidly. Everyone’s growth spurt happens at a different time.' },
    { front: 'Primary Sexual Characteristics', back: 'Physical traits <b>directly involved in reproduction</b>, including the gonads: <b>testes</b> in males and <b>ovaries</b> in females. These changes start during puberty.' },
    { front: 'For Girls: Menstruation', back: 'Most noticeable changes happen between ages <b>11 and 13</b>. The <b>menstrual cycle</b> is the body getting ready each month for possible pregnancy in the future. A period usually lasts <b>3 to 7 days</b>. A regular cycle is <b>21 to 35 days</b>. An <b>irregular</b> cycle is shorter than 21 days or longer than 35 days, with a period longer than 7 days.' },
    { front: 'The Uterus', back: 'A hollow, muscular organ, also called the <b>womb</b>, where a baby grows during pregnancy. About the size of a small pear. If there is no pregnancy, its lining sheds during menstruation. The <b>ovaries</b> make eggs, and the <b>fallopian tubes</b> carry the egg to the uterus.' },
    { front: 'For Girls: Body Changes', back: '<b>Breast development</b> is one of the first signs &mdash; it is normal for one side to grow faster at first. The <b>hips widen</b> and the body may become more curved.' },
    { front: 'For Boys', back: 'Usually begins at <b>9 to 14</b>. The <b>testicles</b> (testes) make sperm and the hormone <b>testosterone</b>.' }
  ],
  quiz: [
    { q: 'According to the lesson, puberty for <b>girls</b> typically begins between which ages?', options: ['8 and 13', '9 and 14', '15 and 18', '3 and 5'], correct: 0, explain: 'For girls, puberty typically begins between <b>8 and 13</b>.', why: ['', '9 to 14 is the range the lesson gives for BOYS.', '15 to 18 is later than the usual range.', '3 to 5 is early childhood, far too young.'], tip: 'Girls usually start a little earlier: 8–13. Boys: 9–14.' },
    { q: 'According to the lesson, puberty for <b>boys</b> typically begins between which ages?', options: ['9 and 14', '8 and 13', '16 and 20', '4 and 6'], correct: 0, explain: 'For boys, puberty typically begins between <b>9 and 14</b>.', why: ['', '8 to 13 is the range the lesson gives for GIRLS.', '16 to 20 is later than the usual range.', '4 to 6 is early childhood, far too young.'], tip: 'Boys = one year later on both ends: 9–14.' },
    { q: 'What <b>triggers</b> puberty?', options: ['hormones', 'eating more rice', 'doing more exercise', 'going to a new school'], correct: 0, explain: 'Puberty is triggered by <b>hormones</b>, special chemicals that start physical and emotional changes.', why: ['', 'Food does not start puberty. Hormones do.', 'Exercise keeps you healthy, but it does not start puberty.', 'Changing schools is a life change, not what starts puberty.'], tip: 'Hormones are the body’s messengers that say “time to grow!”' },
    { q: 'A sudden, big increase in height during puberty is called a ____.', options: ['growth spurt', 'mood swing', 'voice crack', 'menstrual cycle'], correct: 0, explain: 'That is a <b>growth spurt</b>: bones and muscles grow rapidly.', why: ['', 'A mood swing is when feelings change quickly.', 'A voice crack happens when the voice box grows.', 'The menstrual cycle is the monthly cycle in girls.'], tip: 'Spurt = a sudden burst. Growth burst = growing taller fast.' },
    { q: 'What is the general term for kids going through puberty?', options: ['adolescents', 'infants', 'toddlers', 'senior citizens'], correct: 0, explain: '<b>Adolescents</b> are kids in transition from childhood to adulthood.', why: ['', 'Infants are babies.', 'Toddlers are very young children learning to walk.', 'Senior citizens are older adults.'], tip: 'Adolescent sounds like “adult” — on the way to becoming one.' },
    { q: 'How long does a <b>regular</b> menstrual cycle usually last?', options: ['21 to 35 days', '3 to 7 days', '1 to 2 days', '50 to 60 days'], correct: 0, explain: 'A regular cycle is <b>21 to 35 days</b>. The period itself lasts 3 to 7 days.', why: ['', '3 to 7 days is how long the PERIOD lasts, not the whole cycle.', '1 to 2 days is much shorter than the lesson’s range.', '50 to 60 days is longer than a regular cycle.'], tip: 'Cycle = about a month (21–35 days). Period = about a week (3–7 days).' },
    { q: 'How long does a girl’s period usually last?', options: ['3 to 7 days', '21 to 35 days', 'one whole month', 'a few minutes'], correct: 0, explain: 'A period usually lasts <b>3 to 7 days</b>, but it can be longer or shorter for some girls.', why: ['', '21 to 35 days is the whole CYCLE, not the period.', 'A whole month is about the length of the cycle, not the period.', 'A period lasts days, not minutes.'], tip: 'Period ≈ one week (3–7 days).' },
    { q: 'The uterus is also called the ____.', options: ['womb', 'ovary', 'cervix', 'fallopian tube'], correct: 0, explain: 'The uterus is also called the <b>womb</b>, where a baby grows.', why: ['', 'The ovary is a different part. It makes eggs.', 'The cervix is the lower, narrow part of the uterus, not another name for it.', 'The fallopian tube carries the egg to the uterus.'], tip: 'Uterus = womb (two names, same organ).' },
    { q: 'Which part of the female body <b>makes eggs</b>?', options: ['ovary', 'uterus', 'cervix', 'fallopian tube'], correct: 0, explain: 'The <b>ovaries</b> make eggs. There is one on each side.', why: ['', 'The uterus is where a baby grows.', 'The cervix is the lower part of the uterus.', 'The fallopian tube CARRIES the egg, it does not make it.'], tip: 'Ovary → ovum (egg). Both start with “ov”.' },
    { q: 'In boys, where are sperm and the hormone testosterone made?', options: ['in the testicles', 'in the voice box', 'in the urinary bladder', 'in the stomach'], correct: 0, explain: 'The <b>testicles</b> make sperm and the hormone <b>testosterone</b>.', why: ['', 'The voice box makes sound. It grows during puberty, but it does not make sperm.', 'The bladder holds urine.', 'The stomach digests food.'], tip: 'Testicles → testosterone. Both start with “test”.' },
    { q: 'True or False: Breast development is one of the first signs of puberty in girls, and it is normal for one side to grow faster at first.', options: ['True', 'False'], correct: 0, explain: 'Correct — both parts are on the lesson’s Breast Development slide.', why: ['', 'False is not right because the lesson says breast growth is one of the first signs, and uneven growth at first is normal.'], tip: 'Bodies grow at their own pace — even the two sides of one body.' },
    { q: 'What are <b>primary sexual characteristics</b>?', options: ['physical traits directly involved in reproduction', 'changes in friendships', 'mood swings', 'oilier skin and pimples'], correct: 0, explain: 'Primary sexual characteristics are traits <b>directly involved in reproduction</b>, like the testes and ovaries.', why: ['', 'Friendships are a SOCIAL change.', 'Mood swings are an EMOTIONAL change.', 'Oilier skin is a SECONDARY change.'], tip: 'Primary = first and most direct: the reproductive organs themselves.' },
    { q: 'Mae’s menstrual cycle is only 18 days long. What kind of cycle is this, according to the lesson?', options: ['irregular, because it is shorter than 21 days', 'regular, because it is between 21 and 35 days', 'regular, because every cycle is normal', 'irregular, because it is longer than 35 days'], correct: 0, explain: 'A regular cycle is <b>21 to 35 days</b>. A cycle <b>shorter than 21 days</b> or longer than 35 days is <b>irregular</b>.', why: ['', '18 days is NOT between 21 and 35, so it is not regular.', 'The lesson gives a regular range of 21 to 35 days. 18 days is outside it.', 'It IS irregular, but because it is SHORTER than 21 days, not longer than 35.'], tip: 'Regular = 21 to 35. Below 21 or above 35 = irregular.' }
  ]
});
