StudyKit.content('typeIt', {
  'Ano ang tawag sa mga taong sama-samang naninirahan sa isang lugar?': [],
  'Saan karaniwang makikita ang pinuno ng komunidad?': ['barangay'],
  'Ano ang tinatawag na koneksyon o relasyon na nabubuo sa pagitan ng mga kasapi ng komunidad?': [],
  'Ano ang tawag sa araw-araw na pagbabago sa ating himpapawid?': [],
  'Sino ang tanggapan ng pamahalaan na nag-uulat ng pagtataya ng panahon?': [],
  'Ano ang tawag sa pook, lugar, o puwesto kung saan matatagpuan ang isang bagay?': [],
  'Saang uri ng pook mo makikita ang malawak na palayan at tahimik na paligid?': ['rural'],
  'Ano ang tawag sa laki ng sakop ng isang lugar?': [],
  'Karaniwang saan makikita ang makapal na densidad ng populasyon?': ['urban'],
  'Anong anyong-lupa ang patag at malawak?': [],
  'Anong anyong-lupa ang mas maliit kaysa bundok?': [],
  'Anong anyong-lupa ang napapaligiran ng katubigan?': ['Pulo', 'Isla'],
  'Anong anyong-lupa ang dapat pag-ingatan lalo na kapag ito ay sumasabog?': [],
  'Ano ang pinakamalawak na anyong-tubig?': [],
  'Anong anyong-tubig ang napapalibutan ng lupa?': [],
  'Ano ang tawag sa maliit na bahagi ng dagat na napapaligiran ng lupa?': [],
  'Alin ang mahaba at makipot na anyong-tubig?': [],
  'Ano ang tawag sa biswal at patag na representasyon ng isang lugar?': [],
  'Saan karaniwang tumatakbo ang tren?': [],
  'Ano ang tawag sa nagtuturo ng kinaroroonan ng isang bagay o lugar?': ['direksyon'],
  'Ilan ang pangalawang direksiyon?': ['apat'],
  'Anong pangkat ang may edad 15 hanggang 24 na taong gulang?': ['Kabataan'],
  'Ano ang tawag sa mga taong nasa 60 taong gulang pataas?': [],
  'Ilan ang pangkat ng mga taong naninirahan sa komunidad ayon sa edad?': ['apat'],
  'Saan itinuturo ang pagbasa, pagsulat, at pagbilang?': [],
  'Sino ang tumutulong mapanatili ang seguridad at kapayapaan ng komunidad?': [],
  'Saan nabibili ang karamihan sa mga pangunahing pangangailangan ng mga tao?': ['palengke'],
  'Sino ang umaapula ng sunog?': [],
  'Sino ang nagtuturo sa mga mag-aaral sa paaralan?': [],
  'Sino ang gumugupit ng buhok?': [],
  'Saan sinusuri at ginagamot ng doktor ang mga may sakit?': []
});
