StudyKit.lesson({
  tag: 'Lesson 4',
  title: 'I Pray',
  stars: 0,
  icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><rect x="26" y="38" width="24" height="20" fill="var(--card)" stroke="var(--lav)" stroke-width="2"/><polygon points="20,38 38,22 56,38" fill="var(--lav)"/><rect x="36" y="10" width="4" height="10" fill="var(--lav)"/><rect x="33" y="13" width="10" height="3" fill="var(--lav)"/>',
  flashcards: [
    { title: 'PRAYER', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><circle cx="28" cy="34" r="7" fill="var(--lav)"/><circle cx="48" cy="34" r="7" fill="var(--lav-deep)"/><path d="M14 56c2-9 9-13 24-13s22 4 24 13" fill="none" stroke="var(--lav)" stroke-width="3" stroke-linecap="round"/>', text: 'Prayer is our way of talking to God &mdash; anytime, anywhere.' },
    { title: 'CHURCH', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><rect x="26" y="38" width="24" height="20" fill="var(--card)" stroke="var(--lav)" stroke-width="2"/><polygon points="20,38 38,22 56,38" fill="var(--lav)"/><rect x="36" y="10" width="4" height="10" fill="var(--lav)"/><rect x="33" y="13" width="10" height="3" fill="var(--lav)"/>', text: 'A special place where people go to pray, worship God, and learn about His love.' },
    { title: 'RELIGION', icon: '<circle cx="38" cy="38" r="34" fill="var(--good-soft)"/><path d="M38 52c-10-8-18-15-18-24a11 11 0 0 1 18-8 11 11 0 0 1 18 8c0 9-8 16-18 24z" fill="var(--good)"/>', text: 'What people believe about God and how they worship Him. It teaches us to pray, be kind, and do what is right.' },
    { title: 'GIVE THANKS &amp; ASK', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><path d="M22 46c0-14 32-14 32 0" fill="none" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><circle cx="38" cy="24" r="7" fill="var(--accent)"/>', text: 'We pray to thank God for our blessings, and to ask Him for help with our needs.' },
    { title: 'PRAISE &amp; BE SORRY', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><polygon points="38,18 44,32 59,33 47,42 51,57 38,48 25,57 29,42 17,33 32,32" fill="var(--lav)"/>', text: 'We pray to praise God’s goodness, and to say sorry and ask for forgiveness.' }
  ],
  quiz: [
    { type: 'mc', q: 'What is prayer?', options: [{ text: 'Our way of talking to God', correct: true }, { text: 'A kind of song', correct: false, why: 'A song is music we sing. The question asks what prayer is &mdash; it is talking to God.' }, { text: 'A type of game we play at recess', correct: false, why: 'A game at recess is for playing. Prayer is not a game; it is talking to God.' }], good: 'Yes! Prayer is our way of talking to God.', bad: 'Prayer is our way of talking to God, anytime and anywhere.', tip: 'Remember the flashcard: prayer is talking to God, anytime, anywhere. Look for the words talking to God.' },
    { type: 'mc', q: 'Where do people go to pray, worship God, and learn about His love?', options: [{ text: 'Church', correct: true }, { text: 'Market', correct: false, why: 'A market is where people buy and sell things. It is not the special place for worship.' }, { text: 'Playground', correct: false, why: 'A playground is where children play. The special place to worship God is the church.' }], good: 'That’s right! Church is a special place for that.', bad: 'Church is where people go to pray, worship God, and learn about His love.', tip: 'Look for the clue words pray and worship God. The special place for that is the church.' },
    { type: 'tf', q: 'Religion teaches people how to pray, be kind, and do what is right.', answer: true, good: 'Correct! That is what religion teaches us.', bad: 'The answer should be True &mdash; religion teaches us to pray, be kind, and do what is right.', why: 'You said False, but this is true. The lesson says religion teaches us to pray, be kind, and do what is right.', tip: 'Religion is about good things: praying, being kind, and doing right. A sentence that matches this is true.' },
    { type: 'mc', q: 'Which of these is a reason why we pray?', options: [{ text: 'To give thanks to God', correct: true }, { text: 'To ignore others', correct: false, why: 'Ignoring others is not kind. We pray to thank God, not to ignore people.' }, { text: 'To avoid doing chores for our family', correct: false, why: 'Prayer is not a way to skip chores. We pray to thank God for our blessings.' }], good: 'Yes! We pray to give thanks to God.', bad: 'One reason we pray is To give thanks to God for our blessings.', tip: 'The reasons we pray are to thank, to ask, to praise, and to say sorry. Look for one of these.' },
    { type: 'tf', q: 'We only pray when we need to ask God for something.', answer: false, good: 'That’s right! We also pray to give thanks, praise God, and say sorry.', bad: 'The answer should be False &mdash; we also pray to give thanks, praise God, and say sorry.', why: 'You said True, but this is false. The word only makes it wrong &mdash; we also pray to give thanks, praise God, and say sorry.', tip: 'Watch out for the word only. Remember there are many reasons to pray, not just one.' },
    { type: 'mc', q: 'When we say sorry to God and promise not to do it again, what are we doing?', options: [{ text: 'Asking for forgiveness', correct: true }, { text: 'Showing off to our friends at school', correct: false, why: 'Showing off means trying to look better than others. Saying sorry to God is not showing off.' }, { text: 'Complaining', correct: false, why: 'Complaining is saying you are unhappy about something. Saying sorry is asking for forgiveness.' }], good: 'Correct! That is asking for forgiveness.', bad: 'Saying sorry and promising not to do it again is asking for forgiveness.', tip: 'Saying sorry goes with forgiveness. When you say sorry, you ask to be forgiven.' },
    { type: 'tf', q: 'We can talk to God anytime and anywhere through prayer.', answer: true, good: 'That’s right! Prayer lets us talk to God anytime, anywhere.', bad: 'The answer should be True &mdash; we can talk to God anytime and anywhere through prayer.', why: 'You said False, but this is true. Prayer lets us talk to God anytime and anywhere.', tip: 'Remember the flashcard words: anytime, anywhere. There is no wrong time or place to pray.' },
    { type: 'mc', q: 'What do we do when we &ldquo;praise and adore&rdquo; God in prayer?', options: [{ text: 'Appreciate God’s goodness', correct: true }, { text: 'Ask Him for new toys and nothing else', correct: false, why: 'Asking only for toys is not praising. Praising is telling God how good He is.' }, { text: 'Argue with Him', correct: false, why: 'Arguing with God is not praise. To praise and adore means to appreciate God&rsquo;s goodness.' }], good: 'Yes! We appreciate God’s goodness.', bad: 'To praise and adore means we appreciate God’s goodness.', tip: 'Praise means saying how good someone is. Praising God means appreciating His goodness.' },
    { type: 'mc', q: 'What does religion teach us to do?', options: [{ text: 'Pray, be kind, and do what is right', correct: true }, { text: 'Ignore others and only think of yourself', correct: false, why: 'Ignoring others and thinking only of yourself is not kind. Religion teaches us to be kind.' }, { text: 'Avoid praying', correct: false, why: 'Religion teaches us to pray, so avoiding prayer is the opposite.' }], good: 'That’s right! Religion teaches us to pray, be kind, and do what is right.', bad: 'Religion teaches us to pray, be kind, and do what is right.', tip: 'Religion teaches good things. Pick the answer that is kind and right.' },
    { type: 'tf', q: 'We only pray inside a church.', answer: false, good: 'Correct! We can pray anytime and anywhere.', bad: 'The answer should be False &mdash; we can pray anytime and anywhere, not only inside a church.', why: 'You said True, but this is false. The word only makes it wrong &mdash; we can pray anytime and anywhere.', tip: 'The word only is a clue. Remember: we can pray anywhere, not just in church.' },
    { type: 'mc', q: 'Which of these is a reason we pray, besides giving thanks?', options: [{ text: 'To praise God’s goodness', correct: true }, { text: 'To avoid God', correct: false, why: 'Avoiding God is the opposite of praying. When we pray, we talk to God.' }, { text: 'To ignore our blessings and complain', correct: false, why: 'Complaining and ignoring our blessings is not a reason to pray. We pray to thank and praise God.' }], good: 'Yes! We also pray to praise God’s goodness.', bad: 'One reason we pray is To praise God’s goodness.', tip: 'Remember the four reasons: give thanks, ask for help, praise God, and say sorry. Praise is on the list!' },
    { type: 'tf', q: 'Church is a special place where people worship God and learn about His love.', answer: true, good: 'That’s right! Church is a place of worship and learning.', bad: 'The answer should be True &mdash; church is where people worship God and learn about His love.', why: 'You said False, but this is true. Church is a special place where people pray, worship God, and learn about His love.', tip: 'Check the sentence against the church flashcard. If it matches, it is true.' },
    { type: 'tf', q: 'God provides us with all our needs even though we do not know how or why.', answer: true, good: 'That&rsquo;s right! We can trust God to provide for us.', bad: 'The answer should be True &mdash; God provides us with all our needs even though we do not know how or why.', why: 'You said False, but this is true. The lesson says God provides all our needs, even when we do not know how or why.', tip: 'Remember that we pray to ask God for help with our needs. We can trust Him to provide.' }
  ]
});
