StudyKit.lesson({
  tag: 'Lesson 6',
  title: 'I Obey',
  stars: 0,
  icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><circle cx="30" cy="28" r="9" fill="var(--lav-deep)"/><circle cx="48" cy="36" r="6" fill="var(--lav)"/><path d="M16 60c2-14 8-20 14-20s12 6 14 20M40 60c1-8 4-12 8-12s7 4 8 12" fill="none" stroke="var(--lav-deep)" stroke-width="3" stroke-linecap="round"/>',
  flashcards: [
    { title: 'OBEDIENCE', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><path d="M38 16l16 6v12c0 12-7 20-16 24-9-4-16-12-16-24V22z" fill="var(--lav)"/><polyline points="30,38 36,44 47,31" fill="none" stroke="var(--card)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>', text: 'Obedience is following the words and advice of our parents, teachers, elders, and those in charge of us. It is doing what we ought to do as instructed by parents, people in charge, and the law. It is respect and obedience in action.' },
    { title: 'WHY SHOULD YOU OBEY?', icon: '<circle cx="38" cy="38" r="34" fill="var(--good-soft)"/><circle cx="38" cy="38" r="18" fill="var(--good)"/><text x="38" y="46" text-anchor="middle" font-size="24" font-weight="700" fill="var(--card)">?</text>', text: 'Children should obey because:<br>it is for their safety and well-being;<br>it builds better relationships between elders and children;<br>it is good training to make good decisions;<br>it leads to a peaceful family and community; and<br>it is our duty to our family, community, and country.' },
    { title: 'RIGHTS', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><path d="M38 54c-11-9-20-17-20-27a12 12 0 0 1 20-9 12 12 0 0 1 20 9c0 10-9 18-20 27z" fill="var(--accent)"/>', text: 'Rights are the things that every person should have and enjoy.<br>Example: the right to learn, play, and be treated with respect.' },
    { title: 'DUTIES', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><rect x="22" y="18" width="32" height="40" rx="4" fill="var(--card)" stroke="var(--lav)" stroke-width="3"/><polyline points="28,32 32,36 38,28" fill="none" stroke="var(--lav-deep)" stroke-width="3"/><line x1="28" y1="46" x2="48" y2="46" stroke="var(--lav)" stroke-width="3"/>', text: 'Duties are the things that we are expected to do.<br>Example: a learner&rsquo;s duty is to listen to the teacher and follow school rules.' },
    { title: 'RESPONSIBILITIES', icon: '<circle cx="38" cy="38" r="34" fill="var(--green-soft)"/><path d="M22 58l6-22h20l6 22z" fill="var(--green)"/><rect x="34" y="16" width="8" height="22" fill="var(--green-deep)"/>', text: 'Responsibilities are the things we should do properly and responsibly.<br>Example: taking care of school things, helping at home, and keeping the surroundings clean.' },
    { title: 'EVERY CHILD HAS A DUTY TO', icon: '<circle cx="38" cy="38" r="34" fill="var(--good-soft)"/><circle cx="38" cy="28" r="10" fill="var(--good)"/><path d="M18 58c2-14 12-20 20-20s18 6 20 20" fill="none" stroke="var(--good)" stroke-width="4" stroke-linecap="round"/>', text: 'love and respect their parents, family, and community;<br>help the community and cooperate with them;<br>obey community laws and rules;<br>take care of himself or herself and stay away from harm and danger;<br>study diligently and improve his or her talents and skills; and<br>love and respect the country and all its symbols, and take care of government properties.' },
    { title: 'LOVE FOR THE COUNTRY', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><rect x="24" y="16" width="4" height="44" fill="var(--accent-ink)"/><path d="M28 18h28l-8 10 8 10H28z" fill="var(--accent)"/>', text: 'Being an obedient child is being responsible in doing your duties to your family and community. By being a responsible member of the family and community, you develop and show love for the country.' }
  ],
  quiz: [
    { type: 'mc', q: 'What is obedience?', options: [{ text: 'Following the words of our parents, teachers, and elders', correct: true }, { text: 'Doing only what you like, even when your parents and elders say no', correct: false, why: 'Doing only what you like is not obeying. Obedience is following the words of those in charge of us.' }, { text: 'Asking other people to do all of your tasks for you', correct: false, why: 'Asking others to do your tasks is not obedience. Obedience is following the words of parents, teachers, and elders.' }], good: 'That&rsquo;s right! Obedience is following the words of our parents, teachers, and elders.', bad: 'Obedience is following the words and advice of our parents, teachers, elders, and those in charge of us.', tip: 'Obey means to listen and follow. Pick the answer about following your elders.' },
    { type: 'mc', q: 'Whose words and advice should children follow?', options: [{ text: 'Parents, teachers, and elders in charge of us', correct: true }, { text: 'Only the friends who are the very same age as we are', correct: false, why: 'Friends are not in charge of us. We follow our parents, teachers, and elders.' }, { text: 'Anyone at all who shouts the loudest', correct: false, why: 'Shouting does not put someone in charge of us. We follow our parents, teachers, and elders.' }], good: 'Yes! We follow our parents, teachers, and elders in charge of us.', bad: 'Children follow the words of their parents, teachers, and elders in charge of them.', tip: 'Think of the grown-ups who take care of you at home and at school.' },
    { type: 'mc', q: 'Why should Rico obey?\nMama tells Rico to hold her hand while crossing the street.', options: [{ text: 'It is for his safety and well-being', correct: true }, { text: 'So Mama will buy him a new toy later', correct: false, why: 'We do not obey to get toys. Holding Mama&rsquo;s hand keeps Rico safe.' }, { text: 'So he can show off to other children', correct: false, why: 'Obeying is not for showing off. Holding Mama&rsquo;s hand keeps Rico safe.' }], good: 'That&rsquo;s right! Obeying keeps Rico safe.', bad: 'Rico should obey because it is for his safety and well-being.', tip: 'Crossing the street can be dangerous. Obeying keeps us safe.' },
    { type: 'mc', q: 'Which is a reason why children should obey?', options: [{ text: 'It builds better relationships between elders and children', correct: true }, { text: 'It lets children skip all of their chores and homework at home', correct: false, why: 'Obeying does not mean skipping chores or homework. It builds better relationships with our elders.' }, { text: 'It makes children forget the rules', correct: false, why: 'Obeying means following the rules, not forgetting them.' }], good: 'Yes! Obeying builds better relationships with our elders.', bad: 'One reason to obey is that it builds better relationships between elders and children.', tip: 'Remember the reasons: safety, better relationships, good decisions, peace, and duty.' },
    { type: 'tf', q: 'Obeying leads to a peaceful family and community.', answer: true, good: 'That&rsquo;s right! Obeying brings peace to our family and community.', bad: 'The answer should be True &mdash; obeying leads to a peaceful family and community.', why: 'You said False, but this is true. One reason we obey is that it leads to a peaceful family and community.', tip: 'When everyone follows the rules, there is less fighting. That is peace.' },
    { type: 'tf', q: 'Obeying our elders makes our relationships with them worse.', answer: false, good: 'Correct! Obeying makes our relationships with our elders better.', bad: 'The answer should be False &mdash; obeying builds better relationships between elders and children.', why: 'You said True, but this is false. The word worse makes it wrong &mdash; obeying builds better relationships.', tip: 'Watch for the word worse. The lesson says obeying makes relationships better.' },
    { type: 'mc', q: 'What are rights?', options: [{ text: 'Things that every person should have and enjoy', correct: true }, { text: 'Things that we are expected to do at home and at school', correct: false, why: 'Things we are expected to do are duties, not rights.' }, { text: 'Things we should do properly and responsibly', correct: false, why: 'Things we should do properly and responsibly are responsibilities, not rights.' }], good: 'That&rsquo;s right! Rights are things every person should have and enjoy.', bad: 'Rights are the things that every person should have and enjoy.', tip: 'Rights = have and enjoy. Duties = expected to do. Responsibilities = do properly.' },
    { type: 'mc', q: 'Learning, playing, and being treated with respect are examples of ___.', options: [{ text: 'Rights', correct: true }, { text: 'Duties', correct: false, why: 'Duties are things we are expected to do, like following school rules. Learning and playing are things we should have and enjoy.' }, { text: 'Responsibilities', correct: false, why: 'Responsibilities are things we should do properly, like helping at home. Learning and playing are rights.' }], good: 'Yes! Those are rights.', bad: 'Learning, playing, and being treated with respect are Rights &mdash; things every person should have and enjoy.', tip: 'Ask: Is this something I get to have and enjoy? Then it is a right.' },
    { type: 'mc', q: 'Listening to the teacher and following school rules is a learner’s ___.', options: [{ text: 'Duty', correct: true }, { text: 'Right', correct: false, why: 'A right is something we have and enjoy, like playing. Following school rules is something we are expected to do.' }, { text: 'Tradition', correct: false, why: 'A tradition is a special activity a family does together. Following school rules is a duty.' }], good: 'Correct! That is a learner&rsquo;s duty.', bad: 'Listening to the teacher and following school rules is a learner&rsquo;s Duty.', tip: 'A duty is what we are expected to do. At school, we are expected to listen and follow rules.' },
    { type: 'mc', q: 'Taking care of school things, helping at home, and keeping the surroundings clean are examples of ___.', options: [{ text: 'Responsibilities', correct: true }, { text: 'Rights', correct: false, why: 'Rights are things we have and enjoy, like playing. These are things we should do properly.' }, { text: 'Wants', correct: false, why: 'Wants are things we can live without, like toys. These are things we should do properly.' }], good: 'That&rsquo;s right! Those are responsibilities.', bad: 'Taking care of school things, helping at home, and keeping the surroundings clean are Responsibilities.', tip: 'Responsibilities are jobs we should do properly, like keeping things clean and helping at home.' },
    { type: 'mc', q: 'Which of these is a duty of every child?', options: [{ text: 'Obey community laws and rules', correct: true }, { text: 'Break the rules when no one is looking', correct: false, why: 'Breaking rules is the opposite of obeying. Every child has a duty to obey community laws and rules.' }, { text: 'Stop studying once school is over for the day', correct: false, why: 'Every child has a duty to study diligently. Stopping is not a duty.' }], good: 'Yes! Every child has a duty to obey community laws and rules.', bad: 'Every child has a duty to obey community laws and rules.', tip: 'A child&rsquo;s duties are good things: love, help, obey, stay safe, study, and love the country.' },
    { type: 'tf', q: 'Every child has a duty to love and respect the country and its symbols, and to take care of government properties.', answer: true, good: 'That&rsquo;s right! That is one of every child&rsquo;s duties.', bad: 'The answer should be True &mdash; every child has a duty to love and respect the country and its symbols, and take care of government properties.', why: 'You said False, but this is true. It is on the list of duties of every child.', tip: 'Loving our country is one of our duties. Taking care of its symbols and properties shows that love.' },
    { type: 'tf', q: 'Taking care of yourself and staying away from harm and danger is not a child’s duty.', answer: false, good: 'Correct! It is a child&rsquo;s duty to take care of himself or herself.', bad: 'The answer should be False &mdash; every child has a duty to take care of himself or herself and stay away from harm and danger.', why: 'You said True, but this is false. The word not makes it wrong &mdash; taking care of yourself and staying safe is a child&rsquo;s duty.', tip: 'Watch for the word not. Staying safe is on the list of every child&rsquo;s duties.' },
    { type: 'mc', q: 'By being a responsible member of the family and community, what do you develop and show?', options: [{ text: 'Love for the country', correct: true }, { text: 'Fear of other people', correct: false, why: 'Being responsible does not make us afraid of others. It shows love for the country.' }, { text: 'Laziness at home and at school', correct: false, why: 'Being responsible is the opposite of being lazy. It shows love for the country.' }], good: 'That&rsquo;s right! You develop and show love for the country.', bad: 'By being a responsible member of the family and community, you develop and show love for the country.', tip: 'Remember the last flashcard: responsible family and community members show love for the country.' },
    { type: 'tf', q: 'Being obedient is being responsible in doing your duties to your family and community.', answer: true, good: 'Correct! Obedient children are responsible in doing their duties.', bad: 'The answer should be True &mdash; being obedient is being responsible in doing your duties and obligations to your family and community.', why: 'You said False, but this is true. The lesson says being an obedient child is being responsible in doing your duties to your family and community.', tip: 'Obeying and doing your duties go together.' },
    { type: 'mc', q: 'Obedience is doing what we ought to do as instructed by parents, people in charge, and ___.', options: [{ text: 'the law', correct: true }, { text: 'our favorite cartoon characters', correct: false, why: 'Cartoon characters are not in charge of us. Obedience also means following the law.' }, { text: 'anyone who gives us candy', correct: false, why: 'Giving candy does not put someone in charge of us. Obedience means following parents, people in charge, and the law.' }], good: 'That&rsquo;s right! We also obey the law.', bad: 'Obedience is doing what we ought to do as instructed by parents, people in charge, and the law.', tip: 'Parents at home, people in charge, and the rules of the country &mdash; the law.' }
  ]
});
