StudyKit.lesson({
  tag: 'Lesson 7',
  title: 'I Can',
  stars: 0,
  icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><polygon points="38,14 44,30 61,31 47,41 52,58 38,48 24,58 29,41 15,31 32,30" fill="var(--accent)"/>',
  flashcards: [
    { title: 'CONFIDENCE', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><polygon points="38,14 44,30 61,31 47,41 52,58 38,48 24,58 29,41 15,31 32,30" fill="var(--accent)"/>', text: 'Confidence is the belief that you can succeed, even if you make mistakes along the way. It is about focusing on your strengths and trying your best. Confidence grows with practice.' },
    { title: 'FINGERPRINTS', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><ellipse cx="38" cy="38" rx="16" ry="20" fill="none" stroke="var(--lav-deep)" stroke-width="3"/><ellipse cx="38" cy="38" rx="10" ry="13" fill="none" stroke="var(--lav)" stroke-width="3"/><ellipse cx="38" cy="38" rx="4" ry="6" fill="none" stroke="var(--lav-deep)" stroke-width="3"/>', text: 'Your fingerprints are one of a kind. There is no one else who has the same fingerprints as you. This makes you unique.' },
    { title: 'YOU ARE UNIQUE AND SPECIAL', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><path d="M38 54c-11-9-20-17-20-27a12 12 0 0 1 20-9 12 12 0 0 1 20 9c0 10-9 18-20 27z" fill="var(--accent)"/>', text: 'Just like your fingerprints, all the rest of your body parts, behaviors, and characteristics are unique. Every child is unique and special.' },
    { title: 'YOU ARE GIFTED', icon: '<circle cx="38" cy="38" r="34" fill="var(--good-soft)"/><rect x="20" y="32" width="36" height="24" rx="3" fill="var(--good)"/><rect x="16" y="26" width="44" height="8" rx="2" fill="var(--green-deep)"/><rect x="35" y="26" width="6" height="30" fill="var(--card)"/>', text: 'You can do many things as a little child, and much more when you grow up. Your talents and skills boost your self-confidence.' },
    { title: 'ABILITY &amp; TALENT', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><path d="M26 54V26l24-6v28" fill="none" stroke="var(--lav-deep)" stroke-width="4"/><circle cx="22" cy="54" r="6" fill="var(--lav)"/><circle cx="46" cy="48" r="6" fill="var(--lav)"/>', text: 'An <b>ability</b> is something you can do well or learn to do well.<br>A <b>talent</b> is a natural skill or strength that you may develop through practice.<br>Examples: playing sports, helping others, speaking, building or creating things, drawing, singing, dancing, reading, and writing.' },
    { title: '1. ACKNOWLEDGE YOUR GIFTS', icon: '<circle cx="38" cy="38" r="34" fill="var(--accent-soft)"/><path d="M22 46c0-14 32-14 32 0" fill="none" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><circle cx="38" cy="24" r="7" fill="var(--accent)"/>', text: 'Acknowledge your gifts and be proud of what you can do. You have talents because God gave them to you. Being proud of your gifts does not mean being boastful. It simply means owning your talents and skills and being responsible for them.' },
    { title: '2. PRACTICE TO IMPROVE', icon: '<circle cx="38" cy="38" r="34" fill="var(--good-soft)"/><polyline points="18,52 30,40 40,46 58,24" fill="none" stroke="var(--good)" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>', text: 'When you practice, you learn new ways of doing things better. You also learn from your mistakes and avoid repeating them.' },
    { title: '3. USE YOUR TALENTS PROPERLY', icon: '<circle cx="38" cy="38" r="34" fill="var(--lav-soft)"/><circle cx="26" cy="32" r="8" fill="var(--lav)"/><circle cx="50" cy="32" r="8" fill="var(--lav-deep)"/><path d="M30 50c4 4 12 4 16 0" fill="none" stroke="var(--lav-deep)" stroke-width="3" stroke-linecap="round"/>', text: 'Talents and skills are given to you by God so that you enjoy your life better when you use them properly. The best way to use your gifts properly is to share them with others joyfully.' },
    { title: 'MY FAMILY HELPS ME', icon: '<circle cx="38" cy="38" r="34" fill="var(--green-soft)"/><circle cx="26" cy="28" r="7" fill="var(--green)"/><circle cx="50" cy="28" r="7" fill="var(--green-deep)"/><circle cx="38" cy="40" r="5" fill="var(--accent)"/>', text: 'Our family helps us discover our abilities and talents by: encouraging us to try new things, supporting our interests, giving helpful advice, praising our efforts, and giving us opportunities to practice.<br>Listening to our parents and following their advice helps us improve what we do.' }
  ],
  quiz: [
    { type: 'mc', q: 'What is confidence?', options: [{ text: 'Believing you can succeed, even if you make mistakes', correct: true }, { text: 'Believing that you must never make any mistakes at all', correct: false, why: 'Confidence does not mean never making mistakes. It is believing you can succeed even when you make mistakes.' }, { text: 'Thinking that you are better than everyone else', correct: false, why: 'That is being boastful. Confidence is believing you can succeed and trying your best.' }], good: 'That&rsquo;s right! Confidence is believing you can succeed, even with mistakes.', bad: 'Confidence is the belief that you can succeed, even if you make mistakes along the way.', tip: 'Everyone makes mistakes. Confidence means you still believe you can do it.' },
    { type: 'tf', q: 'Confidence grows with practice.', answer: true, good: 'Correct! The more you practice, the more confident you become.', bad: 'The answer should be True &mdash; confidence grows with practice.', why: 'You said False, but this is true. The lesson says confidence grows with practice.', tip: 'Think of riding a bike: the more you practice, the braver you feel. Confidence grows the same way.' },
    { type: 'mc', q: 'Why do your fingerprints make you unique?', options: [{ text: 'No one else has the same fingerprints as you', correct: true }, { text: 'Everyone in your family has the very same fingerprints', correct: false, why: 'This is not true. Your fingerprints are one of a kind &mdash; no one else has the same ones.' }, { text: 'Your fingerprints change into new ones every day', correct: false, why: 'Your fingerprints do not change every day. They are one of a kind, and that makes you unique.' }], good: 'Yes! No one else has your fingerprints.', bad: 'Your fingerprints make you unique because no one else has the same fingerprints as you.', tip: 'Unique means one of a kind. Your fingerprints are yours alone.' },
    { type: 'mc', q: 'What is an ability?', options: [{ text: 'Something you can do well or learn to do well', correct: true }, { text: 'Something that only grown-ups are allowed to do', correct: false, why: 'Children have abilities too. An ability is something you can do well or learn to do well.' }, { text: 'Something that you can never learn, no matter what', correct: false, why: 'An ability can be learned. It is something you can do well or learn to do well.' }], good: 'That&rsquo;s right! An ability is something you can do well or learn to do well.', bad: 'An ability is something you can do well or learn to do well.', tip: 'Ability sounds like able. If you are able to do it well, it is an ability.' },
    { type: 'mc', q: 'What is a talent?', options: [{ text: 'A natural skill that you may develop through practice', correct: true }, { text: 'Something you can buy at a store when you have money', correct: false, why: 'Talents cannot be bought. A talent is a natural skill you develop through practice.' }, { text: 'Something that only famous people on TV have', correct: false, why: 'Every child has talents, not only famous people. A talent is a natural skill you develop through practice.' }], good: 'Yes! A talent is a natural skill you may develop through practice.', bad: 'A talent is a natural skill or strength that you may develop through practice.', tip: 'A talent is already inside you. Practice helps it grow.' },
    { type: 'mc', q: 'Which of these is an example of an ability or talent?', options: [{ text: 'Singing', correct: true }, { text: 'Shouting at others', correct: false, why: 'Shouting at others is unkind. It is not a talent or ability we should grow.' }, { text: 'Breaking your toys', correct: false, why: 'Breaking toys is not a talent. Talents are things like singing, drawing, and dancing.' }], good: 'Correct! Singing is a talent.', bad: 'Singing is an example of an ability or talent, like drawing, dancing, reading, and writing.', tip: 'Talents are good things you can do well: sports, helping, speaking, building, drawing, singing, dancing, reading, writing.' },
    { type: 'mc', q: 'Who gave us our talents?', options: [{ text: 'God', correct: true }, { text: 'The store where we buy our school supplies', correct: false, why: 'Talents cannot be bought at a store. The lesson says God gave us our talents.' }, { text: 'Our classmates when we copy them', correct: false, why: 'Copying classmates does not give us talents. God gave each of us our own talents.' }], good: 'That&rsquo;s right! God gave us our talents.', bad: 'You have talents because God gave them to you.', tip: 'Remember: talents and skills are given to you by God.' },
    { type: 'tf', q: 'Being proud of your gifts means being boastful.', answer: false, good: 'That&rsquo;s right! Being proud of your gifts is not being boastful.', bad: 'The answer should be False &mdash; being proud of your gifts does not mean being boastful. It means owning your talents and being responsible for them.', why: 'You said True, but this is false. The lesson says being proud of your gifts does not mean being boastful &mdash; it means owning your talents and being responsible for them.', tip: 'Boastful means showing off. Being proud means you are happy with your gift and take care of it.' },
    { type: 'mc', q: 'Which is a way to enrich your gifts and talents?', options: [{ text: 'Practice to improve', correct: true }, { text: 'Stop trying after your very first mistake', correct: false, why: 'Mistakes help us learn. When you practice, you learn from your mistakes.' }, { text: 'Hide your talents so no one can see them', correct: false, why: 'Hiding talents does not help them grow. The best way to use them is to share them.' }], good: 'Yes! Practice helps you improve.', bad: 'Practice to improve is one way to enrich your gifts and talents.', tip: 'The three ways: acknowledge your gifts, practice to improve, and use your talents properly.' },
    { type: 'mc', q: 'What is the best way to use your gifts properly?', options: [{ text: 'Share them with others joyfully', correct: true }, { text: 'Keep them only to yourself and never share', correct: false, why: 'Keeping them only to yourself is not the best way. We should share our gifts with others joyfully.' }, { text: 'Use them to show off to your classmates', correct: false, why: 'Showing off is being boastful. The best way is to share your gifts joyfully.' }], good: 'That&rsquo;s right! Share your gifts with others joyfully.', bad: 'The best way to use your gifts properly is to share them with others joyfully.', tip: 'Gifts are for sharing. Think of singing for your family or helping a friend draw.' },
    { type: 'tf', q: 'When you practice, you learn from your mistakes and avoid repeating them.', answer: true, good: 'Correct! Practice helps you learn from your mistakes.', bad: 'The answer should be True &mdash; when you practice, you learn from your mistakes and avoid repeating them.', why: 'You said False, but this is true. The Practice to Improve flashcard says you learn from your mistakes and avoid repeating them.', tip: 'Practice is how we get better. Each mistake teaches us something.' },
    { type: 'mc', q: 'How can our family help us discover our abilities and talents?', options: [{ text: 'By encouraging us to try new things', correct: true }, { text: 'By telling us to stop trying new things', correct: false, why: 'This is the opposite. Our family helps by encouraging us to try new things.' }, { text: 'By never letting us practice at home', correct: false, why: 'This is the opposite. Our family gives us opportunities to practice.' }], good: 'Yes! Our family encourages us to try new things.', bad: 'Our family helps us by encouraging us to try new things, supporting our interests, giving advice, praising our efforts, and letting us practice.', tip: 'Families help in kind ways: encourage, support, advise, praise, and give chances to practice.' },
    { type: 'tf', q: 'Listening to our parents and following their advice will help us improve what we do.', answer: true, good: 'That&rsquo;s right! Our parents&rsquo; advice helps us improve.', bad: 'The answer should be True &mdash; listening to our parents and following their advice helps us improve what we do.', why: 'You said False, but this is true. The lesson says listening to our parents and following their advice helps us improve.', tip: 'Our parents want us to grow. Their advice helps us get better.' },
    { type: 'tf', q: 'Only some children are unique and special.', answer: false, good: 'Correct! Every child is unique and special.', bad: 'The answer should be False &mdash; every child is unique and special.', why: 'You said True, but this is false. The word only makes it wrong &mdash; every child is unique and special.', tip: 'Watch for the word only. Remember: every child is unique and special.' },
    { type: 'mc', q: 'What is the best way to enrich your talents?', options: [{ text: 'Share them', correct: true }, { text: 'Keep them a secret', correct: false, why: 'Keeping talents a secret does not help them grow. The best way to enrich your talents is to share them.' }, { text: 'Stop using them', correct: false, why: 'Talents grow when we use them. The best way to enrich your talents is to share them.' }], good: 'Yes! The best way to enrich your talents is to share them.', bad: 'The best way to enrich your talents is to share them.', tip: 'Remember the recap: the best way to enrich your talents is to share them.' },
    { type: 'tf', q: 'Your talents and skills boost your self-confidence.', answer: true, good: 'That&rsquo;s right! Your talents and skills make you more confident.', bad: 'The answer should be True &mdash; your talents and skills boost your self-confidence.', why: 'You said False, but this is true. The You Are Gifted flashcard says your talents and skills boost your self-confidence.', tip: 'When you know you can do something well, you feel confident.' },
    { type: 'tf', q: 'You should hide your gifts and talents instead of being proud of them.', answer: false, good: 'Correct! You should accept, enrich, and be proud of your gifts.', bad: 'The answer should be False &mdash; you should accept, enrich, and be proud of your gifts and talents.', why: 'You said True, but this is false. The lesson says you should accept, enrich, and be proud of your gifts and talents.', tip: 'Gifts come from God. Be proud of them and share them, do not hide them.' }
  ]
});
