StudyKit.content('walkthroughs', [
  {
    id: 'wt1',
    text: 'A baker has <b>3/4 kilogram</b> of dough. She divides the dough into portions of <b>1/8 kilogram</b> each. She uses <b>2</b> of the portions to make bread rolls. How many portions of dough remain?',
    givens: [{ t: 'There is 3/4 kilogram of dough', is: true, w: 'The problem says &ldquo;A baker has 3/4 kilogram of dough.&rdquo;' }, { t: 'Each portion is 1/8 kilogram', is: true, w: 'The problem says she divides the dough into portions of 1/8 kilogram each.' }, { t: 'She uses 2 portions', is: true, w: 'The problem says &ldquo;She uses 2 of the portions.&rdquo;' }, { t: 'The dough weighs 8 kilograms', is: false, w: 'The problem never says this. The 8 only appears in 1/8 kilogram, the size of each portion. The dough is 3/4 kilogram.' }, { t: 'She bakes the rolls for 30 minutes', is: false, w: 'The problem never mentions baking time. Only facts written in the problem are givens.' }],
    asked: [{ t: 'How many portions remain', c: true, w: 'The last sentence asks &ldquo;How many portions of dough remain?&rdquo; That is exactly what you must find.' }, { t: 'How much dough she started with', c: false, w: 'The problem already tells you that: 3/4 kilogram. You never need to find something the problem gives you.' }, { t: 'How heavy one portion is', c: false, w: 'That is given too: each portion is 1/8 kilogram. The question asks how many portions remain.' }],
    plan: [{ t: 'Divide 3/4 by 1/8, then subtract 2', c: true, w: 'Dividing 3/4 by 1/8 tells how many 1/8-kilogram portions fit in the dough (6). Taking away the 2 she used leaves what remains.' }, { t: 'Multiply 3/4 by 1/8, then subtract 2', c: false, w: 'Multiplying gives 3/32 kilogram, not a number of portions. To find how many 1/8s fit in 3/4, divide.' }, { t: 'Subtract 2 from 3/4, then divide by 1/8', c: false, w: 'The order is wrong. The 2 is a number of portions, not kilograms, so you cannot take it from 3/4 kilogram. Make the portions first, then subtract.' }, { t: 'Divide 3/4 by 1/8, then add 2', c: false, w: 'She USES 2 portions, so they are taken away. &ldquo;Remain&rdquo; means subtract, not add.' }],
    answer: { num: 4, den: 1 },
    unit: 'portions',
    work: '3/4 &divide; 1/8 = 3/4 &times; 8/1 = 24/4 = <b>6 portions</b>. Then 6 &minus; 2 = <b>4</b>.',
    check: [{ t: '3/4 is the same as 6/8, so there are 6 eighths. Using 2 leaves 4.', c: true, w: 'It rebuilds the answer another way: 3/4 = 6/8, so there are 6 portions of 1/8. Using 2 leaves 4. Both ways agree.' }, { t: '4 is smaller than 6, so the answer must be wrong.', c: false, w: 'The answer SHOULD be smaller than 6, because she used up 2 of the 6 portions. Smaller is exactly what makes sense here.' }, { t: 'The answer should be a fraction, because we divided fractions.', c: false, w: 'Dividing fractions can give a whole number. 3/4 &divide; 1/8 = 6 because six eighths fit in three quarters. Portions are counted in whole numbers.' }]
  },
  {
    id: 'wt2',
    text: 'A container holds <b>5/6 liter</b> of juice. The juice is poured into cups that hold <b>1/6 liter</b> each. After filling the cups, <b>2</b> cups are given to the teachers. How many cups are left?',
    givens: [{ t: 'There is 5/6 liter of juice', is: true, w: 'The problem says &ldquo;A container holds 5/6 liter of juice.&rdquo;' }, { t: 'Each cup holds 1/6 liter', is: true, w: 'The problem says the cups hold 1/6 liter each.' }, { t: '2 cups are given away', is: true, w: 'The problem says 2 cups are given to the teachers.' }, { t: 'There are 6 teachers', is: false, w: 'The problem never says how many teachers there are. The 6 comes from the fractions 5/6 and 1/6.' }, { t: 'Each cup costs 5 pesos', is: false, w: 'The problem never mentions money. The 5 comes from 5/6 liter.' }],
    asked: [{ t: 'How many cups are left', c: true, w: 'The last sentence asks &ldquo;How many cups are left?&rdquo; That is exactly what you must find.' }, { t: 'How many liters are left', c: false, w: 'The question counts cups, not liters. Read the last sentence again.' }, { t: 'How many cups were given to the teachers', c: false, w: 'The problem already says 2 cups were given away. You need the cups that are LEFT.' }],
    plan: [{ t: 'Divide 5/6 by 1/6, then subtract 2', c: true, w: 'Dividing 5/6 by 1/6 tells how many cups can be filled (5). Taking away the 2 cups given to the teachers leaves the rest.' }, { t: 'Divide 5/6 by 1/6, then add 2', c: false, w: 'The 2 cups are GIVEN AWAY, so they are taken off. &ldquo;Left&rdquo; means subtract.' }, { t: 'Multiply 5/6 by 1/6, then subtract 2', c: false, w: 'Multiplying gives 5/36 liter, not a number of cups. To find how many 1/6s fit in 5/6, divide.' }, { t: 'Subtract 1/6 from 5/6 two times', c: false, w: 'That gives 3/6 liter of juice, not a number of cups. The question asks for cups, so first find how many cups were filled.' }],
    answer: { num: 3, den: 1 },
    unit: 'cups',
    work: '5/6 &divide; 1/6 = 5/6 &times; 6/1 = 30/6 = <b>5 cups</b>. Then 5 &minus; 2 = <b>3</b>.',
    check: [{ t: '5 cups of 1/6 liter is 5/6 liter, which matches the container. Giving away 2 leaves 3.', c: true, w: 'Working backwards: 5 cups of 1/6 liter is 5/6 liter, exactly the juice in the container. So 5 cups is right, and 5 &minus; 2 = 3.' }, { t: '5/6 is less than 1, so the answer must be less than 1.', c: false, w: 'The answer counts cups, not liters. Many small 1/6-liter cups fit in 5/6 liter, so the count can be more than 1.' }, { t: 'There were 6 cups because the denominator is 6.', c: false, w: 'The denominator only names the size of each part (sixths). 5/6 liter is five sixths, so it fills 5 cups, not 6.' }]
  },
  {
    id: 'wt3',
    text: 'A science class has <b>5/6 liter</b> of liquid. The teacher pours the liquid equally into containers that hold <b>1/12 liter</b> each. She then prepares <b>2</b> additional containers using another liquid. How many containers does she prepare altogether?',
    givens: [{ t: 'There is 5/6 liter of liquid', is: true, w: 'The problem says the class has 5/6 liter of liquid.' }, { t: 'Each container holds 1/12 liter', is: true, w: 'The problem says the containers hold 1/12 liter each.' }, { t: 'She prepares 2 additional containers', is: true, w: 'The problem says she prepares 2 additional containers using another liquid.' }, { t: 'There are 12 students in the class', is: false, w: 'The problem never mentions students. The 12 comes from 1/12 liter, the size of each container.' }, { t: 'The second liquid is also 5/6 liter', is: false, w: 'The problem never says how much of the second liquid there is, only that it fills 2 more containers.' }],
    asked: [{ t: 'How many containers she prepares altogether', c: true, w: 'The last sentence asks &ldquo;How many containers does she prepare altogether?&rdquo; That includes the 2 extra containers.' }, { t: 'How many containers she filled with the first liquid', c: false, w: 'That is only part of the answer (10). &ldquo;Altogether&rdquo; means you must also count the 2 additional containers.' }, { t: 'How much liquid is in each container', c: false, w: 'That is given: each container holds 1/12 liter. The question asks for a number of containers.' }],
    plan: [{ t: 'Divide 5/6 by 1/12, then add 2', c: true, w: 'Dividing 5/6 by 1/12 finds how many containers the first liquid fills (10). The 2 extra containers are added because the question says &ldquo;altogether&rdquo;.' }, { t: 'Divide 5/6 by 1/12, then subtract 2', c: false, w: 'The 2 containers are ADDITIONAL, so she prepares more, not fewer. &ldquo;Altogether&rdquo; means add.' }, { t: 'Multiply 5/6 by 1/12, then add 2', c: false, w: 'Multiplying gives 5/72 liter, not a number of containers. To find how many 1/12s fit in 5/6, divide.' }, { t: 'Add 2 to 5/6, then divide by 1/12', c: false, w: 'The 2 is a number of containers, not liters, so it cannot be added to 5/6 liter. Fill the containers first, then add 2.' }],
    answer: { num: 12, den: 1 },
    unit: 'containers',
    work: '5/6 &divide; 1/12 = 5/6 &times; 12/1 = 60/6 = <b>10 containers</b>. Then 10 + 2 = <b>12</b>.',
    check: [{ t: '5/6 is the same as 10/12, so 10 containers can be filled. Two more makes 12.', c: true, w: 'It rebuilds the answer another way: 5/6 = 10/12, so 10 containers of 1/12 liter. Adding the 2 extra gives 12. Both ways agree.' }, { t: 'We added 2 because there are 2 liquids.', c: false, w: 'That is not why. We added 2 because she prepares 2 ADDITIONAL containers. This only explains a step; it does not prove the answer.' }, { t: 'The answer is 12 because the denominator is 12.', c: false, w: 'The 12 matching the denominator is just a coincidence. A real check works the numbers again: 5/6 = 10/12, so 10 containers, plus 2 makes 12.' }]
  },
  {
    id: 'wt4',
    text: 'A roll of wire is <b>7/8 meter</b> long. It is cut into pieces that are <b>1/8 meter</b> each. The craft group uses <b>3</b> pieces for a project. How many pieces are left?',
    givens: [{ t: 'The wire is 7/8 meter long', is: true, w: 'The problem says the roll of wire is 7/8 meter long.' }, { t: 'Each piece is 1/8 meter', is: true, w: 'The problem says it is cut into pieces of 1/8 meter each.' }, { t: '3 pieces are used', is: true, w: 'The problem says the craft group uses 3 pieces.' }, { t: 'The craft group has 8 members', is: false, w: 'The problem never says how many members the group has. The 8 comes from the fractions 7/8 and 1/8.' }, { t: 'The project takes 3 hours', is: false, w: 'The problem never mentions time. The 3 is the number of pieces used, not hours.' }],
    asked: [{ t: 'How many pieces are left', c: true, w: 'The last sentence asks &ldquo;How many pieces are left?&rdquo; That is exactly what you must find.' }, { t: 'How many meters of wire are left', c: false, w: 'The question counts pieces, not meters. Read the last sentence again.' }, { t: 'How many pieces the wire was cut into', c: false, w: 'That is only the first step (7 pieces). The question asks how many are LEFT after 3 are used.' }],
    plan: [{ t: 'Divide 7/8 by 1/8, then subtract 3', c: true, w: 'Dividing 7/8 by 1/8 finds how many 1/8-meter pieces there are (7). Taking away the 3 used pieces leaves the answer.' }, { t: 'Subtract 3/8 from 7/8', c: false, w: 'That gives 4/8 meter, a length of wire, not a number of pieces. The question asks how many pieces.' }, { t: 'Multiply 7/8 by 1/8, then subtract 3', c: false, w: 'Multiplying gives 7/64 meter, not a number of pieces. To find how many 1/8s fit in 7/8, divide.' }, { t: 'Divide 7/8 by 3, then subtract 1/8', c: false, w: 'This mixes up the numbers. You divide by the piece size (1/8), and subtract the 3 pieces that were used.' }],
    answer: { num: 4, den: 1 },
    unit: 'pieces',
    work: '7/8 &divide; 1/8 = 7/8 &times; 8/1 = 56/8 = <b>7 pieces</b>. Then 7 &minus; 3 = <b>4</b>.',
    check: [{ t: 'There are 7 eighths in 7/8, and 7 &minus; 3 = 4. Those 4 pieces are 4/8 = 1/2 meter of wire, which is reasonable.', c: true, w: 'It checks both ways: 7 eighths minus 3 eighths leaves 4 eighths, and 4 pieces of 1/8 meter is 1/2 meter of wire, a sensible amount.' }, { t: '4 pieces is 4 meters of wire.', c: false, w: 'Each piece is only 1/8 meter, so 4 pieces is 4/8 = 1/2 meter. The whole wire was less than 1 meter.' }, { t: 'Dividing made the number bigger, so something went wrong.', c: false, w: 'Dividing by a fraction smaller than 1 SHOULD make the number bigger, because many small pieces fit in the wire. Nothing went wrong.' }]
  },
  {
    id: 'wt5',
    text: 'A cake recipe needs <b>2/3 cup</b> of sugar for one full batch. You only want to make <b>1/2</b> of the recipe. How much sugar do you need?',
    givens: [{ t: 'One full batch needs 2/3 cup of sugar', is: true, w: 'The problem says the recipe needs 2/3 cup of sugar for one full batch.' }, { t: 'You are making 1/2 of the recipe', is: true, w: 'The problem says you only want to make 1/2 of the recipe.' }, { t: 'You are making 2 cakes', is: false, w: 'The problem never says 2 cakes. You are making HALF of one recipe. The 2 only appears in 1/2 and 2/3.' }, { t: 'The cake bakes at 1/2 heat', is: false, w: 'The problem never mentions heat. The 1/2 is how much of the recipe you make.' }],
    asked: [{ t: 'How much sugar is needed for half a batch', c: true, w: 'The question asks &ldquo;How much sugar do you need?&rdquo; for 1/2 of the recipe. That is half a batch.' }, { t: 'How many batches you can make with 2/3 cup', c: false, w: 'You are not making several batches. You are making just 1/2 of one recipe.' }, { t: 'How much sugar is needed for 2 batches', c: false, w: 'There are no 2 batches. You want HALF a batch, so you need less sugar, not more.' }],
    plan: [{ t: 'Multiply 2/3 by 1/2, because "of" means multiply', c: true, w: '&ldquo;1/2 of the recipe&rdquo; means 1/2 &times; the amount. 2/3 &times; 1/2 = 2/6 = 1/3 cup.' }, { t: 'Divide 2/3 by 1/2, because the recipe is being split', c: false, w: 'Dividing by 1/2 doubles the amount (4/3 cups). Half a recipe needs LESS sugar, so multiply by 1/2.' }, { t: 'Divide 1/2 by 2/3', c: false, w: 'This divides the wrong way round and does not match the story. Half of 2/3 cup is 2/3 &times; 1/2.' }, { t: 'Subtract 1/2 from 2/3', c: false, w: 'The 1/2 is a fraction OF the recipe, not 1/2 cup of sugar. Taking it away gives 1/6 cup, which is not half of 2/3.' }],
    answer: { num: 1, den: 3 },
    unit: 'cup of sugar',
    work: '2/3 &times; 1/2 = 2/6 = <b>1/3 cup</b>.',
    check: [{ t: 'Half a batch needs less sugar than a full batch, and 1/3 is less than 2/3. It works.', c: true, w: 'It checks the size of the answer: half a batch must need less sugar than a full batch, and 1/3 is less than 2/3. Also 1/3 + 1/3 = 2/3, the full batch.' }, { t: 'The answer should be bigger than 2/3 because we used a fraction.', c: false, w: 'Multiplying by a fraction smaller than 1 makes the answer SMALLER. Half a batch needs less sugar, not more.' }, { t: '1 1/3 cups is correct because 2/3 &divide; 1/2 = 4/3.', c: false, w: '1 1/3 cups is MORE than the full recipe needs (2/3 cup). Half a recipe cannot need more sugar than the whole recipe.' }]
  },
  {
    id: 'wt6',
    text: 'A smoothie recipe uses <b>3/4 liter</b> of milk for one full batch. You are making <b>1/3</b> of the recipe. How much milk will you use?',
    givens: [{ t: 'One full batch uses 3/4 liter of milk', is: true, w: 'The problem says one full batch uses 3/4 liter of milk.' }, { t: 'You are making 1/3 of the recipe', is: true, w: 'The problem says you are making 1/3 of the recipe.' }, { t: 'You are making 3 smoothies', is: false, w: 'The problem never says 3 smoothies. You are making 1/3 of one recipe. The 3 only appears in 1/3 and 3/4.' }, { t: 'The blender holds 3/4 liter', is: false, w: 'The problem never mentions a blender. The 3/4 liter is the milk for one full batch.' }],
    asked: [{ t: 'How much milk is used for 1/3 of the recipe', c: true, w: 'The question asks &ldquo;How much milk will you use?&rdquo; when making 1/3 of the recipe.' }, { t: 'How many thirds are in 3/4 liter', c: false, w: 'That would be a division question. You are making 1/3 OF the recipe, so you need the milk for that part.' }, { t: 'How much milk is left over', c: false, w: 'The problem does not ask about leftovers. It asks how much milk you will USE.' }],
    plan: [{ t: 'Multiply 3/4 by 1/3, because "of" means multiply', c: true, w: '&ldquo;1/3 of the recipe&rdquo; means 1/3 &times; the amount. 3/4 &times; 1/3 = 3/12 = 1/4 liter.' }, { t: 'Divide 3/4 by 1/3', c: false, w: 'Dividing by 1/3 makes the amount three times bigger (9/4 liters). A third of a recipe needs LESS milk, so multiply.' }, { t: 'Divide 3/4 by 3, then add 1/3', c: false, w: 'Dividing by 3 is a good start (it gives 1/4), but adding 1/3 afterwards makes no sense. Nothing in the story is added.' }, { t: 'Subtract 1/3 from 3/4', c: false, w: 'The 1/3 is a fraction OF the recipe, not 1/3 liter of milk. Taking it away gives 5/12, which is not one third of 3/4.' }],
    answer: { num: 1, den: 4 },
    unit: 'liter of milk',
    work: '3/4 &times; 1/3 = 3/12 = <b>1/4 liter</b>.',
    check: [{ t: 'One third of a batch needs less milk, and 1/4 is less than 3/4. Also 1/4 &times; 3 = 3/4, which brings us back to one full batch.', c: true, w: 'It checks two ways: 1/4 is less than 3/4, because a third of a batch needs less. And 1/4 &times; 3 = 3/4 gives back the full batch.' }, { t: '2 1/4 liters is right, because 3/4 &divide; 1/3 = 9/4.', c: false, w: '2 1/4 liters is three times MORE than a full batch. A third of the recipe cannot need more milk than the whole recipe.' }, { t: 'The answer must be more than 3/4 because we divided.', c: false, w: 'We did not divide: &ldquo;of&rdquo; means multiply. And taking 1/3 of something always gives LESS than the whole.' }]
  },
  {
    id: 'wt7',
    text: 'A cookie recipe requires <b>5/8 cup</b> of flour. If you divide the recipe into <b>2</b> equal parts, how much flour is in each part?',
    givens: [{ t: 'The whole recipe uses 5/8 cup of flour', is: true, w: 'The problem says the cookie recipe requires 5/8 cup of flour.' }, { t: 'The recipe is split into 2 equal parts', is: true, w: 'The problem says you divide the recipe into 2 equal parts.' }, { t: 'Each cookie needs 5/8 cup', is: false, w: 'The 5/8 cup is for the WHOLE recipe, not for each cookie.' }, { t: 'You bake 8 cookies', is: false, w: 'The problem never says how many cookies you bake. The 8 comes from 5/8 cup.' }],
    asked: [{ t: 'How much flour is in each equal part', c: true, w: 'The question asks &ldquo;how much flour is in each part?&rdquo; after the recipe is split into 2.' }, { t: 'How many parts you can make from 5/8 cup', c: false, w: 'The problem already says 2 equal parts. You must find how much flour is in EACH part.' }, { t: 'How much flour is used altogether', c: false, w: 'That is given: the whole recipe uses 5/8 cup. The question asks about each part.' }],
    plan: [{ t: 'Divide 5/8 by 2, which is the same as multiplying by 1/2', c: true, w: 'Splitting into 2 equal parts means divide by 2, and dividing by 2 is the same as &times; 1/2. 5/8 &times; 1/2 = 5/16.' }, { t: 'Divide 5/8 by 1/2, which is the same as multiplying by 2', c: false, w: 'The recipe is split into 2 parts, so you divide by 2, not by 1/2. Dividing by 1/2 doubles the flour.' }, { t: 'Multiply 5/8 by 2', c: false, w: 'Multiplying by 2 doubles the flour (10/8). Splitting into 2 parts makes each part SMALLER.' }, { t: 'Subtract 2 from 5/8', c: false, w: 'You cannot take 2 away from 5/8, which is less than 1. Splitting into 2 equal parts means divide by 2.' }],
    answer: { num: 5, den: 16 },
    unit: 'cup of flour',
    work: '5/8 &divide; 2 = 5/8 &times; 1/2 = <b>5/16 cup</b>.',
    check: [{ t: 'Each part must be smaller than 5/8, and 5/16 is. Two parts of 5/16 make 10/16 = 5/8, the whole recipe.', c: true, w: 'It checks two ways: each part (5/16) is smaller than the whole (5/8), and 2 parts of 5/16 add up to 10/16 = 5/8, the whole recipe.' }, { t: '1 1/4 cups is right, because 5/8 &divide; 2 makes the answer bigger.', c: false, w: 'Dividing by a whole number like 2 makes the answer SMALLER. 1 1/4 cups is double the whole recipe.' }, { t: '5/16 is bigger than 5/8 because 16 is bigger than 8.', c: false, w: 'A bigger denominator means SMALLER pieces. Sixteenths are half the size of eighths, so 5/16 is less than 5/8.' }]
  },
  {
    id: 'wt8',
    text: 'A ribbon is <b>9/10 meter</b> long. It is cut into strips of <b>1/10 meter</b> each. 4 of the strips are used to wrap gifts. How many strips are left?',
    givens: [{ t: 'The ribbon is 9/10 meter long', is: true, w: 'The problem says the ribbon is 9/10 meter long.' }, { t: 'Each strip is 1/10 meter', is: true, w: 'The problem says it is cut into strips of 1/10 meter each.' }, { t: '4 strips are used', is: true, w: 'The problem says 4 of the strips are used to wrap gifts.' }, { t: 'There are 10 gifts to wrap', is: false, w: 'The problem never says how many gifts there are. The 10 comes from the fractions 9/10 and 1/10.' }, { t: 'The ribbon costs 9 pesos', is: false, w: 'The problem never mentions money. The 9 comes from 9/10 meter.' }],
    asked: [{ t: 'How many strips are left', c: true, w: 'The last sentence asks &ldquo;How many strips are left?&rdquo; That is exactly what you must find.' }, { t: 'How long each strip is', c: false, w: 'That is given: each strip is 1/10 meter. The question asks how many strips are left.' }, { t: 'How many meters of ribbon were used', c: false, w: 'The question counts strips that are LEFT, not meters that were used.' }],
    plan: [{ t: 'Divide 9/10 by 1/10, then subtract 4', c: true, w: 'Dividing 9/10 by 1/10 finds how many strips there are (9). Taking away the 4 used strips leaves the answer.' }, { t: 'Divide 9/10 by 4, then subtract 1/10', c: false, w: 'This mixes up the numbers. You divide by the strip size (1/10), and subtract the 4 strips that were used.' }, { t: 'Multiply 9/10 by 1/10, then subtract 4', c: false, w: 'Multiplying gives 9/100 meter, not a number of strips. To find how many 1/10s fit in 9/10, divide.' }, { t: 'Subtract 4/10 from 9/10', c: false, w: 'That gives 5/10 meter, a length of ribbon, not a number of strips. The question asks how many strips.' }],
    answer: { num: 5, den: 1 },
    unit: 'strips',
    work: '9/10 &divide; 1/10 = 9/10 &times; 10/1 = 90/10 = <b>9 strips</b>. Then 9 &minus; 4 = <b>5</b>.',
    check: [{ t: 'There are 9 tenths in 9/10, so there are 9 strips. Using 4 leaves 5.', c: true, w: 'It rebuilds the answer: 9/10 is nine tenths, so there are 9 strips of 1/10 meter. Using 4 leaves 5, the same answer.' }, { t: 'The answer is 5/10 meter of ribbon.', c: false, w: 'The question asks how many STRIPS are left, so the answer is a count: 5 strips. 5/10 meter is only their length.' }, { t: '9/10 is almost 1, so there can only be 1 strip.', c: false, w: 'Each strip is only 1/10 meter, much shorter than the ribbon. Nine of them fit in 9/10 meter.' }]
  },
  {
    id: 'wt9',
    text: 'A can holds <b>2/3 liter</b> of paint. It is poured into small jars that hold <b>1/9 liter</b> each. 3 more jars are then filled from a different can. How many jars are filled altogether?',
    givens: [{ t: 'The can holds 2/3 liter of paint', is: true, w: 'The problem says the can holds 2/3 liter of paint.' }, { t: 'Each jar holds 1/9 liter', is: true, w: 'The problem says the small jars hold 1/9 liter each.' }, { t: '3 more jars are filled from another can', is: true, w: 'The problem says 3 more jars are filled from a different can.' }, { t: 'There are 9 cans of paint', is: false, w: 'The problem never says there are 9 cans. The 9 comes from 1/9 liter, the size of each jar.' }, { t: 'The paint dries in 3 hours', is: false, w: 'The problem never mentions drying time. The 3 is the number of extra jars, not hours.' }],
    asked: [{ t: 'How many jars are filled altogether', c: true, w: 'The last sentence asks &ldquo;How many jars are filled altogether?&rdquo; That includes the 3 jars from the other can.' }, { t: 'How many jars came from the first can', c: false, w: 'That is only part of the answer (6). &ldquo;Altogether&rdquo; means you must also count the 3 more jars.' }, { t: 'How much paint is in each jar', c: false, w: 'That is given: each jar holds 1/9 liter. The question asks for a number of jars.' }],
    plan: [{ t: 'Divide 2/3 by 1/9, then add 3', c: true, w: 'Dividing 2/3 by 1/9 finds how many jars the first can fills (6). The 3 more jars are added because the question says &ldquo;altogether&rdquo;.' }, { t: 'Divide 2/3 by 1/9, then subtract 3', c: false, w: 'The 3 jars are MORE jars being filled, not jars taken away. &ldquo;Altogether&rdquo; means add.' }, { t: 'Multiply 2/3 by 1/9, then add 3', c: false, w: 'Multiplying gives 2/27 liter, not a number of jars. To find how many 1/9s fit in 2/3, divide.' }, { t: 'Add 3 to 2/3, then divide by 1/9', c: false, w: 'The 3 is a number of jars, not liters, so it cannot be added to 2/3 liter. Fill the jars first, then add 3.' }],
    answer: { num: 9, den: 1 },
    unit: 'jars',
    work: '2/3 &divide; 1/9 = 2/3 &times; 9/1 = 18/3 = <b>6 jars</b>. Then 6 + 3 = <b>9</b>.',
    check: [{ t: '2/3 is the same as 6/9, so 6 jars can be filled. Three more makes 9.', c: true, w: 'It rebuilds the answer another way: 2/3 = 6/9, so 6 jars of 1/9 liter. Three more makes 9. Both ways agree.' }, { t: 'We added 3 because 1/3 of the paint was left over.', c: false, w: 'No paint was left over: the can filled exactly 6 jars. We added 3 because 3 more jars came from a different can.' }, { t: '6 jars is the final answer, because that is what the division gave us.', c: false, w: 'The division only counts jars from the first can. The question says &ldquo;altogether&rdquo;, so the 3 jars from the other can must be added.' }]
  },
  {
    id: 'wt10',
    text: 'There is <b>3/4 kilogram</b> of rice. It is packed into bags of <b>1/12 kilogram</b> each. 4 of the bags are given to a neighbour. How many bags are left?',
    givens: [{ t: 'There is 3/4 kilogram of rice', is: true, w: 'The problem says there is 3/4 kilogram of rice.' }, { t: 'Each bag holds 1/12 kilogram', is: true, w: 'The problem says it is packed into bags of 1/12 kilogram each.' }, { t: '4 bags are given away', is: true, w: 'The problem says 4 of the bags are given to a neighbour.' }, { t: 'The neighbour has 4 children', is: false, w: 'The problem never mentions the neighbour&rsquo;s children. The 4 is the number of bags given away.' }, { t: 'There are 12 bags to start with', is: false, w: 'The problem never says 12 bags. The 12 comes from 1/12 kilogram, the size of each bag. Finding the number of bags is part of the work.' }],
    asked: [{ t: 'How many bags are left', c: true, w: 'The last sentence asks &ldquo;How many bags are left?&rdquo; That is exactly what you must find.' }, { t: 'How many kilograms of rice are left', c: false, w: 'The question counts bags, not kilograms. Read the last sentence again.' }, { t: 'How many bags were given away', c: false, w: 'That is given: 4 bags went to the neighbour. You need the bags that are LEFT.' }],
    plan: [{ t: 'Divide 3/4 by 1/12, then subtract 4', c: true, w: 'Dividing 3/4 by 1/12 finds how many bags can be packed (9). Taking away the 4 bags given away leaves the answer.' }, { t: 'Divide 3/4 by 4, then subtract 1/12', c: false, w: 'This mixes up the numbers. You divide by the bag size (1/12), and subtract the 4 bags given away.' }, { t: 'Multiply 3/4 by 1/12, then subtract 4', c: false, w: 'Multiplying gives 3/48 = 1/16 kilogram, not a number of bags. To find how many 1/12s fit in 3/4, divide.' }, { t: 'Divide 3/4 by 1/12, then add 4', c: false, w: 'The 4 bags are GIVEN AWAY, so they are taken off. &ldquo;Left&rdquo; means subtract.' }],
    answer: { num: 5, den: 1 },
    unit: 'bags',
    work: '3/4 &divide; 1/12 = 3/4 &times; 12/1 = 36/4 = <b>9 bags</b>. Then 9 &minus; 4 = <b>5</b>.',
    check: [{ t: '3/4 is the same as 9/12, so 9 bags can be packed. Giving away 4 leaves 5.', c: true, w: 'It rebuilds the answer: 3/4 = 9/12, so 9 bags of 1/12 kilogram. Giving away 4 leaves 5.' }, { t: 'There must be 12 bags because each bag is 1/12 kilogram.', c: false, w: '12 bags would need a full kilogram (12/12). There is only 3/4 = 9/12 kilogram, so only 9 bags.' }, { t: 'The answer is 5/12 kilogram of rice.', c: false, w: 'The question asks how many BAGS are left, so the answer is a count: 5 bags. 5/12 kilogram is only the rice inside them.' }]
  },
  {
    id: 'wt11',
    text: 'A tank has <b>3/4 liter</b> of water. It is poured into bottles that hold <b>3/8 liter</b> each. 3 more bottles are then filled from a second tank. How many bottles are filled altogether?',
    givens: [{ t: 'The tank has 3/4 liter of water', is: true, w: 'The problem says the tank has 3/4 liter of water.' }, { t: 'Each bottle holds 3/8 liter', is: true, w: 'The problem says the bottles hold 3/8 liter each.' }, { t: '3 more bottles are filled from a second tank', is: true, w: 'The problem says 3 more bottles are filled from a second tank.' }, { t: 'The second tank also holds 3/4 liter', is: false, w: 'The problem never says how much water the second tank holds, only that it fills 3 more bottles.' }, { t: 'There are 8 bottles in total', is: false, w: 'The problem never says 8 bottles. The 8 comes from 3/8 liter, and the total number of bottles is what you must find.' }],
    asked: [{ t: 'How many bottles are filled altogether', c: true, w: 'The last sentence asks &ldquo;How many bottles are filled altogether?&rdquo; That includes the 3 from the second tank.' }, { t: 'How much water each bottle holds', c: false, w: 'That is given: each bottle holds 3/8 liter. The question asks for a number of bottles.' }, { t: 'How much water is left in the tank', c: false, w: 'The problem does not ask about water left over. It asks how many bottles are filled altogether.' }],
    plan: [{ t: 'Divide 3/4 by 3/8, then add 3', c: true, w: 'Dividing 3/4 by 3/8 finds how many bottles the first tank fills (2). The 3 more bottles are added because the question says &ldquo;altogether&rdquo;.' }, { t: 'Multiply 3/4 by 3/8, then add 3', c: false, w: 'Multiplying gives 9/32 liter, not a number of bottles. To find how many 3/8s fit in 3/4, divide.' }, { t: 'Divide 3/8 by 3/4, then add 3', c: false, w: 'The order is backwards. You divide the WATER (3/4) by the bottle size (3/8). Flipping them gives 1/2, not 2.' }, { t: 'Divide 3/4 by 3/8, then subtract 3', c: false, w: 'The 3 bottles are MORE bottles being filled, not bottles taken away. &ldquo;Altogether&rdquo; means add.' }],
    answer: { num: 5, den: 1 },
    unit: 'bottles',
    work: '3/4 &divide; 3/8 = 3/4 &times; 8/3 = 24/12 = <b>2 bottles</b>. Then 2 + 3 = <b>5</b>.',
    check: [{ t: 'Two bottles of 3/8 liter hold 6/8 = 3/4 liter, which is exactly what the tank had. Three more makes 5.', c: true, w: 'Working backwards: 2 bottles of 3/8 liter hold 6/8 = 3/4 liter, exactly what the tank had. So 2 is right, and 2 + 3 = 5.' }, { t: 'The answer is 24/12 bottles.', c: false, w: '24/12 is not simplified: it equals 2. And it only counts the first tank; you still add the 3 more bottles.' }, { t: 'Dividing by 3/8 should give a smaller answer than 3/4.', c: false, w: 'Dividing by a fraction smaller than 1 gives a BIGGER answer. 3/4 &divide; 3/8 = 2, which is bigger than 3/4, and that is correct.' }]
  },
  {
    id: 'wt12',
    text: 'A piece of cloth is <b>4/5 meter</b> long. It is cut into pieces of <b>2/15 meter</b> each. 2 of the pieces are used for a sample. How many pieces are left?',
    givens: [{ t: 'The cloth is 4/5 meter long', is: true, w: 'The problem says the cloth is 4/5 meter long.' }, { t: 'Each piece is 2/15 meter', is: true, w: 'The problem says it is cut into pieces of 2/15 meter each.' }, { t: '2 pieces are used', is: true, w: 'The problem says 2 of the pieces are used for a sample.' }, { t: 'The cloth is 15 meters wide', is: false, w: 'The problem never says how wide the cloth is. The 15 comes from 2/15 meter, the size of each piece.' }, { t: 'There are 5 samples to make', is: false, w: 'The problem talks about just one sample. The 5 comes from 4/5 meter.' }],
    asked: [{ t: 'How many pieces are left', c: true, w: 'The last sentence asks &ldquo;How many pieces are left?&rdquo; That is exactly what you must find.' }, { t: 'How many meters of cloth are left', c: false, w: 'The question counts pieces, not meters. Read the last sentence again.' }, { t: 'How long each piece is', c: false, w: 'That is given: each piece is 2/15 meter. The question asks how many pieces are left.' }],
    plan: [{ t: 'Divide 4/5 by 2/15, then subtract 2', c: true, w: 'Dividing 4/5 by 2/15 finds how many pieces can be cut (6). Taking away the 2 used pieces leaves the answer.' }, { t: 'Multiply 4/5 by 2/15, then subtract 2', c: false, w: 'Multiplying gives 8/75 meter, not a number of pieces. To find how many 2/15s fit in 4/5, divide.' }, { t: 'Divide 4/5 by 2, then subtract 2/15', c: false, w: 'This mixes up the numbers. You divide by the piece size (2/15), and subtract the 2 pieces that were used.' }, { t: 'Subtract 2/15 from 4/5 two times', c: false, w: 'That gives 8/15 meter, a length of cloth, not a number of pieces. First find how many pieces were cut.' }],
    answer: { num: 4, den: 1 },
    unit: 'pieces',
    work: '4/5 &divide; 2/15 = 4/5 &times; 15/2 = 60/10 = <b>6 pieces</b>. Then 6 &minus; 2 = <b>4</b>.',
    check: [{ t: 'Six pieces of 2/15 meter make 12/15 = 4/5 meter, the whole cloth. Using 2 leaves 4.', c: true, w: 'Working backwards: 6 pieces of 2/15 meter make 12/15 = 4/5 meter, the whole cloth. So 6 is right, and 6 &minus; 2 = 4.' }, { t: '6 pieces is the answer, because that is what dividing gave us.', c: false, w: 'The division counts ALL the pieces cut. The question asks how many are LEFT, so the 2 used pieces must be taken away.' }, { t: '4/5 is less than 1, so fewer than 1 piece can be cut.', c: false, w: 'Each piece is only 2/15 meter, much shorter than the cloth. Six of them fit in 4/5 meter.' }]
  },
  {
    id: 'wt13',
    text: 'A jar holds <b>2/3 kilogram</b> of honey. It is packed into small jars that hold <b>2/9 kilogram</b> each. 4 more small jars are filled from a different batch. How many small jars are there altogether?',
    givens: [{ t: 'There is 2/3 kilogram of honey', is: true, w: 'The problem says the jar holds 2/3 kilogram of honey.' }, { t: 'Each small jar holds 2/9 kilogram', is: true, w: 'The problem says the small jars hold 2/9 kilogram each.' }, { t: '4 more small jars are filled from another batch', is: true, w: 'The problem says 4 more small jars are filled from a different batch.' }, { t: 'There are 9 small jars available', is: false, w: 'The problem never says 9 jars. The 9 comes from 2/9 kilogram, the size of each small jar.' }, { t: 'The honey costs 4 pesos per jar', is: false, w: 'The problem never mentions money. The 4 is the number of extra jars, not pesos.' }],
    asked: [{ t: 'How many small jars there are altogether', c: true, w: 'The last sentence asks &ldquo;How many small jars are there altogether?&rdquo; That includes the 4 from the other batch.' }, { t: 'How many small jars came from the first batch', c: false, w: 'That is only part of the answer (3). &ldquo;Altogether&rdquo; means you must also count the 4 more jars.' }, { t: 'How much honey is in each small jar', c: false, w: 'That is given: each small jar holds 2/9 kilogram. The question asks for a number of jars.' }],
    plan: [{ t: 'Divide 2/3 by 2/9, then add 4', c: true, w: 'Dividing 2/3 by 2/9 finds how many small jars the honey fills (3). The 4 more jars are added because the question says &ldquo;altogether&rdquo;.' }, { t: 'Multiply 2/3 by 2/9, then add 4', c: false, w: 'Multiplying gives 4/27 kilogram, not a number of jars. To find how many 2/9s fit in 2/3, divide.' }, { t: 'Divide 2/9 by 2/3, then add 4', c: false, w: 'The order is backwards. You divide the HONEY (2/3) by the jar size (2/9). Flipping them gives 1/3, not 3.' }, { t: 'Divide 2/3 by 2/9, then subtract 4', c: false, w: 'The 4 jars are MORE jars being filled, not jars taken away. &ldquo;Altogether&rdquo; means add.' }],
    answer: { num: 7, den: 1 },
    unit: 'small jars',
    work: '2/3 &divide; 2/9 = 2/3 &times; 9/2 = 18/6 = <b>3 jars</b>. Then 3 + 4 = <b>7</b>.',
    check: [{ t: 'Three jars of 2/9 kilogram hold 6/9 = 2/3 kilogram, which matches. Four more makes 7.', c: true, w: 'Working backwards: 3 jars of 2/9 kilogram hold 6/9 = 2/3 kilogram, which matches the honey. So 3 is right, and 3 + 4 = 7.' }, { t: 'The answer is 18/6 jars.', c: false, w: '18/6 is not simplified: it equals 3. And it only counts the first batch; you still add the 4 more jars.' }, { t: 'We should have added 4 before dividing.', c: false, w: 'The 4 is a number of jars, not kilograms of honey, so it cannot go into the division. Divide first, then add 4.' }]
  },
  {
    id: 'wt14',
    text: 'A baker has <b>5/8 kilogram</b> of sugar. She shares it equally into <b>5</b> bags. How much sugar is in each bag?',
    givens: [{ t: 'There is 5/8 kilogram of sugar', is: true, w: 'The problem says the baker has 5/8 kilogram of sugar.' }, { t: 'It is shared equally into 5 bags', is: true, w: 'The problem says she shares it equally into 5 bags.' }, { t: 'Each bag holds 5/8 kilogram', is: false, w: 'The 5/8 kilogram is ALL the sugar. Each bag gets only a share of it, and that share is what you must find.' }, { t: 'She has 8 bags', is: false, w: 'The problem says 5 bags, not 8. The 8 comes from 5/8 kilogram.' }],
    asked: [{ t: 'How much sugar is in each bag', c: true, w: 'The question asks &ldquo;How much sugar is in each bag?&rdquo;' }, { t: 'How many bags she can fill', c: false, w: 'The problem already says 5 bags. You must find how much sugar goes in EACH bag.' }, { t: 'How much sugar she has altogether', c: false, w: 'That is given: 5/8 kilogram. The question asks about each bag.' }],
    plan: [{ t: 'Divide 5/8 by 5, which is the same as multiplying by 1/5', c: true, w: 'Sharing equally into 5 bags means divide by 5, and dividing by 5 is the same as &times; 1/5. 5/8 &times; 1/5 = 5/40 = 1/8.' }, { t: 'Divide 5/8 by 1/5, which is the same as multiplying by 5', c: false, w: 'The sugar is shared into 5 bags, so you divide by 5, not by 1/5. Dividing by 1/5 makes the sugar 5 times bigger.' }, { t: 'Multiply 5/8 by 5', c: false, w: 'Multiplying by 5 gives 25/8 kilograms, more than she has. Sharing into 5 bags makes each bag SMALLER.' }, { t: 'Subtract 5 from 5/8', c: false, w: 'You cannot take 5 away from 5/8, which is less than 1. Sharing equally into 5 bags means divide by 5.' }],
    answer: { num: 1, den: 8 },
    unit: 'kilogram per bag',
    work: '5/8 &divide; 5 = 5/8 &times; 1/5 = 5/40 = <b>1/8 kilogram</b>.',
    check: [{ t: 'Each bag must hold less than 5/8, and 1/8 is less. Five bags of 1/8 make 5/8, the amount she started with.', c: true, w: 'It checks two ways: each bag (1/8) holds less than the whole (5/8), and 5 bags of 1/8 make 5/8, the amount she started with.' }, { t: '3 1/8 kilograms is right, because 5/8 &times; 5 = 25/8.', c: false, w: '3 1/8 kilograms is far MORE sugar than she has (5/8). One bag cannot hold more than the whole amount.' }, { t: 'Sharing into 5 bags makes each bag bigger.', c: false, w: 'Sharing always makes each share SMALLER than the whole. Each bag gets only part of the 5/8 kilogram.' }]
  }
]);
