StudyKit.lesson({
  id: 'myself',
  icon: '🌱',
  title: 'Knowing & Understanding Myself',
  subtitle: 'Strengths, weaknesses, change & resilience',
  cards: [
    { front: 'Knowing Yourself', back: 'Understanding your personality, likes and dislikes, strengths, weaknesses, and feelings.' },
    { front: 'Strengths', back: 'Things you do well — like drawing, singing, solving math problems, helping others, being kind, or being responsible.' },
    { front: 'Weaknesses', back: 'Things you still need to improve — like being easily distracted, shy when speaking, poor time management, or afraid to try new things.' },
    { front: '3 Kinds of Change', back: 'Physical (becoming taller/stronger), Emotional (understanding and managing feelings), Personal (discovering new skills, talents, interests).' },
    { front: 'Resilience', back: 'The ability to recover from difficulties and keep going. Challenges at home or school help build resilience.' },
    { front: '5 Ways to Value Yourself', back: '1) Obey your parents, 2) Change undesirable attitudes, 3) Do something good for yourself and others, 4) Learn to appreciate, 5) Be aware of yourself.' },
    { front: 'Remember', back: '"Growth begins when we embrace change."' }
  ],
  quiz: [
    { q: 'True or False: Knowing yourself only means knowing your favorite color and food.', options: ['True', 'False'], correct: 1, explain: 'Knowing yourself means understanding your personality, likes/dislikes, strengths, weaknesses, AND feelings — much more than favorites.', why: ['The word "only" makes this false. Knowing yourself also means understanding your personality, strengths, weaknesses and feelings — favorites are just a small part.', ''], tip: 'Watch for the word "only" in True/False. Ask: is that REALLY the only thing? If the lesson lists more, the answer is False.' },
    { q: 'Ana always finishes her homework on time and helps classmates who don’t understand a lesson. Which STRENGTH does this show?', options: ['Being disorganized', 'Being responsible and helpful', 'Being shy', 'Being easily distracted'], correct: 1, explain: 'Finishing tasks on time and helping others shows responsibility and helpfulness — both strengths.', why: ['Being disorganized would look like Ana losing her things or forgetting her homework — but she finishes her homework on time.', '', 'Being shy would look like Ana staying quiet and keeping away from others — but she goes and helps her classmates.', 'Being easily distracted would look like Ana not finishing her work — but she finishes on time.'], tip: 'Match each action to a word: "finishes on time" = responsible, "helps classmates" = helpful. A strength is something good that she does well.' },
    { q: 'True or False: A weakness is something you can never improve, no matter how hard you try.', options: ['True', 'False'], correct: 1, explain: 'Weaknesses are things you still NEED to improve — they can get better with effort, unlike the statement claims.', why: ['The word "never" makes this false. The lesson calls weaknesses things you still NEED to improve — with effort they can get better.', ''], tip: 'Words like "never" and "always" often make a statement false. Remember: a weakness is a "not yet," not a "never."' },
    { q: 'Miguel gets nervous and forgets his words whenever he speaks in front of the class. Which weakness does this show?', options: ['Poor time management', 'Shy when speaking', 'Easily distracted', 'Afraid of change'], correct: 1, explain: 'Getting nervous while speaking in front of others is the weakness "shy when speaking."', why: ['Poor time management would mean Miguel runs out of time or is late with his work — the story is about his speaking, not his time.', '', 'Being easily distracted would mean his attention wanders to other things — Miguel is nervous, not distracted.', 'Being afraid of change is about fearing new things — Miguel\'s problem is speaking in front of the class.'], tip: 'Find the key action in the story ("nervous... speaks in front of the class") and pick the weakness that names that same action.' },
    { q: 'True or False: Becoming taller and stronger as you grow older is an example of physical change.', options: ['True', 'False'], correct: 0, explain: 'Yes — becoming taller and stronger is exactly what physical change means.', why: ['', 'This statement is true. Physical change is about your body, and becoming taller and stronger is exactly the lesson\'s example.'], tip: 'Remember the 3 kinds of change: Physical = body, Emotional = feelings, Personal = new skills and interests. Taller and stronger is about the body.' },
    { q: 'Which of these shows an EMOTIONAL change?', options: ['Growing three inches taller', 'Learning to stay calm instead of shouting when angry', 'Discovering you are good at chess', 'Wearing a bigger shoe size'], correct: 1, explain: 'Learning to understand and manage your feelings, like calming down instead of shouting, is emotional change.', why: ['Growing taller is a change in your body, so it is a PHYSICAL change, not an emotional one.', '', 'Discovering you are good at chess is finding a new skill or talent — that is a PERSONAL change.', 'A bigger shoe size means your body grew — that is a PHYSICAL change.'], tip: 'EMOTIONAL has the word "emotion" in it. Look for the choice about feelings, like anger or staying calm.' },
    { q: 'True or False: Resilience means giving up immediately when something becomes difficult.', options: ['True', 'False'], correct: 1, explain: 'Resilience is the OPPOSITE — it means recovering from difficulty and continuing on.', why: ['Resilience is the opposite of giving up. It means recovering from difficulties and continuing on.', ''], tip: 'Think of a ball that bounces back. A resilient person bounces back from problems instead of quitting.' },
    { q: 'Liza’s parents told her to stop staying up late playing games because it affects her studies. What should Liza do to value herself, based on the lesson?', options: ['Ignore her parents completely', 'Get angry at her parents', 'Listen and respect their advice', 'Play even later to prove a point'], correct: 2, explain: '"Obey your parents — listen, learn from their experience, and respect their advice" is one of the 5 ways to value yourself.', why: ['Ignoring her parents is the opposite of "Obey your parents," one of the 5 ways to value yourself.', 'Getting angry does not show respect. The lesson says to listen to your parents and respect their advice.', '', 'Playing even later goes against her parents\' advice and hurts her studies — that does not value herself.'], tip: 'When a question is about a parent\'s advice, remember Way #1: Obey your parents — listen, learn and respect.' },
    { q: 'True or False: One way to value yourself is to help other people and join school or community activities.', options: ['True', 'False'], correct: 0, explain: 'Yes — "do something good for yourself and others" includes helping people and joining activities.', why: ['', 'This statement is true. "Do something good for yourself and others" is one of the 5 ways, and helping people and joining activities fit it.'], tip: 'Check the statement against the 5 Ways to Value Yourself. If it matches one of them, it is True.' },
    { q: 'Every night before bed, Carlo thinks of three things he is thankful for. Which of the 5 Ways to Value Oneself is Carlo practicing?', options: ['Obey your parents', 'Change undesirable attitudes', 'Learn to appreciate', 'Be aware of yourself'], correct: 2, explain: 'Being thankful and practicing gratitude every day is exactly "learn to appreciate."', why: ['Obey your parents is about listening to their advice — Carlo\'s story is about being thankful.', 'Changing undesirable attitudes means fixing a bad habit — Carlo is not fixing anything, he is giving thanks.', '', 'Being aware of yourself is about knowing your own strengths and feelings — Carlo is thinking about what he is thankful for.'], tip: 'Clue word: "thankful." Thankful = appreciate. Link the key word in the story to the name of the way.' }
  ]
});
