StudyKit.lesson({
  id: 'saving',
  icon: '🐷',
  title: 'Saving Early & Spending Wisely',
  subtitle: 'Needs vs wants, budgeting & good habits',
  cards: [
    { front: 'Saving', back: 'Keeping part of your money instead of spending it all, so you can use it for important things in the future.' },
    { front: 'Why We Save', back: 'To prepare for emergencies, buy things we really need, reach our goals, and become responsible with money.' },
    { front: 'How to Save Money', back: 'Do budget planning, shop only with a list, stay within your means, and learn to be thrifty.' },
    { front: 'Wise Spending', back: 'Thinking before buying, buying what you need first, avoiding unnecessary expenses, and comparing prices.' },
    { front: 'Needs vs Wants', back: 'Needs: food, water, school supplies, medicine. Wants: toys, expensive gadgets, fancy accessories, makeup.' },
    { front: 'Good Saving Habits', back: 'Save part of your allowance, use a piggy bank, set a savings goal, avoid impulse buying, spend only within budget.' },
    { front: 'Remember', back: '"A penny saved is a penny earned." — Benjamin Franklin' }
  ],
  quiz: [
    { q: 'True or False: Saving means spending all your money right away so it doesn’t get lost.', options: ['True', 'False'], correct: 1, explain: 'Saving means keeping PART of your money instead of spending it all.', why: ['"Spending all your money right away" makes this false. Saving means keeping PART of your money, not spending it all.', ''], tip: 'Saving = keeping. If a sentence says "spend it all," it cannot be describing saving.' },
    { q: 'Your parents give you ₱200. What is the WISEST thing to do?', options: ['Buy toys immediately', 'Buy everything you want', 'Save some and spend only what you need', 'Give it all away'], correct: 2, explain: 'Saving some and spending only what you truly need is the wise choice from the lesson.', why: ['Buying toys right away spends money on a want without thinking, and leaves nothing saved.', 'Buying everything you want means spending it all — the opposite of saving and wise spending.', '', 'Giving it all away leaves nothing for your needs or your savings. The lesson says save some and spend only on what you need.'], tip: 'The wisest choice usually does two things: it covers what you need AND saves some. Look for the word "save."' },
    { q: 'True or False: Food, water, medicine, and school supplies are examples of NEEDS.', options: ['True', 'False'], correct: 0, explain: 'Correct — these are all things people need, not just want.', why: ['', 'This statement is true. The lesson lists food, water, medicine and school supplies as NEEDS.'], tip: 'Ask: "Can I live or go to school without it?" If not, it is a need.' },
    { q: 'Which of these is a WANT, not a need?', options: ['School supplies', 'Medicine', 'Expensive gadgets', 'Water'], correct: 2, explain: 'Expensive gadgets are a want — nice to have, but not necessary for survival or school.', why: ['School supplies are a need — you use them to learn at school.', 'Medicine is a need — it keeps you healthy when you are sick.', '', 'Water is a need — everyone needs it to live.'], tip: 'Cross out the needs you know (food, water, medicine, school supplies). The one left over is the want.' },
    { q: 'True or False: Wise spending means buying anything you like as long as you have money in your pocket.', options: ['True', 'False'], correct: 1, explain: 'Wise spending means thinking before buying, buying needs first, and comparing prices — not buying anything you like.', why: ['"Anything you like" makes this false. Wise spending means thinking before buying, buying needs first, and comparing prices.', ''], tip: 'Wise spending asks "Do I need this?" before buying. If a statement skips the thinking, it is not wise spending.' },
    { q: 'True or False: Maria receives ₱100 allowance. She spends ₱40 on snacks, ₱20 on school materials, and saves ₱40. Maria is spending wisely.', options: ['True', 'False'], correct: 0, explain: 'Correct — she covered her needs, allowed a small treat, and still saved part of her money.', why: ['', 'This statement is true. Maria paid for school materials, had a small treat, and still saved ₱40 — that is wise spending.'], tip: 'For money stories, check three things: Were the needs covered? Was some money saved? Did she stay within her budget?' },
    { q: 'True or False: Having personal savings can help you avoid unnecessary debts.', options: ['True', 'False'], correct: 0, explain: 'Correct — when you have spare money saved, you don’t need to borrow as much.', why: ['', 'This statement is true. When you have money saved, you do not need to borrow as much, so you avoid unnecessary debts.'], tip: 'Think: if I already have money saved, do I need to borrow? No — so savings help you avoid debt.' },
    { q: 'Before buying a new toy, what should you ask yourself first, based on the lesson?', options: ['"Will my friends be jealous?"', '"Do I really need this, and can I save this money instead?"', '"Is it the most expensive one?"', '"Can I buy it without telling anyone?"'], correct: 1, explain: 'The lesson’s "Think Before You Buy" questions are: Do I need this? Can I save instead? Will it help me in the future?', why: ['Making your friends jealous is not a good reason to buy something. The lesson asks whether you really need it.', '', 'Choosing the most expensive one goes against comparing prices and avoiding unnecessary expenses.', 'Buying something secretly is not honest, and it skips the "Think Before You Buy" questions.'], tip: 'Remember the "Think Before You Buy" questions: Do I need this? Can I save instead? Will it help me in the future?' },
    { q: 'True or False: Using a piggy bank and setting a savings goal are examples of good saving habits.', options: ['True', 'False'], correct: 0, explain: 'Correct — both are listed as good saving habits in the lesson.', why: ['', 'This statement is true. Using a piggy bank and setting a savings goal are both on the list of good saving habits.'], tip: 'Recall the Good Saving Habits: save part of your allowance, use a piggy bank, set a savings goal, avoid impulse buying, stay within budget.' },
    { q: 'Jayson’s group has ₱2,000 for a weekend hangout. Which shows a responsible group?', options: ['Spend all ₱2,000 on snacks and games', 'Plan a budget, buy what’s needed, and set aside money for savings', 'Borrow more money to spend more', 'Spend everything on the first item they see'], correct: 1, explain: 'Responsible people plan their budget and still set aside savings, even while having fun.', why: ['Spending all ₱2,000 leaves nothing saved — responsible people set some money aside.', '', 'Borrowing more money means spending more than you have and getting into debt.', 'Buying the first thing they see is impulse buying, which good savers avoid.'], tip: 'Look for the choice with a plan. "Budget," "what\'s needed" and "savings" are the clue words of responsible spending.' }
  ]
});
