StudyKit.lesson({
  id: 'dignity',
  icon: '🤝',
  title: 'Valuing Human Dignity',
  subtitle: 'Respect, worth & caring for others',
  cards: [
    { front: 'Human Dignity', back: 'Every person has value and worth simply because he or she is a human being.' },
    { front: 'Everyone Deserves', back: 'Love, respect, kindness, and fair treatment — no exceptions.' },
    { front: 'Understanding Human Dignity', back: 'Your worth as a person; human life is a gift; everyone is unique; everyone can dream; everyone has something to contribute.' },
    { front: 'What Destroys Human Dignity', back: 'Forced or child labor, hate crimes, trespassing on human rights, lack of access to basic necessities, the refugee crisis, and fake news.' },
    { front: '3 Ways to Respect Human Life', back: '1) Improve your life through education, 2) Practice values and virtues, 3) Accept corrections from parents and teachers with humility.' },
    { front: 'Remember', back: '"Every person is special. We may look different, think differently, or come from different backgrounds, but we all deserve respect because every human being has dignity."' }
  ],
  quiz: [
    { q: 'True or False: Human dignity means only smart or rich people deserve respect.', options: ['True', 'False'], correct: 1, explain: 'Everyone deserves respect simply because they are human — dignity is not based on being smart or rich.', why: ['The word "only" makes this false. Everyone deserves respect simply because they are human, not because they are smart or rich.', ''], tip: 'Human dignity belongs to EVERY person. If a statement says only some people deserve respect, it is False.' },
    { q: 'A classmate is being teased for wearing old shoes. What should you do to respect his human dignity?', options: ['Join the teasing', 'Ignore it and walk away', 'Defend him and treat him with kindness', 'Laugh along quietly'], correct: 2, explain: 'Standing up for someone and showing kindness respects their dignity as a person.', why: ['Joining the teasing hurts him even more and does not respect his dignity.', 'Walking away leaves him alone while he is being hurt. Respecting dignity means showing kindness.', '', 'Laughing, even quietly, still joins in the teasing and makes him feel small.'], tip: 'Ask yourself: "Which choice treats him with kindness and respect?" Choices that hurt him or ignore him do not respect dignity.' },
    { q: 'True or False: Every person is unique, but only some people have something to contribute to the world.', options: ['True', 'False'], correct: 1, explain: 'The lesson says EVERYONE has something to contribute, not just some people.', why: ['"Only some people" makes this false. The lesson says EVERYONE has something to contribute.', ''], tip: 'Read each half of the sentence. The first half is true, but "only some people" is wrong — one wrong part makes the whole statement False.' },
    { q: 'Which situation is an example of something that DESTROYS human dignity?', options: ['A child being forced to work instead of going to school', 'A student studying hard for a test', 'A family sharing a meal', 'Friends helping each other with homework'], correct: 0, explain: 'Forced or child labor is listed as something that destroys and violates human dignity.', why: ['', 'A student studying hard is improving her life through education — that respects human life.', 'A family sharing a meal shows love and care, which respects dignity.', 'Friends helping each other with homework is kindness — it respects dignity.'], tip: 'Remember the list of what destroys dignity: forced or child labor, hate crimes, lack of basic necessities, the refugee crisis and fake news. Find the choice that hurts someone.' },
    { q: 'True or False: Accepting corrections from your parents and teachers is a sign of humility and respect for human life.', options: ['True', 'False'], correct: 0, explain: 'Correct — accepting corrections with humility is one of the 3 ways to respect human life.', why: ['', 'This statement is true. Accepting corrections from parents and teachers with humility is one of the 3 ways to respect human life.'], tip: 'Remember the 3 ways to respect human life: education, values and virtues, and accepting corrections with humility.' },
    { q: 'You see a younger student struggling to carry their bags. What is the BEST way to show you value human dignity?', options: ['Walk past without helping', 'Offer to help carry the bags', 'Tell them it’s not your problem', 'Take a photo to post online'], correct: 1, explain: 'Offering help is a direct way of showing kindness and respect for another person’s worth.', why: ['Walking past without helping shows no kindness to someone who needs it.', '', 'Saying "it\'s not your problem" is unkind and ignores the person\'s worth.', 'Taking a photo to post online does not help them, and it could embarrass them.'], tip: 'In "BEST way" questions, pick the choice that actually helps the person with kindness.' },
    { q: 'True or False: Spreading fake news about someone is an example of respecting their human dignity.', options: ['True', 'False'], correct: 1, explain: 'Fake news is listed as something that destroys human dignity, not respects it.', why: ['Fake news is on the list of things that DESTROY human dignity, so spreading it does not respect anyone.', ''], tip: 'If an action is on the "destroys dignity" list, it can never be a way of respecting dignity.' },
    { q: 'According to the lesson, which is one of the 3 ways to respect human life?', options: ['Avoiding school', 'Practicing values and virtues', 'Ignoring corrections', 'Comparing yourself to others'], correct: 1, explain: 'Practicing values and virtues is one of the 3 ways to respect human life mentioned in the lesson.', why: ['Avoiding school is the opposite of "improve your life through education."', '', 'Ignoring corrections is the opposite of "accept corrections with humility."', 'Comparing yourself to others is not one of the 3 ways to respect human life.'], tip: 'Wrong choices are often the OPPOSITE of the real list. Remember the 3 ways: education, values and virtues, and accepting corrections.' },
    { q: 'True or False: Everyone deserves love, respect, kindness, and fair treatment, no matter who they are.', options: ['True', 'False'], correct: 0, explain: 'Correct — this is exactly what human dignity means.', why: ['', 'This statement is true. "No matter who they are" is the whole point — every person deserves love, respect, kindness and fair treatment.'], tip: 'Statements that say EVERYONE deserves respect match the lesson on human dignity, so they are True.' },
    { q: 'A new student joins your class and looks different from everyone else. What should you do?', options: ['Avoid talking to them', 'Treat them the same way you’d want to be treated, with respect', 'Make fun of how they look', 'Tell others not to be friends with them'], correct: 1, explain: 'Treating everyone with respect, regardless of how they look, is the core of valuing human dignity.', why: ['Avoiding the new student leaves them alone just because they look different — that is not fair treatment.', '', 'Making fun of how someone looks hurts them and does not respect their dignity.', 'Telling others not to be friends with them is unfair and unkind.'], tip: 'Use this question: "How would I want to be treated if I were the new student?" That choice is the answer.' }
  ]
});
