StudyKit.lesson({
  id: 'faith',
  icon: '🙏',
  title: 'Faith',
  subtitle: 'Believing in God and choosing what is good',
  cards: [
    { front: 'What Is Faith?', back: '<b>Believing in God.</b>' },
    { front: 'Why Faith Matters', back: 'Faith <b>guides us to choose what is good and avoid what is wrong</b>.' },
    { front: 'How Faith Helps Us Choose', back: 'It <b>gives us guidance in doing what is right and good</b> &mdash; not just whatever makes us happy.' },
    { front: 'What Faith Is NOT', back: 'Believing <b>only in yourself</b>, believing only in what you can <b>see</b>, or simply <b>following what other people do</b>.' },
    { front: 'Faith Does NOT Teach Us To&hellip;', back: 'Get even when someone hurts us &middot; always put ourselves first &middot; do whatever we want &middot; think we are better than other people.' }
  ],
  quiz: [
    { q: 'What does &ldquo;faith&rdquo; mean?', options: ['Believing in God', 'Believing only in oneself', 'Believing in what we can see', 'Following what other people do'], correct: 0, explain: 'Faith means <b>believing in God</b>.', why: ['', 'Believing only in yourself is on the list of what faith is NOT.', 'Believing only in what you can see is on the list of what faith is NOT.', 'Simply following what other people do is on the list of what faith is NOT.'], tip: 'Faith = believing in God. The other choices all come from the "What Faith Is NOT" card.' },
    { q: 'Why is faith important in a person&rsquo;s life?', options: ['It guides us to choose what is good and avoid what is wrong.', 'It teaches us to get even when someone hurts us.', 'It teaches us to always put ourselves first.', 'It teaches us to do whatever we want.'], correct: 0, explain: 'Faith <b>guides</b> us toward what is good and away from what is wrong.', why: ['', 'Getting even when someone hurts us is something faith does NOT teach.', 'Always putting ourselves first is something faith does NOT teach.', 'Doing whatever we want is something faith does NOT teach — faith guides us to do what is good.'], tip: 'Faith points us to what is GOOD. Any choice about getting even, being selfish or doing whatever we want is wrong.' },
    { q: 'How does faith help us know what is right and wrong?', options: ['It gives us guidance in doing what is right and good.', 'It makes us better than other people.', 'It tells us to do only what makes us happy.', 'It means we no longer need to listen to others.'], correct: 0, explain: 'Faith gives us <b>guidance</b> in doing what is right and good.', why: ['', 'Faith does not make us better than other people — thinking that way is something faith does NOT teach.', 'Faith guides us to what is right and good, not just to whatever makes us happy.', 'Faith does not tell us to stop listening to others. It gives us guidance in doing what is right.'], tip: 'Clue word: "guidance." Faith guides us, so look for the choice about doing what is right and good.' },
    { q: 'True or False: Faith means believing only in yourself.', options: ['True', 'False'], correct: 1, explain: 'False — faith means <b>believing in God</b>, not only in yourself.', why: ['"Only in yourself" makes this false. Faith means believing in God — believing only in yourself is what faith is NOT.', ''], tip: 'If a sentence says faith is believing in something other than God, it is False.' },
    { q: 'True or False: Faith guides us to choose what is good and avoid what is wrong.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is why faith is important in a person&rsquo;s life.', why: ['', 'This statement is true. Guiding us to choose good and avoid wrong is exactly why faith is important in a person\'s life.'], tip: 'Remember why faith matters: it guides us to choose good and avoid wrong. A statement that says this is True.' },
    { q: 'True or False: Faith teaches us to get even when someone hurts us.', options: ['True', 'False'], correct: 1, explain: 'False — getting even is the opposite of what faith teaches. Faith guides us to do what is <b>good</b>.', why: ['Getting even is on the list of things faith does NOT teach. Faith guides us to do what is good.', ''], tip: 'Getting even (paying someone back for hurting you) is never what faith teaches. Spot "get even" and answer False.' },
    { q: 'True or False: Faith can guide us in doing what is right and good.', options: ['True', 'False'], correct: 0, explain: 'Correct — faith gives us guidance in doing what is right and good.', why: ['', 'This statement is true. Faith gives us guidance in doing what is right and good.'], tip: 'Faith + guidance + right and good = True. Look for those words together.' },
    { q: 'A classmate took your pencil without asking. Which choice shows faith guiding you?', options: ['Calmly ask for it back and forgive her', 'Take something of hers so you are even', 'Tell the whole class that she is a thief', 'Refuse to ever talk to her again at all'], correct: 0, explain: 'Faith guides us to choose what is <b>good</b>, not to get even.', why: ['', 'Taking something of hers so you are "even" is getting even — faith does not teach that.', 'Calling her a thief in front of the class hurts and embarrasses her. That is not choosing what is good.', 'Refusing to ever talk to her again is holding on to anger instead of forgiving.'], tip: 'In a "someone hurt me" story, the faith choice is calm and forgiving — never getting even or hurting back.' },
    { q: 'Which of these is NOT something faith teaches us?', options: ['to always put ourselves first', 'to choose what is good', 'to avoid what is wrong', 'to do what is right'], correct: 0, explain: 'Always putting ourselves first is one of the wrong answers on your test. The other three are what faith teaches.', why: ['', 'Choosing what is good IS something faith teaches, so it is not the answer — we need the one faith does NOT teach.', 'Avoiding what is wrong IS something faith teaches, so it is not the answer — we need the one that is NOT.', 'Doing what is right IS something faith teaches, so it is not the answer — we need the one that is NOT.'], tip: 'For NOT questions, cross out every choice that faith DOES teach. The one left over is your answer.' },
    { q: 'Which of these best describes a person guided by faith?', options: ['She chooses what is right even when no one is watching.', 'She does whatever she wants, whenever she feels like it.', 'She believes only in the things that she can see herself.', 'She copies whatever her friends decide to do each day.'], correct: 0, explain: 'Faith guides us to do what is right and good, not whatever we want or whatever others do.', why: ['', 'Doing whatever she wants is something faith does NOT teach.', 'Believing only in what she can see is on the list of what faith is NOT.', 'Copying her friends is "following what other people do," which is what faith is NOT.'], tip: 'Check each choice against the "What Faith Is NOT" card. The one that is NOT on that card describes the person guided by faith.' }
  ]
});
