StudyKit.lesson({
  id: 'manners',
  icon: '🎩',
  title: 'Good Manners & Right Conduct',
  subtitle: 'Kindness, honesty &amp; respect in everyday situations',
  cards: [
    { front: 'Good Manners', back: '<b>Polite and respectful ways</b> we speak and act toward other people.' },
    { front: 'Right Conduct', back: 'Choosing to do what is <b>right, honest and good</b> &mdash; even when no one is watching.' },
    { front: 'Magic Words', back: '&ldquo;<b>Please</b>,&rdquo; &ldquo;<b>Thank you</b>,&rdquo; &ldquo;<b>Sorry</b>,&rdquo; &ldquo;<b>Excuse me</b>&rdquo; &mdash; and <b>po</b> and <b>opo</b> when talking to elders.' },
    { front: 'Comfort Others', back: 'When someone is hurt or sad, <b>stay with them</b>, ask if they are okay, and help them get help.' },
    { front: 'Be Honest', back: 'If you find something that is not yours, <b>return it</b> to the owner or bring it to the <b>Lost and Found</b>.' },
    { front: 'Show Thanks', back: 'Say <b>thank you</b> when someone gives you a gift, lends you something, or helps you.' },
    { front: 'Respect Elders', back: 'Greet them politely, do the <b>mano</b>, <b>offer your seat</b>, and help them &mdash; like pushing a lola&rsquo;s wheelchair.' },
    { front: 'Respect During Prayer', back: 'Stay <b>quiet</b>, bow your head, and pray or listen respectfully. Talk only after the prayer.' }
  ],
  quiz: [
    { q: 'During a game, a classmate falls and starts to cry. What shows right conduct?', options: ['Help him up, check on him, and tell the teacher', 'Laugh, because the way he fell looked really funny', 'Keep on playing so your team will not lose', 'Grab the ball and go play somewhere else'], correct: 0, explain: 'Comforting someone who is hurt and <b>helping him get help</b> is right conduct.', why: ['', 'Laughing at someone who is hurt is unkind and makes him feel worse.', 'Winning the game matters less than a hurt classmate. Stay with him and help.', 'Walking off with the ball leaves him alone while he is hurt.'], tip: 'When someone is hurt, remember "Comfort Others": stay with them, ask if they are okay, and help them get help.' },
    { q: 'You find a wallet in the school hallway. What should you do?', options: ['Bring it to the Lost and Found or give it to a teacher', 'Keep the money and throw the empty wallet away', 'Keep it all, because &ldquo;finders, keepers&rdquo;', 'Leave it on the floor for someone else to deal with'], correct: 0, explain: 'Returning what is not yours shows <b>honesty</b>.', why: ['', 'Keeping the money is taking what is not yours — that is not honest.', '"Finders, keepers" is not honest. The wallet still belongs to its owner.', 'Leaving it on the floor does not help the owner get it back. Bring it to the Lost and Found.'], tip: 'Ask yourself: "Whose is this?" If it is not yours, return it or bring it to the Lost and Found.' },
    { q: 'Your tita gives you a birthday gift that you do not really like. What should you do?', options: ['Smile and say &ldquo;Thank you po&rdquo;', 'Tell her you do not like it at all', 'Give it back and ask for money', 'Put it down without saying anything'], correct: 0, explain: 'We <b>say thank you</b> to show appreciation for the thought and effort behind a gift.', why: ['', 'Saying you do not like it hurts her feelings. We say thank you for the thought and effort behind a gift.', 'Giving it back and asking for money is rude and does not appreciate her gift.', 'Putting it down without a word does not show any thanks.'], tip: 'For any gift, liked or not, the magic words are "Thank you po."' },
    { q: 'A lola gets on the crowded jeepney and there is no seat left for her. What should you do?', options: ['Politely offer her your seat', 'Pretend to be asleep so she won&rsquo;t ask', 'Tell her to wait for the next jeepney', 'Put your bag on the seat next to you'], correct: 0, explain: '<b>Offering your seat</b> is a way of respecting elders.', why: ['', 'Pretending to be asleep avoids helping her — that is not respecting elders.', 'Telling her to wait for the next jeepney is not respectful. Offer your seat instead.', 'Putting your bag on the seat keeps a seat away from her.'], tip: 'Remember the Respect Elders card: greet them, do the mano, OFFER YOUR SEAT, and help them.' },
    { q: 'Your class is praying before lunch, but your seatmate keeps whispering to you. What should you do?', options: ['Stay quiet and pray; talk after the prayer', 'Whisper back so she will not feel ignored', 'Laugh out loud at what she is saying', 'Start eating your lunch while they pray'], correct: 0, explain: 'During prayer we stay <b>quiet and respectful</b>.', why: ['', 'Whispering back is still talking during prayer. Talk only after the prayer.', 'Laughing out loud disturbs the prayer.', 'Eating while the others pray is not respectful. Wait until the prayer is done.'], tip: 'During prayer: quiet, head bowed, pray or listen. Any noisy choice is the wrong one.' },
    { q: 'You accidentally bump a classmate, and his books fall on the floor. What should you do?', options: ['Say &ldquo;Sorry&rdquo; and help him pick up the books', 'Walk away quickly before anyone notices it', 'Blame him for standing in your way', 'Laugh and tell him to be more careful'], correct: 0, explain: 'Saying <b>sorry</b> and helping fix the mistake is good manners.', why: ['', 'Walking away hides your mistake instead of fixing it.', 'Blaming him is not fair — you were the one who bumped him.', 'Laughing and telling him to be careful blames him instead of saying sorry.'], tip: 'When YOU cause an accident, use the magic word "Sorry" and help fix it.' },
    { q: 'You need to pass between two teachers who are talking in the hallway. What should you do?', options: ['Say &ldquo;Excuse me po&rdquo; and pass politely', 'Run between them without saying a word', 'Push between them because you are in a hurry', 'Interrupt loudly and ask them to move aside'], correct: 0, explain: '&ldquo;<b>Excuse me</b>&rdquo; plus <b>po</b> is the polite and respectful way.', why: ['', 'Running between them without a word is not polite — say "Excuse me."', 'Pushing is rude, even when you are in a hurry.', 'Interrupting loudly is disrespectful. A quiet "Excuse me po" is enough.'], tip: 'Passing between people? Use the magic words "Excuse me," plus po for elders.' },
    { q: 'A classmate lends you a pencil during a quiz. What shows good manners?', options: ['Say thank you and return it in good condition', 'Keep it because she has many other pencils', 'Return it broken without saying a word', 'Lend it to someone else without asking her'], correct: 0, explain: '<b>Thank</b> the person and <b>take care</b> of what you borrow.', why: ['', 'Keeping it is not right — it is her pencil, even if she has many others.', 'Returning it broken without a word does not thank her or take care of what you borrowed.', 'Her pencil is not yours to lend. Lending it without asking is not respectful.'], tip: 'The borrowing rule: say thank you, take care of it, and give it back in good condition.' },
    { q: 'During a quiz, you see your friend copying answers. Later she asks you to keep it a secret. What is the right thing to do?', options: ['Kindly tell her cheating is wrong; urge her to tell the teacher', 'Help her copy again on the next quiz so she will like you', 'Tell the whole class so everyone will laugh at her', 'Copy answers too, since she did not get caught'], correct: 0, explain: 'Right conduct means choosing <b>honesty</b> &mdash; and helping a friend be honest with the teacher too.', why: ['', 'Helping her copy again is joining in the cheating, which is not honest.', 'Telling the whole class so they laugh at her is unkind. The right way is to kindly talk to her.', 'Copying too because she did not get caught is still cheating. Right conduct means doing right even when no one is watching.'], tip: 'Right conduct is honest AND kind. Pick the choice that is both.' },
    { q: 'True or False: Good manners are only needed when a teacher or a parent is watching.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; right conduct means doing good <b>even when no one is watching</b>.', why: ['"Only when a teacher or parent is watching" makes this false. Right conduct means doing good even when no one is watching.', ''], tip: 'Good manners are for all the time. "Only when someone is watching" is a sign the statement is False.' },
    { q: 'True or False: Saying &ldquo;po&rdquo; and &ldquo;opo&rdquo; when talking to elders is a sign of respect.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; <b>po</b> and <b>opo</b> show respect to older people.', why: ['', 'This statement is true. Po and opo are part of the magic words we use when talking to elders.'], tip: 'Remember the Magic Words card: please, thank you, sorry, excuse me — and po and opo for elders.' },
    { q: 'True or False: Returning a lost item to its owner shows honesty and right conduct.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; that is why schools have a <b>Lost and Found</b>.', why: ['', 'This statement is true. Returning something that is not yours is honesty, and that is right conduct.'], tip: 'Return it = honest. That matches the Be Honest card.' },
    { q: 'True or False: If someone gives you something you did not ask for, you do not need to say thank you.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; we <b>always</b> say thank you to show appreciation.', why: ['The lesson says we always say thank you to show appreciation, even for something we did not ask for.', ''], tip: 'Thank you is always right. A statement that says you "do not need" to thank someone is False.' }
  ]
});
