StudyKit.lesson({
  id: 'sacred',
  icon: '📖',
  title: 'Respecting Sacred Books',
  subtitle: 'Handling holy books and respecting every faith',
  cards: [
    { front: 'Sacred Book', back: 'A <b>holy book</b> that a religion treats with great respect, because it holds <b>God&rsquo;s word</b> or the religion&rsquo;s teachings.' },
    { front: 'Examples', back: 'The <b>Bible</b> is the sacred book of <b>Christians</b>. The <b>Qur&rsquo;an</b> is the sacred book of <b>Muslims</b>.' },
    { front: 'Handle It with Care', back: 'Hold it with <b>clean hands</b> &middot; keep it in a <b>clean, proper place</b> &middot; <b>never</b> put it on the floor, step on it, or sit on it.' },
    { front: 'Respect Every Faith', back: 'Even if a sacred book is <b>not from your religion</b>, treat it with respect and <b>never make fun of it</b>.' },
    { front: 'Reading It', back: 'Read it with a <b>quiet, respectful attitude</b>. Its teachings guide us to do what is good.' },
    { front: 'Book of Life', back: 'Your GMRC lesson also calls a <b>sacred book</b> a Book of Life, because it guides how believers live. It gives believers <b>spiritual guidance</b> &mdash; it teaches them how to live a good life, like being kind and welcoming to others.' }
  ],
  quiz: [
    { q: 'What is a sacred book?', options: ['A holy book that a religion treats with great respect', 'Any storybook that you can borrow from the library', 'A notebook where you write your daily homework', 'A comic book about heroes and their adventures'], correct: 0, explain: 'A sacred book is a <b>holy book</b> treated with great respect.', why: ['', 'A library storybook is not a holy book — it does not hold God\'s word or a religion\'s teachings.', 'A homework notebook is for your school notes, not a holy book of a religion.', 'A comic book tells fun stories about heroes — it is not a holy book of a religion.'], tip: 'Sacred = holy. Look for the choice about a holy book that a religion treats with great respect.' },
    { q: 'Which is the sacred book of Christians?', options: ['The Bible', 'The Qur&rsquo;an', 'A dictionary', 'An atlas'], correct: 0, explain: 'Christians read the <b>Bible</b>.', why: ['', 'The Qur\'an is the sacred book of Muslims, not Christians.', 'A dictionary is not a sacred book. The sacred books in the lesson are the Bible and the Qur\'an.', 'An atlas is not a sacred book. The sacred books in the lesson are the Bible and the Qur\'an.'], tip: 'Memory hook: Christians — Bible; Muslims — Qur\'an. Cross out the books that are not sacred first.' },
    { q: 'Which is the sacred book of Muslims?', options: ['The Qur&rsquo;an', 'The Bible', 'A dictionary', 'An atlas'], correct: 0, explain: 'Muslims read the <b>Qur&rsquo;an</b>.', why: ['', 'The Bible is the sacred book of Christians, not Muslims.', 'A dictionary is not a sacred book. The sacred books in the lesson are the Bible and the Qur\'an.', 'An atlas is not a sacred book. The sacred books in the lesson are the Bible and the Qur\'an.'], tip: 'Memory hook: Muslims — Qur\'an; Christians — Bible. Cross out the books that are not sacred, then match the religion.' },
    { q: 'Your little brother stands on the Bible to reach a high shelf. What should you do?', options: ['Gently stop him and put the Bible back where it belongs', 'Let him, since it helps him reach the shelf faster', 'Laugh and take a video of him to show your friends', 'Give him more books to stand on so he gets higher'], correct: 0, explain: 'We <b>never step on</b> a sacred book &mdash; it belongs in a <b>proper place</b>.', why: ['', 'Letting him stand on it is disrespectful — we never step on a sacred book.', 'Laughing and filming him makes fun of the sacred book instead of protecting it.', 'Giving him more books to stand on still has him stepping on the Bible.'], tip: 'Handle with Care: never on the floor, never stepped on, never sat on. Put it back in its proper place.' },
    { q: 'Your Muslim classmate brings her Qur&rsquo;an to school, and some classmates make jokes about it. What should you do?', options: ['Kindly tell them to respect it; it is her sacred book', 'Join in the jokes so that the others will like you too', 'Hide her Qur&rsquo;an in your bag while she is not looking', 'Say nothing and laugh quietly along with the others'], correct: 0, explain: 'We <b>respect every faith</b>, even when the sacred book is not ours.', why: ['', 'Joining in the jokes makes fun of her sacred book — we never do that.', 'Hiding her Qur\'an is not respectful to her or to her sacred book.', 'Laughing quietly still joins in making fun of it.'], tip: 'Respect Every Faith: even when a sacred book is not from your religion, treat it with respect.' },
    { q: 'You want to read the Bible right after playing outside with muddy hands. What should you do first?', options: ['Wash and dry your hands', 'Wipe your hands on the pages', 'Put the Bible on the floor', 'Read it fast before the mud dries'], correct: 0, explain: 'Hold a sacred book with <b>clean hands</b>.', why: ['', 'Wiping mud on the pages makes the sacred book dirty.', 'A sacred book is never put on the floor.', 'Reading fast with muddy hands still makes it dirty. Wash your hands first.'], tip: 'Clean hands first! Any choice that dirties the book or puts it on the floor is wrong.' },
    { q: 'During Bible reading in class, your seatmate keeps folding and crumpling the pages. What should you do?', options: ['Politely remind him to handle it with care', 'Crumple the pages of your own Bible too', 'Tear out a page and throw it at him', 'Tell the whole class to look and laugh'], correct: 0, explain: 'A sacred book is handled <b>with care and respect</b>.', why: ['', 'Crumpling the pages of your own Bible copies the disrespect instead of stopping it.', 'Tearing out a page and throwing it is very disrespectful to a sacred book.', 'Making the class laugh at him is unkind, and it does not protect the book.'], tip: 'Pick the choice that protects the book AND is polite: "politely remind."' },
    { q: 'True or False: It is okay to put a sacred book on the floor.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; keep it in a <b>clean, proper place</b>, never on the floor.', why: ['We never put a sacred book on the floor. It belongs in a clean, proper place.', ''], tip: 'Floor = never. Remember: clean hands and a clean place.' },
    { q: 'True or False: We should respect the sacred books of other religions, even if they are not ours.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; respecting every faith is good manners and right conduct.', why: ['', 'This statement is true. We respect every faith, even when the sacred book is not ours.'], tip: 'Respect is for ALL sacred books, not only the one from your own religion.' },
    { q: 'True or False: A sacred book should be kept in a clean and proper place.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; that shows respect for it.', why: ['', 'This statement is true. Keeping a sacred book in a clean and proper place shows respect for it.'], tip: 'Clean, proper place = respect. That is True.' },
    { q: 'True or False: It is fine to make fun of a sacred book if it is not from your religion.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; we <b>never make fun</b> of any sacred book.', why: ['We never make fun of any sacred book, even one that is not from our religion.', ''], tip: '"If it is not from your religion" does not change the rule — respect every faith.' },
    { q: 'What is the &ldquo;Book of Life&rdquo;?', options: ['A sacred book', 'A storybook', 'A notebook', 'A coloring book'], correct: 0, explain: 'The &ldquo;Book of Life&rdquo; is another name for a <b>sacred book</b>.', why: ['', 'A storybook tells stories for fun. The Book of Life is a sacred book.', 'A notebook is where you write your school notes. The Book of Life is a sacred book.', 'A coloring book is for coloring pictures. The Book of Life is a sacred book.'], tip: 'Book of Life = sacred book. It is a holy book that guides how believers live.' },
    { q: 'What does a Book of Life provide to believers?', options: ['Spiritual guidance', 'Entertainment', 'Business ideas', 'Sports activities'], correct: 0, explain: 'A sacred book gives believers <b>spiritual guidance</b> &mdash; it teaches them how to live a good life.', why: ['', 'A sacred book is not read for fun like a movie. It guides believers in their faith.', 'A sacred book does not teach how to run a business. It guides believers in their faith.', 'A sacred book is not about sports. It guides believers in their faith.'], tip: 'A sacred book guides the spirit: look for &ldquo;spiritual guidance.&rdquo;' },
    { q: 'You see a new student sitting alone during recess. How can you apply the values you learn from your sacred book?', options: ['Invite the student to join you and your friends', 'Wait for the student to approach you first', 'Ask another classmate to talk to the student', 'Let the student stay alone because you do not know them'], correct: 0, explain: 'Sacred books teach us to <b>love and be kind to others</b>. Inviting the new student puts that value into action.', why: ['', 'Waiting does nothing for the student now. Kindness means you take the first step.', 'Asking someone else passes the kind act to them. You can be kind yourself.', 'Leaving the student alone is not kind. Not knowing someone yet is a reason to welcome them.'], tip: 'Apply the value yourself: pick the choice where YOU do the kind act right away.' }
  ]
});
