StudyKit.lesson({
  id: 'ewaste',
  icon: '♻️',
  title: 'E-waste',
  subtitle: 'What to do with old and broken gadgets',
  cards: [
    { front: 'E-waste', back: '<b>Old, broken or unwanted electronic devices</b> &mdash; like cellphones, chargers, earphones, computers, TVs and batteries.' },
    { front: 'Why Is It Dangerous?', back: 'It contains <b>harmful substances</b> (like lead and mercury) that can harm <b>people, animals, soil and water</b> if thrown away the wrong way.' },
    { front: 'DON&rsquo;T', back: '<b>Don&rsquo;t</b> throw e-waste in the regular trash, <b>don&rsquo;t burn it</b>, and <b>don&rsquo;t dump it</b> in rivers, canals or empty lots.' },
    { front: 'DO', back: 'Bring it to an <b>e-waste collection or drop-off point</b>, or give it to a <b>proper recycler</b>.' },
    { front: 'Repair &amp; Reuse', back: '<b>Repair</b> a broken device if you can. <b>Donate</b> or pass on devices that still work.' },
    { front: 'Reduce', back: '<b>Take good care of your devices</b> so they last longer, and avoid buying new gadgets you do not need.' }
  ],
  quiz: [
    { q: 'What do we need to do with e-waste?', options: ['Bring it to an e-waste collection point for proper recycling', 'Throw it in the regular trash bin with the other garbage', 'Burn it in the backyard so that it quickly disappears', 'Throw it into the river so it gets carried far away'], correct: 0, explain: 'E-waste goes to an <b>e-waste collection point</b> or a <b>proper recycler</b>.', why: ['', 'The lesson says do NOT throw e-waste in the regular trash.', 'The lesson says do NOT burn e-waste — its harmful substances go into the air.', 'The lesson says do NOT dump e-waste in rivers — it can harm the water, animals and people.'], tip: 'Remember the DON\'T list: no trash, no burning, no dumping. The DO is: an e-waste collection point or a proper recycler.' },
    { q: 'Which of these is e-waste?', options: ['An old, broken cellphone', 'A pile of banana peels', 'Used paper plates', 'Dry leaves from the yard'], correct: 0, explain: 'E-waste is <b>electronic</b> &mdash; a broken cellphone.', why: ['', 'Banana peels are food scraps, not an electronic device.', 'Paper plates are not an electronic device.', 'Dry leaves come from plants, not from electronic devices.'], tip: 'E-waste = ELECTRONIC waste. Ask: "Is it an old or broken electronic device?"' },
    { q: 'Your old tablet still works, but you got a new one. What is the BEST thing to do with the old one?', options: ['Donate it or give it to someone who can use it', 'Throw it in the trash since you do not need it', 'Smash it so that nobody else can ever use it', 'Bury it in the garden behind your house'], correct: 0, explain: 'Devices that still work can be <b>reused</b> by someone else.', why: ['', 'It still works, so throwing it away wastes it — and e-waste never goes in the regular trash.', 'Smashing a tablet that still works wastes it and just makes more e-waste.', 'Burying it can let its harmful substances get into the soil.'], tip: 'Still works? Reuse it — donate it or pass it on.' },
    { q: 'Your family&rsquo;s old TV is broken. A neighbor says to burn it with the garbage. What should you say?', options: ['Burning it is harmful; bring it to an e-waste drop-off', 'That is a good idea, because it will be gone very quickly', 'Throw it in the canal instead so it will not make smoke', 'Just leave it out on the street for someone to take'], correct: 0, explain: '<b>Never burn e-waste</b> &mdash; its harmful substances go into the air.', why: ['', 'Burning is never a good idea — the harmful substances go into the air.', 'Throwing it in the canal is dumping, which harms the water.', 'Leaving it on the street is not proper disposal. Bring it to an e-waste drop-off.'], tip: 'For broken gadgets, the only right place is an e-waste drop-off or a proper recycler.' },
    { q: 'You find old used batteries in a drawer. What should you do with them?', options: ['Set them aside for an e-waste collection point', 'Throw them in the bin together with the food scraps', 'Toss them into the fire so they burn away', 'Give them to your baby brother to play with'], correct: 0, explain: 'Batteries are <b>e-waste</b> and go to a collection point.', why: ['', 'Batteries are e-waste, so they do not go in the bin with food scraps.', 'Burning e-waste like batteries releases harmful substances.', 'Batteries contain harmful substances — they are not toys for a baby.'], tip: 'Batteries are on the e-waste list! Keep them apart and bring them to a collection point.' },
    { q: 'Your charger broke because you always bent the cord. How can you reduce e-waste next time?', options: ['Handle your new charger gently so it lasts longer', 'Bend the cord of the new charger even harder', 'Buy three chargers at once so you have extras', 'Leave the charger plugged in out in the rain'], correct: 0, explain: '<b>Taking good care of devices</b> means less e-waste.', why: ['', 'Bending the cord even harder will break it faster and make more e-waste.', 'Buying extra chargers you do not need goes against Reduce.', 'Leaving it in the rain will damage it — devices should be kept away from water.'], tip: 'Reduce card: take good care of your devices so they last longer, and do not buy gadgets you do not need.' },
    { q: 'Your school holds an e-waste collection drive. How can your family help?', options: ['Bring your old, broken gadgets to the drive', 'Ignore it, since it is only for the teachers', 'Bring your leftover food scraps to the drive', 'Keep the broken gadgets hidden at home forever'], correct: 0, explain: 'A <b>collection drive</b> is the right place for e-waste.', why: ['', 'The drive is not only for teachers — families can help by bringing their old gadgets.', 'Food scraps are not e-waste, so they do not belong at an e-waste drive.', 'Hiding broken gadgets at home forever does not dispose of them properly.'], tip: 'A collection drive is on the DO list: bring your old, broken gadgets there.' },
    { q: 'Why should e-waste NOT be thrown into rivers?', options: ['Its harmful substances can pollute the water and harm fish and people', 'It will float on the water and look very ugly to people passing by', 'The river belongs to someone else, so you need their permission first', 'It will make the water in the river taste much sweeter than before'], correct: 0, explain: 'E-waste can <b>harm water, animals and people</b>.', why: ['', 'The problem is not how it looks — its harmful substances pollute the water.', 'Permission is not the reason. E-waste should never be dumped in rivers at all.', 'E-waste does not make water sweeter. It pollutes the water and harms fish and people.'], tip: 'E-waste is dangerous because of its harmful substances. Look for the words "harm" or "pollute."' },
    { q: 'True or False: E-waste can harm people and the environment if it is thrown away the wrong way.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; that is why it needs <b>proper disposal</b>.', why: ['', 'This statement is true. E-waste has harmful substances that can hurt people, animals, soil and water if it is thrown away the wrong way.'], tip: 'Remember "Why Is It Dangerous?": its harmful substances hurt people and the environment.' },
    { q: 'True or False: Burning old gadgets is a safe way to get rid of e-waste.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; burning releases <b>harmful substances</b> into the air.', why: ['"Safe" makes this false. Burning releases harmful substances into the air — the lesson says don\'t burn e-waste.', ''], tip: 'Burning is on the DON\'T list, so any statement that calls it safe is False.' },
    { q: 'True or False: Repairing a broken device instead of throwing it away helps reduce e-waste.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; <b>repair and reuse</b> means less e-waste.', why: ['', 'This statement is true. Repairing and reusing a device means less e-waste.'], tip: 'Repair & Reuse = less e-waste. Fixing is better than throwing away.' },
    { q: 'True or False: E-waste can be thrown in the same bin as food scraps.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; e-waste is kept apart and brought to a <b>collection point</b>.', why: ['E-waste must be kept apart from food scraps and brought to a collection point.', ''], tip: 'E-waste never goes with regular trash. Keep it separate.' }
  ]
});
