StudyKit.lesson({
  id: 'devices',
  icon: '📱',
  title: 'Using Devices Properly',
  subtitle: 'Screen time, online safety &amp; being kind online',
  cards: [
    { front: 'Devices', back: 'Gadgets like <b>cellphones, tablets, laptops and computers</b> that help us learn and communicate.' },
    { front: 'Use Them for Good', back: 'For <b>learning and research</b>, and for keeping in touch with family.' },
    { front: 'Balance Your Screen Time', back: 'Follow the <b>time limit your parents set</b> &middot; take <b>breaks</b> to rest your eyes &middot; leave time for study, play, chores, family and sleep.' },
    { front: 'Ask Permission', back: 'Ask your parents <b>before</b> using a device, downloading an app, or going online.' },
    { front: 'Stay Safe Online', back: '<b>Never share</b> your password, address or personal information &middot; don&rsquo;t chat with or meet strangers &middot; <b>tell a parent or teacher</b> if something online makes you uncomfortable.' },
    { front: 'Be Kind Online', back: '<b>Think before you post</b> &middot; never bully, tease or spread rumors &middot; <b>ask permission</b> before posting someone&rsquo;s photo.' },
    { front: 'Device Manners', back: 'Put devices away during <b>meals, class and prayer</b> unless allowed. Keep them away from water and handle them with clean hands.' }
  ],
  quiz: [
    { q: 'How do we use our devices properly?', options: ['For learning, with our parents&rsquo; permission and a time limit', 'For playing games all night long until we fall asleep', 'During class whenever we want, even without permission', 'By sharing our password with everyone we chat with'], correct: 0, explain: 'Use devices <b>for good</b>, with <b>permission</b> and a <b>time limit</b>.', why: ['', 'Playing all night breaks the time limit and leaves no time for sleep.', 'Using devices in class without permission breaks device manners.', 'Sharing your password is never safe online.'], tip: 'Proper device use has 3 parts: use it for good, with permission, and with a time limit.' },
    { q: 'Your screen time is over, but you are in the middle of a game. What should you do?', options: ['Stop the game and follow the time limit', 'Hide in your room and keep on playing', 'Cry until your parents give you more time', 'Borrow a friend&rsquo;s phone and keep playing'], correct: 0, explain: 'Following the <b>time limit</b> your parents set is proper device use.', why: ['', 'Hiding in your room to keep playing is disobeying the time limit.', 'Crying for more time does not follow the limit your parents set.', 'Borrowing a friend\'s phone is still breaking the time limit.'], tip: 'When time is up, it is up. Follow the limit your parents set.' },
    { q: 'Someone you do not know online asks for your home address and school. What should you do?', options: ['Do not answer, and tell a parent or teacher', 'Give it, because they seem really friendly', 'Give only the name of your school to them', 'Ask for their address first, then give yours'], correct: 0, explain: '<b>Never share personal information</b> with strangers, and tell a trusted adult.', why: ['', 'Seeming friendly does not make a stranger safe — never share personal information.', 'The name of your school is personal information too. Do not give it to a stranger.', 'Trading addresses still gives your personal information to a stranger.'], tip: 'Stranger + personal information = do not share, and tell a parent or teacher.' },
    { q: 'A classmate posts an embarrassing photo of another classmate, and others laugh at it. What should you do?', options: ['Do not share or laugh at it, and tell a teacher', 'Share it to your group chat to spread the fun', 'Write a funny comment under the photo', 'Click like so your classmate feels happy'], correct: 0, explain: '<b>Be kind online</b> &mdash; never join in teasing, and tell a trusted adult.', why: ['', 'Sharing it spreads the teasing to even more people. Being kind online means never joining in.', 'A funny comment joins in the teasing.', 'Clicking like shows you agree with the teasing — it does not make your classmate happy.'], tip: 'Be Kind Online: if a post hurts someone, do not share, comment or like it — tell a teacher.' },
    { q: 'Your phone keeps buzzing during family dinner. What should you do?', options: ['Put it away, enjoy dinner, and check it later', 'Answer every message quickly while you keep eating', 'Watch videos while eating so dinner is more fun', 'Keep it on the table and ignore your family'], correct: 0, explain: 'Put devices away during <b>meals</b> &mdash; family time comes first.', why: ['', 'Answering messages while eating takes you away from family time.', 'Watching videos during meals breaks device manners.', 'Keeping it on the table and ignoring your family is not right — family time comes first.'], tip: 'Device Manners: meals, class and prayer are "phone away" times.' },
    { q: 'You want to download a new game app. What should you do first?', options: ['Ask your parents for permission', 'Download it secretly at night', 'Use mom&rsquo;s password without asking', 'Download many games all at once'], correct: 0, explain: 'Always <b>ask permission</b> before downloading apps.', why: ['', 'Downloading it secretly means you did not ask permission.', 'Using mom\'s password without asking is not honest, and it skips permission.', 'Downloading many games at once still skips asking permission.'], tip: 'Before any download, the first step is always: ask your parents.' },
    { q: 'Your friend asks for your password so he can &ldquo;help&rdquo; level up your game. What should you do?', options: ['Politely say no and keep your password private', 'Give it, because he is your good friend', 'Post your password in your group chat', 'Write your password on the classroom board'], correct: 0, explain: '<b>Never share your password</b>, even with friends.', why: ['', 'Even a good friend should not get your password — keep it private.', 'Posting your password in a group chat lets many people see it.', 'Writing it on the board shows your password to the whole class.'], tip: 'Your password is private. Never share it, not even with friends.' },
    { q: 'You get a message online that makes you feel scared and uncomfortable. What should you do?', options: ['Tell a parent or teacher right away', 'Keep it a secret from everyone', 'Reply with an angry message', 'Forward it to all your friends'], correct: 0, explain: '<b>Tell a trusted adult</b> whenever something online makes you uncomfortable.', why: ['', 'Keeping it a secret means no one can help you.', 'An angry reply can make things worse. Tell a trusted adult instead.', 'Forwarding it spreads the scary message to your friends.'], tip: 'Something online makes you uncomfortable? Tell a parent or teacher right away.' },
    { q: 'You want to post a picture of your classmate online. What should you do first?', options: ['Ask her permission before posting it', 'Post it right away without asking her', 'Take the picture secretly so she won&rsquo;t know', 'Edit it to make her look funny, then post it'], correct: 0, explain: '<b>Ask permission</b> before posting someone else&rsquo;s photo.', why: ['', 'Posting it without asking breaks the rule to ask permission first.', 'Taking the picture secretly skips asking her permission.', 'Editing her to look funny is teasing — that is being unkind online.'], tip: 'Someone else\'s photo? Ask permission first, and think before you post.' },
    { q: 'True or False: Taking short breaks from the screen to rest your eyes is a good habit.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; <b>breaks</b> are part of balancing screen time.', why: ['', 'This statement is true. Taking breaks to rest your eyes is part of balancing your screen time.'], tip: 'Balance Your Screen Time card: follow the time limit, take breaks, and leave time for other things.' },
    { q: 'True or False: Posting a friend&rsquo;s photo without her permission is okay if she looks nice in it.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; always <b>ask permission</b> first.', why: ['Looking nice does not change the rule — always ask permission before posting someone\'s photo.', ''], tip: 'Watch for "okay if..." — an excuse never replaces asking permission.' },
    { q: 'True or False: Devices can be used for learning, like researching a school project.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; that is using devices <b>for good</b>.', why: ['', 'This statement is true. Using devices for learning and research is using them for good.'], tip: 'Use Them for Good card: learning, research, and keeping in touch with family.' },
    { q: 'True or False: It is okay to use your phone during class whenever you feel bored.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; put devices away during <b>class</b> unless your teacher allows it.', why: ['Feeling bored is not permission. Devices are put away during class unless your teacher allows it.', ''], tip: '"Whenever you feel" is a trap. In class, only your teacher can allow devices.' },
    { q: 'Which action shows the wisest use of a technological device?', options: ['Using a device for homework and following the set time limit', 'Playing games after homework but continuing until bedtime', 'Using a device for homework and taking breaks only when tired', 'Playing games after homework and stopping when someone reminds you'], correct: 0, explain: 'The wisest use is for <b>learning</b>, while <b>following the time limit</b>.', why: ['', 'Playing until bedtime goes past the time limit and leaves no time to rest.', 'Breaks are good, but you still need to follow the time limit your parents set.', 'You should stop on your own when the time is up, not only when someone reminds you.'], tip: 'Wisest = good use + time limit. Find the choice that has both.' },
    { q: 'You need to study for a test, but you also want to play an online game. What is the wisest thing to do?', options: ['Finish studying first, then play within your allowed screen time.', 'Study while playing the game at the same time.', 'Play first and study later if there is still enough time.', 'Play for a while and study when you are no longer interested.'], correct: 0, explain: '<b>Study first</b>, then play &mdash; and only within your allowed screen time.', why: ['', 'Doing both at once means you cannot focus on studying.', 'Playing first can use up the time you need to study.', 'Studying only when you are bored of the game puts the game first.'], tip: 'Work first, play after &mdash; and keep to the time limit.' },
    { q: 'Your friend sends you a message asking for your password. What should you do?', options: ['Keep your password private and politely refuse to share it.', 'Give your password because your friend can be trusted.', 'Give your password only if your friend shares theirs first.', 'Share your password but ask your friend not to tell anyone.'], correct: 0, explain: '<b>Never share your password</b>, even with a friend. Say no politely.', why: ['', 'Even a trusted friend should not have your password. Keep it private.', 'Trading passwords puts both of your accounts at risk.', 'Once you share it, you cannot control who else will see it.'], tip: 'Every choice that says &ldquo;give&rdquo; or &ldquo;share&rdquo; is wrong. Your password stays private.' }
  ]
});
