StudyKit.lesson({
  id: 'search',
  icon: '🔍',
  title: 'Using a Search Engine',
  subtitle: 'Search engines, their parts & keywords',
  cards: [
    { front: 'Search Engine', back: 'A software program that helps users find information on the internet. Examples: <b>Google, Yahoo, Bing</b> (and Ecosia).' },
    { front: 'Search Engines for Young People', back: '<b>Kiddle, KidzSearch, Fact Monster</b> and <b>DuckDuckGo</b>. Your book names DuckDuckGo as a search engine made for young people like you.' },
    { front: 'Parts of a Search Engine (1)', back: '<b>Search Box</b> &mdash; where you type your keywords.<br><b>Search Button</b> &mdash; you click it to start the search.' },
    { front: 'Parts of a Search Engine (2)', back: '<b>Microphone and Image</b> &mdash; search by speaking or with a picture.<br><b>Search Results</b> &mdash; the list of web pages the search engine found.' },
    { front: 'Keyword', back: 'A specific word or phrase that a user types into a search engine to find information. Keywords help search engines find information <b>faster</b>.' },
    { front: 'Good Keywords', back: 'Good keywords are <b>short and specific</b>. You do <b>not</b> need to type a complete sentence.' },
    { front: 'Sentence &rarr; Keywords', back: '&ldquo;What is the capital of the Philippines?&rdquo; &rarr; <b>Capital of the Philippines</b><br>&ldquo;Who was the first President of the Philippines?&rdquo; &rarr; <b>First president, Philippines</b><br>&ldquo;Who wrote Noli Me Tangere?&rdquo; &rarr; <b>author of Noli Me Tangere</b>' },
    { front: 'Which Keywords Are Best?', back: 'Tallest mountain? &rarr; <b>Tallest mountain in the Philippines</b> (not &ldquo;Mountain&rdquo;).<br>What do pandas eat? &rarr; <b>Panda food</b> (not &ldquo;Eat&rdquo; or &ldquo;Panda&rdquo;).<br>Largest ocean? &rarr; <b>Largest ocean, world</b> (not &ldquo;Ocean&rdquo; or &ldquo;Sea&rdquo;).' },
    { front: 'Self-Reliance', back: 'In the Internet Detective Challenge you search <b>on your own</b>: work independently, use effective keywords, and do your best.' },
    { front: 'Remember', back: 'Think carefully about what you type. Keep the important words of the question, drop the extra ones like &ldquo;what&rdquo;, &ldquo;is&rdquo; and &ldquo;the&rdquo;.' }
  ],
  quiz: [
    { q: 'What is a search engine?', options: ['A cable that connects your computer to the internet', 'A program that helps you find information online', 'A key on the keyboard that deletes the words you typed', 'A website where you can only play games'], correct: 1, explain: 'A search engine is a software program that helps users find information on the internet, like Google, Yahoo or Bing.', why: ['A cable is hardware, not a program. A search engine is software that finds information for you.', '', 'That describes the Backspace or Delete key. A search engine is a program for finding information.', 'A search engine is not for games. It is a program that helps you find information on the internet.'], tip: 'Remember the definition: search engine = a <b>program</b> that helps you <b>find information</b> on the internet.' },
    { q: 'What is used to look for information on the World Wide Web?', options: ['Website', 'Search bar', 'Search engine'], correct: 2, explain: 'A search engine is used to look for information on the World Wide Web. (Book, p. 9)', why: ['A website is a place you visit. You use a search engine to find which websites have the information.', 'The search bar (search box) is only one part of a search engine. The whole tool that looks for information is the search engine.', ''], tip: 'A search box is just one PART. The question asks for the whole tool that looks for information: the search engine.' },
    { q: 'What words are used to search for information on the web?', options: ['Wordplay', 'Keywords', 'Buzzwords'], correct: 1, explain: 'Keywords are the words or phrases you type into a search engine to find information. (Book, p. 9)', why: ['Wordplay is a fun game with words, not what you type into a search engine.', '', 'Buzzwords are popular trendy words. The words you type to search are called keywords.'], tip: 'The KEY to finding information is the right KEYword.' },
    { q: 'Which of these is a search engine?', options: ['Microsoft Word', 'Bing', 'Bluetooth', 'A USB flash drive'], correct: 1, explain: 'Bing is a search engine, like Google and Yahoo.', why: ['Microsoft Word is a program for typing documents, not for searching the internet.', '', 'Bluetooth is a way to share files between nearby devices, not a search engine.', 'A USB flash drive stores and moves files. It does not search the internet.'], tip: 'The deck’s three examples are Google, Yahoo and Bing.' },
    { q: 'What is an example of a search engine made for young people like us?', options: ['DuckDuckGo', 'Google', 'Bing'], correct: 0, explain: 'Your book (p. 9) names DuckDuckGo. The deck also shows Kiddle, KidzSearch and Fact Monster as search engines for young people.', why: ['', 'Google is a search engine for everyone. The book’s answer for young people is DuckDuckGo.', 'Bing is a search engine for everyone. The book’s answer for young people is DuckDuckGo.'], tip: 'Google, Yahoo and Bing are for everyone. The young-people list: Kiddle, KidzSearch, Fact Monster, DuckDuckGo.' },
    { q: 'Sophia wants to find out more about planting a tree. Which words will help her search?', options: ['Grass and goat', 'Weather and seeds', 'Planting and trees'], correct: 2, explain: '“Planting” and “trees” are the important words in her question, so they make the best keywords. (Book, p. 9)', why: ['Grass and goat have nothing to do with planting a tree.', 'Weather and seeds are not what she asked about. Her topic is planting a tree.', ''], tip: 'Pick the keywords that come straight from the question’s main idea.' },
    { q: 'Which part of a search engine is where you type your keywords?', options: ['Search results', 'Search button', 'Search box', 'Microphone'], correct: 2, explain: 'You type your keywords in the search box.', why: ['Search results are the list of pages you get AFTER searching.', 'You click the search button after typing. You type in the search box.', '', 'The microphone is for searching by voice, not by typing.'], tip: 'BOX = where words go in. BUTTON = what you click. RESULTS = what comes out.' },
    { q: 'You want to search by speaking instead of typing. Which part of the search engine do you use?', options: ['Search results', 'Microphone', 'Search box', 'Search button'], correct: 1, explain: 'The microphone lets you search with your voice. (The image icon lets you search with a picture.)', why: ['Search results are only the list of pages found. They do not listen to you.', '', 'The search box is for typing, and you want to speak.', 'The search button starts a typed search. It does not listen to your voice.'], tip: 'Speaking needs a microphone. A picture search uses the image icon beside it.' },
    { q: 'After you click Search, a list of web pages appears. What part of the search engine is this?', options: ['Search results', 'Search box', 'Keywords', 'Search button'], correct: 0, explain: 'The list of web pages that the search engine found is called the search results.', why: ['', 'The search box is where you type. The list that appears after searching is the results.', 'Keywords are the words you typed in, not the list that comes back.', 'The search button is what you clicked. The list it brings back is the search results.'], tip: 'Results come AFTER the search. Think: result = what you get at the end.' },
    { q: 'Which keywords are the best for: “What do pandas eat?”', options: ['Eat', 'Panda', 'Panda food'], correct: 2, explain: '“Panda food” is short and specific. It keeps both important ideas: pandas and food.', why: ['“Eat” alone is too general. It does not even say which animal.', '“Panda” alone gives you everything about pandas, not just what they eat.', ''], tip: 'The best keywords keep ALL the important ideas in the question, but nothing extra.' },
    { q: 'Which keywords are the best for: “What is the tallest mountain in the Philippines?”', options: ['Mountain', 'Tallest mountain in the Philippines', 'Tall mountain'], correct: 1, explain: '“Tallest mountain in the Philippines” keeps every important detail: tallest, mountain, and Philippines.', why: ['“Mountain” is too general. You would get every mountain in the world.', '', '“Tall mountain” forgets the Philippines and that you want the TALLEST one.'], tip: 'Check each important idea in the question. If a keyword choice drops one, it is not the best.' },
    { q: 'Which keywords are the best for: “What is the largest ocean in the world?”', options: ['Ocean', 'Sea', 'Largest ocean, world'], correct: 2, explain: '“Largest ocean, world” is short but keeps the important details.', why: ['“Ocean” is too general. It does not say you want the LARGEST one.', '“Sea” is not even the same word as ocean, and it drops “largest”.', ''], tip: 'Short is good, but not too short. Keep the important describing word (largest).' },
    { q: 'Which keywords are the best for: “Who wrote Noli Me Tangere?”', options: ['Who wrote the book Noli Me Tangere and why', 'Author of Noli Me Tangere', 'Book', 'Tangere'], correct: 1, explain: 'The deck turns this question into the keywords “author of Noli Me Tangere”.', why: ['That is a long sentence, and it adds “why”, which you did not ask. Keywords should be short and specific.', '', '“Book” is far too general.', '“Tangere” is only part of the title and does not say you want the author.'], tip: 'Name the thing you are asking about (the book) and what you want to know about it (the author).' },
    { q: 'True or False: Good keywords are long, complete sentences.', options: ['True', 'False'], correct: 1, explain: 'False. Good keywords are short and specific. You do not need to type a complete sentence.', why: ['True is not right. The lesson says good keywords are SHORT and specific, and a complete sentence is not needed.', ''], tip: 'Short and specific beats long and complete.' },
    { q: 'True or False: Keywords help search engines find information faster.', options: ['True', 'False'], correct: 0, explain: 'True. The deck says keywords help search engines find information faster.', why: ['', 'False is not right. The deck says exactly this: keywords help search engines find information faster.'], tip: 'If a True/False matches a flashcard word for word, it is True.' },
    { q: 'True or False: Doing the Internet Detective Challenge on your own, using good keywords, shows self-reliance.', options: ['True', 'False'], correct: 0, explain: 'True. Self-reliance means working independently and doing your best on your own.', why: ['', 'False is not right. Working independently and doing your best is exactly what self-reliance means.'], tip: 'Self-reliance = relying on yourself.' },
    { q: 'Which of the following is a search engine?', options: ['Paint', 'Ecosia', 'PowerPoint', 'Microsoft Word'], correct: 1, explain: 'Ecosia is a search engine, like Google, Yahoo and Bing. Paint, PowerPoint and Microsoft Word are programs for drawing, slides and typing.', why: ['Paint is a program for drawing pictures, not for searching the internet.', '', 'PowerPoint is a program for making slide presentations, not a search engine.', 'Microsoft Word is a program for typing documents, not a search engine.'], tip: 'Ask: “Does this program FIND information on the internet?” Only a search engine does.' },
    { q: 'Which keyword is BEST to search for information about volcanoes?', options: ['Volcanoes', 'Can you explain volcanoes to me?', 'Tell me everything about volcanoes', 'I need help with my science homework'], correct: 0, explain: 'You want information about volcanoes in general, so the one word “Volcanoes” already says everything you need. Short and specific wins.', why: ['', 'This is a whole question. Keywords do not need words like “can you explain” and “to me”.', 'This is a long sentence. Drop the extra words and keep only the topic: volcanoes.', 'This does not even say volcanoes. A search engine would not know your topic.'], tip: 'Find the topic word and drop the rest. Here the whole topic is “volcanoes”, so one word is enough.' },
    { q: 'Your teacher asks you to research healthy foods. Which keyword would give the BEST search results?', options: ['Food', 'Healthy foods', 'Homework answer', 'Tell me everything about healthy foods'], correct: 1, explain: '“Healthy foods” is short and specific. It keeps both important ideas: healthy and foods.', why: ['“Food” is too general. It drops “healthy”, so you would get all kinds of food.', '', '“Homework answer” does not say your topic at all.', 'This is a long sentence. The keywords inside it, “healthy foods”, are all you need.'], tip: 'Keep every important idea (healthy + foods), but nothing extra.' }
  ]
});
