StudyKit.lesson({
  id: 'risks',
  icon: '🛡️',
  title: 'File-Sharing Risks & Safety',
  subtitle: 'Firewall, piracy, malware & staying safe',
  cards: [
    { front: 'Sharing Files Can Be Dangerous', back: 'Possible risks: <b>virus, malware, stolen personal information</b>, the <b>wrong person</b> receives the file, and <b>fake files</b>.' },
    { front: 'Risk 1: Broken Firewall', back: 'A <b>firewall</b> is a security system that monitors, filters and controls incoming and outgoing network traffic based on preset rules. It is a <b>barrier</b> between a trusted network and untrusted networks like the internet. It can be <b>hardware or software</b>.' },
    { front: 'Why a Broken Firewall Is Risky', back: 'Some peer-to-peer (P2P) networks ask users to <b>turn off their firewall</b> to download files. This gives other users or <b>hackers</b> a chance to access their computers.' },
    { front: 'Risk 2: Piracy', back: 'The <b>illegal</b> copying, sharing, using or selling of digital materials. Like sea pirates who steal treasure. Pirated copies are often <b>poor quality</b> and have <b>malware</b>.' },
    { front: 'Examples of Piracy', back: 'Sharing <b>one paid program</b> with many friends, downloading <b>cracked games</b> from the internet, and <b>selling fake software</b>.' },
    { front: 'Risk 3: Malware', back: 'Short for <b>malicious software</b>: any harmful program made to damage, disrupt or steal data from computers and networks. Common types: <b>viruses, ransomware, spyware</b>. Users are pulled in by great &ldquo;deals&rdquo; and big discounts, then end up with malware.' },
    { front: 'File Sharing Safety (1)', back: '&#10004; Always ask <b>permission and assistance</b> before accessing shared files.<br>&#10004; Use <b>legal</b> file-sharing services.<br>&#10004; Use your <b>best judgement</b> when sharing files.' },
    { front: 'File Sharing Safety (2)', back: '&#10004; Use <b>strong passwords</b>.<br>&#10004; <b>Scan USB drives</b> before opening.<br>&#10004; <b>Check the file</b> before downloading.' },
    { front: 'Safe or Risky?', back: '&#9989; SAFE: homework from the teacher&rsquo;s email; class pictures from a friend through Bluetooth.<br>&#9888;&#65039; RISKY: a stranger sends &ldquo;Free Game.exe&rdquo;; an unknown USB found outside (the Mystery USB!).' },
    { front: '🔑 Memory Hook', back: 'The 3 risks are <b>F-P-M</b>: <b>F</b>irewall broken, <b>P</b>iracy, <b>M</b>alware. Pirates steal treasure, piracy steals digital work.' }
  ],
  quiz: [
    { q: 'What is a firewall?', options: ['A security system that controls network traffic', 'A fire alarm inside the computer that rings when it gets too hot', 'A game you download for free', 'A type of USB flash drive'], correct: 0, explain: 'A firewall is a security system that monitors, filters and controls incoming and outgoing network traffic. It acts as a barrier against untrusted networks.', why: ['', 'Despite its name, a firewall has nothing to do with real fire. It is a security system for network traffic.', 'A firewall is not a game. It is a security system that protects your computer.', 'A USB flash drive stores files. A firewall is a security barrier.'], tip: 'Think of a firewall as a WALL that guards what comes in and goes out.' },
    { q: 'Some P2P networks ask you to turn off your firewall before downloading. Why is this risky?', options: ['It makes the download much slower, so you have to wait a very long time', 'It gives other users or hackers a chance to access your computer', 'It deletes all your folders', 'It uses up your printer ink'], correct: 1, explain: 'Turning off the firewall removes the barrier, giving other users or hackers opportunities to access your computer.', why: ['The lesson’s worry is not speed. Without the firewall, hackers can get in.', '', 'Turning off a firewall does not delete folders by itself. The danger is that hackers can get in.', 'Printer ink has nothing to do with a firewall.'], tip: 'No wall = anyone can walk in. Never turn off your firewall to download.' },
    { q: 'What is piracy?', options: ['Sending homework by email', 'Saving a file in a subfolder', 'The illegal copying, sharing, using or selling of digital materials', 'Using a strong password with letters, numbers and symbols'], correct: 2, explain: 'Piracy is the illegal copying, sharing, using or selling of digital materials.', why: ['Sending homework by email is safe, legal file sharing.', 'Saving in a subfolder is just organizing files.', '', 'Using a strong password is a SAFETY measure, not a risk.'], tip: 'Pirates steal treasure. Digital piracy steals games, programs, music and movies.' },
    { q: 'Which of these is an example of piracy?', options: ['Downloading cracked games from the internet', 'Sending class pictures to a friend’s phone through Bluetooth', 'Submitting homework through email', 'Scanning a USB drive before opening it'], correct: 0, explain: 'Downloading cracked games is piracy. So are sharing one paid program with many friends and selling fake software.', why: ['', 'Sharing your own class pictures with a friend is safe, not piracy.', 'Submitting homework through email is safe and legal.', 'Scanning a USB is a SAFETY measure.'], tip: 'Piracy examples: one paid program shared with many, cracked games, fake software for sale.' },
    { q: 'Your classmate buys one paid program and gives copies to many friends. What is this?', options: ['Cloud storage', 'Piracy', 'A firewall', 'Netiquette'], correct: 1, explain: 'Sharing one paid program with many friends is one of the deck’s examples of piracy.', why: ['Cloud storage is a place to keep files online, not illegal copying.', '', 'A firewall is a security system, not copying programs.', 'Netiquette is good manners online. Copying paid programs is piracy.'], tip: 'Paid program + many free copies = piracy.' },
    { q: 'What does “malware” stand for?', options: ['Mail software', 'Malicious software', 'Making software', 'Manual hardware'], correct: 1, explain: 'Malware is short for malicious software, a harmful program designed to damage, disrupt or steal data.', why: ['“Mail” is about email. Malware means MALICIOUS (harmful) software.', '', 'Malware does not mean making software. It means harmful (malicious) software.', 'Malware is software, not hardware.'], tip: '“Mal” means bad. Malware = bad (malicious) software.' },
    { q: 'Which of these is a common type of malware?', options: ['Spyware', 'Bluetooth', 'Dropbox', 'Firewall'], correct: 0, explain: 'Common types of malware are viruses, ransomware and spyware.', why: ['', 'Bluetooth is a type of file sharing, not malware.', 'Dropbox is cloud storage, not malware.', 'A firewall PROTECTS you. It is not malware.'], tip: 'Malware family: virus, ransomware, spyware.' },
    { q: 'A website offers a famous game at a huge discount, but it is not the real store. What is the danger the lesson warns about?', options: ['You might end up with malware', 'Your folders will get organized', 'The game will be too easy', 'Your firewall will get stronger'], correct: 0, explain: 'The deck warns that users are attracted to great “deals” and big discounts, but end up with malware.', why: ['', 'A fake deal does not organize your folders. The danger is malware.', 'The lesson is not about how hard the game is. The danger is malware.', 'A fake deal does not make your firewall stronger. It can bring in malware.'], tip: 'Too-good-to-be-true deals often hide malware.' },
    { q: 'A stranger sends you a file called “Free Game.exe”. Is this safe or risky?', options: ['Safe, because it is free', 'Risky, because it is from a stranger', 'Safe, because games are fun', 'Safe, as long as you open it very quickly and close it'], correct: 1, explain: 'This is risky. The file is from a stranger and could be a fake file or malware.', why: ['“Free” is not a reason to trust it. Free offers are a common trick for spreading malware.', '', 'Being fun does not make a file safe. A file from a stranger can hide malware.', 'Opening it quickly does not make it safe. Do not open files from strangers.'], tip: 'Stranger + “free” file = risky. Do not open it.' },
    { q: 'You find an unknown USB flash drive outside the school. What should you do?', options: ['Plug it into your computer to find out whose it is', 'Do not open it; give it to a teacher', 'Copy its files to your computer', 'Share it with your classmates'], correct: 1, explain: 'An unknown USB found outside is risky. Do not open it. Ask an adult, and remember to scan USB drives before opening.', why: ['Plugging in an unknown USB can spread malware to your computer.', '', 'Copying its files could copy malware too.', 'Sharing it spreads the danger to your classmates.'], tip: 'Mystery USB = risky. Ask for permission and assistance first.' },
    { q: 'True or False: Receiving homework from your teacher’s email is risky.', options: ['True', 'False'], correct: 1, explain: 'False. Homework from your teacher’s email comes from someone you know and trust, so it is safe.', why: ['True is not right. The teacher is a trusted sender, so this one is SAFE.', ''], tip: 'Ask “Do I know and trust the sender?” Teacher = safe. Stranger = risky.' },
    { q: 'True or False: You should scan USB drives before opening them.', options: ['True', 'False'], correct: 0, explain: 'True. Scanning USB drives before opening is one of the file sharing safety measures.', why: ['', 'False is not right. “Scan USB drives before opening” is on the safety list.'], tip: 'Safety list: ask permission, legal services, best judgement, strong passwords, scan USBs, check files.' },
    { q: 'True or False: Pirated copies of games are usually high quality and safe to use.', options: ['True', 'False'], correct: 1, explain: 'False. Most of the time, pirated copies are of poor quality and have malware.', why: ['True is not right. The deck says pirated copies are usually POOR quality and have malware.', ''], tip: 'Pirated = poor quality + malware risk.' },
    { q: 'Toby receives a message from someone he does not know. The person asks Toby to send a file containing his personal information. What should Toby do?', options: ['Send the file because the person said that it was needed immediately.', 'Ask the person for more personal information first.', 'Send the file carefully.', 'Ignore the request.'], correct: 3, explain: 'Toby should ignore the request. Sharing files with strangers can lead to stolen personal information.', why: ['Saying “it is needed right away” is a trick to rush you. Never send personal information to a stranger.', 'Talking more with the stranger about personal information is still risky.', 'There is no careful way to send your personal information to a stranger.', ''], tip: 'Stranger + personal information = do not send.' }
  ]
});
