StudyKit.lesson({
  id: 'online',
  icon: '☁️',
  title: 'Sharing Files Online',
  subtitle: 'Online storage, steps & permissions',
  cards: [
    { front: 'What Is a File?', back: 'A collection of digital information stored on a computer or electronic device. Files can contain <b>text, images, videos, audio, or data</b>.' },
    { front: 'Online Storage', back: 'A digital service that lets you save files, photos and videos on <b>remote servers via the internet</b> instead of your device&rsquo;s local hard drive. You can access, share and edit them anytime from any connected computer, phone or tablet.' },
    { front: 'Local vs Online Storage', back: '<b>Local storage</b>: files are saved on <b>one device</b>.<br><b>Online storage</b>: files are saved on the internet and can be accessed <b>anytime, anywhere</b> as long as you have an internet connection.' },
    { front: 'Uses of Online Storage', back: 'Save files online &bull; Access files from different devices &bull; Keep a backup of important files &bull; Share files with other people &bull; Work together on files at the same time.' },
    { front: 'Examples of Online Storage', back: '<b>Google Drive, Microsoft OneDrive, Dropbox, iCloud</b>' },
    { front: 'Accessing Files Online (5 steps)', back: '1. Connect to the internet.<br>2. Open a web browser or storage app.<br>3. Sign in to your account.<br>4. Open the online storage space.<br>5. Find and open the file you need.' },
    { front: 'What Does Sharing a File Online Mean?', back: 'Giving another person <b>permission to access</b> a file. Example: Ana uploaded her presentation and shared it with her group so they could access it.' },
    { front: 'Why Share Online?', back: 'Instead of sending many copies, you share <b>one file</b>. Everyone with access can contribute in <b>real time</b>, and the changes are there right away.' },
    { front: 'Sharing a File (7 steps)', back: '1. Open your online storage space.<br>2. Find and select the file or folder.<br>3. Click the <b>Share</b> button.<br>4. Enter or choose the person.<br>5. Choose the appropriate <b>permission</b>.<br>6. Send or share the file.<br>7. <b>Check</b> that you shared it with the correct person.' },
    { front: 'Sharing Through a Link', back: 'Open storage &rarr; select the file &rarr; click <b>Share</b> &rarr; choose the permission &rarr; click <b>&ldquo;Copy Link&rdquo;</b> &rarr; check it is the correct file &rarr; send the link to the correct person.' },
    { front: 'Sharing Permissions', back: '<b>Viewer</b> &mdash; can view or read the file.<br><b>Commenter</b> &mdash; can view and leave comments.<br><b>Editor</b> &mdash; can make changes to the file.' },
    { front: 'Think Before You Share!', back: 'Who am I sharing this with? &bull; What am I sharing? &bull; Does the file contain private information? &bull; What permission should I give? &bull; Do I have permission to share it?' },
    { front: '🔑 Memory Hook', back: 'Permissions go up like stairs: <b>V-C-E</b>. <b>V</b>iewer reads, <b>C</b>ommenter reads + comments, <b>E</b>ditor reads + changes.' }
  ],
  quiz: [
    { q: 'What is online storage?', options: ['Saving files only on your own computer’s hard drive, never on the internet', 'A service that saves your files on remote servers via the internet', 'A drawer where you keep printed papers', 'A USB flash drive you carry in your bag'], correct: 1, explain: 'Online storage lets you save files on remote servers via the internet instead of your device’s local hard drive.', why: ['That is LOCAL storage: files saved on one device.', '', 'Online storage is digital, not a drawer for paper.', 'A USB flash drive is removable storage media, not online storage.'], tip: 'Online storage = saved on the internet, reachable from any connected device.' },
    { q: 'What is the difference between local storage and online storage?', options: ['Local storage always needs the internet; online storage never needs it', 'They are exactly the same', 'Local storage is on one device; online storage is on the internet', 'Online storage can only hold music'], correct: 2, explain: 'Local storage keeps files on one device. Online storage keeps files on the internet, so you can reach them anytime, anywhere with a connection.', why: ['It is the opposite: ONLINE storage needs the internet.', 'They are different. One is on a device, the other is on the internet.', '', 'Online storage can hold files, photos, videos and more, not only music.'], tip: 'Local = on this device. Online = on the internet.' },
    { q: 'Which of these is an example of online storage?', options: ['iCloud', 'Bluetooth', 'Microsoft Word', 'A firewall'], correct: 0, explain: 'Google Drive, Microsoft OneDrive, Dropbox and iCloud are examples of online storage services.', why: ['', 'Bluetooth shares files between nearby devices. It does not store them online.', 'Microsoft Word is for typing documents.', 'A firewall is a security system.'], tip: 'Drive, OneDrive, Dropbox, iCloud = online storage.' },
    { q: 'Which is NOT one of the uses of online storage in the lesson?', options: ['Keep a backup of important files', 'Make your computer run without electricity', 'Access files from different devices', 'Work together on the same files at the same time'], correct: 1, explain: 'The uses are: save files online, access from different devices, keep a backup, share with others, and work together at the same time.', why: ['Keeping a backup IS a use of online storage.', '', 'Accessing files from different devices IS a use of online storage.', 'Working together on files at the same time IS a use of online storage.'], tip: 'Uses: save, access anywhere, backup, share, work together.' },
    { q: 'What is the FIRST step in accessing your files online?', options: ['Sign in to your account', 'Find and open the file', 'Connect to the internet', 'Open the online storage space'], correct: 2, explain: 'Step 1 is to connect to the internet. Without it, you cannot reach online storage.', why: ['Signing in is Step 3. You need the internet and a browser first.', 'Finding and opening the file is the LAST step (Step 5).', '', 'Opening the storage space is Step 4.'], tip: 'Internet &rarr; Browser or app &rarr; Sign in &rarr; Storage &rarr; File.' },
    { q: 'You have opened a web browser. According to the steps, what do you do next to access your files online?', options: ['Sign in to your account', 'Connect to the internet', 'Click Copy Link', 'Choose Editor permission'], correct: 0, explain: 'Step 3, after opening a browser or storage app, is to sign in to your account.', why: ['', 'Connecting to the internet is Step 1. It comes before opening a browser.', 'Copy Link is for sharing a link, not for accessing your files.', 'Choosing a permission is for sharing, not accessing.'], tip: 'Internet &rarr; Browser &rarr; SIGN IN &rarr; Storage &rarr; File.' },
    { q: 'What does it mean to share a file online?', options: ['To print the file for someone', 'To give another person permission to access the file', 'To delete the file from your storage after everyone has used it', 'To rename the file'], correct: 1, explain: 'Sharing a file online means giving another person permission to access the file.', why: ['Printing makes a paper copy. Sharing online gives access to the file.', '', 'Deleting removes the file. Sharing gives others access.', 'Renaming only changes the file’s name.'], tip: 'Share online = give permission to access.' },
    { q: 'When sharing a file online with a person, what comes right after clicking the Share button?', options: ['Check that you shared the right file with the right person', 'Open your online storage space', 'Enter or choose the person to share with', 'Find and select the file'], correct: 2, explain: 'Step 3 is click Share, and Step 4 is enter or choose the person you want to share with.', why: ['Checking is the LAST step (Step 7).', 'Opening the storage space is Step 1.', '', 'Finding the file is Step 2, BEFORE clicking Share.'], tip: 'Open &rarr; Select &rarr; Share &rarr; Person &rarr; Permission &rarr; Send &rarr; Check.' },
    { q: 'What is the LAST step when sharing a file online with a person?', options: ['Click the Share button', 'Check that you shared it with the correct person', 'Choose the appropriate permission: Viewer, Commenter or Editor', 'Open your online storage space'], correct: 1, explain: 'Step 7: check that you shared it with the correct person.', why: ['Clicking Share is Step 3.', '', 'Choosing a permission is Step 5.', 'Opening storage is Step 1.'], tip: 'Always finish by CHECKING: right file, right person.' },
    { q: 'Ana wants her group to read her presentation but NOT change anything. Which permission should she give?', options: ['Editor', 'Viewer', 'Owner', 'Sender'], correct: 1, explain: 'A Viewer can view or read the file but cannot change it.', why: ['An Editor can make changes, which Ana does not want.', '', 'Owner is not one of the three sharing permissions in the lesson.', 'Sender is not one of the sharing permissions.'], tip: 'Read only = Viewer.' },
    { q: 'Your teacher wants to read your essay and leave notes, but not change your words. Which permission fits?', options: ['Viewer', 'Editor', 'Commenter', 'Sender'], correct: 2, explain: 'A Commenter can view the file and leave comments, but cannot change it.', why: ['A Viewer can only read. The teacher wants to leave notes too.', 'An Editor can change your words, which you do not want here.', '', 'Sender is not one of the sharing permissions.'], tip: 'Read + notes = Commenter.' },
    { q: 'Your groupmates need to type their parts into the shared report. Which permission should you give them?', options: ['Editor', 'Viewer', 'Commenter', 'Reader'], correct: 0, explain: 'An Editor can make changes to the file.', why: ['', 'A Viewer can only read. They could not type their parts.', 'A Commenter can only leave comments, not change the report.', 'Reader is not one of the permissions in the lesson.'], tip: 'Make changes = Editor.' },
    { q: 'When sharing through a link, which button do you click to get the link?', options: ['Rename', 'Delete', 'New Folder', 'Copy Link'], correct: 3, explain: 'After choosing the permission, click “Copy Link”, then send the link to the correct person.', why: ['Rename changes a name. It does not give you a link.', 'Delete removes the file.', 'New Folder makes a folder, not a link.', ''], tip: 'Link sharing: Share &rarr; permission &rarr; Copy Link &rarr; check &rarr; send.' },
    { q: 'True or False: Before sharing a file, you should check if it contains private information.', options: ['True', 'False'], correct: 0, explain: 'True. “Does the file contain private information?” is one of the Think Before You Share questions.', why: ['', 'False is not right. Checking for private information is on the Think Before You Share list.'], tip: 'Think before you share: Who? What? Private? Which permission? Am I allowed?' },
    { q: 'True or False: It is okay to share another person’s work online without asking them.', options: ['True', 'False'], correct: 1, explain: 'False. Ask yourself, “Do I have permission to share it?” Do not share another person’s work without permission.', why: ['True is not right. The lesson says do NOT share another person’s work without permission.', ''], tip: 'Not yours? Ask first.' },
    { q: 'True or False: Online storage lets you access your files from different devices.', options: ['True', 'False'], correct: 0, explain: 'True. Accessing files from different devices is one of the uses of online storage.', why: ['', 'False is not right. Online storage can be reached from any connected computer, phone or tablet.'], tip: 'Online = anywhere, any device, as long as you have internet.' }
  ]
});
