StudyKit.lesson({
  id: 'chat',
  icon: '💬',
  title: 'Chat & Instant Messages',
  subtitle: 'Chat vs IM, pros & cons, BE AWARE',
  cards: [
    { front: 'Chat', back: 'A way of communicating with other people by <b>exchanging messages online</b>. Chat also uses a <b>chat room</b>, where many users who may not know each other connect to exchange text and images on a topic or interest.' },
    { front: 'Instant Messaging (IM)', back: 'A form of online communication that lets people send and receive messages <b>immediately</b> or almost immediately. It allows conversation between two or more people.' },
    { front: 'Friend List / Contact List', back: 'IM gives users a list of their contacts called a <b>friend list</b> or <b>contact list</b>. From it, users can see each other&rsquo;s <b>status</b>: available, offline, or busy.' },
    { front: 'Chat vs Instant Messaging (1)', back: '<b>Chat</b>: a <b>general</b> way of communicating online; can involve discussions or conversations.<br><b>IM</b>: a <b>specific</b> type of online messaging; focuses on <b>quick</b> message exchange.' },
    { front: 'Chat vs Instant Messaging (2)', back: '<b>Chat</b>: can happen in groups; used for sharing ideas and discussing topics.<br><b>IM</b>: can be one-on-one or in groups; used for sending and receiving messages quickly.' },
    { front: 'Advantages of Both', back: 'Communicate even when far apart &bull; Discuss topics with others &bull; Communicate in <b>real time</b> &bull; One-on-one or group conversations &bull; Help people stay connected.' },
    { front: 'Disadvantages of Both', back: 'Messages can be misunderstood &bull; People may say things they would not say face-to-face &bull; False information can be shared &bull; Private information may be shared carelessly &bull; Messages can interrupt your work or study.' },
    { front: 'Practice BE AWARE', back: '<b>A</b> &ndash; Ask: Is this message necessary?<br><b>W</b> &ndash; Wary: Be wary of everybody!<br><b>A</b> &ndash; Avoid: sharing private information.<br><b>R</b> &ndash; Respect: other people&rsquo;s feelings and opinions.<br><b>E</b> &ndash; Examine: check the messages before sending.' },
    { front: '🔑 Memory Hook', back: 'Chat = a <b>chat room</b> full of people talking about a topic. IM = <b>Instant</b>: quick messages to people on your <b>contact list</b>.' }
  ],
  quiz: [
    { q: 'What is chat?', options: ['A way of communicating by exchanging messages online', 'A program that stores your files and photos on the internet', 'A security system that blocks hackers', 'A search engine for kids'], correct: 0, explain: 'Chat is a way of communicating with other people by exchanging messages online.', why: ['', 'That is online storage, not chat.', 'That is a firewall, not chat.', 'A search engine finds information. Chat is for exchanging messages.'], tip: 'Chat = exchanging messages online.' },
    { q: 'In which place can many users who may not know each other exchange text and images about a topic?', options: ['A friend list', 'A chat room', 'A USB flash drive', 'A subfolder'], correct: 1, explain: 'Chat uses a chat room, where multiple users who may not know each other connect on a topic or interest.', why: ['A friend list shows your own contacts and their status.', '', 'A USB flash drive stores files. It is not a place to talk.', 'A subfolder is a folder inside a folder.'], tip: 'Strangers sharing an interest meet in a CHAT ROOM.' },
    { q: 'What is instant messaging?', options: ['Sending a handwritten letter through the post office and waiting for a reply', 'Online communication where messages are sent and received immediately', 'Saving a file in a flash drive', 'Posting on a discussion board for weeks'], correct: 1, explain: 'Instant messaging lets people send and receive messages immediately or almost immediately.', why: ['A mailed letter takes days. IM is immediate.', '', 'Saving a file is not messaging.', 'A discussion board is a different tool, and IM is about quick, immediate messages.'], tip: 'Instant = right away.' },
    { q: 'In instant messaging, what do you call the list where you can see if your contacts are available, offline, or busy?', options: ['Search results', 'Chat room', 'Friend list or contact list', 'Discussion thread'], correct: 2, explain: 'IM gives users a friend list or contact list showing each contact’s status.', why: ['Search results come from a search engine.', 'A chat room is where many people, even strangers, talk about a topic.', '', 'A discussion thread is a set of posts on a discussion board.'], tip: 'Your contacts + their status = friend list / contact list.' },
    { q: 'Which describes CHAT, not instant messaging?', options: ['A specific type of online messaging', 'Focuses on quick message exchange', 'A general way of communicating online', 'Has a contact list that shows who is busy'], correct: 2, explain: 'Chat is a GENERAL way of communicating online. IM is a SPECIFIC type that focuses on quick messages.', why: ['“A specific type of online messaging” describes IM.', '“Focuses on quick message exchange” describes IM.', '', 'The contact list with statuses belongs to IM.'], tip: 'Chat = General. IM = Specific and quick.' },
    { q: 'Which describes INSTANT MESSAGING, not chat?', options: ['Used for sharing ideas and discussing topics', 'Uses a chat room for people who may not know each other', 'A general way of communicating online', 'Used for sending and receiving messages quickly'], correct: 3, explain: 'IM is used for sending and receiving messages quickly. Chat is for sharing ideas and discussing topics.', why: ['Sharing ideas and discussing topics describes chat.', 'The chat room belongs to chat.', '“A general way of communicating online” describes chat. IM is a SPECIFIC type.', ''], tip: 'Quick messages = IM. Topics and discussions = Chat.' },
    { q: 'Which is an ADVANTAGE of chat and instant messaging?', options: ['Messages can be misunderstood', 'People can communicate in real time', 'False information can be shared', 'Messages can interrupt your work or study'], correct: 1, explain: 'Communicating in real time is an advantage. The other three are disadvantages.', why: ['Being misunderstood is a DISADVANTAGE.', '', 'Sharing false information is a DISADVANTAGE.', 'Interrupting your study is a DISADVANTAGE.'], tip: 'Advantages connect people. Disadvantages cause trouble.' },
    { q: 'Which is a DISADVANTAGE of chat and instant messaging?', options: ['It helps people stay connected', 'People can talk even when far apart', 'Private information may be shared carelessly', 'It can be used for one-on-one or group conversations'], correct: 2, explain: 'Private information being shared carelessly is a disadvantage.', why: ['Staying connected is an ADVANTAGE.', 'Talking when far apart is an ADVANTAGE.', '', 'Group conversations are an ADVANTAGE.'], tip: 'Ask: does this cause a problem? Then it is a disadvantage.' },
    { q: 'In BE AWARE, what does the W stand for?', options: ['Write: type as fast as you can', 'Wary: be wary of everybody', 'Wait: never reply to anyone', 'Win: always win the argument'], correct: 1, explain: 'W stands for Wary: be wary of everybody!', why: ['Typing fast is not part of BE AWARE.', '', 'BE AWARE does not say never reply. It says be wary (careful).', 'Winning arguments is not part of BE AWARE. R is for Respect.'], tip: 'A-W-A-R-E: Ask, Wary, Avoid, Respect, Examine.' },
    { q: 'In BE AWARE, what does the E stand for?', options: ['Examine: check the messages before sending', 'Erase: delete all your messages', 'Enjoy: send as many messages as you like, all day', 'Email: always use email instead'], correct: 0, explain: 'E stands for Examine: check the messages before sending.', why: ['', 'Erasing everything is not part of BE AWARE.', 'Sending many messages can disturb others. E is for Examine.', 'BE AWARE does not tell you to use email. E is for Examine.'], tip: 'Examine = check before you send.' },
    { q: 'Before sending a message, Ella asks herself, “Is this message necessary?” Which part of BE AWARE is this?', options: ['Ask', 'Avoid', 'Respect', 'Examine'], correct: 0, explain: 'The first A stands for Ask: Is this message necessary?', why: ['', 'Avoid is about not sharing private information.', 'Respect is about other people’s feelings and opinions.', 'Examine is checking the message before sending.'], tip: 'First A = Ask. Second A = Avoid.' },
    { q: 'True or False: Instant messaging can only be used one-on-one, never in groups.', options: ['True', 'False'], correct: 1, explain: 'False. Instant messaging can be one-on-one or in groups.', why: ['True is not right. The word “never” is the trap: IM can be one-on-one OR in groups.', ''], tip: 'Watch for “only” and “never”.' },
    { q: 'True or False: Chat and instant messaging allow people to communicate even when they are far apart.', options: ['True', 'False'], correct: 0, explain: 'True. That is one of the advantages of both.', why: ['', 'False is not right. Communicating when far apart is the first advantage listed.'], tip: 'Advantages: far apart, discuss, real time, one-on-one or group, stay connected.' },
    { q: 'True or False: In BE AWARE, the second A tells you to avoid sharing private information.', options: ['True', 'False'], correct: 0, explain: 'True. A = Avoid sharing private information.', why: ['', 'False is not right. The second A in AWARE is Avoid: sharing private information.'], tip: 'A-W-A-R-E: Ask, Wary, Avoid, Respect, Examine.' },
    { q: 'Which situation BEST shows the difference between chat and instant messaging?', options: ['Chat allows people to communicate online.', 'Instant messaging allows people to send messages online.', 'Chat usually involves online conversations, while instant messaging allows quick private messages.', 'Chat and instant messaging are exactly the same because both allow people to communicate using the Internet.'], correct: 2, explain: 'Only this answer tells how the two are DIFFERENT: chat is for online conversations and discussions, while IM focuses on quick messages.', why: ['This is true, but it only describes chat. It does not show a difference.', 'This is true, but it only describes IM. It does not show a difference.', '', 'They are not exactly the same. Chat is general; IM is a specific, quick type of messaging.'], tip: 'A “difference” answer must talk about BOTH and say how they are not alike.' }
  ]
});
