StudyKit.content('typeIt', {
  'Sino ang karaniwang pinuno ng sinaunang barangay?': [],
  '"Ako ang katawagan sa ilang pinuno sa pamayanang may impluwensiyang Malay-Indonesian." Sino ako?': ['Raja', 'Radya'],
  'Ang isang pamayanan ay naimpluwensiyahan ng Islam. Ano ang malamang na katawagan sa pinuno nito?': [],
  'Alin ang <b>pinakamataas</b> na antas ng sinaunang lipunan?': [],
  '"Kabilang ako sa pinakamababang antas ng sinaunang lipunan." Sino ako?': [],
  'Anong hanapbuhay ang umunlad sa <b>kapatagan</b>?': ['pagsasaka', 'pagtatanim'],
  'Anong hanapbuhay ang umunlad sa <b>baybaying-dagat</b>?': [],
  'Ano ang natutuhang gamitin ng mga sinaunang Pilipino upang mapahusay ang paggawa ng kagamitan?': [],
  'Kailan natuklasan ng National Museum of the Philippines ang mga artifact ng balangay?': ['1977'],
  'Tinatayang ilan ang kapasidad ng isang balangay?': ['320'],
  'Ang Filipino, Cebuano, Ilokano, at Waray ay mga halimbawa ng alin?': [],
  'Anong tirahan ang gumagamit ng materyales mula sa kapaligiran at may simple at praktikal na disenyo?': ['bahaykubo'],
  'Ano ang tawag ng mga Espanyol sa paniniwala ng ating mga ninuno sa mga anito?': [],
  'Ano ang tawag ng mga <b>Igorot</b> sa kanilang diyos?': ['Kabunian'],
  'Sino ang diyos na sinasamba ng mga Tagalog kapag panahon ng <b>pagtatanim</b>?': [],
  'Sino ang diyos ng mga <b>mangingibig</b> ayon sa aralin?': [],
  'Ano ang tawag sa tagapamagitan sa mga espiritu at sa mga tao sa mga <b>Bisaya</b>?': [],
  'Ano ang tawag ng ating mga ninuno sa <b>buwaya</b> bilang tanda ng paggalang?': [],
  'Ano ang tawag ng mga Bikolano sa <b>aswang</b>?': [],
  'Ano ang tawag sa mga <b>higanteng elemento sa kagubatan</b>?': [],
  'Ano ang ginagamit upang <b>mapaibig</b> ang isang tao?': [],
  'Ayon sa pag-aaral ng historyador na si William Henry Scott, ano ang isinasama sa paglibing sa mga yumao?': ['alahas'],
  'Ang <b>Manunggul Jar</b> ay halimbawa ng anong uri ng banga?': ['secondary burial'],
  'Saan natagpuan ang <b>Manunggul Jar</b>?': ['Palawan'],
  'Kailan nahukay ang mga anthropomorphic jar sa bayan ng Maitum, Sarangani?': ['1991'],
  'Ano ang tawag sa halaga ng yamang ibinibigay ng pamilya ng lalaki sa pamilya ng babae?': [],
  'Ano ang tawag sa kompensasyong maaaring hingin ng nanay ng babae para sa kaniyang pag-aalaga sa anak?': [],
  'May kaklase kang nagsabing sabay-sabay umunlad ang mga tao sa Timog-Silangang Asya. Anong teorya ang kaniyang tinutukoy?': ['Core Population'],
  'Aling teorya ang tungkol sa pagdating ng mga sinaunang tao nang pa-alon-alon, sa magkakaibang panahon?': ['Wave Migration'],
  'Ano ang tawag sa pag-aaral ng mga pangyayari sa nakaraan batay sa mga ebidensiya?': [],
  'Sino ang Diyos ng mga Samal na lumikha sa unang tao na si Nur Muhammad ayon sa kanilang kaalamang bayan?': []
});
