StudyKit.content('typeIt', {
  'Sino ang karaniwang pinuno ng sinaunang barangay?': [],
  '"Ako ang katawagan sa ilang pinuno sa pamayanang may impluwensiyang Malay-Indonesian." Sino ako?': ['Raja', 'Radya'],
  'Ang isang pamayanan ay naimpluwensiyahan ng Islam. Ano ang malamang na katawagan sa pinuno nito?': [],
  'Alin ang <b>pinakamataas</b> na antas ng sinaunang lipunan?': [],
  '"Kabilang ako sa pinakamababang antas ng sinaunang lipunan." Sino ako?': [],
  'Anong hanapbuhay ang umunlad sa <b>kapatagan</b>?': ['pagsasaka', 'pagtatanim'],
  'Anong hanapbuhay ang umunlad sa <b>baybaying-dagat</b>?': [],
  'Ano ang natutuhang gamitin ng mga sinaunang Pilipino upang mapahusay ang paggawa ng kagamitan?': [],
  'Kailan natuklasan ng National Museum of the Philippines ang mga artifact ng balangay?': ['1977'],
  'Tinatayang ilan ang kapasidad ng isang balangay?': ['320'],
  'Ang Filipino, Cebuano, Ilokano, at Waray ay mga halimbawa ng alin?': [],
  'Anong tirahan ang gumagamit ng materyales mula sa kapaligiran at may simple at praktikal na disenyo?': ['bahaykubo'],
  'Ano ang tawag ng mga Espanyol sa paniniwala ng ating mga ninuno sa mga anito?': [],
  'Ano ang tawag ng mga <b>Igorot</b> sa kanilang diyos?': ['Kabunian'],
  'Sino ang diyos na sinasamba ng mga Tagalog kapag panahon ng <b>pagtatanim</b>?': [],
  'Sino ang diyos ng mga <b>mangingibig</b> ayon sa aralin?': [],
  'Ano ang tawag sa tagapamagitan sa mga espiritu at sa mga tao sa mga <b>Bisaya</b>?': [],
  'Ano ang tawag ng ating mga ninuno sa <b>buwaya</b> bilang tanda ng paggalang?': [],
  'Ano ang tawag ng mga Bikolano sa <b>aswang</b>?': [],
  'Ano ang tawag sa mga <b>higanteng elemento sa kagubatan</b>?': [],
  'Ano ang ginagamit upang <b>mapaibig</b> ang isang tao?': [],
  'Ayon sa pag-aaral ng historyador na si William Henry Scott, ano ang isinasama sa paglibing sa mga yumao?': ['alahas'],
  'Ang <b>Manunggul Jar</b> ay halimbawa ng anong uri ng banga?': ['secondary burial'],
  'Saan natagpuan ang <b>Manunggul Jar</b>?': ['Palawan'],
  'Kailan nahukay ang mga anthropomorphic jar sa bayan ng Maitum, Sarangani?': ['1991'],
  'Ano ang tawag sa halaga ng yamang ibinibigay ng pamilya ng lalaki sa pamilya ng babae?': [],
  'Ano ang tawag sa kompensasyong maaaring hingin ng nanay ng babae para sa kaniyang pag-aalaga sa anak?': [],
  'May kaklase kang nagsabing sabay-sabay umunlad ang mga tao sa Timog-Silangang Asya. Anong teorya ang kaniyang tinutukoy?': ['Core Population'],
  'Aling teorya ang tungkol sa pagdating ng mga sinaunang tao nang pa-alon-alon, sa magkakaibang panahon?': ['Wave Migration'],
  'Ano ang tawag sa pag-aaral ng mga pangyayari sa nakaraan batay sa mga ebidensiya?': [],
  'Sino ang Diyos ng mga Samal na lumikha sa unang tao na si Nur Muhammad ayon sa kanilang kaalamang bayan?': ['Tuhan'],
  'Mula sa anong wika nagmula ang salitang Ingles na &ldquo;history&rdquo;?': [],
  'Sino ang tinaguriang Ama ng Pantayong Pananaw?': ['Salazar'],
  'Ano ang tawag sa taong nagsasaliksik at nagsusulat tungkol sa kasaysayan?': ['historyador'],
  'Sinong historyador ang nagsabing mahalaga ang kritikal na pag-iisip?': ['Constantino'],
  'Sino ang nagpanukala ng Continental Drift Theory noong 1912?': ['Wegener'],
  'Ano ang ibig sabihin ng &ldquo;Pangaea&rdquo;?': [],
  'Sino ang nagpanukala ng Volcanic Origin Theory?': ['Willis'],
  'Sino ang lumikha ng tao mula sa putik ayon sa paniniwala ng mga Ifugao?': [],
  'Sino ang Filipinong antropologo na nagpanukala ng Core Population Theory?': ['Jocano'],
  'Ano ang tawag sa Taong Callao?': [],
  'Kailan natuklasan ang Taong Tabon?': [],
  'Ano ang tawag sa bansang binubuo ng maraming isla?': ['kapuluan'],
  'Ano ang isa pang tawag sa arkipelago?': [],
  'Sino ang pinuno ng sinaunang pamayanan sa Kabisayaan?': [],
  'Ano ang tawag sa mataas na antas ng lipunan sa Luzon?': ['Maguinoo'],
  'Ano ang tawag sa malayang tao sa Kabisayaan?': [],
  'Ang <b>oripun</b> sa Kabisayaan ay katapat ng anong pangkat sa Luzon?': [],
  'Ano ang tawag sa mga kaugalian o gawaing ipinapasa mula sa isang salinlahi patungo sa susunod?': [],
  'Clue: &ldquo;May pagsamba at ritwal na may kaugnayan sa pananampalataya.&rdquo; Anong bahagi ng kalinangang di-materyal ito?': [],
  'Clue: &ldquo;Mahalaga sa kanila ang pagtutulungan sa pamayanan.&rdquo; Anong bahagi ng kalinangang di-materyal ito?': [],
  'Sino ang nagtatag ng Sultanato ng Sulu noong 1450 at itinuturing na unang sultan ng bansa?': ['Abu Bakr'],
  'Sino ang nagtatag ng Sultanato ng Maguindanao noong 1515?': ['Kabungsuwan'],
  'Ano ang naging tawag sa mga dating <b>raha</b> nang maitatag ang sultanato?': [],
  'Ano ang tawag sa kataas-taasang ministro sa Sultanato ng Sulu?': [],
  'Ano ang tawag sa kataas-taasang ministro sa Sultanato ng Maguindanao?': [],
  'Ano ang tawag sa komunidad ng mga mananampalataya at tagasunod ng Islam?': [],
  'Anong haligi ng Islam ang pagdarasal nang limang beses sa loob ng isang araw?': [],
  'Anong haligi ng Islam ang pag-aayuno sa panahon ng Ramadan?': [],
  'Isang bansa na nakipag-ugnayan sa ating bansa noong sinaunang panahon at may kaugalian ng paggunita sa mga yumao. Anong bansa ito?': ['China']
});
