StudyKit.content('typeIt', {
  '&ldquo;<i>Kindness should always be shared with others.</i>&rdquo; What element of a narrative is this?': [],
  'Which element answers the question &ldquo;What lesson does the story teach?&rdquo;': [],
  'The story happens at school, at lunchtime. Which element of the story is this?': [],
  'What part of the plot introduces the characters and setting?': [],
  'Which part of the plot shows events after the climax and leads to the ending?': [],
  'Which part of the plot is the most exciting part, the turning point?': [],
  'In which part of the plot does the problem appear and the events build up?': [],
  'Which word means a serious situation where many people do not have enough food for a long time?': [],
  'Which word means to give or do something <b>in return</b> for something you received?': [],
  'Which word means something that is <b>certain to happen</b> and cannot be avoided?': [],
  'Which word means to choose or assign someone to a position or duty?': [],
  '&ldquo;<i>Her smile was as bright as the sun.</i>&rdquo; This is a&hellip;': [],
  '&ldquo;<i>The sun smiled down on us.</i>&rdquo; This is an example of&hellip;': [],
  '&ldquo;<i>My brother is a sleepy bear in the morning.</i>&rdquo; This is an example of&hellip;': [],
  '&ldquo;<i>Peter picked pink peppers.</i>&rdquo; This is an example of&hellip;': [],
  '&ldquo;<i>Go slow over the road.</i>&rdquo; The long <i>o</i> sound repeats. This is an example of&hellip;': [],
  '“<i>The thunder boomed across the sky.</i>” Which sound device does <b>boomed</b> show?': [],
  '“I. Benefits of Exercise &mdash; A. Physical Health, B. Mental Health, C. Better Sleep.” What kind of outline is this?': ['topic outline'],
  '“<i>Ben tried to sneak into the kitchen for a midnight snack. Unfortunately, he stepped on the squeaky toy and woke the entire house.</i>” The purpose is&hellip;': ['entertain'],
  'Who feels the <b>mood</b>?': ['reader'],
  '“<b>They</b> handled the problem well.” <i>They</i> is&hellip;': ['subject pronoun'],
  '“Mike gave the book to <b>me</b>.” <i>Me</i> is&hellip;': ['object pronoun'],
  '“The shirt is <b>mine</b>.” <i>Mine</i> is&hellip;': ['possessive pronoun'],
  '“The pillow belongs to Ria. It is ___.”': [],
  'Which demonstrative pronoun is for things that are <b>near</b> and <b>two or more</b>?': [],
  'Which demonstrative pronoun is for <b>one</b> thing that is <b>far</b>?': [],
  '“Mojo encourages <b>himself</b>.” <i>Himself</i> is a&hellip;': ['reflexive'],
  '“We cleaned the whole room by ___.”': [],
  'Which visual element shows <b>where the subject is looking</b>?': [],
  'Which visual element suggests <b>mood</b> and creates atmosphere?': ['color'],
  'Which visual element is the <b>layout</b> that draws attention to the subject?': []
});
