StudyKit.content('typeIt', {
  'What are the tiniest particles that make up matter?': ['atom'],
  'What do you call a group of atoms?': ['molecules'],
  'Which state of matter has no definite shape but has a definite volume?': [],
  'Which state of matter can spread out and fill the space inside a container?': [],
  'In which state of matter are the particles tightly packed and only vibrate in place?': [],
  'How many grams are in 1 kilogram?': ['1000'],
  'What is the standard unit for measuring mass?': ['kilogram', 'kilograms', 'kg'],
  'What is the standard unit for measuring liquid volume?': ['liter', 'liters', 'L'],
  'Which method is used to find the volume of an irregular solid, like a stone?': ['water displacement', 'displacement', 'displacement method'],
  'A cube has sides of 3 cm each. What is its volume?': ['27', '27 cubic centimeters', '27 cubic cm'],
  'What tool is used to measure temperature?': [],
  'A student places a piece of dry ice in an open container. After some time, the dry ice disappears and changes directly into a gas. What process occurs?': [],
  'A student observes that a candle becomes soft and produces liquid wax when heated. What process is shown?': [],
  'Mark sees water droplets forming on the outside of a cold glass. What change of state is happening?': [],
  'Frost forms when water vapor turns directly into ice without becoming a liquid first. What is this process called?': [],
  'Which step is a summarized statement based on the observations and results of the experiment?': [],
  'Lara says, &ldquo;I think sunlight makes an ice cube melt faster.&rdquo; She has not tested it yet. Which step is this?': ['hypothesis', 'form a hypothesis', 'forming hypothesis'],
  'Which state of matter is sand?': [],
  'Which state of matter is the wind?': [],
  'What do you call the factor that can be changed, controlled, or manipulated in an experiment?': ['variables'],
  'What must be done to an experiment to make sure the results are really accurate?': ['repeat', 'repeat the experiment'],
  'Bacteria that are shaped like spheres are called...': [],
  'Which helpful bacterium is found in yogurt and other fermented foods?': [],
  'Which division of fungi is known as the bread molds?': [],
  'Which division includes the yeasts used in baking?': [],
  'Mushrooms, toadstools and shelf fungi belong to which division?': [],
  'What does the word &ldquo;gymnosperm&rdquo; mean in Greek?': ['naked seeds'],
  'The leaves of pteridophytes are called...': ['frond'],
  'Which is the largest and most diverse group of plants?': ['angiosperm', 'flowering plants', 'flowering plant'],
  'Mosses, liverworts and hornworts belong to which group?': ['bryophyte'],
  'Mammals are named after which body part?': ['mammary glands', 'mammary gland'],
  'Which fin provides stability to a fish?': ['dorsal fin', 'dorsal'],
  'The caudal fin is also known as the...': ['tail'],
  'How many body segments does an insect have?': ['3'],
  'Which group includes spiders, scorpions, ticks and mites?': ['arachnid'],
  'Snails, clams, squids and octopus belong to which group?': ['mollusk'],
  'Crabs, lobsters and shrimp are examples of...': ['crustacean'],
  'Which part of the root grows downward from the seed?': ['primary root'],
  'Which tissue transports water and water-soluble nutrients?': [],
  'Which zone of the root enables root growth?': ['meristematic zone', 'meristematic'],
  'Which part of the plant is mainly responsible for photosynthesis?': ['leaves', 'leaf'],
  'Which part is the reproductive organ of the plant?': ['flower', 'flowers'],
  'Which structure is an underground stem that grows horizontally?': ['rhizome'],
  'Onions and tulips grow from which specialized structure?': ['bulb'],
  'Ginger and bamboo are examples of plants with...': ['rhizome'],
  'A student finds mold growing on an old piece of fruit. Which group should the student classify the mold into?': ['fungus'],
  'What are living things that are too small to be seen clearly with the naked eye called?': ['microorganism'],
  'A plant has a short underground stem surrounded by thick, fleshy leaves that store food. Which specialized structure is being described?': ['bulbs']
});
