StudyKit.lesson({
  id: 'measure',
  icon: '📏',
  title: 'Measuring Matter',
  subtitle: 'kg, g, mg, mL, &deg;C & balances',
  cards: [
    { front: 'Mass: kilogram (kg)', back: 'For <b>heavy</b> things, like a <b>bag of rice</b>, a school bag or a watermelon. The kilogram is the <b>standard unit</b> of mass.' },
    { front: 'Mass: gram (g)', back: 'For <b>small</b> amounts, like a <b>small powder sample</b>. There are <b>1,000 grams in 1 kilogram</b>. Smallest to biggest: <b>mg &lt; g &lt; kg</b>.' },
    { front: 'Mass: milligram (mg)', back: 'For <b>very light</b> things. On your test the key used milligrams for a <b>paper clip</b>.' },
    { front: 'Liquid: milliliter (mL)', back: 'For the <b>amount of liquid</b>, like the water in a small container.' },
    { front: 'Temperature: degree Celsius (&deg;C)', back: 'For how <b>hot or cold</b> an object or place is, like water or a room.' },
    { front: 'Match the Unit to the Job', back: 'kg, g and mg measure <b>mass</b>. mL measures <b>liquid amount</b>. &deg;C measures <b>temperature</b>. A unit from the wrong group is always wrong: never grams for temperature, never &deg;C for mass.' },
    { front: 'Mass or Volume?', back: 'Solid things like a <b>watermelon, fish or vegetable</b> are measured by their <b>mass</b>. Liquids like <b>blood, cooking oil and milk</b> are measured by their <b>volume</b>.' },
    { front: 'Balances Measure Mass', back: '<b>Platform balance</b>: has a platform where the objects are placed. <b>Double beam balance</b>: two parallel beams, each with a pan at one end and a sliding counterweight on the other. <b>Triple beam balance</b>: three beams that carry the weights.' },
    { front: 'Using a Balance', back: 'Put it on a smooth, even surface. <b>Set the pointer to zero first.</b> Place the object on the pan (at the center for a triple beam). Move the counterweights, <b>largest first</b>, until the pointer is back at zero. Add up the readings to get the mass.' }
  ],
  quiz: [
    { q: 'During a classroom activity, Carla measures the amount of water in a small container. Which unit should she use?', options: ['milliliter (mL)', 'gram (g)', 'kilogram (kg)', 'degree celsius (&deg;C)'], correct: 0, explain: 'An amount of liquid is measured in <b>milliliters (mL)</b>.', why: ['', 'Grams measure mass, the amount of material in a small object. Carla is measuring an amount of LIQUID, which uses mL.', 'Kilograms measure the mass of heavy things, like a bag of rice. An amount of liquid uses mL.', 'Degrees Celsius measure how hot or cold something is, not how much water there is.'], tip: 'First ask: what am I measuring - mass, amount of liquid, or temperature? Amount of liquid = mL. Then pick the unit from that group.' },
    { q: 'Ana plans to use kilograms (kg) to measure a paper clip, grams (g) to measure a bag of rice, and degree celsius (&deg;C) to measure temperature. Which evaluation is CORRECT?', options: ['Ana should use milligrams (mg) for the paper clip and kilogram (kg) for the bag of rice.', 'Ana used all units correctly.', 'Ana should use grams (g) for measuring temperature.', 'Ana should use degrees celsius (&deg;C) for measuring the mass of objects.'], correct: 0, explain: 'She swapped them: the light paper clip needs a small unit (mg) and the heavy rice needs <b>kilograms</b>. Her &deg;C for temperature was right.', why: ['', 'Ana did NOT use all units correctly. She used kg for a light paper clip and g for a heavy bag of rice - those two are swapped.', 'Grams measure mass, not temperature. Ana was already right to use degrees Celsius for temperature.', 'Degrees Celsius measure temperature, not mass. Mass uses kg, g or mg.'], tip: 'Check each of Ana\'s choices one at a time: light thing = small unit, heavy thing = kg, hot or cold = degrees Celsius. Then find the choice that fixes only what she got wrong.' },
    { q: 'A scientist measures the amount of a very small powder sample for an experiment. Which unit is the most suitable to use?', options: ['gram (g)', 'kilogram (kg)', 'milliliter (mL)', 'degree celsius (&deg;C)'], correct: 0, explain: 'Powder needs a <b>mass</b> unit. Milligrams were <b>not one of the choices</b>, so the best answer is <b>grams</b> &mdash; kilograms are for heavy things, mL is for liquids and &deg;C is for temperature.', why: ['', 'Kilograms are for heavy things, like a bag of rice. A very small powder sample is far too light for kg.', 'Milliliters measure an amount of liquid. Powder is not a liquid, so it is measured by mass.', 'Degrees Celsius measure temperature, not how much powder there is.'], tip: 'If the best unit (like mg) is not in the choices, pick the closest unit from the right group. Here: mass group, small amount, so grams.' },
    { q: 'Which unit is used to measure the temperature of an object or place?', options: ['degree celsius (&deg;C)', 'grams (g)', 'kilogram (kg)', 'milligram (mg)'], correct: 0, explain: 'Temperature is measured in <b>degrees Celsius (&deg;C)</b>.', why: ['', 'Grams measure mass, the amount of material in a small object. They cannot tell how hot or cold something is.', 'Kilograms measure the mass of heavy things. They cannot tell how hot or cold something is.', 'Milligrams measure the mass of very light things. They cannot tell how hot or cold something is.'], tip: 'Temperature has its own unit group: degrees. Any unit that ends in \'gram\' is for mass, so cross those out.' },
    { q: 'Which situation shows the CORRECT use of a unit of measurement?', options: ['measuring the temperature of water using degree celsius (&deg;C)', 'measuring the mass of a pencil using kilograms (kg)', 'measuring the temperature of a room using grams (g)', 'measuring the mass of a bag of rice using milligrams (mg)'], correct: 0, explain: '&deg;C for temperature is correct. A pencil is too light for kg, grams cannot measure temperature, and rice is too heavy for mg.', why: ['', 'A pencil is light, so kilograms (for heavy things) are too big a unit for it.', 'Grams measure mass. The temperature of a room is measured in degrees Celsius.', 'A bag of rice is heavy, so milligrams (for very light things) are far too small. Rice uses kg.'], tip: 'For each situation, ask two things: is it the right group (mass, liquid, temperature)? Is it the right size (light or heavy)? Only one choice passes both.' },
    { q: 'Which unit is commonly used to measure the mass of a school bag?', options: ['kilogram', 'milligram', 'gram', 'degree Celsius'], correct: 0, explain: 'A school bag is heavy, so use <b>kilograms</b>.', why: ['', 'Milligrams are for very light things, like a paper clip. A school bag is heavy.', 'Grams are for small amounts, like a small powder sample. A school bag is heavy, so kilograms fit better.', 'Degrees Celsius measure temperature, not mass.'], tip: 'Heavy things you would carry with two hands or on your back - a school bag, rice, a watermelon - use kilograms.' },
    { q: 'Ana wants to measure the temperature of warm water. Which unit should she use?', options: ['degree Celsius (&deg;C)', 'gram (g)', 'kilogram (kg)', 'milliliter (mL)'], correct: 0, explain: 'Temperature &rarr; <b>&deg;C</b>.', why: ['', 'Grams measure mass, not how warm the water is.', 'Kilograms measure the mass of heavy things, not how warm the water is.', 'Milliliters would tell how MUCH water there is, not how warm it is. The word \'temperature\' is the clue.'], tip: 'Watch for the trap: the object is water (a liquid), but the question asks about its TEMPERATURE. Always answer what is being measured, not what the object is.' },
    { q: 'Which of these is measured by its VOLUME?', options: ['cooking oil', 'watermelon', 'fish', 'vegetable'], correct: 0, explain: 'Cooking oil is a liquid, so it is measured by <b>volume</b>. The others are measured by mass.', why: ['', 'A watermelon is solid, so it is measured by its mass, not its volume.', 'A fish is solid, so it is measured by its mass, not its volume.', 'A vegetable is solid, so it is measured by its mass, not its volume.'], tip: 'Solid foods are weighed (mass). Liquids like oil, milk and blood are measured by volume. Find the liquid.' },
    { q: 'Which of these is measured by its MASS?', options: ['watermelon', 'milk', 'blood', 'cooking oil'], correct: 0, explain: 'A watermelon is a solid, so it is measured by <b>mass</b>. Milk, blood and cooking oil are measured by volume.', why: ['', 'Milk is a liquid, so it is measured by its volume, not its mass.', 'Blood is a liquid, so it is measured by its volume, not its mass.', 'Cooking oil is a liquid, so it is measured by its volume, not its mass.'], tip: 'When three choices are liquids and one is solid, the solid one is measured by mass. Find the odd one out.' },
    { q: 'How many grams are in 1 kilogram?', options: ['1,000', '100', '10', '500'], correct: 0, explain: '<b>1 kg = 1,000 g</b>.', why: ['', '100 is too small. There are 1,000 grams in 1 kilogram, ten times more than 100.', '10 is much too small. There are 1,000 grams in 1 kilogram.', '500 grams is only half of a kilogram. A whole kilogram is 1,000 grams.'], tip: 'Memory hook: a kilogram is a THOUSAND grams (1 kg = 1,000 g). If a choice is smaller than 1,000, it is only part of a kilogram.' },
    { q: 'What is the standard unit for measuring mass?', options: ['kilogram (kg)', 'gram (g)', 'milligram (mg)', 'liter (L)'], correct: 0, explain: 'The <b>kilogram</b> is the standard unit of mass. The liter is for liquid volume.', why: ['', 'Grams are a mass unit for small amounts, but the standard unit of mass is the kilogram.', 'Milligrams are a mass unit for very light things, but the standard unit of mass is the kilogram.', 'The liter is a unit of liquid volume, not mass.'], tip: 'Remember the two \'standard\' units: kilogram for mass, liter for liquid volume. Do not mix them up.' },
    { q: 'Which balance has three beams that carry the weights?', options: ['triple beam balance', 'double beam balance', 'platform balance', 'spring balance'], correct: 0, explain: '<b>Triple</b> = three beams. A double beam balance has two.', why: ['', 'A double beam balance has TWO beams, not three.', 'A platform balance has a platform where the objects are placed. It is not named for having three beams.', 'The question asks for three beams, and a spring balance is not the one named for three beams. \'Triple\' means three.'], tip: 'Use the number word: double = 2, triple = 3. The name of the balance tells you how many beams it has.' },
    { q: 'What should you do FIRST before weighing an object on a balance?', options: ['Set the needle pointer to zero.', 'Add up the readings.', 'Move the smallest counterweight.', 'Write down the mass.'], correct: 0, explain: 'Always <b>set the pointer to zero</b> first, or every reading will be off.', why: ['', 'Adding up the readings is the LAST step, after the counterweights are moved.', 'The counterweights are moved largest first, not smallest, and only after the pointer is set to zero.', 'You can only write down the mass after you have weighed the object, so this comes at the end.'], tip: 'For \'what do you do FIRST?\' questions, think: which step must happen before anything else can work? A balance must start at zero.' },
    { q: 'True or False: Grams (g) can be used to measure the temperature of a room.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; grams measure <b>mass</b>. Temperature uses <b>&deg;C</b>.', why: ['Grams measure mass, the amount of material. The temperature of a room is measured in degrees Celsius.', ''], tip: 'Check that the unit is from the right group. Any \'gram\' unit belongs to mass, so it can never measure temperature.' },
    { q: 'True or False: A bag of rice is best measured in kilograms (kg).', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; kilograms are for heavy things.', why: ['', 'This statement is correct. A bag of rice is heavy, and kilograms are the unit for heavy things.'], tip: 'Ask: heavy or light? Heavy objects like rice, a school bag or a watermelon go with kilograms.' },
    { q: 'True or False: Milliliters (mL) are used to measure the amount of a liquid.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; like Carla measuring water in a container.', why: ['', 'This statement is correct. Milliliters measure an amount of liquid, like the water in Carla\'s container.'], tip: 'Link mL and L (liters) with liquids. If the thing being measured can be poured, think milliliters.' },
    { q: 'True or False: Degree Celsius (&deg;C) is used to measure the mass of objects.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; &deg;C measures <b>temperature</b>. Mass uses kg, g or mg.', why: ['Degrees Celsius measure temperature (how hot or cold), not mass. Mass uses kg, g or mg.', ''], tip: 'Check that the unit matches the job: degrees go with temperature, grams go with mass. A mismatch means False.' },
    { q: 'True or False: Kilograms are used to measure temperature.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; kilograms measure <b>mass</b>. Temperature uses &deg;C.', why: ['Kilograms measure the mass of heavy things. Temperature is measured in degrees Celsius.', ''], tip: 'Any unit with \'gram\' in it (kg, g, mg) is a mass unit. If a statement uses it for temperature, it is False.' },
    { q: 'True or False: Diego measures the mass of a watermelon using kilograms.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; a watermelon is heavy, so kilograms fit.', why: ['', 'This statement is correct. A watermelon is heavy and solid, so its mass is measured in kilograms.'], tip: 'Two checks: is mass the right thing to measure (solid = yes), and is kg the right size (heavy = yes)? Both pass, so True.' },
    { q: 'Which unit would you use to measure a glass of juice?', options: ['milliliter (mL)', 'kilogram (kg)', 'degree celsius (&deg;C)', 'milligram (mg)'], correct: 0, explain: 'Juice is a liquid, so use <b>milliliters</b>.', why: ['', 'Kilograms measure the mass of heavy solid things. Juice is a liquid, so we measure its amount in mL.', 'Degrees Celsius measure how hot or cold the juice is, not how much juice there is.', 'Milligrams measure the mass of very light things. An amount of liquid uses mL.'], tip: 'Liquids are measured by volume. For a glass of juice, milk or water, reach for milliliters.' }
  ]
});
