StudyKit.lesson({
  id: 'volume',
  icon: '🧪',
  title: 'Volume, Density & Temperature',
  subtitle: 'Liters, displacement, meniscus, density & thermometers',
  cards: [
    { front: 'Volume Units', back: 'Volume is the space matter occupies. It is measured in <b>cubic meters (m&sup3;)</b>, <b>liters (L)</b> and <b>milliliters (mL)</b>. The <b>standard unit for liquid volume is the liter</b>. mL is for <b>small</b> amounts of liquid; L is for <b>larger</b> amounts.' },
    { front: 'Tools for Liquids', back: 'Measure liquid volume with a <b>graduated cylinder</b>, a <b>beaker</b> or a <b>flask</b>.' },
    { front: 'Volume of a Cube', back: '<b>Volume = side &times; side &times; side</b>. Example: 3 cm &times; 3 cm &times; 3 cm = <b>27 cm&sup3;</b>.' },
    { front: 'Volume of a Rectangular Prism', back: '<b>Volume = length &times; width &times; height</b>. Example: 5 cm &times; 3 cm &times; 2 cm = <b>30 cm&sup3;</b>.' },
    { front: 'Water Displacement', back: 'For an <b>irregular solid</b> like a stone. Put water in a graduated cylinder (V1), drop the stone in, read the new level (V2). <b>Volume = V2 &minus; V1</b>. Example: 180 mL &minus; 150 mL = <b>30 mL</b>.' },
    { front: 'Meniscus', back: 'The <b>curved surface</b> of a liquid in a cylinder. Most liquids have a <b>concave</b> meniscus. Read it at the <b>bottom of the curve, at eye level</b>.' },
    { front: 'Density', back: 'The <b>mass per unit of volume</b>. <b>Density = mass &divide; volume</b>, usually in <b>g/cm&sup3;</b>. Example: 45 g &divide; 15 cm&sup3; = <b>3 g/cm&sup3;</b>. Also: mass = density &times; volume, and volume = mass &divide; density.' },
    { front: '1 mL = 1 cm&sup3;', back: 'One milliliter is equal to <b>one cubic centimeter</b>.' },
    { front: 'Temperature', back: 'How <b>hot or cold</b> an object is. It is measured with a <b>thermometer</b>.' },
    { front: 'Three Temperature Scales', back: '<b>Celsius (&deg;C)</b>: used most in the world. Water boils at <b>100 &deg;C</b> and freezes at <b>0 &deg;C</b>. <b>Fahrenheit (&deg;F)</b>: used most in the United States. Water boils at <b>212 &deg;F</b> and freezes at <b>32 &deg;F</b>. <b>Kelvin (K)</b>: used mostly by scientists; its 0 is absolute zero.' }
  ],
  quiz: [
    { q: 'What is the standard unit for measuring liquid volume?', options: ['liter (L)', 'milliliter (mL)', 'gram (g)', 'meter (m)'], correct: 0, explain: 'The <b>liter</b> is the standard unit. mL is also a volume unit, but for small amounts.', why: ['', 'Milliliters ARE a volume unit, but only for small amounts of liquid. The standard unit is the liter.', 'Grams measure mass, the amount of material, not the space a liquid takes up.', 'The lesson\'s volume units are cubic meters (m&sup3;), liters and milliliters. A plain meter (m) is not one of them.'], tip: 'Watch the word \'standard\'. Several units can measure liquid volume, but only one is THE standard: the liter.' },
    { q: 'Which tool is used to measure the volume of a liquid?', options: ['graduated cylinder', 'thermometer', 'triple beam balance', 'ruler'], correct: 0, explain: 'A <b>graduated cylinder</b> (or a beaker or flask) measures liquid volume. A thermometer measures temperature; a balance measures mass.', why: ['', 'A thermometer measures temperature, how hot or cold something is, not how much liquid there is.', 'A triple beam balance measures mass, not the volume of a liquid.', 'A ruler is not one of the liquid tools in this lesson. Liquid volume is measured with a graduated cylinder, a beaker or a flask.'], tip: 'Match tool to job: thermometer = temperature, balance = mass, graduated cylinder / beaker / flask = liquid volume.' },
    { q: 'A cube has sides of 3 cm each. What is its volume?', options: ['27 cm&sup3;', '9 cm&sup3;', '12 cm&sup3;', '6 cm&sup3;'], correct: 0, explain: 'side &times; side &times; side = 3 &times; 3 &times; 3 = <b>27 cm&sup3;</b>.', why: ['', '9 is 3 &times; 3 - that uses only TWO sides. A cube\'s volume needs all three: 3 &times; 3 &times; 3 = 27 cm&sup3;.', '12 is 3 + 3 + 3 + 3, which adds the sides. Volume multiplies them: 3 &times; 3 &times; 3 = 27 cm&sup3;.', '6 is 3 + 3, which adds the sides. Volume multiplies side &times; side &times; side = 27 cm&sup3;.'], tip: 'Volume of a cube = side &times; side &times; side. Say \'times, times\' out loud and count three numbers before you answer.' },
    { q: 'A box is 5 cm long, 3 cm wide, and 2 cm high. What is its volume?', options: ['30 cm&sup3;', '10 cm&sup3;', '15 cm&sup3;', '25 cm&sup3;'], correct: 0, explain: 'length &times; width &times; height = 5 &times; 3 &times; 2 = <b>30 cm&sup3;</b>.', why: ['', '10 is 5 + 3 + 2, which ADDS the sides. Volume multiplies them: 5 &times; 3 &times; 2 = 30 cm&sup3;.', '15 is 5 &times; 3 - the height (2 cm) was left out. 15 &times; 2 = 30 cm&sup3;.', '25 does not come from 5 &times; 3 &times; 2. Work it step by step: 5 &times; 3 = 15, then 15 &times; 2 = 30 cm&sup3;.'], tip: 'Volume of a box = length &times; width &times; height. Multiply two numbers first, then multiply that answer by the third. Check you used all three.' },
    { q: 'A graduated cylinder has 150 mL of water. After a stone is dropped in, the water rises to 180 mL. What is the volume of the stone?', options: ['30 mL', '180 mL', '150 mL', '330 mL'], correct: 0, explain: 'V2 &minus; V1 = 180 &minus; 150 = <b>30 mL</b>.', why: ['', '180 mL is the water AND the stone together (V2). The stone alone is the rise: 180 &minus; 150 = 30 mL.', '150 mL is just the water before the stone went in (V1). The stone is the difference: 180 &minus; 150 = 30 mL.', '330 mL is 180 + 150 - the readings were added. Water displacement SUBTRACTS: 180 &minus; 150 = 30 mL.'], tip: 'Volume by water displacement = V2 &minus; V1 (after minus before). The stone\'s volume is only how much the water went UP.' },
    { q: 'Which method is used to find the volume of an irregular solid, like a stone?', options: ['water displacement method', 'multiplying length &times; width &times; height', 'using a thermometer', 'using a spring balance'], correct: 0, explain: 'A stone has no straight sides, so we use <b>water displacement</b>: V2 &minus; V1.', why: ['', 'Length &times; width &times; height works for a box with straight sides. A stone has no straight sides to measure.', 'A thermometer measures temperature, not the space an object takes up.', 'A spring balance is not a way to find volume in this lesson. For an irregular solid like a stone, the lesson\'s method is water displacement.'], tip: 'Irregular (bumpy) shape = let the water do the measuring. Drop it in and see how much the water rises.' },
    { q: 'How should you read the concave meniscus of water in a graduated cylinder?', options: ['at the bottom of the curve, at eye level', 'at the top of the curve, looking from above', 'at the top edge of the cylinder', 'after tilting the cylinder'], correct: 0, explain: 'Read the <b>bottom of the curve</b>, with your eyes <b>level</b> with the water.', why: ['', 'The top of the curve is the wrong part, and looking from above makes the reading off. Read the BOTTOM of the curve at eye level.', 'The top edge of the cylinder is not where the water is. You read the water\'s curved surface itself, at the bottom of the curve.', 'Tilting the cylinder moves the water and gives a wrong reading. Keep it still and read at eye level.'], tip: 'Two rules for a meniscus: bottom of the curve, and eyes level with the water. Any choice that breaks one of them is wrong.' },
    { q: 'What is the formula for density?', options: ['mass &divide; volume', 'volume &divide; mass', 'mass &times; volume', 'mass + volume'], correct: 0, explain: 'Density = <b>mass &divide; volume</b>.', why: ['', 'Volume &divide; mass is upside down. Density is mass per unit of volume, so mass goes first: mass &divide; volume.', 'Mass &times; volume is not the density formula. Density divides: mass &divide; volume. (It is mass that equals density &times; volume.)', 'Adding mass and volume does not give density. Density = mass &divide; volume.'], tip: 'Memory hook: density is \'mass PER volume\', and \'per\' means divide. Mass on top, volume below.' },
    { q: 'An object has a mass of 45 grams and a volume of 15 cm&sup3;. What is its density?', options: ['3 g/cm&sup3;', '60 g/cm&sup3;', '30 g/cm&sup3;', '675 g/cm&sup3;'], correct: 0, explain: '45 &divide; 15 = <b>3 g/cm&sup3;</b>.', why: ['', '60 is 45 + 15 - the numbers were added. Density divides: 45 &divide; 15 = 3 g/cm&sup3;.', '30 is 45 &minus; 15 - the numbers were subtracted. Density divides: 45 &divide; 15 = 3 g/cm&sup3;.', '675 is 45 &times; 15 - the numbers were multiplied. Density divides: 45 &divide; 15 = 3 g/cm&sup3;.'], tip: 'Write the formula first (density = mass &divide; volume), then put the numbers in. Checking: 3 &times; 15 = 45, so 3 is right.' },
    { q: 'At what temperature does water boil on the Celsius scale?', options: ['100 &deg;C', '0 &deg;C', '32 &deg;C', '212 &deg;C'], correct: 0, explain: 'Water boils at <b>100 &deg;C</b>. 212 is the boiling point in <b>Fahrenheit</b> &mdash; a common trap.', why: ['', '0 &deg;C is where water FREEZES on the Celsius scale, not where it boils.', '32 is the freezing point of water on the Fahrenheit scale (32 &deg;F), not the Celsius boiling point.', '212 is the boiling point on the Fahrenheit scale (212 &deg;F). On the Celsius scale it is 100 &deg;C.'], tip: 'Keep two pairs apart: Celsius = 0 and 100 (freeze, boil); Fahrenheit = 32 and 212. Check which scale the question names.' },
    { q: 'Which temperature scale is used mostly by scientists?', options: ['Kelvin (K)', 'Celsius (&deg;C)', 'Fahrenheit (&deg;F)', 'liter (L)'], correct: 0, explain: '<b>Kelvin</b> is mostly used by scientists. Celsius is used most in the world; Fahrenheit in the United States.', why: ['', 'Celsius is the scale used most in the world, not the one used mostly by scientists.', 'Fahrenheit is the scale used most in the United States, not the one used mostly by scientists.', 'A liter is a unit of liquid volume, not a temperature scale at all.'], tip: 'Match each scale to its users: Celsius = the world, Fahrenheit = the United States, Kelvin = scientists.' },
    { q: 'What tool is used to measure temperature?', options: ['thermometer', 'beaker', 'balance', 'graduated cylinder'], correct: 0, explain: 'A <b>thermometer</b> measures how hot or cold something is.', why: ['', 'A beaker measures liquid volume, not temperature.', 'A balance measures mass, not temperature.', 'A graduated cylinder measures liquid volume, not temperature.'], tip: 'Temperature has only one tool in this lesson: the thermometer. Beakers, cylinders and balances measure volume or mass.' },
    { q: 'True or False: One milliliter (mL) is equal to one cubic centimeter (cm&sup3;).', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; 1 mL = 1 cm&sup3;.', why: ['', 'This statement is correct: 1 mL = 1 cm&sup3;. That is why a stone\'s volume can be written in mL.'], tip: 'Remember the pair: 1 mL = 1 cm&sup3;. It lets you switch between liquid units and cube units.' },
    { q: 'True or False: Water freezes at 32 &deg;C.', options: ['True', 'False'], correct: 1, explain: 'False &mdash; water freezes at <b>0 &deg;C</b>. 32 is the freezing point in <b>&deg;F</b>.', why: ['The number 32 belongs to the Fahrenheit scale (32 &deg;F). On the Celsius scale water freezes at 0 &deg;C.', ''], tip: 'When you see a freezing or boiling number, check the scale letter. 0 and 100 go with &deg;C; 32 and 212 go with &deg;F.' },
    { q: 'True or False: Liters are used to measure larger amounts of liquid.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; liters for larger amounts, milliliters for small amounts.', why: ['', 'This statement is correct. Liters are for larger amounts of liquid, and milliliters are for small amounts.'], tip: 'Think of size: a big bottle of water = liters; a small spoonful of medicine = milliliters.' },
    { q: 'True or False: Temperature is measured in liters (L).', options: ['True', 'False'], correct: 1, explain: 'False &mdash; liters measure <b>volume</b>. Temperature uses &deg;C, &deg;F or K.', why: ['Liters measure liquid volume. Temperature is measured in &deg;C, &deg;F or K with a thermometer.', ''], tip: 'Check that the unit matches the job. Liters go with volume, so they can never measure temperature.' },
    { q: 'True or False: A beaker can be used to measure liquid volume.', options: ['True', 'False'], correct: 0, explain: 'Correct &mdash; so can a graduated cylinder and a flask.', why: ['', 'This statement is correct. A beaker is one of the three liquid tools, with the graduated cylinder and the flask.'], tip: 'Remember the three liquid tools together: graduated cylinder, beaker, flask.' }
  ]
});
