StudyKit.lesson({
  id: 'fungi',
  icon: '🍄',
  title: 'Major Groups of Fungi',
  subtitle: 'The 4 divisions & the discovery of penicillin',
  cards: [
    { front: 'What Are Fungi?', back: 'Organisms that can be <b>unicellular</b> (single-celled) or <b>multicellular</b> &mdash; such as mushrooms or molds.' },
    { front: 'Why Fungi Matter', back: 'They break down dead plants, help the process of <b>decomposition</b>, and are used in making <b>breads</b> and <b>medicines</b> (antibiotics).' },
    { front: 'The 4 Divisions', back: '<b>Chytridiomycota</b> (chytrids) &middot; <b>Zygomycota</b> (bread molds) &middot; <b>Ascomycota</b> (yeasts and sac fungi) &middot; <b>Basidiomycota</b> (club fungi)' },
    { front: 'Chytridiomycota (chytrids)', back: 'Found in diverse habitats: freshwater, soil, and even the <b>digestive system of animals</b>. They have <b>flagellated spores</b>, which means they can swim and move around.' },
    { front: 'Zygomycota (bread molds)', back: 'Commonly found on bread, fruits, and other decaying plant materials. They have a <b>fast growth rate</b> and reproduce using <b>spores</b>.' },
    { front: 'Ascomycota (yeasts and sac fungi)', back: 'Yeast used in baking produces <b>carbon dioxide</b>, which helps bread rise. They are also crucial in the <b>fermentation</b> that makes wine and beer. Sac fungi include edible mushrooms and truffles.' },
    { front: 'Basidiomycota (club fungi)', back: 'Includes <b>mushrooms, toadstools, and shelf fungi</b>. They play important roles in the environment as <b>decomposers</b>.' },
    { front: 'Alexander Fleming (1881&ndash;1955)', back: 'A Scottish physician and microbiologist. In <b>1928</b> he accidentally discovered <b>penicillin</b> from the <i>Penicillium rubens</i> mold &mdash; the beginning of the antibiotic era.' }
  ],
  quiz: [
    { q: 'True or False: Fungi can be either unicellular or multicellular.', options: ['True', 'False'], correct: 0, explain: 'Correct — some fungi are single-celled, like yeast, and others are multicellular, like mushrooms.', why: ['', 'This statement is correct. Some fungi are single-celled (like yeast) and others are multicellular (like mushrooms and molds).'], tip: 'Uni = one cell, multi = many cells. Fungi come in both kinds; bacteria are only single-celled.' },
    { q: 'Which division of fungi is known as the bread molds?', options: ['Zygomycota', 'Ascomycota', 'Basidiomycota', 'Chytridiomycota'], correct: 0, explain: 'Zygomycota are the bread molds, found on bread, fruits, and decaying plant materials.', why: ['', 'Ascomycota are the yeasts and sac fungi, not the bread molds.', 'Basidiomycota are the club fungi - mushrooms, toadstools and shelf fungi.', 'Chytridiomycota are the chytrids, with swimming spores. They are not the bread molds.'], tip: 'Link each division to one picture: Zygomycota = mold on bread, Ascomycota = yeast, Basidiomycota = mushroom, Chytridiomycota = swimming spores.' },
    { q: 'True or False: Chytrids have flagellated spores, which means they can swim and move around.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is what makes chytrids unusual among fungi.', why: ['', 'This statement is correct. Chytrids have flagellated spores, so they can swim and move around.'], tip: 'Chytrids are the swimmers of the fungi world. Flagellated spores = swimming spores.' },
    { q: 'Which division includes the yeasts used in baking?', options: ['Basidiomycota', 'Ascomycota', 'Zygomycota', 'Chytridiomycota'], correct: 1, explain: 'Ascomycota &mdash; the yeasts and sac fungi. Yeast is what makes bread rise.', why: ['Basidiomycota are the club fungi (mushrooms, toadstools, shelf fungi), not the baking yeasts.', '', 'Zygomycota are the bread MOLDS that grow on bread. The yeast that makes bread rise is in Ascomycota.', 'Chytridiomycota are the chytrids with swimming spores, not the baking yeasts.'], tip: 'Do not mix up \'bread mold\' (Zygomycota, grows ON bread) with \'yeast\' (Ascomycota, makes bread RISE).' },
    { q: 'True or False: Yeast produces oxygen, and that is what makes bread rise.', options: ['True', 'False'], correct: 1, explain: 'False — yeast produces <b>carbon dioxide</b>, and that is the gas that helps bread rise.', why: ['The gas is wrong. Yeast produces carbon dioxide, not oxygen, and carbon dioxide is what helps bread rise.', ''], tip: 'Check each named thing in the statement. Yeast + bread = carbon dioxide. If a different gas is named, it is False.' },
    { q: 'Mushrooms, toadstools and shelf fungi belong to which division?', options: ['Basidiomycota', 'Zygomycota', 'Ascomycota', 'Chytridiomycota'], correct: 0, explain: 'Basidiomycota, the club fungi. They are important decomposers.', why: ['', 'Zygomycota are the bread molds found on bread and fruits, not mushrooms and shelf fungi.', 'Ascomycota are the yeasts and sac fungi. The group with mushrooms, toadstools AND shelf fungi together is Basidiomycota.', 'Chytridiomycota are the chytrids with swimming spores, not mushrooms and shelf fungi.'], tip: 'Mushrooms, toadstools and shelf fungi are the club fungi = Basidiomycota. Learn that trio as a set.' },
    { q: 'True or False: Alexander Fleming discovered penicillin in 1928.', options: ['True', 'False'], correct: 0, explain: 'Correct — it was an accidental discovery from the <i>Penicillium rubens</i> mold, and it began the antibiotic era.', why: ['', 'This statement is correct. Fleming discovered penicillin in 1928 from the Penicillium rubens mold.'], tip: 'Remember the three facts together: Fleming, penicillin, 1928.' },
    { q: 'Penicillin was discovered from which mold?', options: ['<i>Penicillium rubens</i>', '<i>Lactobacillus</i>', '<i>Leptospira</i>', '<i>Bacillus cereus</i>'], correct: 0, explain: 'Fleming discovered penicillin from the <i>Penicillium rubens</i> mold in 1928.', why: ['', 'Lactobacillus is a good bacterium in yogurt, not a mold.', 'Leptospira is a bacterium that can cause leptospirosis, not a mold.', 'Bacillus cereus is a bacterium that causes food poisoning, not a mold.'], tip: 'PENICillin came from PENICillium. The names match, and the other choices are all bacteria.' },
    { q: 'True or False: Fungi are only harmful and have no useful role in nature.', options: ['True', 'False'], correct: 1, explain: 'False — fungi break down dead plants, drive decomposition, and are used to make bread and medicines.', why: ['The word \'only\' makes this False. Fungi break down dead plants and are used to make bread and medicines.', ''], tip: 'Think of one good thing fungi do (bread, penicillin, decomposing). If you can, then \'only harmful\' must be False.' },
    { q: 'Which division of fungi is found in freshwater, soil, and even the digestive system of animals?', options: ['Chytridiomycota', 'Zygomycota', 'Ascomycota', 'Basidiomycota'], correct: 0, explain: 'Chytrids (Chytridiomycota) live in those diverse habitats.', why: ['', 'Zygomycota are found on bread, fruits and decaying plant materials.', 'Ascomycota are the yeasts and sac fungi used in baking and fermentation, not the ones described here.', 'Basidiomycota are the club fungi like mushrooms, known as decomposers.'], tip: 'Chytrids have swimming spores, so it makes sense they live in water and wet places. Link \'freshwater\' to chytrids.' }
  ]
});
