StudyKit.lesson({
  id: 'adapt',
  icon: '🌵',
  title: 'Plant Adaptations & Helpful Microbes',
  subtitle: 'Drought, floods, special structures, soap & penicillin',
  cards: [
    { front: 'Hard Conditions', back: 'A <b>lack of rain</b> can make it difficult for some plants to survive.' },
    { front: 'Dry Places', back: 'Plants that often go long periods without rain survive by <b>storing water in their parts</b>.' },
    { front: 'Flooded Places', back: 'Plants in areas that often flood survive by <b>developing roots above the soil</b>.' },
    { front: 'Aerial Roots', back: 'Roots that grow <b>above the ground</b> help <b>support</b> the plant and <b>absorb moisture</b> from the air.' },
    { front: 'Bulb vs Tuber', back: '<b>Bulb</b>: a short underground stem surrounded by <b>thick, fleshy leaves</b> that store food. <b>Tuber</b>: stores food <b>underground</b>.' },
    { front: 'Antibacterial Soap', back: 'Its main purpose is to <b>reduce harmful bacteria</b>, like Mia washing her hands before eating.' },
    { front: 'Helpful Microorganisms', back: 'Alexander Fleming saw a mold stop bacteria from growing and discovered <b>penicillin</b>: some microorganisms can <b>help treat bacterial infections</b>.' }
  ],
  quiz: [
    { q: 'Which environmental condition can be difficult for some plants to survive?', options: ['lack of rain', 'bright sunlight', 'fresh air', 'rich soil'], correct: 0, explain: 'Plants need water, so a <b>lack of rain</b> is hard on them.', why: ['', 'Bright sunlight is not the hard condition in this lesson. The lesson says a lack of rain makes survival difficult.', 'Fresh air is not a hard condition for plants. The lesson\'s hard condition is a lack of rain.', 'Rich soil is not a hard condition for plants. The lesson\'s hard condition is a lack of rain.'], tip: 'Look for the choice that describes something MISSING that plants need. \'Lack of\' is a clue word for a hard condition.' },
    { q: 'A plant grows in an area that often experiences long periods without rain. Which adaptation would help the plant survive?', options: ['storing water in its parts', 'growing taller stems', 'growing wider flowers', 'producing more colorful leaves'], correct: 0, explain: 'With little rain, <b>storing water</b> is what keeps it alive.', why: ['', 'Taller stems do not give the plant water. With little rain, what helps is storing water.', 'Wider flowers do not give the plant water during long dry periods.', 'Colorful leaves do not help the plant get or keep water.'], tip: 'Match the adaptation to the problem. Problem: no water. Solution: store water.' },
    { q: 'A plant grows in an area that is often flooded. Which adaptation would BEST help it survive?', options: ['developing roots above the soil', 'producing smaller flowers', 'growing shorter leaves', 'having thinner stems'], correct: 0, explain: 'Roots above the soil stay out of the flood water.', why: ['', 'Smaller flowers do not help with flood water around the roots.', 'Shorter leaves do not help with flood water around the roots.', 'Thinner stems do not help with flood water around the roots.'], tip: 'Problem: too much water in the soil. Solution: roots that grow above the soil.' },
    { q: 'A plant has roots that grow above the ground and help support the plant while taking in moisture from the air. What can you conclude about the purpose of these roots?', options: ['They absorb moisture and provide support.', 'They store food for the plant.', 'They protect the plant from animals.', 'They help the plant produce flowers.'], correct: 0, explain: 'The question already names both jobs: <b>support</b> and taking in <b>moisture</b>.', why: ['', 'Storing food is what tubers and bulbs do. The question describes support and taking in moisture.', 'Protecting the plant from animals is what thorns do, not these roots.', 'The question does not say these roots make flowers. It says they support the plant and take in moisture.'], tip: 'Read the question again for the answer: when the description already names the jobs (support, moisture), pick the choice that repeats them.' },
    { q: 'A plant has a short underground stem surrounded by thick, fleshy leaves that store food. Which specialized structure is being described?', options: ['bulb', 'tuber', 'thorn', 'rhizome'], correct: 0, explain: 'Thick, fleshy leaves around a short stem &rarr; <b>bulb</b>.', why: ['', 'A tuber stores food underground too, but it is an enlarged modified stem, like a potato - it does not have fleshy leaves around it.', 'A thorn is a sharp defense structure, not an underground food store.', 'A rhizome is an underground stem that grows horizontally. It is not surrounded by fleshy leaves.'], tip: 'The clue \'fleshy leaves around a short stem\' belongs only to the bulb, like an onion.' },
    { q: 'Which specialized plant structure helps store food underground?', options: ['tuber', 'thorn', 'rhizome', 'aerial root'], correct: 0, explain: 'A <b>tuber</b> is an underground food store, like a potato.', why: ['', 'A thorn is a sharp defense structure on the stem, not a food store.', 'A rhizome is an underground stem that grows sideways and sends out roots and shoots. The lesson\'s underground food store, like a potato, is the tuber.', 'Aerial roots grow above the ground, so they cannot store food underground.'], tip: 'Tuber = underground food store (potato). Rhizome = sideways underground stem (ginger). Remember the main job of each.' },
    { q: 'Mia washes her hands with antibacterial soap before eating. What is the main purpose of the antibacterial soap?', options: ['to help reduce harmful bacteria', 'to help increase useful bacteria', 'to help make bacteria grow faster', 'to help make bacteria easier to see'], correct: 0, explain: 'Antibacterial soap <b>reduces harmful bacteria</b>.', why: ['', 'Antibacterial soap does not add useful bacteria. It reduces harmful bacteria.', 'Antibacterial soap does the opposite of making bacteria grow faster - it reduces them.', 'Soap does not make bacteria easier to see. Bacteria are too small to see clearly anyway.'], tip: 'Anti means against. Antibacterial = against bacteria, so it reduces harmful bacteria.' },
    { q: 'Alexander Fleming discovered penicillin after observing that a type of mold stopped bacteria from growing. What does this discovery show about some microorganisms?', options: ['Some microorganisms can help treat bacterial infections.', 'Some microorganisms can cause serious human diseases.', 'Some microorganisms can grow on different types of food.', 'Some microorganisms can survive in different environments.'], correct: 0, explain: 'The mold <b>stopped bacteria</b>, so it can help <b>treat infections</b>. The other choices are true facts, but not what this discovery shows.', why: ['', 'Some microorganisms do cause diseases, but Fleming\'s mold STOPPED bacteria. That shows helping, not harming.', 'Growing on food is true of molds, but the discovery was about the mold stopping bacteria.', 'Surviving in different places is not what Fleming saw. He saw a mold stop bacteria from growing.'], tip: 'When several choices are true facts, pick the one that matches THIS story. Mold stopped bacteria = can help treat infections.' },
    { q: 'What makes bacteria different from many living things we can see?', options: ['They are too small to see clearly', 'They are too large to move quickly.', 'They are too colorful to see clearly.', 'They are too strong to study easily.'], correct: 0, explain: 'Bacteria are <b>too small</b> to see clearly without a microscope.', why: ['', 'Bacteria are not large. They are tiny, single-celled organisms.', 'Color is not the reason. Bacteria are hard to see because they are too small.', 'Strength is not the reason. Bacteria are hard to see because they are too small.'], tip: 'The question hints at the answer: \'things we can see\'. What stops us seeing bacteria? Their tiny size.' },
    { q: 'Why are fungi and bacteria classified as microorganisms?', options: ['They are very small and usually require a microscope to observe.', 'They are always harmful.', 'They can only live in water.', 'They can be seen easily without tools.'], correct: 0, explain: 'Their <b>small size</b> is what makes them microorganisms. They are not always harmful &mdash; penicillin came from a mold.', why: ['', 'They are not always harmful. Lactobacillus helps us, and penicillin came from a mold.', 'They do not live only in water. Bacteria are all around us, and mold grows on bread and fruit.', 'This is the opposite. Microorganisms usually need a microscope because they are too small to see easily.'], tip: 'Microorganism is about SIZE, not about being harmful or where it lives. Look for \'very small\' and \'microscope\'.' },
    { q: 'True or False: Antibacterial soap helps make bacteria grow faster.', options: ['True', 'False'], correct: 1, explain: 'False — it helps <b>reduce harmful bacteria</b>.', why: ['Antibacterial soap does the opposite: it helps REDUCE harmful bacteria.', ''], tip: 'Anti = against. Anything \'anti-bacterial\' works against bacteria, never helps them grow.' },
    { q: 'True or False: Aerial roots help support a plant and absorb moisture from the air.', options: ['True', 'False'], correct: 0, explain: 'Correct — both jobs at once.', why: ['', 'This statement is correct. Aerial roots do both jobs: they support the plant and take in moisture from the air.'], tip: 'Aerial roots have two jobs: support and moisture. If a statement names both, it is True.' }
  ]
});
