StudyKit.lesson({
  id: 'plot',
  icon: '⛰️',
  title: 'Parts of the Plot',
  subtitle: 'Exposition to resolution',
  cards: [
    { front: 'The Plot Mountain', back: '<b>Exposition</b> &rarr; <b>Rising Action</b> &rarr; <b>Climax</b> &rarr; <b>Falling Action</b> &rarr; <b>Resolution</b>.<br>Climb up, reach the top, walk back down.' },
    { front: 'Exposition', back: 'The <b>beginning</b>. It <b>introduces the characters and setting</b>.' },
    { front: 'Rising Action', back: 'The <b>problem</b> appears and events <b>build up</b>, getting more exciting.' },
    { front: 'Climax', back: 'The <b>top of the mountain</b> &mdash; the most exciting part, the turning point.' },
    { front: 'Falling Action', back: 'Events <b>after the climax</b> that <b>lead to the ending</b>.' },
    { front: 'Resolution', back: 'The <b>ending</b> of the story &mdash; everything is wrapped up. (The conflict is <i>being solved</i> in the falling action, just before it.)' },
    { front: 'Two From Your Test', back: '<b>Exposition</b> = introduces characters and setting (start).<br><b>Falling Action</b> = after the climax, leads to the ending.<br>Both were on your summative test.' },
    { front: 'Your Teacher’s Slides', back: '<b>Rising action</b> introduces the <b>conflict or problem</b>.<br><b>Climax</b> is the most exciting part.<br><b>Falling action</b> is where the conflict is <b>being solved</b>.<br><b>Resolution</b> is the <b>ending</b> of the story.' }
  ],
  quiz: [
    { q: 'What part of the plot introduces the characters and setting?', options: ['Exposition', 'Climax', 'Rising Action', 'Falling Action'], correct: 0, explain: 'The <b>exposition</b> is the beginning &mdash; it introduces who and where.', why: ['', 'The climax is the most exciting part, the top of the mountain — not the start where we meet the characters.', 'Rising action is where the problem appears and events build up. The characters were already introduced before it.', 'Falling action comes after the climax and leads to the ending, so it is near the end, not the beginning.'], tip: 'Think of the plot mountain. Meeting the characters and the place happens at the <b>very start</b> — the exposition.' },
    { q: 'Which part of the plot shows events after the climax and leads to the ending?', options: ['Falling Action', 'Exposition', 'Climax', 'Rising Action'], correct: 0, explain: 'The <b>falling action</b> comes down the mountain after the climax.', why: ['', 'Exposition is the beginning that introduces characters and setting — it comes before the climax, not after.', 'The climax is the top itself. The question asks what comes <b>after</b> it.', 'Rising action comes <b>before</b> the climax, climbing up to it.'], tip: 'Picture the mountain: going up is rising action, the top is the climax, and coming <b>down</b> after the top is falling action.' },
    { q: 'Which part of the plot is the most exciting part, the turning point?', options: ['Climax', 'Resolution', 'Exposition', 'Falling Action'], correct: 0, explain: 'The <b>climax</b> is the top of the plot mountain.', why: ['', 'Resolution is the ending, where everything is wrapped up. It is calm, not the most exciting part.', 'Exposition is the beginning that introduces characters and setting. The excitement has not started yet.', 'Falling action comes after the most exciting part, when things start to calm down.'], tip: 'The key words are <b>most exciting</b> and <b>turning point</b>. That is always the top of the mountain — the climax.' },
    { q: 'In which part of the plot does the problem appear and the events build up?', options: ['Rising Action', 'Resolution', 'Falling Action', 'Exposition'], correct: 0, explain: 'The <b>rising action</b> climbs toward the climax as the problem grows.', why: ['', 'Resolution is the ending, where the problem is already over.', 'Falling action comes after the climax, when the conflict is being solved — not when it first appears.', 'Exposition only introduces the characters and setting. The problem shows up after it.'], tip: 'The words <b>build up</b> sound like climbing. Climbing up the mountain is the rising action.' },
    { q: 'True or False: The exposition comes at the beginning of the story.', options: ['True', 'False'], correct: 0, explain: 'Correct — it opens the story by introducing the characters and setting.', why: ['', 'The exposition really is the beginning — it opens the story by introducing the characters and setting. So the statement is true.'], tip: 'Link the two: exposition = <b>start</b> of the mountain.' },
    { q: 'True or False: The falling action happens before the climax.', options: ['True', 'False'], correct: 1, explain: 'False — the falling action comes <b>after</b> the climax. The rising action is the part before it.', why: ['Falling action comes <b>after</b> the climax, not before. The word <b>before</b> is what makes this false.', ''], tip: 'In True or False, check the small time words like <b>before</b> and <b>after</b>. Picture the mountain: you can only come down after you reach the top.' },
    { q: 'True or False: The climax is the turning point, the most exciting part of the story.', options: ['True', 'False'], correct: 0, explain: 'Correct — it is the top of the plot mountain.', why: ['', 'The climax really is the turning point and the most exciting part — the top of the plot mountain. So the statement is true.'], tip: 'Turning point, most exciting, top of the mountain — all three mean climax.' },
    { q: 'True or False: The resolution introduces the characters and the setting.', options: ['True', 'False'], correct: 1, explain: 'False — that is the <b>exposition</b>. The resolution is the ending of the story.', why: ['Introducing characters and setting is the job of the <b>exposition</b> at the beginning. The resolution is the ending, so the statement is false.', ''], tip: 'Check if the statement swapped two parts. Beginning = exposition, ending = resolution.' },
    { q: 'Which shows the parts of the plot in the correct order?', options: ['Exposition, Rising Action, Climax, Falling Action, Resolution', 'Exposition, Climax, Rising Action, Falling Action, Resolution', 'Rising Action, Exposition, Climax, Resolution, Falling Action', 'Climax, Exposition, Falling Action, Rising Action, Resolution'], correct: 0, explain: 'Start (exposition), climb (rising action), top (climax), come down (falling action), end (resolution).', why: ['', 'This puts the climax before the rising action. You have to climb up before you reach the top.', 'This starts with rising action and puts the resolution before the falling action. The story must begin with the exposition and end with the resolution.', 'This starts with the climax. A story cannot reach its most exciting part before it even begins.'], tip: 'Say the mountain out loud: <b>start, climb, top, come down, end</b>. Check each option against that order.' },
    { q: '&ldquo;Mia discovered that her puppy had escaped, so she asked her neighbors to help her search.&rdquo; Which part of the plot is this?', options: ['Rising Action', 'Exposition', 'Resolution', 'Falling Action'], correct: 0, explain: 'The problem has appeared and the search is building up &mdash; <b>rising action</b>.', why: ['', 'The exposition only introduces the characters and setting. Here a problem has already happened — the puppy escaped.', 'The resolution is the ending. The puppy has not been found yet, so the story is not over.', 'Falling action is when the conflict is being solved after the climax. Mia is only starting to search, so things are still building up.'], tip: 'Ask: has the problem just appeared? If the trouble is new and the action is growing, it is rising action.' },
    { q: 'In which part of the plot is the conflict <b>being solved</b>?', options: ['Falling Action', 'Exposition', 'Rising Action', 'Climax'], correct: 0, explain: 'Your teacher’s slide: the <b>falling action</b> is where the conflict is being solved. The resolution comes after it &mdash; the ending.', why: ['', 'Exposition is the beginning, where there is no conflict yet to solve.', 'Rising action introduces the conflict or problem — it does not solve it.', 'The climax is the most exciting part, the turning point. The solving comes right after it.'], tip: 'Your teacher’s slide says it exactly: the conflict is <b>being solved</b> in the falling action. The resolution is simply the ending.' }
  ]
});
