StudyKit.lesson({
  id: 'traits',
  icon: '🧑‍🤝‍🧑',
  title: 'Character Traits',
  subtitle: 'Trait or feeling? Prove it with because',
  cards: [
    { front: 'Character Trait', back: 'A word that tells what a character is <b>usually like</b> &mdash; their personality.<br><i>helpful, patient, organized, kind, careless, brave</i>' },
    { front: 'Feeling (NOT a trait)', back: 'How a character feels <b>at one moment</b>. It changes quickly.<br><i>overwhelmed, tired, happy, scared, excited</i>' },
    { front: 'The All-the-Time Test', back: 'Ask: &ldquo;Is this person like this <b>all the time</b>, or just <b>right now</b>?&rdquo;<br>All the time &rarr; trait. Right now &rarr; feeling.' },
    { front: 'Your Test: &ldquo;Overwhelmed&rdquo;', back: 'On your summative test, &ldquo;Liam is <b>overwhelmed</b>&rdquo; was marked <b>not a trait</b>. Overwhelmed is a <b>feeling</b>. Choose a personality word instead.' },
    { front: 'Inferring a Trait', back: 'Look at what the character <b>does</b>, <b>says</b>, and <b>how they treat others</b>. Then name the personality those actions show.' },
    { front: 'The Answer Format', back: '&ldquo;<b>___ is ___ because ___.</b>&rdquo;<br>Give the <b>trait</b>, then the <b>evidence</b> from the text. The &ldquo;because&rdquo; part earns points too.' },
    { front: 'Sofia', back: '<b>Organized</b> &mdash; organized her materials before class began.<br><b>Helpful</b> &mdash; offered to help Liam and explained step by step.<br><b>Patient</b> &mdash; stayed patient even when Liam made mistakes.' },
    { front: 'Liam', back: 'Clues: rushed in as the bell rang, dropped his bag loudly, sighed whenever something seemed difficult.<br>Traits you could infer: <b>careless</b>, or <b>easily discouraged</b>.' },
    { front: 'Feeling or Trait? Game', back: '<b>angry</b> &rarr; feeling<br><b>kind</b> &rarr; trait<br><b>nervous</b> &rarr; feeling<br><b>honest</b> &rarr; trait' },
    { front: 'Clues to Look For', back: '<b>Actions</b> &mdash; what the character does.<br><b>Dialogue</b> &mdash; what the character says, and how.<br><b>Thoughts/Feelings</b> &mdash; what the character thinks.<br><b>Physical descriptions</b> &mdash; how the character looks.' },
    { front: 'Jordan and the Puppy', back: 'Folded the blanket <b>carefully</b>, <b>whispered</b> “It’s okay, you’re safe now,” <b>stayed beside</b> it.<br>Model sentence: <b>Jordan is kind and compassionate because he carefully helped the puppy and spoke to it gently.</b>' }
  ],
  quiz: [
    { q: 'Which word is a <b>character trait</b>?', options: ['helpful', 'tired', 'overwhelmed', 'scared'], correct: 0, explain: 'Helpful describes what someone is <b>usually like</b>. The other three are feelings.', why: ['', 'Tired is how someone feels right now. It changes after a rest, so it is a feeling.', 'Overwhelmed is a feeling — it was marked not a trait on your test.', 'Scared is a feeling at one moment, not what someone is usually like.'], tip: 'Use the All-the-Time Test: is the person like this <b>all the time</b> (trait) or just <b>right now</b> (feeling)?' },
    { q: 'Which word is a <b>feeling</b>, not a trait?', options: ['overwhelmed', 'organized', 'patient', 'helpful'], correct: 0, explain: 'Overwhelmed is how someone feels <b>right now</b> &mdash; exactly the word marked &ldquo;not a trait&rdquo; on your test.', why: ['', 'Organized describes what someone is usually like — a trait, like Sofia.', 'Patient describes someone’s personality — a trait.', 'Helpful describes what someone is usually like — a trait.'], tip: 'This question asks for the <b>feeling</b>. Find the word that could change in a few minutes.' },
    { q: 'True or False: &ldquo;Overwhelmed&rdquo; is a character trait.', options: ['True', 'False'], correct: 1, explain: 'False — overwhelmed is a <b>feeling</b>. It changes from moment to moment.', why: ['Overwhelmed is a <b>feeling</b>. It changes from moment to moment, so it is not a trait. Your summative test marked it not a trait.', ''], tip: 'Feelings can change quickly (overwhelmed, tired, scared). Traits stay (kind, patient, organized).' },
    { q: 'True or False: A character trait tells what a character is usually like.', options: ['True', 'False'], correct: 0, explain: 'Correct — it is their personality, not a passing mood.', why: ['', 'This is the definition of a trait — what a character is usually like, their personality. So the statement is true.'], tip: 'Key word: <b>usually</b>. Usually = trait. Right now = feeling.' },
    { passage: 'Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor. He quickly started his work but sighed whenever something seemed difficult.<br><br>Across the room, Sofia had already organized her materials before class began. When she noticed Liam struggling, she quietly offered to help and explained the instructions step by step. She listened carefully and stayed patient, even when Liam made mistakes.', q: '&ldquo;Sofia had already organized her materials before class began.&rdquo; Which trait does this show?', options: ['organized', 'lazy', 'careless', 'nervous'], correct: 0, explain: 'Getting everything ready before class shows she is <b>organized</b>.', why: ['', 'Lazy is someone who does not get things done. Sofia got everything ready early — the opposite.', 'Careless is someone who is not careful. Sofia prepared her materials before class.', 'Nervous is a feeling, and nothing in the sentence shows Sofia was worried.'], tip: 'Look at the action: getting things ready <b>before</b> class. Ask: what kind of person does that?' },
    { passage: 'Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor. He quickly started his work but sighed whenever something seemed difficult.<br><br>Across the room, Sofia had already organized her materials before class began. When she noticed Liam struggling, she quietly offered to help and explained the instructions step by step. She listened carefully and stayed patient, even when Liam made mistakes.', q: '&ldquo;She stayed patient, even when Liam made mistakes.&rdquo; This shows Sofia is&hellip;', options: ['patient', 'impatient', 'tired', 'bossy'], correct: 0, explain: 'The text tells you directly: she <b>stayed patient</b>.', why: ['', 'Impatient is the opposite. The passage says she <b>stayed patient</b>.', 'Tired is a feeling, and the passage does not say Sofia was tired.', 'Bossy is someone who orders others around. Sofia quietly offered help.'], tip: 'Sometimes the answer is written right in the text. Look back at the passage: “she … stayed <b>patient</b>.”' },
    { passage: 'Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor. He quickly started his work but sighed whenever something seemed difficult.<br><br>Across the room, Sofia had already organized her materials before class began. When she noticed Liam struggling, she quietly offered to help and explained the instructions step by step. She listened carefully and stayed patient, even when Liam made mistakes.', q: 'Which is the <b>best</b> answer in the &ldquo;___ is ___ because ___&rdquo; format?', options: ['Sofia is helpful because she offered to help Liam and explained the steps.', 'Sofia is nervous because she organized all of her materials before class.', 'Sofia is careless because she explained the instructions to Liam step by step.', 'Sofia is happy because the bell rang and the class began that morning.'], correct: 0, explain: 'A real trait (<b>helpful</b>) with evidence from the text that proves it.', why: ['', 'Nervous is a feeling, not a trait, and organizing materials does not prove someone is nervous.', 'The evidence (explaining step by step) shows Sofia is helpful, not careless. The trait and the because part do not match.', 'Happy is a feeling, and the bell ringing is not evidence about Sofia at all.'], tip: 'Check both halves: is the first word a real <b>trait</b>, and does the <b>because</b> part actually prove it?' },
    { passage: 'Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor. He quickly started his work but sighed whenever something seemed difficult.<br><br>Across the room, Sofia had already organized her materials before class began. When she noticed Liam struggling, she quietly offered to help and explained the instructions step by step. She listened carefully and stayed patient, even when Liam made mistakes.', q: 'True or False: &ldquo;He sighed whenever something seemed difficult&rdquo; is a clue that can help you infer one of Liam&rsquo;s traits.', options: ['True', 'False'], correct: 0, explain: 'Correct — sighing every time work gets hard suggests he is <b>easily discouraged</b>.', why: ['', 'Sighing <b>whenever</b> work gets hard is something Liam does again and again, so it is a clue to his trait (easily discouraged). The statement is true.'], tip: 'Actions a character repeats (words like <b>whenever</b>) are good clues for traits.' },
    { q: 'True or False: A good trait answer only needs the trait word; the &ldquo;because&rdquo; part is optional.', options: ['True', 'False'], correct: 1, explain: 'False — the <b>because</b> part is the evidence, and it is worth points on your test.', why: ['The because part is the <b>evidence</b> from the text, and it earns points on your test. It is not optional, so the statement is false.', ''], tip: 'Remember the format: <b>trait + because + evidence</b>. Every good trait answer has all three.' },
    { passage: 'Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor. He quickly started his work but sighed whenever something seemed difficult.<br><br>Across the room, Sofia had already organized her materials before class began. When she noticed Liam struggling, she quietly offered to help and explained the instructions step by step. She listened carefully and stayed patient, even when Liam made mistakes.', q: '&ldquo;Liam rushed into the classroom just as the bell rang, dropping his bag loudly on the floor.&rdquo; Which trait fits Liam best?', options: ['careless', 'organized', 'patient', 'calm'], correct: 0, explain: 'Rushing in at the last second and dropping his bag loudly shows he is <b>careless</b>. Organized and patient describe Sofia, and nothing Liam does is calm.', why: ['', 'Organized describes Sofia, who got her materials ready before class. Liam rushed in at the last second.', 'Patient describes Sofia. Liam sighed whenever work got hard, which is not patient.', 'Calm does not fit — Liam rushed in and dropped his bag loudly.'], tip: 'Make sure the trait matches the <b>right character</b>. Look back at what Liam did, not what Sofia did.' },
    { q: 'Which word is a <b>character trait</b>, not a feeling?', options: ['honest', 'angry', 'nervous', 'tired'], correct: 0, explain: 'In the “Feeling or Trait?” game, <b>honest</b> and <b>kind</b> are traits. Angry and nervous are feelings.', why: ['', 'Angry is a feeling — in the game, angry was sorted as a feeling.', 'Nervous is a feeling — in the game, nervous was sorted as a feeling.', 'Tired is a feeling. It goes away after rest.'], tip: 'Try the All-the-Time Test on each word. Honest is who you are; angry, nervous and tired are how you feel for a while.' },
    { passage: '“Jordan carefully folded the blanket around the shivering puppy and whispered, ‘It’s okay, you’re safe now.’ He gently stroked its fur and stayed beside it.”', q: 'Which traits does this passage show?', options: ['kind and compassionate', 'careless and rude', 'lazy and bored', 'bossy and selfish'], correct: 0, explain: 'He helped the puppy <b>carefully</b> and spoke <b>gently</b>, so Jordan is <b>kind and compassionate</b>.', why: ['', 'Jordan folded the blanket <b>carefully</b> and spoke gently — the opposite of careless and rude.', 'Jordan stayed beside the puppy and cared for it. Nothing shows he was lazy or bored.', 'Jordan helped the puppy, not himself. Nothing shows he was bossy or selfish.'], tip: 'Look at how the character treats others: “gently stroked,” “It’s okay, you’re safe now.” Pick traits that match those actions.' },
    { passage: '“Jordan carefully folded the blanket around the shivering puppy and whispered, ‘It’s okay, you’re safe now.’ He gently stroked its fur and stayed beside it.”', q: 'Which clue is <b>dialogue</b>?', options: ['He whispered, “It’s okay, you’re safe now.”', 'He carefully folded the blanket around the puppy.', 'He gently stroked its fur with his hand.', 'He stayed beside the puppy the whole time.'], correct: 0, explain: 'Dialogue is <b>what the character says</b>. The others are actions.', why: ['', 'Folding the blanket is an <b>action</b> — something Jordan does, not says.', 'Stroking the fur is an <b>action</b>, not something he says.', 'Staying beside the puppy is an <b>action</b>, not dialogue.'], tip: 'Dialogue = what the character <b>says</b>. Look for quotation marks and words like whispered or said.' }
  ]
});
