StudyKit.lesson({
  id: 'sound',
  icon: '🎵',
  title: 'Sound Devices',
  subtitle: 'Onomatopoeia, alliteration, assonance & consonance',
  cards: [
    { front: 'Sound Devices', back: 'Ways writers <b>repeat sounds</b> to make lines fun to read aloud and easy to remember.' },
    { front: 'Alliteration', back: 'Repeats the <b>beginning consonant sounds</b> of words.<br>&ldquo;<b>S</b>illy <b>s</b>nakes <b>s</b>lide <b>s</b>ilently.&rdquo;' },
    { front: 'Assonance', back: 'Repeats <b>vowel sounds</b> in nearby words.<br>&ldquo;The l<b>i</b>ght of the f<b>i</b>re is br<b>i</b>ght.&rdquo; (the long <i>i</i> sound)' },
    { front: 'Consonance', back: 'Repeats <b>consonant sounds</b> inside or at the end of words.<br>&ldquo;The bla<b>ck</b> sa<b>ck</b> stu<b>ck</b> in the ba<b>ck</b>.&rdquo; (the <i>k</i> sound)' },
    { front: 'How to Tell Them Apart', back: 'Same sound at the <b>start</b> of words &rarr; <b>alliteration</b>.<br>Same <b>vowel</b> sound &rarr; <b>assonance</b>.<br>Same <b>consonant</b> sound in the middle or end &rarr; <b>consonance</b>.' },
    { front: 'Pick the MOST Exact Answer', back: '&ldquo;It repeats sounds&rdquo; is true of all three. For alliteration the best answer is the exact one: <b>it repeats beginning consonant sounds</b>.' },
    { front: 'Onomatopoeia', back: 'Words that <b>imitate the sounds</b> they name.<br>“The bees <b>buzzed</b> around the garden.” “The clock went <b>tick-tock</b>.” “The thunder <b>boomed</b> across the sky.”' },
    { front: 'Why Use Sound Devices?', back: 'They use the sounds of words to create <b>rhythm, mood, emphasis, and meaning</b>, making writing more engaging, memorable, and expressive.' },
    { front: 'More From Class', back: 'Alliteration: “<b>S</b>ally <b>s</b>old <b>s</b>eashells by the <b>s</b>eashore.”<br>Assonance: “The r<b>ai</b>n in Sp<b>ai</b>n falls m<b>ai</b>nly on the pl<b>ai</b>n.”<br>Consonance: repeats the sound <b>inside or at the end</b> of words, not only at the start.' },
    { front: 'Sound and Mood', back: '“Sunlight dances on my face&hellip;” &rarr; <b>joyful and cheerful</b>.<br>“Raindrops whisper on the ground, soft and slow, a lonely sound&hellip;” &rarr; <b>sad and lonely</b>.' }
  ],
  quiz: [
    { q: 'How does alliteration make the sentence &ldquo;<i>Silly snakes slide silently</i>&rdquo; more interesting?', options: ['It repeats beginning consonant sounds.', 'It repeats sounds.', 'It tells a story.', 'It adds meaning.'], correct: 0, explain: '&ldquo;It repeats sounds&rdquo; is not wrong, but it is not the <b>best</b> answer. Alliteration repeats the <b>beginning consonant</b> sound: s-s-s-s.', why: ['', '“It repeats sounds” is true, but it is true of assonance and consonance too. The best answer names the exact sound: beginning consonants.', 'The sentence does not tell a story. It is just four words with the same starting sound.', '“Adds meaning” is too general. The question is about how alliteration works — repeating beginning consonant sounds.'], tip: 'When two answers are true, pick the <b>most exact</b> one. Alliteration = beginning consonant sounds.' },
    { q: 'Why is &ldquo;<i>The light of the fire is bright</i>&rdquo; an example of assonance?', options: ['because it repeats vowel sounds in nearby words', 'because it repeats the same letters in every word', 'because it tells a short story about a fire', 'because it rhymes at the end of every word'], correct: 0, explain: 'light, fire, bright all share the long <b>i vowel</b> sound &mdash; that is assonance.', why: ['', 'The words do not have the same letters. What matches is the long <b>i</b> vowel sound.', 'Assonance is about sounds, not about telling a story.', 'Not every word rhymes. Light, fire and bright share a vowel sound — that is assonance.'], tip: 'Assonance = <b>vowel</b> sounds (a, e, i, o, u). Say the words out loud and listen for the same vowel.' },
    { q: 'Which of the following sentences uses <b>consonance</b> correctly?', options: ['The black sack stuck in the back.', 'The dog barked at me.', 'The doorbell rang very loudly today.', 'My friend waved hello.'], correct: 0, explain: 'black, sack, stuck, back all repeat the <b>k</b> consonant sound at the end.', why: ['', 'There is no consonant sound repeated in the words here.', 'No consonant sound repeats in the middle or at the end of these words.', 'No consonant sound repeats in these words.'], tip: 'Say each sentence out loud and listen for the same consonant sound in the middle or end of words, like the <b>k</b> in black, sack, stuck, back.' },
    { q: 'True or False: Alliteration repeats the vowel sounds in the middle of words.', options: ['True', 'False'], correct: 1, explain: 'False — that describes <b>assonance</b>. Alliteration repeats the <b>beginning consonant</b> sounds.', why: ['Repeating vowel sounds is <b>assonance</b>. Alliteration repeats the <b>beginning consonant</b> sounds, so the statement is false.', ''], tip: 'Check if the statement swapped two sound devices. Beginning sound = alliteration; vowel sound = assonance.' },
    { q: 'True or False: &ldquo;Big brown bears bounce&rdquo; is an example of alliteration.', options: ['True', 'False'], correct: 0, explain: 'Correct — every word begins with the same <b>b</b> sound.', why: ['', 'Every word begins with the same <b>b</b> sound. That is alliteration, so the statement is true.'], tip: 'Look at the first letter of each word. If they all start with the same sound, it is alliteration.' },
    { q: 'True or False: Assonance is the repetition of vowel sounds in nearby words.', options: ['True', 'False'], correct: 0, explain: 'Correct — like the long <i>i</i> in &ldquo;The light of the fire is bright.&rdquo;', why: ['', 'That is the definition of assonance — like the long i in “The light of the fire is bright.” So the statement is true.'], tip: 'Memory hook: <b>A</b>ssonance — <b>a</b> is a vowel. Assonance repeats vowel sounds.' },
    { q: '&ldquo;<i>Peter picked pink peppers.</i>&rdquo; This is an example of&hellip;', options: ['Alliteration', 'Assonance', 'Personification', 'Metaphor'], correct: 0, explain: 'Every word starts with the <b>p</b> sound &mdash; alliteration.', why: ['', 'Assonance repeats vowel sounds. Here the repeated sound is the <b>p</b> at the start — a consonant.', 'Personification gives human actions to non-human things. Peter is a person.', 'A metaphor says one thing is another. This sentence does not compare anything.'], tip: 'Every word starts with <b>p</b>. Same starting sound = alliteration.' },
    { q: '&ldquo;<i>Go slow over the road.</i>&rdquo; The long <i>o</i> sound repeats. This is an example of&hellip;', options: ['Assonance', 'Alliteration', 'Metaphor', 'Simile'], correct: 0, explain: 'A repeated <b>vowel</b> sound (go, slow, over, road) is assonance.', why: ['', 'Alliteration repeats beginning consonant sounds. These words start with different letters but share the long <b>o</b> vowel sound.', 'A metaphor says one thing is another. Nothing is being compared here.', 'A simile compares using like or as. There is no comparison here.'], tip: 'The question tells you the clue: the long <b>o</b> sound repeats. A repeated vowel sound = assonance.' },
    { q: 'True or False: Consonance is the repetition of vowel sounds in nearby words.', options: ['True', 'False'], correct: 1, explain: 'False — that is <b>assonance</b>. Consonance repeats <b>consonant</b> sounds, like the <b>k</b> in &ldquo;The black sack stuck in the back.&rdquo;', why: ['Repeating vowel sounds is <b>assonance</b>. Consonance repeats <b>consonant</b> sounds, like the k in “black sack.” So the statement is false.', ''], tip: 'Memory hook: <b>consonance</b> starts like <b>consonant</b>. It repeats consonant sounds.' },
    { q: 'Which sound is repeated in &ldquo;<i>Silly snakes slide silently</i>&rdquo;?', options: ['the s sound at the start of each word', 'the long i sound in each word', 'the k sound at the end of each word', 'the t sound in the middle of each word'], correct: 0, explain: 'Each word begins with <b>s</b> &mdash; that repeated beginning sound is what makes it alliteration.', why: ['', 'Silly, snakes, slide and silently do not all share a long i sound. What they share is the <b>s</b> at the start.', 'These words do not end with a k sound.', 'The t sound is not in every word. The repeated sound is the s at the beginning.'], tip: 'Look at the first letter of every word. When they all match, that beginning sound is the answer.' },
    { q: '“<i>The thunder boomed across the sky.</i>” Which sound device does <b>boomed</b> show?', options: ['Onomatopoeia', 'Assonance', 'Alliteration', 'Consonance'], correct: 0, explain: '<b>Boomed</b> imitates the sound thunder makes &mdash; onomatopoeia.', why: ['', 'Assonance repeats vowel sounds in nearby words. The question is about one word, <b>boomed</b>, that sounds like thunder.', 'Alliteration repeats beginning consonant sounds across several words. The question is about one sound word.', 'Consonance repeats consonant sounds in the middle or end of words. Boomed is special because it imitates a sound.'], tip: 'If a word sounds like the noise it names (buzz, tick-tock, boom), it is onomatopoeia.' },
    { q: 'True or False: Onomatopoeia words imitate the sounds they describe, like <i>buzz</i> and <i>tick-tock</i>.', options: ['True', 'False'], correct: 0, explain: 'Correct — they help readers <b>hear</b> what is happening.', why: ['', 'Buzz and tick-tock really do imitate the sounds they name. That is onomatopoeia, so the statement is true.'], tip: 'Say the word out loud. If it sounds like the noise itself, it is onomatopoeia.' },
    { q: '“<i>Raindrops whisper on the ground, / Soft and slow, a lonely sound.</i>” What mood do these lines create?', options: ['sad and lonely', 'joyful and cheerful', 'angry and loud', 'silly and funny'], correct: 0, explain: 'Words like <b>lonely</b>, <b>soft</b> and <b>slow</b> create a quiet, <b>sad and lonely</b> mood.', why: ['', 'Joyful and cheerful fits lines like “Sunlight dances on my face.” These lines use the words <b>lonely</b>, <b>soft</b> and <b>slow</b>.', 'Angry and loud does not fit — the rain is <b>soft</b> and <b>whispers</b>.', 'Nothing in these lines is funny. The word <b>lonely</b> shows the mood.'], tip: 'To find the mood, circle the feeling words in the lines (lonely, soft, slow) and ask how they make you feel.' }
  ]
});
