StudyKit.lesson({
  id: 'summary',
  icon: '📝',
  title: 'Summarizing a Story',
  subtitle: 'Important events vs minor details',
  cards: [
    { front: 'What Is a Summary?', back: 'A summary tells the <b>most important parts</b> of a story in a <b>shorter form</b>.' },
    { front: 'The 5 Steps', back: '1. Identify the <b>beginning, middle, and ending</b>.<br>2. Choose only the <b>important events</b>.<br>3. Leave out <b>minor details</b> and repeated information.<br>4. Tell the events in the <b>correct order</b>.<br>5. Use your <b>own words</b>.' },
    { front: 'Important Event', back: 'Something that moves the story forward. Take it away and the story stops making sense. <i>&ldquo;Mia discovered that her puppy had escaped from the backyard.&rdquo;</i>' },
    { front: 'Minor Detail', back: 'Extra information the story still works without &mdash; colours, clothes, what someone was carrying, the exact spot. <i>&ldquo;Mia was wearing her favorite yellow shirt.&rdquo;</i>' },
    { front: 'The Quick Test', back: 'Ask: <b>&ldquo;Would the story still make sense without this?&rdquo;</b> Yes &rarr; it is a minor detail, leave it out. No &rarr; it is an important event, keep it.' },
    { front: 'Mia&rsquo;s Puppy &mdash; Important', back: 'Puppy escaped from the backyard &rarr; she asked her neighbors to help search &rarr; they found the puppy near the town park &rarr; Mia brought the puppy home safely.' },
    { front: 'Mia&rsquo;s Puppy &mdash; Minor', back: 'Her <b>yellow shirt</b>. Carlo&rsquo;s <b>blue umbrella</b>. The puppy sitting beside a <b>large tree</b>. None of these change what happens.' },
    { front: 'A Good Summary Should&hellip;', back: 'include the <b>main idea</b> or main event &middot; include the <b>important events</b> &middot; present events in the <b>correct order</b> &middot; leave out <b>minor details</b> &middot; use your <b>own words</b> &middot; be <b>shorter</b> than the original.' },
    { front: 'The Summary Formula', back: '<b>WHO + WHAT HAPPENED + IMPORTANT EVENTS + HOW IT ENDED</b>' },
    { front: 'Anna’s Homework', back: 'Summary: “Anna forgot her homework at home, so she hurried back to get it and returned just in time to catch the bus to school.”<br>What she ate and putting on her uniform are left out &mdash; minor details.' }
  ],
  quiz: [
    { q: 'True or False: A summary tells the most important parts of a story in a shorter form.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is exactly what your worksheet says a summary is.', why: ['', 'That is exactly what a summary is — the most important parts, in a shorter form. So the statement is true.'], tip: 'Two things make a summary: <b>important parts only</b> and <b>shorter</b> than the story.' },
    { q: 'True or False: A good summary includes every detail so nothing is missed.', options: ['True', 'False'], correct: 1, explain: 'False — a summary leaves out <b>minor details</b> and repeated information. Only the important events go in.', why: ['A summary leaves out minor details. The words <b>every detail</b> make the statement false.', ''], tip: 'If a True or False says a summary includes <b>everything</b>, it is a trap. A summary picks only the important events.' },
    { q: 'Which of these is an <b>important event</b> in Mia&rsquo;s story?', options: ['She asked her neighbors to help her search.', 'Mia was wearing her favorite yellow shirt.', 'Her neighbor, Carlo, was carrying a blue umbrella.', 'The puppy was sitting beside a large tree.'], correct: 0, explain: 'Asking the neighbors for help moves the story forward. The shirt, the umbrella and the tree are minor details.', why: ['', 'Her yellow shirt does not change what happens. The story still makes sense without it — a minor detail.', 'Carlo’s blue umbrella does not change what happens — a minor detail.', 'Exactly where the puppy sat is extra information. What matters is that they found it.'], tip: 'Use the Quick Test: <b>would the story still make sense without this?</b> If yes, it is a minor detail.' },
    { q: 'Which of these is a <b>minor detail</b> that can be left out?', options: ['Carlo was carrying a blue umbrella.', 'They found the puppy near the town park.', 'Mia brought the puppy home safely.', 'Mia discovered her puppy had escaped.'], correct: 0, explain: 'Carlo&rsquo;s umbrella does not change what happens. The other three are the important events of the story.', why: ['', 'Finding the puppy is a big event — the story would not make sense without it.', 'Bringing the puppy home is how the story ends, so it must stay.', 'The puppy escaping is the problem that starts the story, so it must stay.'], tip: 'This question wants the <b>minor</b> one. Ask for each option: if I take this away, does the story still work? The umbrella can go.' },
    { q: 'True or False: &ldquo;The puppy was sitting beside a large tree&rdquo; is an important event that must be in the summary.', options: ['True', 'False'], correct: 1, explain: 'False — it is a <b>minor detail</b>. What matters is that they found the puppy near the town park, not exactly where it sat.', why: ['The tree is only where the puppy happened to sit. The story still makes sense without it, so it is a minor detail and the statement is false.', ''], tip: 'Colors, clothes and exact spots are usually minor details. Keep only what moves the story forward.' },
    { q: 'True or False: &ldquo;Mia brought the puppy home safely&rdquo; belongs in the summary because it is how the story ends.', options: ['True', 'False'], correct: 0, explain: 'Correct — a summary needs the <b>ending</b>, and this is it.', why: ['', 'A summary needs the ending, and this is how Mia’s story ends. So the statement is true.'], tip: 'Remember the formula ends with <b>HOW IT ENDED</b>. The ending always belongs in a summary.' },
    { q: 'When you summarize, you should tell the events&hellip;', options: ['in the correct order', 'starting from the ending', 'in any order you like', 'from most to least exciting'], correct: 0, explain: 'Step 4: tell the events in the <b>correct order</b> &mdash; beginning, middle, ending.', why: ['', 'Starting from the ending would mix up the story. Step 4 says tell events in the correct order.', 'A summary cannot be in any order — the reader would get confused.', 'Excitement is not the rule. Events go in the order they happened.'], tip: 'Step 4 of the 5 Steps: <b>tell the events in the correct order</b> — beginning, middle, ending.' },
    { q: 'What should you leave out of a summary?', options: ['Minor details and repeated information', 'The beginning, middle, and ending', 'The main problem the character must solve', 'The events in the order they happened'], correct: 0, explain: 'Step 3: leave out <b>minor details and repeated information</b>. The beginning, the problem and the ending all stay.', why: ['', 'The beginning, middle and ending are Step 1 — you must include them.', 'The main problem is an important part of the story, so it stays.', 'Telling events in order is Step 4 — you keep the order, you do not leave it out.'], tip: 'The question asks what to <b>leave out</b>. Only one option is something you throw away: minor details and repeated information.' },
    { q: 'True or False: A summary should be written in your own words.', options: ['True', 'False'], correct: 0, explain: 'Correct — Step 5 is to use your <b>own words</b>, not copy sentences from the story.', why: ['', 'Step 5 says use your own words, so the statement is true.'], tip: 'Do not copy the story’s sentences. Read, close the book, then say it <b>your way</b>.' },
    { passage: '<strong>The Lost Lunchbox</strong><br>Lara was excited to eat lunch with her friends at school. When lunchtime came, however, she discovered that her lunchbox was missing. She checked her desk, her locker, and the classroom shelves, but she could not find it.', q: 'Which is the <b>most important event</b> in this part of the story?', options: ['Lara discovered that her lunchbox was missing.', 'Lara checked the shelves in the classroom.', 'Lara checked inside her locker for it.', 'Lara was excited to eat with her friends.'], correct: 0, explain: 'The missing lunchbox is the problem the whole story is about. The places she checked are smaller details of the search.', why: ['', 'Checking the shelves is one small step of her search — a detail.', 'Checking her locker is one small step of her search — a detail.', 'Being excited to eat is how the passage starts, but the problem that drives the story is the missing lunchbox.'], tip: 'Look back at the passage for the <b>problem</b>: “she discovered that her lunchbox was missing.” The problem is usually the most important event.' },
    { passage: '<strong>The Lost Lunchbox</strong><br>Lara remembered that she had brought her lunchbox to the library earlier that morning. She hurried to the library and asked the librarian for help. Together, they looked around the tables and bookshelves.', q: 'Which sentence is the <b>best summary</b> of this part?', options: ['Lara went back to the library and asked the librarian for help.', 'Lara hurried, and the library had many tables and bookshelves.', 'Lara was very excited to eat lunch with her friends at school.', 'Lara checked her desk, her locker, and the classroom shelves.'], correct: 0, explain: 'It keeps the important events (going back, asking for help) in her own words and drops the minor details (tables, bookshelves).', why: ['', 'It adds that the library had many tables and bookshelves — a minor detail — and leaves out asking the librarian for help.', 'Being excited to eat with friends is from an earlier part, not this part about the library.', 'Checking her desk and locker is from an earlier part. This part is about going to the library.'], tip: 'Make sure the summary is about <b>this part</b> of the story. Look back: “She hurried to the library and asked the librarian for help.”' },
    { q: 'Which is the summary formula from class?', options: ['WHO + WHAT HAPPENED + IMPORTANT EVENTS + HOW IT ENDED', 'TITLE + AUTHOR + EVERY DETAIL + FAVORITE PART', 'SETTING + COLORS + CLOTHES + WEATHER + TIME', 'WHERE + WHEN + WHY + OPINION + LESSON'], correct: 0, explain: 'Who, what happened, the important events, and how it ended &mdash; nothing more.', why: ['', 'A summary never includes every detail, and your favorite part is an opinion.', 'Colors, clothes and weather are minor details — the things a summary leaves out.', 'An opinion does not belong in a summary, and this leaves out what happened.'], tip: 'Remember: <b>WHO + WHAT HAPPENED + IMPORTANT EVENTS + HOW IT ENDED</b>. Check that the formula tells the story, not the extras.' },
    { passage: '<b>The Forgotten Project</b><br>Miguel was excited because his class was going to present their science projects. He carefully placed his project inside a large cardboard box. The box was blue and had a small sticker on the side.<br><br>The next morning, Miguel arrived at school and realized that he had left his project at home. He became worried because the presentation was only an hour away. He called his mother and asked her to bring the project to school.<br><br>Miguel’s mother arrived just before the presentation began. Miguel thanked her and was able to present his project to the class. He felt relieved and proud of himself.', q: 'Which is the <b>best summary</b>?', options: ['Miguel left his project at home, called his mother, and she brought it in time so he could present.', 'Miguel put his project in a large blue box that had a small sticker on its side.', 'Miguel was excited, and his box was blue, and his mother came, and he thanked her.', 'Miguel’s class was going to present science projects to their teacher that week.'], correct: 0, explain: 'It keeps who, what happened, the important events and how it ended. The blue box and the sticker are minor details.', why: ['', 'This only tells about the blue box and the sticker — the passage calls them small details. It leaves out the problem and the ending.', 'It strings together “and, and, and” and keeps a minor detail (the blue box) but leaves out the problem: he forgot his project.', 'This is only the beginning. It does not tell the problem or how it ended.'], tip: 'Check the formula: does it say <b>who</b>, the <b>problem</b> (“left his project at home”) and <b>how it ended</b> (“able to present”)? Only one option has all of them.' },
    { q: 'True or False: A good summary is shorter than the original story.', options: ['True', 'False'], correct: 0, explain: 'Correct — it keeps only the most important ideas or events.', why: ['', 'A summary keeps only the most important parts, so it is shorter. The statement is true.'], tip: 'If your summary is as long as the story, you kept too many details.' }
  ]
});
