StudyKit.lesson({
  id: 'outline',
  icon: '🗂️',
  title: 'Outlining',
  subtitle: 'Main topics, subtopics & points',
  cards: [
    { front: 'Outline', back: 'A <b>plan</b> that shows a general idea of the <b>content and structure</b> of a piece of writing. It is divided into sections and subsections to separate the main ideas from the supporting ideas.' },
    { front: 'Three Parts', back: '<b>Main topics</b> &mdash; the broadest ideas.<br><b>Subtopics</b> &mdash; clarify the characteristics of those broad ideas.<br><b>Points</b> &mdash; clarify the subtopics by giving examples.<br>An outline goes from <b>broad to specific</b>.' },
    { front: 'Two Kinds', back: '<b>Sentence outline</b> &mdash; main topic and subtopics in <b>complete sentences</b>.<br><b>Topic outline</b> &mdash; main topic and subtopics in <b>phrases and words</b>.' },
    { front: 'Topic Outline Example', back: 'I. Benefits of Exercise<br>&nbsp;&nbsp;A. Physical Health<br>&nbsp;&nbsp;B. Mental Health<br>&nbsp;&nbsp;C. Better Sleep<br>(The slide used small a, b, c here, but the formatting rule is <b>capital letters</b> for subtopics.)' },
    { front: 'Numbers and Letters', back: '<b>Roman numerals</b> (I, II, III) &rarr; main topics<br><b>Capital letters</b> (A, B, C) &rarr; subtopics<br><b>Arabic numerals</b> (1, 2, 3) &rarr; points' },
    { front: 'Indent Each Level', back: 'Each sub-level is <b>indented further</b>, so you can see which ideas belong under a bigger idea.' },
    { front: 'Taking Care of Earth', back: 'III. Join movements. &larr; main topic<br>&nbsp;&nbsp;B. Participate in the activities of environmental organizations. &larr; subtopic<br>&nbsp;&nbsp;&nbsp;&nbsp;1. Plant trees. &larr; point' }
  ],
  quiz: [
    { q: 'What is an <b>outline</b>?', options: ['a plan that shows the content and structure of writing', 'a short retelling of the important events in a story', 'the lesson or message the author wants to share', 'a list of hard words and meanings at the end of a book'], correct: 0, explain: 'An outline is a <b>plan</b> that shows the content and structure of a piece of writing.', why: ['', 'A short retelling of important events is a <b>summary</b>.', 'The lesson or message of a story is the <b>theme</b>.', 'A list of hard words at the end of a book is a <b>glossary</b>.'], tip: 'Think of an outline as a <b>plan</b> or skeleton for writing — it shows how the ideas are arranged.' },
    { q: 'In an outline, <b>main topics</b> are marked with&hellip;', options: ['Roman numerals (I, II, III)', 'capital letters (A, B, C)', 'Arabic numerals (1, 2, 3)', 'bullets and stars'], correct: 0, explain: 'Roman numerals are used only for the main topics.', why: ['', 'Capital letters (A, B, C) mark the <b>subtopics</b>.', 'Arabic numerals (1, 2, 3) mark the <b>points</b>.', 'Outlines in your lesson do not use bullets or stars.'], tip: 'Biggest idea gets the biggest mark: <b>Roman numerals (I, II, III)</b> for main topics.' },
    { q: 'In an outline, <b>subtopics</b> are marked with&hellip;', options: ['capital letters (A, B, C)', 'Roman numerals (I, II, III)', 'Arabic numerals (1, 2, 3)', 'the title of the essay'], correct: 0, explain: 'Capital letters mark the subtopics, indented under each main topic.', why: ['', 'Roman numerals mark the <b>main topics</b>, the broadest ideas.', 'Arabic numerals mark the <b>points</b>, the most specific ideas.', 'The title names the whole outline. It is not how subtopics are marked.'], tip: 'Remember the ladder: I, II, III → A, B, C → 1, 2, 3. Subtopics are the <b>middle</b> step.' },
    { q: 'In an outline, <b>points</b> are marked with&hellip;', options: ['Arabic numerals (1, 2, 3)', 'capital letters (A, B, C)', 'Roman numerals (I, II, III)', 'the author’s name'], correct: 0, explain: 'Arabic numerals mark the points &mdash; the specific details and examples.', why: ['', 'Capital letters mark the <b>subtopics</b>.', 'Roman numerals mark the <b>main topics</b>.', 'The author’s name is not part of how an outline marks ideas.'], tip: 'Points are the smallest, most specific ideas, so they are at the bottom of the ladder: <b>1, 2, 3</b>.' },
    { q: 'True or False: An outline arranges ideas from broad to specific.', options: ['True', 'False'], correct: 0, explain: 'Correct — main topics are broadest, then subtopics, then points.', why: ['', 'An outline goes from main topics (broadest) to subtopics to points (most specific). So the statement is true.'], tip: 'Picture a funnel: wide at the top (main topics), narrow at the bottom (points).' },
    { q: 'True or False: The points are the broadest ideas in an outline.', options: ['True', 'False'], correct: 1, explain: 'False — the <b>main topics</b> are the broadest. Points are the most specific.', why: ['The <b>main topics</b> are the broadest ideas. Points are the most specific — the examples. So the statement is false.', ''], tip: 'Check if the statement swapped the top and the bottom of the outline.' },
    { q: 'True or False: A topic outline lists the main topic and subtopics in phrases and words.', options: ['True', 'False'], correct: 0, explain: 'Correct — a <b>sentence</b> outline uses complete sentences instead.', why: ['', 'A topic outline uses phrases and words, so the statement is true.'], tip: '<b>Topic</b> outline = short phrases. <b>Sentence</b> outline = complete sentences. The name tells you.' },
    { q: 'True or False: A sentence outline lists the subtopics in single words only.', options: ['True', 'False'], correct: 1, explain: 'False — a sentence outline uses <b>complete sentences</b>. Phrases and words belong in a topic outline.', why: ['A sentence outline uses <b>complete sentences</b>. Phrases and words belong in a topic outline, so the statement is false.', ''], tip: 'The name gives the answer away: a <b>sentence</b> outline uses sentences.' },
    { q: '“I. Benefits of Exercise &mdash; A. Physical Health, B. Mental Health, C. Better Sleep.” What kind of outline is this?', options: ['a topic outline', 'a sentence outline', 'a summary', 'a glossary'], correct: 0, explain: 'The subtopics are <b>phrases</b>, not complete sentences &mdash; a topic outline.', why: ['', 'A sentence outline would use complete sentences. “Physical Health” is only a phrase.', 'A summary retells a story. This is a list of topics and subtopics.', 'A glossary is a list of words and meanings at the end of a book.'], tip: 'Check the subtopics: are they complete sentences or short phrases? Phrases = topic outline.' },
    { passage: '<b>Taking Care of Earth</b><br>I. Segregate wastes properly.<br>&nbsp;&nbsp;&nbsp;A. Sort nonbiodegradable wastes from biodegradable.<br>&nbsp;&nbsp;&nbsp;B. Reduce, reuse, and recycle as much as possible.<br>II. Reduce paper consumption.<br>&nbsp;&nbsp;&nbsp;A. Use both sides of paper.<br>&nbsp;&nbsp;&nbsp;B. Recycle paper.<br>III. Join movements.<br>&nbsp;&nbsp;&nbsp;A. Donate to environmental nongovernment organizations.<br>&nbsp;&nbsp;&nbsp;B. Participate in the activities of environmental organizations.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Plant trees.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Initiate a Clean Up.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Grow a community garden.', q: '“1. Plant trees.” is which part of this outline?', options: ['a point', 'a main topic', 'a subtopic', 'the title'], correct: 0, explain: 'It is marked with an Arabic numeral, so it is a <b>point</b>.', why: ['', 'Main topics are marked with Roman numerals, like “III. Join movements.”', 'Subtopics are marked with capital letters, like “B. Participate in the activities...”', 'The title is “Taking Care of Earth,” at the very top.'], tip: 'Look back at the mark in front of the line. An Arabic numeral (1, 2, 3) always means a point.' },
    { passage: '<b>Taking Care of Earth</b><br>I. Segregate wastes properly.<br>&nbsp;&nbsp;&nbsp;A. Sort nonbiodegradable wastes from biodegradable.<br>&nbsp;&nbsp;&nbsp;B. Reduce, reuse, and recycle as much as possible.<br>II. Reduce paper consumption.<br>&nbsp;&nbsp;&nbsp;A. Use both sides of paper.<br>&nbsp;&nbsp;&nbsp;B. Recycle paper.<br>III. Join movements.<br>&nbsp;&nbsp;&nbsp;A. Donate to environmental nongovernment organizations.<br>&nbsp;&nbsp;&nbsp;B. Participate in the activities of environmental organizations.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Plant trees.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Initiate a Clean Up.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Grow a community garden.', q: 'Which is a <b>subtopic</b> under “II. Reduce paper consumption”?', options: ['Use both sides of paper.', 'Join movements.', 'Segregate wastes properly.', 'Taking Care of Earth'], correct: 0, explain: '“Use both sides of paper” is marked A under II. “Join movements” and “Segregate wastes properly” are main topics.', why: ['', '“Join movements” has the Roman numeral III — it is a main topic, not under II.', '“Segregate wastes properly” has the Roman numeral I — it is a main topic.', '“Taking Care of Earth” is the title of the whole outline.'], tip: 'Find II in the outline, then look at the lines with capital letters <b>right under it</b>: A. Use both sides of paper.' },
    { q: 'What does indenting each level show?', options: ['which ideas belong under a bigger idea', 'which ideas are the most exciting', 'which ideas the writer likes best', 'which ideas should be left out'], correct: 0, explain: 'Indenting shows that a smaller idea <b>belongs under</b> the bigger idea above it.', why: ['', 'Indenting is about how ideas are organized, not which are exciting.', 'Indenting does not show the writer’s favorites.', 'Indenting does not remove ideas — everything indented is still part of the outline.'], tip: 'Indented lines are like children standing under a parent. Indent = <b>belongs under</b> the bigger idea above.' }
  ]
});
