StudyKit.lesson({
  id: 'purpose',
  icon: '✍️',
  title: 'Author’s Purpose',
  subtitle: 'Inform, entertain, or describe',
  cards: [
    { front: 'Author’s Purpose', back: 'The <b>reason</b> an author writes. Every text has a mission!' },
    { front: 'I Is for Inform', back: 'Gives <b>facts</b>, teaches a topic, or explains how things are done. Few opinions.<br>“Rain is a form of precipitation&hellip;” gives facts about rain.' },
    { front: 'Inform &mdash; Examples', back: '<b>Textbooks</b> &middot; <b>news reports</b> &middot; <b>instruction manuals</b>' },
    { front: 'E Is for Entertain', back: 'To <b>amuse</b>, engage, excite, or emotionally involve the reader &mdash; make you laugh, feel curious or scared, or enjoy a story.<br>Ben stepped on a squeaky toy and woke the whole house.' },
    { front: 'Entertain &mdash; Examples', back: '<b>Stories</b> (exciting tales) &middot; <b>comics</b> (funny pictures and dialogue) &middot; <b>poems</b> (rhythm, rhyme, and feelings)' },
    { front: 'D Is for Describe', back: 'Helps the reader <b>imagine or understand what something is like</b>.<br>“Tall sunflowers stood beside small pink roses, while butterflies flew from one plant to another.”' },
    { front: 'Describe &mdash; Examples', back: '<b>Travel brochures</b> &middot; <b>picture books</b> &middot; <b>menu books</b>' }
  ],
  quiz: [
    { passage: 'Bees play an important role in helping plants reproduce. As bees move from one flower to another, they carry pollen with them. This allows many plants to produce fruits and seeds.', q: 'What is the author’s purpose in the passage about bees?', options: ['To inform', 'To entertain', 'To describe'], correct: 0, explain: 'It gives <b>facts</b> about how bees help plants &mdash; to inform.', why: ['', 'An entertaining text is a story that makes you laugh, feel curious or scared. This passage just gives facts: bees “carry pollen” so plants can “produce fruits and seeds.”', 'A describing text helps you picture what something looks like. This passage explains how bees help plants.'], tip: 'Ask: is the writer <b>teaching me facts</b>? Facts about how nature works = inform.' },
    { passage: 'Milo opened his lunchbox and gasped. His sandwich was gone! He looked under his chair and behind his bag. Suddenly, he heard a loud crunch. His puppy, Max, was sitting beside the table with the sandwich in his mouth.', q: 'What is the author’s purpose in the passage about Milo?', options: ['To entertain', 'To inform', 'To describe'], correct: 0, explain: 'It is a funny little story about a puppy stealing a sandwich &mdash; to entertain.', why: ['', 'An informing text gives facts. This one tells a little story: Milo “gasped” and his puppy had the sandwich.', 'A describing text helps you picture what something is like. This passage is mostly things happening in a story.'], tip: 'A story with a character, a problem and a surprise (the puppy!) is written to <b>entertain</b>.' },
    { passage: 'The old house stood at the end of a quiet road. Its wooden walls were covered with green vines, and its windows were dusty and cracked. A tall mango tree stretched its branches over the rusty roof.', q: 'What is the author’s purpose in the passage about the old house?', options: ['To describe', 'To inform', 'To entertain'], correct: 0, explain: 'It helps you picture <b>what the house looks like</b> &mdash; vines, dusty windows, a rusty roof. To describe.', why: ['', 'Informing gives facts or explains how things are done. This passage paints a picture: “dusty and cracked” windows, a “rusty roof.”', 'Entertaining tells a story that amuses or excites. Nothing happens here — it only shows how the house looks.'], tip: 'Lots of looks-like words (colors, dusty, tall, rusty) with no action = <b>describe</b>.' },
    { passage: 'A volcano is an opening in Earth’s surface through which hot materials, such as lava, ash, and gases, may escape. Some volcanoes are active, while others have not erupted for thousands of years.', q: 'What is the author’s purpose in the passage about volcanoes?', options: ['To inform', 'To describe', 'To entertain'], correct: 0, explain: 'It explains <b>facts</b> about volcanoes &mdash; to inform.', why: ['', 'Describing helps you picture something. This passage explains what a volcano <b>is</b> — facts like “some volcanoes are active.”', 'Entertaining tells an exciting or funny story. There is no character or story here.'], tip: 'A text that starts with “A ___ is…” and explains it is usually written to <b>inform</b>.' },
    { passage: 'Lena tiptoed into the kitchen to find the last piece of chocolate cake. Just as she reached for it, the lights suddenly went out. “Who turned off the lights?” she whispered. Then she heard footsteps behind her.', q: 'What is the author’s purpose in the passage about Lena?', options: ['To entertain', 'To describe', 'To inform'], correct: 0, explain: 'It is an exciting, slightly scary story that keeps you curious &mdash; to entertain.', why: ['', 'Describing helps you picture something. This passage keeps you curious about what happens next: “the lights suddenly went out.”', 'Informing gives facts. There are no facts here — it is a story with a character, Lena.'], tip: 'If a passage makes you feel curious or a little scared and want to read more, the purpose is to <b>entertain</b>.' },
    { q: '“<i>Ben tried to sneak into the kitchen for a midnight snack. Unfortunately, he stepped on the squeaky toy and woke the entire house.</i>” The purpose is&hellip;', options: ['To entertain', 'To inform', 'To describe'], correct: 0, explain: 'The writer wants you to <b>enjoy the funny situation</b> &mdash; to entertain.', why: ['', 'Informing gives facts or steps. This is a funny moment in a story, not facts.', 'Describing helps you picture something. This passage tells a funny event: he “woke the entire house.”'], tip: 'Ask: does the writer want me to <b>enjoy</b> or <b>laugh</b>? Funny situations = entertain.' },
    { q: 'Which text is usually written to <b>inform</b>?', options: ['an instruction manual', 'a comic strip', 'a funny poem', 'a travel brochure'], correct: 0, explain: 'Instruction manuals, textbooks and news reports give facts and steps.', why: ['', 'Comic strips use funny pictures and dialogue to entertain.', 'A funny poem is written to entertain.', 'A travel brochure is written to describe a place.'], tip: 'Remember the Inform examples: <b>textbooks, news reports, instruction manuals</b>.' },
    { q: 'Which text is usually written to <b>describe</b>?', options: ['a menu book', 'a news report', 'a textbook', 'a comic strip'], correct: 0, explain: 'Menu books, travel brochures and picture books help you imagine what something is like.', why: ['', 'A news report is written to inform.', 'A textbook is written to inform.', 'A comic strip is written to entertain.'], tip: 'Remember the Describe examples: <b>travel brochures, picture books, menu books</b>.' },
    { q: 'True or False: Comics are usually written to entertain.', options: ['True', 'False'], correct: 0, explain: 'Correct — funny pictures and dialogue are meant to amuse you.', why: ['', 'Comics use funny pictures and dialogue to amuse you — that is entertaining. So the statement is true.'], tip: 'Memory hook: comics are <b>comical</b> — funny — so they entertain.' },
    { q: 'True or False: A text written to inform is full of the author’s opinions.', options: ['True', 'False'], correct: 1, explain: 'False — informing texts focus on <b>facts</b>, steps and real-world data, without many opinions.', why: ['Informing texts focus on <b>facts</b>, with few opinions. The words <b>full of opinions</b> make the statement false.', ''], tip: 'Informing = facts. If a statement says an informing text is full of opinions, answer False.' },
    { q: '“<i>The garden was filled with colorful flowers. Tall sunflowers stood beside small pink roses.</i>” Why did the author write this?', options: ['To describe the garden', 'To inform us about roses', 'To entertain with a joke'], correct: 0, explain: 'The writer gives details about <b>how the garden looks</b> &mdash; to describe.', why: ['', 'Roses are only one part. The sentences mainly show how the whole garden looks, not facts about roses.', 'There is no joke or funny story here — only a picture of the garden.'], tip: 'Look for picture words: <b>colorful, tall, small pink</b>. When the writer paints a picture, the purpose is to describe.' }
  ]
});
