StudyKit.lesson({
  id: 'tone',
  icon: '🎭',
  title: 'Tone & Mood',
  subtitle: 'The author’s voice, the reader’s feeling',
  cards: [
    { front: 'Tone', back: 'The <b>author’s attitude</b> &mdash; the author’s “voice”. Serious? Excited? Inspiring? Find it by looking at the <b>specific words</b> the author uses.' },
    { front: 'Mood', back: 'What <b>the reader</b> feels. It is made by the <b>setting and atmosphere</b>.' },
    { front: 'Tone vs Mood', back: '<b>Who feels it?</b> Tone: the author or narrator. Mood: the reader (you!).<br><b>How is it made?</b> Tone: word choice and attitude. Mood: setting and atmosphere.' },
    { front: 'Example Words', back: 'Tone: <b>serious, uplifting, humorous</b>.<br>Mood: <b>peaceful, gloomy, motivated</b>.' },
    { front: 'Formal Tone', back: 'For <b>official settings</b> where authority, accuracy and respect matter. Uses full words, exact vocabulary and standard grammar. <b>Avoids slang</b> and emotional bias.' },
    { front: 'Informal Tone', back: '<b>Conversational, direct, and warm</b> &mdash; for friends and familiar people. Uses contractions, everyday phrases, shorter sentences and expressive language.' },
    { front: 'Analyzing a Stanza', back: '“Come, love your troubled country, / Embrace it with all your heart tomorrow!”<br>Tone: <b>inspiring and encouraging</b>. Mood: <b>proud and motivated</b>.' }
  ],
  quiz: [
    { q: 'What is <b>tone</b>?', options: ['the author’s attitude toward the subject', 'the feeling the reader gets', 'the place and time of the story', 'the most exciting part of the story'], correct: 0, explain: 'Tone is the <b>author’s attitude</b>. The feeling the reader gets is the mood.', why: ['', 'The feeling the reader gets is the <b>mood</b>, not the tone.', 'The place and time of the story is the <b>setting</b>.', 'The most exciting part of the story is the <b>climax</b>.'], tip: 'Tone = the <b>author’s</b> voice. Mood = the <b>reader’s</b> feeling. Ask: whose feeling is it?' },
    { q: 'Who feels the <b>mood</b>?', options: ['the reader', 'the author', 'the narrator', 'the illustrator'], correct: 0, explain: 'Mood is what <b>you, the reader</b>, feel. Tone belongs to the author or narrator.', why: ['', 'The author has the <b>tone</b> — the attitude. The mood belongs to the reader.', 'The narrator also has the <b>tone</b>, not the mood.', 'The illustrator draws pictures. The lesson says the mood is what the reader feels.'], tip: 'Memory hook: <b>M</b>ood is what <b>M</b>E, the reader, feels.' },
    { q: 'True or False: Tone is shown through word choice and the author’s attitude.', options: ['True', 'False'], correct: 0, explain: 'Correct — look at the specific words the author uses.', why: ['', 'Tone comes from the specific words the author chooses and their attitude. So the statement is true.'], tip: 'To find the tone, look at the author’s <b>word choice</b>.' },
    { q: 'True or False: Mood is the author’s attitude, and tone is how the reader feels.', options: ['True', 'False'], correct: 1, explain: 'False — it is the other way around. <b>Tone</b> is the author’s attitude; <b>mood</b> is how the reader feels.', why: ['The statement swapped the two. <b>Tone</b> is the author’s attitude; <b>mood</b> is how the reader feels. So it is false.', ''], tip: 'When a True or False has two definitions, check each one. One swap makes the whole statement false.' },
    { q: 'Which word from the lesson describes a <b>mood</b>?', options: ['gloomy', 'humorous', 'serious', 'uplifting'], correct: 0, explain: 'In your teacher’s table, <b>gloomy</b>, peaceful and motivated are moods. Serious, uplifting and humorous are tones.', why: ['', 'Humorous is a <b>tone</b> word in your teacher’s table.', 'Serious is a <b>tone</b> word in your teacher’s table.', 'Uplifting is a <b>tone</b> word in your teacher’s table.'], tip: 'Remember the table: tone words are <b>serious, uplifting, humorous</b>; mood words are <b>peaceful, gloomy, motivated</b>.' },
    { passage: '“Come, you who have lived dreaming<br>Of future joy, yet tasted only sorrow,<br>Come, love your troubled country,<br>Embrace it with all your heart tomorrow!”', q: 'What is the <b>tone</b> of this stanza?', options: ['inspiring and encouraging', 'angry and bitter', 'funny and silly', 'bored and sleepy'], correct: 0, explain: '“Come, love your troubled country, embrace it with all your heart” &mdash; the poet is <b>inspiring and encouraging</b> the reader.', why: ['', 'The poet is not angry. The poem says “love your troubled country” and “embrace it with all your heart.”', 'Nothing is funny here. The poet is calling the reader to love the country.', '“Come… embrace it with all your heart tomorrow!” is full of energy, not bored.'], tip: 'Look at the author’s words: <b>Come, love, embrace</b>. Words that call you to act show an inspiring, encouraging tone.' },
    { passage: '“Come, you who have lived dreaming<br>Of future joy, yet tasted only sorrow,<br>Come, love your troubled country,<br>Embrace it with all your heart tomorrow!”', q: 'What <b>mood</b> does this stanza create?', options: ['proud and motivated', 'scared and nervous', 'sleepy and bored', 'confused and lost'], correct: 0, explain: 'The reader is left feeling <b>proud and motivated</b>.', why: ['', 'Nothing in the stanza is meant to scare you. It asks you to love your country.', 'The exclamation “with all your heart tomorrow!” wakes you up — it is not sleepy.', 'The message is clear: love your country. It does not leave you confused.'], tip: 'Ask yourself how <b>you</b> feel after reading “Come, love your troubled country.” That feeling is the mood.' },
    { q: 'Which sentence has a <b>formal</b> tone?', options: ['We would like to inform you that the meeting starts at nine.', 'Hey guys, the meeting’s gonna start at nine, so don’t be late, okay?', 'Gonna be late, sorry! Save me a seat, pls!', 'Yay, no meeting tomorrow, woohoo!'], correct: 0, explain: 'Full words and standard grammar with no slang &mdash; formal. The others use slang and contractions.', why: ['', '“Hey guys” and “gonna” are slang, so this is informal.', '“Gonna” and “pls” are slang, so this is informal.', '“Yay” and “woohoo” are expressive everyday words, so this is informal.'], tip: 'Formal tone = <b>full words and no slang</b>. Cross out any option with gonna, pls, hey or yay.' },
    { q: 'Which sentence has an <b>informal</b> tone?', options: ['Can’t wait to see you guys later!', 'The principal will address the students this afternoon.', 'Please submit your reports on or before Friday.', 'Visitors are required to sign in at the front desk.'], correct: 0, explain: '“Can’t” and “you guys” are conversational &mdash; an informal tone.', why: ['', 'This uses full words and standard grammar — a formal tone.', '“Please submit your reports” is polite and official — formal.', '“Visitors are required to sign in” sounds official — formal.'], tip: 'Informal clues: contractions like <b>can’t</b> and friendly words like <b>you guys</b>.' },
    { q: 'True or False: A formal tone uses slang and lots of contractions.', options: ['True', 'False'], correct: 1, explain: 'False — a formal tone <b>avoids slang</b> and uses full words. Contractions belong to an informal tone.', why: ['A formal tone <b>avoids</b> slang and uses full words. Slang and contractions belong to an informal tone, so the statement is false.', ''], tip: 'Formal = full words, no slang. Informal = contractions and everyday phrases.' },
    { q: 'True or False: An informal tone is conversational, direct, and warm.', options: ['True', 'False'], correct: 0, explain: 'Correct — it is built for friends and familiar audiences.', why: ['', 'An informal tone really is conversational, direct and warm, like talking to a friend. So the statement is true.'], tip: 'Think of how you talk to your best friend — that is an informal tone.' },
    { q: 'Where would a <b>formal</b> tone fit best?', options: ['a letter to the school principal', 'a text message to your best friend', 'a chat with your cousin', 'a birthday card for your sister'], correct: 0, explain: 'A formal tone is for <b>official settings</b> where respect matters.', why: ['', 'A text to your best friend is a familiar setting, so an informal tone fits.', 'A chat with your cousin is with family, so an informal tone fits.', 'A birthday card for your sister is warm and familiar, so an informal tone fits.'], tip: 'Ask: is this person someone in an <b>official</b> role, where respect matters? Then use a formal tone.' }
  ]
});
