StudyKit.lesson({
  id: 'nouns',
  icon: '🧺',
  title: 'Kinds of Nouns',
  subtitle: 'Concrete, collective & abstract',
  cards: [
    { front: 'Noun', back: 'A word that names a <b>person, place, thing, or idea</b>.' },
    { front: 'Concrete Noun', back: 'Something you can <b>see, touch, hear, smell, or taste</b>.<br><i>basket, whiteboard, teacher, birds</i>' },
    { front: 'Abstract Noun', back: 'An <b>idea, feeling, or quality</b> &mdash; you cannot touch it.<br><i>honesty, courage, kindness</i>' },
    { front: 'Collective Noun', back: 'Names a <b>group</b> of people, animals, or things as one unit.<br><i>team, audience, flock, class</i>' },
    { front: 'The 3-Question Test', back: 'Is it a <b>group</b>? &rarr; collective.<br>Is it an <b>idea, feeling, or quality</b>? &rarr; abstract.<br>Can you <b>touch</b> it? &rarr; concrete.' },
    { front: 'Watch the Bold Word', back: '&ldquo;A <b>flock</b> of birds flew across the sky.&rdquo; <b>Flock</b> is collective, but <i>birds</i> is concrete. Only judge the word in bold.' },
    { front: 'Your Own Sentences', back: 'Abstract: &ldquo;Her <b>kindness</b> inspired everyone in the classroom.&rdquo;<br>Concrete: &ldquo;The teacher wrote a note on the <b>whiteboard</b>.&rdquo;' }
  ],
  quiz: [
    { q: 'The <b>team</b> celebrated after winning the championship. What kind of noun is <b>team</b>?', options: ['Collective', 'Concrete', 'Abstract'], correct: 0, explain: 'A team is a <b>group</b> of players named as one unit &mdash; collective.', why: ['', 'You can see each player, but <b>team</b> names the whole group as one unit. That makes it collective.', 'Abstract nouns are ideas, feelings or qualities. A team is a group of people.'], tip: 'Use the 3-Question Test in order. First ask: <b>is it a group?</b> If yes, it is collective.' },
    { q: '<b>Honesty</b> is an important quality of a good friend. What kind of noun is <b>honesty</b>?', options: ['Abstract', 'Collective', 'Concrete'], correct: 0, explain: 'Honesty is a <b>quality</b> &mdash; you cannot touch it. Abstract.', why: ['', 'Collective nouns name a group. Honesty is not a group.', 'You cannot see or touch honesty itself. It is a quality, so it is not concrete.'], tip: 'Ask: <b>can I touch it?</b> If not, and it is an idea, feeling or quality, it is abstract.' },
    { q: 'The <b>audience</b> listened quietly during the school program. What kind of noun is <b>audience</b>?', options: ['Collective', 'Abstract', 'Concrete'], correct: 0, explain: 'An audience is a group of people watching &mdash; collective.', why: ['', 'Abstract nouns are ideas or feelings. An audience is a group of people.', 'You can see the people, but <b>audience</b> names them all together as one group — collective.'], tip: 'Group words come first in the test. Audience = many people as one unit = collective.' },
    { q: 'A <b>flock</b> of birds flew across the sky. What kind of noun is <b>flock</b>?', options: ['Collective', 'Concrete', 'Abstract'], correct: 0, explain: 'A flock is a group of birds &mdash; collective.', why: ['', 'Birds are concrete, but the question asks about <b>flock</b>, which names the group.', 'Abstract nouns are ideas or feelings. A flock is a group of birds.'], tip: 'Only judge the word the question names. Here it is <b>flock</b>, the group word.' },
    { q: 'The <b>basket</b> was filled with fresh fruits. What kind of noun is <b>basket</b>?', options: ['Concrete', 'Collective', 'Abstract'], correct: 0, explain: 'You can see and touch a basket &mdash; concrete.', why: ['', 'A basket is one thing, not a group of things.', 'Abstract nouns cannot be touched. You can see and touch a basket.'], tip: 'Ask: <b>can I touch it?</b> A basket — yes. Concrete.' },
    { q: 'A <b>class</b> of students prepared a presentation for the program. What kind of noun is <b>class</b>?', options: ['Collective', 'Abstract', 'Concrete'], correct: 0, explain: 'A class is a group of students &mdash; collective.', why: ['', 'Abstract nouns are ideas or feelings. A class is a group of students.', 'You can see the students, but <b>class</b> names them together as one group — collective.'], tip: '“A class <b>of</b> students” — when a word names a group <b>of</b> something, it is often collective.' },
    { q: 'True or False: &ldquo;Honesty&rdquo; is a concrete noun because you can see an honest person.', options: ['True', 'False'], correct: 1, explain: 'False — you can see the <i>person</i>, but honesty itself is a quality you cannot touch. It is <b>abstract</b>.', why: ['You can see the person, but honesty itself is a quality you cannot touch. So it is abstract and the statement is false.', ''], tip: 'Judge the word itself, not the person who has it. Can you hold <b>honesty</b> in your hand?' },
    { q: 'True or False: A collective noun names a group of people, animals, or things as one unit.', options: ['True', 'False'], correct: 0, explain: 'Correct — team, audience, flock and class are all collective nouns.', why: ['', 'That is the definition of a collective noun — team, audience, flock, class. So the statement is true.'], tip: 'Collective = <b>collect</b> — many things gathered as one unit.' },
    { q: 'True or False: In &ldquo;A flock of birds flew across the sky,&rdquo; the word <i>birds</i> is the collective noun.', options: ['True', 'False'], correct: 1, explain: 'False — <b>flock</b> is the collective noun. <i>Birds</i> is a concrete noun.', why: ['<b>Flock</b> is the collective noun — it names the group. Birds is a concrete noun. So the statement is false.', ''], tip: 'In “a ___ of ___,” the first word is usually the group (collective) and the second is what is in the group.' },
    { q: 'True or False: In &ldquo;The teacher wrote a note on the whiteboard,&rdquo; <i>whiteboard</i> is a concrete noun.', options: ['True', 'False'], correct: 0, explain: 'Correct — you can see and touch a whiteboard.', why: ['', 'You can see and touch a whiteboard, so it is concrete and the statement is true.'], tip: 'Can you see it or touch it? Then it is concrete.' },
    { q: 'Which sentence uses an <b>abstract</b> noun?', options: ['Her kindness inspired everyone.', 'The basket was full of fruit.', 'A flock of birds flew by.', 'The teacher used the whiteboard.'], correct: 0, explain: '<b>Kindness</b> is a quality you cannot touch &mdash; abstract. The others name things you can see.', why: ['', 'Basket and fruit are things you can see and touch — concrete.', 'Flock is collective and birds is concrete. Neither is an idea or feeling.', 'Teacher and whiteboard can be seen and touched — concrete.'], tip: 'Hunt for a word that names a <b>feeling or quality</b>, like kindness, honesty or courage.' }
  ]
});
