StudyKit.lesson({
  id: 'visual',
  icon: '🖼️',
  title: 'Visual Elements',
  subtitle: 'Lines, symbols, colors & more',
  cards: [
    { front: 'Visual Elements', back: 'The <b>pictures, colors, symbols, shapes, fonts</b>, and other visual features used in a text to <b>communicate ideas or feelings</b>. They make an output vivid and stir the reader’s emotions.' },
    { front: 'Lines', back: 'Show <b>pattern, growth, depth, movement</b>, and emotions. They can be natural or man-made.<br>The line a swing makes represents <b>height</b>.' },
    { front: 'Symbols', back: '<b>Represent concepts</b> and suggest the overall message.<br>A child represents <b>youthful imagination</b>.' },
    { front: 'Colors', back: 'Suggest <b>mood</b> and create <b>atmosphere</b>.<br>White clouds represent a <b>joyful</b> atmosphere.' },
    { front: 'Gaze', back: 'Shows the connection between the viewer and the subject &mdash; <b>where the subject is looking</b>.<br>The child on the swing looking up adds to the positive atmosphere.' },
    { front: 'Framing', back: 'The <b>layout</b> of the visual elements. It <b>draws attention</b> to the subject.<br>The framing focuses on the joy of the child.' },
    { front: 'Social Distance', back: 'How <b>close</b> the subject is to the viewer.<br>A child shown far away suggests a more <b>objective</b> look.' }
  ],
  quiz: [
    { q: 'What are <b>visual elements</b>?', options: ['pictures, colors, symbols, and fonts that share ideas', 'the words a character says in a story', 'the order of events in a story’s plot', 'the sounds that repeat in a poem'], correct: 0, explain: 'Visual elements are the pictures, colors, symbols, shapes and fonts used to communicate ideas or feelings.', why: ['', 'The words a character says are <b>dialogue</b>.', 'The order of events is the <b>plot</b>.', 'Repeated sounds in a poem are <b>sound devices</b>.'], tip: '<b>Visual</b> means seeing. Visual elements are the things you <b>see</b>: pictures, colors, symbols, fonts.' },
    { q: 'Which visual element shows <b>where the subject is looking</b>?', options: ['gaze', 'framing', 'lines', 'colors'], correct: 0, explain: '<b>Gaze</b> connects the viewer and the subject through where the subject looks.', why: ['', 'Framing is the layout that draws attention to the subject.', 'Lines show pattern, growth, depth and movement.', 'Colors suggest mood and create atmosphere.'], tip: 'Gaze means looking. Where the subject <b>looks</b> = gaze.' },
    { q: 'Which visual element suggests <b>mood</b> and creates atmosphere?', options: ['colors', 'gaze', 'social distance', 'framing'], correct: 0, explain: '<b>Colors</b> suggest mood &mdash; white clouds for a joyful atmosphere.', why: ['', 'Gaze shows where the subject is looking.', 'Social distance shows how close the subject is to the viewer.', 'Framing is the layout that draws attention to the subject.'], tip: 'Think of the swing poster: white clouds made it joyful. <b>Colors</b> set the mood.' },
    { q: 'Which visual element is the <b>layout</b> that draws attention to the subject?', options: ['framing', 'symbols', 'lines', 'gaze'], correct: 0, explain: '<b>Framing</b> is the layout that focuses your attention on the subject.', why: ['', 'Symbols represent ideas, like a child for youthful imagination.', 'Lines show pattern, growth and movement.', 'Gaze shows where the subject is looking.'], tip: 'Framing is like a picture frame — it is the <b>layout</b> that points your eyes to the subject.' },
    { q: 'What does <b>social distance</b> refer to?', options: ['how close the subject is to the viewer', 'where the subject is looking', 'which colors are used', 'how big the letters are'], correct: 0, explain: 'Social distance is the <b>proximity</b> of the subject and the viewer.', why: ['', 'Where the subject is looking is the <b>gaze</b>.', 'Colors are their own visual element that sets the mood.', 'The size of the letters is about fonts, not social distance.'], tip: 'The word <b>distance</b> is the clue — how near or far the subject is from you.' },
    { q: 'What do <b>symbols</b> do in a visual text?', options: ['represent concepts or ideas', 'show where the subject looks', 'list the steps of a process', 'tell the order of events'], correct: 0, explain: 'Symbols represent concepts &mdash; a child can represent youthful imagination.', why: ['', 'Showing where the subject looks is the job of <b>gaze</b>.', 'Listing steps is what instructions do, not symbols.', 'The order of events is the <b>plot</b>.'], tip: 'A symbol <b>stands for</b> an idea. A child can stand for youthful imagination.' },
    { q: 'True or False: Lines can show movement, growth, and height.', options: ['True', 'False'], correct: 0, explain: 'Correct — the line a swing makes represents height.', why: ['', 'Lines show pattern, growth, depth and movement — like the line a swing makes showing height. So the statement is true.'], tip: 'Picture the swing’s path: the line shows how high it goes.' },
    { q: 'True or False: A subject shown far from the viewer suggests a more objective look.', options: ['True', 'False'], correct: 0, explain: 'Correct — that is what social distance tells us.', why: ['', 'That is what social distance tells us about a subject shown far away. So the statement is true.'], tip: 'Near or far matters. Social distance = <b>how close</b> the subject is to you.' },
    { q: 'True or False: Visual elements have nothing to do with the meaning of a text.', options: ['True', 'False'], correct: 1, explain: 'False — they <b>contribute to the meaning and purpose</b> of a text.', why: ['Visual elements help share the meaning and purpose of a text. The words <b>nothing to do with</b> make the statement false.', ''], tip: 'Pictures and colors are not just decoration — they help tell the message.' },
    { q: 'True or False: In the swing poster, the white clouds create a gloomy, sad atmosphere.', options: ['True', 'False'], correct: 1, explain: 'False — white clouds represent a <b>joyful</b> atmosphere.', why: ['In the swing poster, white clouds represent a <b>joyful</b> atmosphere, not a gloomy one. So the statement is false.', ''], tip: 'Check the feeling word. The lesson says white clouds = <b>joyful</b>.' },
    { passage: 'A poster shows a boy turning off a kitchen tap. Big words say <b>SMALL ACTIONS, BIG IMPACT</b> and <b>SAVE WATER</b>. Blue, green and yellow water-drop shapes carry the lines “Every drop counts” and “Save today for a better tomorrow.”', q: 'Why are the words <b>SAVE WATER</b> printed so large?', options: ['to catch the reader’s attention first', 'to fill up the empty space on the poster', 'because the poster has no pictures at all', 'to make the poster harder to read'], correct: 0, explain: 'Big words are the first thing the eye sees, so the main message stands out.', why: ['', 'The big words carry the main message, not just fill empty space.', 'The poster does have a picture — “a boy turning off a kitchen tap.”', 'Big words make the message easier to see, not harder to read.'], tip: 'Ask: what does my eye see <b>first</b>? Designers make the most important words biggest.' },
    { passage: 'A poster shows a boy turning off a kitchen tap. Big words say <b>SMALL ACTIONS, BIG IMPACT</b> and <b>SAVE WATER</b>. Blue, green and yellow water-drop shapes carry the lines “Every drop counts” and “Save today for a better tomorrow.”', q: 'What <b>message</b> does this poster want to share?', options: ['to encourage people to save water', 'to teach how to fix a kitchen tap', 'to sell a new kind of water bottle', 'to tell a funny story about a boy'], correct: 0, explain: 'The pictures, symbols and words all work together to encourage people to <b>save water</b>.', why: ['', 'The boy is turning off the tap, not fixing it. The words say “SAVE WATER.”', 'Nothing on the poster is for sale. It says “Every drop counts.”', 'The poster does not tell a funny story. Its words are “SMALL ACTIONS, BIG IMPACT.”'], tip: 'Look back at the biggest words on the poster — <b>SAVE WATER</b>. The main message is usually the biggest text.' }
  ]
});
